-- generated by construct/lean/run_lemmas_t2.py from construct/schemas.py itself
import Std.Tactic.BVDecide

theorem schema_below_or_equal_unsigned_w32_16_0 (v0 : BitVec 16) (v1 : BitVec 16) (v2 : BitVec 16) (v3 : BitVec 16) :
    (if ((v0 ++ v1).ule (v2 ++ v3)) = true then (1#8) else (0#8)) = (if ((!(v2.ule v0)) || ((v0 == v2) && (v1.ule v3))) = true then (1#8) else (0#8)) := by
  bv_decide
