-- generated by construct/lean/run_lemmas_t2.py from construct/schemas.py itself
import Std.Tactic.BVDecide

theorem schema_equal_w128_64_0 (v0 : BitVec 64) (v1 : BitVec 64) (v2 : BitVec 64) (v3 : BitVec 64) :
    (if ((v1 == v3) && (v0 == v2)) = true then (1#8) else (0#8)) = (if ((v1 == v3) && (v0 == v2)) = true then (1#8) else (0#8)) := by
  bv_decide
