-- generated by construct/lean/run_lemmas_t2.py from construct/schemas.py itself
import Std.Tactic.BVDecide

theorem schema_sub_w65_64_0 (v1 : BitVec 64) (v3 : BitVec 64) :
    (v1 + ((18446744073709551615#64) * v3)) = (v1 + ((18446744073709551615#64) * v3)) := by
  bv_decide
