-- generated by Research/op_pipeline/lean/run_edges_L1.py
import Std.Tactic.BVDecide

theorem edge_04_E01658_E01661 (v0 : BitVec 64) (v1 : BitVec 64) :
    ((if ((v0.extractLsb 7 0) == (v1.extractLsb 7 0)) = true then (0#8) else (1#8)) ||| (if ((0#8).sle (v0.extractLsb 7 0)) = true then (0#8) else (1#8))) = ((if ((v0.extractLsb 7 0) == (v1.extractLsb 7 0)) = true then (0#8) else (1#8)) ||| (if ((0#8).sle (v1.extractLsb 7 0)) = true then (0#8) else (1#8))) := by
  bv_decide
