#!/bin/sh
# op-pipeline lane -- cpp -- generated by
# Research/op_pipeline/lane_gen.py .  Do not hand-edit.
# steps 1b/2/3: compile-or-refuse, then the ANCHOR and SHIP
# builds of every probe the compiler accepted, then objdump
# extraction, then the anchor's DWARF parameter table.
set -u
export HOME=/work
export PATH=/persist/swift/usr/bin:$PATH
export GOTOOLCHAIN=local
export GOPROXY=off
export GOFLAGS=-mod=mod
ROOT=/work/regen_cpp_c0013
export GOCACHE="$ROOT/gocache"
export GOPATH="$ROOT/gopath"
# swift's binaries want libncurses.so.6 and the image ships
# only libncursesw.so.6.6; the symlink lives in the image's
# own /usr/lib and does NOT survive a container restart.
if [ -f /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 ]; then
  ln -sf /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 \
     /usr/lib/x86_64-linux-gnu/libncurses.so.6 2>/dev/null
  ldconfig 2>/dev/null
fi
echo "=== op pipeline -- cpp -- 400 candidate probes ==="
date -u +%Y-%m-%dT%H:%M:%SZ
# refuse in seconds rather than in an hour
if ! /usr/bin/clang++ --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: /usr/bin/clang++ is not runnable in this container."
  echo "!! tried: /usr/bin/clang++ --version"
  exit 4
fi
/usr/bin/clang++ --version 2>&1 | head -2
if ! objdump --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: objdump is not runnable."
  exit 4
fi
objdump --version 2>&1 | head -1
rm -rf "$ROOT"; mkdir -p "$ROOT" "$GOCACHE" "$GOPATH"
df -Pm /work | awk 'NR==2{print "free /work: " $4 " MB"}'
FREE=`df -Pm /work | awk 'NR==2{print $4}'`
if [ "$FREE" -lt 400 ]; then
  echo "!! REFUSING TO START: only $FREE MB free on /work, need 400"
  exit 3
fi
base64 -d <<'T_EOF' | gunzip > "$ROOT/table.json"
H4sIAAAAAAAC/7Wc3W4cV3ZGX4VQbhzAE3fV3rt+kiBAEmBeIJdRIFAy/QPIpCCTGA8Mv3uOlE6L
VfVVU6uMb2484ni4tVDsU4vdtdfvr97f3v/4dPvj3at/vnn17sOHV9/evHp4evz0p+/aP7/7ePfj
3f2b9j+8eXc6dfFPj789fvpXPnx8eHv3a/u3/vv3V/ftH9WfTu3Lv/79l7cP7z/9nx8+vPn0tVeX
L765++323afv+/jx6e7TVx+ePr77PPW7724+f7vP3+TmL3+5efvz/e3Hv9/85fX9P/x8/+790/d3
N//67tfH73++f/y3xdcefvlw+/Fu8bX7u7+1P7++v/vt8e7j/c3rV//5+tXN7dPjw+v781/pmzdv
2jfq+unN483ttzdv/uv28ebp/teff7y/+/7mzb+/e/f0y83bf3x9//vr+5v2n493j0/tG93etL/X
v7y+/+P1/as/vr25UHeCuqPUnZ26u07914/tbwmoe0HdU+reTt1fpX7/cP8jv+Ah0IOihx09vgKd
XvUU6EnR046eV9F//enh4yO/7CXYi7KXnb2+hp1e90GwD5R9sLMPa/Y3b3/oBsA5Cs6Rco52znHD
+cP7h9tPfwask2CdKOtkZ522rB/QNZ0F50w5ZzvnvOH8+e0v6Ip2wr866l+d3b+605b0///09azC
ujpqXZ3durqNdb15OgArZKujstXZZatby9bbh4f3gFJ4VUe9qrN7Vbf2qnc/3X4ElEKhOqpQnV2h
uhSU3YB+aoUwdVSYOrswdSVIo0ekQo86qkedXY+6QZCyg0j4UUf9qLP7Ubf2o+8fnt6+vwOcwo06
6kad3Y26tRt9tkCAKdSoo2rU2dWoW6vRT7fvf/h6yl5oUU+1qLdrUb/WovbfAaTwoZ76UG/3oX7t
Q5/fhvh6SiFCPRWh3i5Cfa8o6RsOvfChnvpQb/ehPiQsfIehF1rUUy3q7VrUp4Klt5demFFPzai3
m1FfCha+YoUa9VSNersa9Ws1+r/3yb4eU4hRT8Wot4tRP0pMfDIJPeqpHvV2PeonTUuPJmFJPbWk
3m5J/dqSzu/4sl9PQ8hSUFkKuyzFScMiZwrhTEGdKezOFJ1mZQdxCHUKqk5hV6for8BCYuFPQf0p
7P4UoYnhHSiEQAUVqLALVKwF6vDn7iEkKqhEhV2ionaB4X0ohEoFVamwq1QMe8DwTiSUKqhShV2p
YtzDZfcioVRBlSrsShXTHi08m4VTBXWqsDtVzFdx6ZGVQq6SylXa5SpP16nhuZVCs5JqVto1K7ur
1OznO4VtJbWttNtW9nvM0D5SuFZS10q7a2Vc58UvaCFdSaUr7dKV+QI2fUUL9UqqXmlXr1yr198+
GQj5vCuFciVVrrQrV35SrqfFYwb0B1nIVlLZSrts5bgB/Q/0jEEKzUqqWWnXrJw2nH/9/IAXeO4p
hWIlVay0K1bOW1R2GpWwqqJWVXarqtMG9NOTmfSVWsKmitpU2W2qOk1Lr63wqKIeVXaPql7SHvol
oYRKFVWpsqtUxRVkepWFRhXVqLJrVKVEPqaOJRyqqEOV3aGqrjHT6yx0qqhOlV2napDMh9+pLCFX
ReWq7HJV4wvY9GoL1yrqWmV3rZquYx87xIV8FZWvsstXzV/DDq/7IHxsoD422H1sOF1nP3asD0LP
Bqpng13Phu6r4OmVF7Y2UFsb7LY2bG0N7gkNwtEG6miD3dGGraMdWBQahJ0N1M4Gu50NKWDRptAg
lGygSjbYlWzYKhleFRqEiQ3UxAa7iQ2DQMXrM4Pwr4H612D3r2HrX0eWhQahXQPVrsGuXcNGu9i2
0CAMa6CGNdgNa9gYFvsUfBQyNVKZGu0yNZ4UJtsXGoU6jVSdRrs6jZ1CZQtDoxClkYrSaBelsVeo
6DQahSmN1JRGuymNG1Oiz3SPwpJGakmj3ZLGjSXBnaFRSNJIJWm0S9K4kSS2NDQKQRqpII12QRo3
goSeOhqFGY3UjEa7GY0bM2JPY4xCiUaqRKNdicZJYtK3IEZhRiM1o9FuRuOsaeF7DpMQpIkK0mQX
pOkkaeldZhKONFFHmuyONHWSlr1qJyFJE5WkyS5J00aS4LNTk1CkiSrSZFekKTQnPZ4mIUoTFaXJ
LkpT7uDS80n40kR9abL70rTxpUMPbU9CmyaqTZNdm6ZhhxbZ0yTsaaL2NNntaRp3YOFxLCRqohI1
2SVqmq7RQmRhUhM1qcluUtO8gwxvRLNQqZmq1GxXqXmjUoc/mZ+FTs1Up2a7Ts3dPjG8Hc1CqmYq
VbNdquZ+l5jdkGYhVzOVq9kuV3Ps8qJb0izkaqZyNdvlas5dXHZCz8KuZmpXs92u5rrOi88toVkz
1azZrlnz8AI2PbyEcM1UuGa7cM3jdWz4Iy68a6beNdu9a552oamGCOuaqXXNduua5xeA4Ys6RD49
aD497Pn0OJ1e4mav6hAB9aAB9bAH1OO0kTC6ThQimh40mh72aHqb8M3nz+L5HlGINnrQNnrY2+ht
whdCtEAUooAetIAe9gJ6m/AFkG4OhSidBy2dh7103iY8Y4RHziAIB0o42AmHL4QHdoVC5MyD5szD
njNvE1aY9GpOAnOimJMdc1piHjH/EDXzoDXzsNfM2wTFCq+r6JkH7ZmHvWfeJixZj9mfCJoHDZqH
PWjeJkhYemWFCNGgediD5m3CEvbo+4wh0uZB0+ZhT5u3CXu89PoKS6KR87BHztuEHd5DR7PonQft
nYe9d94mXIWmV1qYFE2fhz193ibsQB88rIVY0Q562DvobcJ1anqthWfRKnrYq+htwhdqttcTIoge
NIge9iB6m/CMEC/0hAiiBw2ihz2I3iY8pySbPCFq6EFr6GGvobcJzwjhCk+IFnrQFnrYW+htwnNG
us0SIoIeNIIe9gh6m/CM8ukAphAmmj8Pe/68Tbhgom2dEMXzoMXzsBfP24QLH/qYOUTmPGjmPOyZ
8zZhwYf2c0I0zoM2zsPeOG8TFoxoMSdE2Txo2TzsZfM2YcHIjhrhODRnHvaceZtwQYQPSYdomAdt
mIe9Yd4mXAjZDk6IcHnQcHnYw+VtwgUQLd+EaJUHbZWHvVXeJlz4yEM6IcLkQcPkYQ+TtwkXPPTE
QogUedAUedhT5G3Cko++CSAC5EED5GEPkLcJK0z4W7/IjgfNjoc9O94mLDHxTUPYDc2Nhz033iYs
MeErU+gNrYyHvTLeJlwg2bNDIbriQbviYe+KtwkrQHr2iJJ40JJ42EvibcKaEx4+oh0etB0e9nZ4
m/CF88BTyiFy4UFz4WHPhbcJa0zkPSISHjQSHvZIeJuwpmSHrIiCB42Chz0K3iZITMgqHIiWwMNe
Am8T1qzwviJC4EFD4GEPgbcJF87Dn1WLFHjQFHjYU+BtgkCldxehQ7QGHvYaeJuwRYX3F6FFtAUe
9hZ4m7AFRXcYkQIPmgIPewq8TdhysnNXVMCDVsDDXgFvE3ZA6aEkOuBBO+Bh74C3CXu88GQSEfCg
EfCwR8DbhB1e+NMsjIn2v8Pe/24TtrTQI0T1O2j1O+zV7zZhjxS/cIU40eR32JPfbcIuMH3lCn2i
se+wx77bhAswXmMRYe+gYe+wh73bhG8+W9KBNRaR7w6a7w57vrtN+ELI1lhEoztoozvsje424Qsg
XmMRKe6gKe6wp7jbhGeM7KwRve2gve2w97bbhC+ER9ZYRG07aG077LXtNmGFSa+msCDa2Q57Z7tN
WGIe8nmR2g6a2g57artNUKz0ugoFoq3tsLe224Ql6zHfE63toK3tsLe22wQJS6+sECGa2g57artN
WMIefmtQNLeDNrfD3txuE/Z44fUV8e2g8e2wx7fbhB3eQ0ezyHAHzXCHPcPdJlyFpldamBQNcoc9
yN0m7EAfO6xFnDtonDvsce424To1vdbCs2ipO+yl7jbhCzVcYxGN7qCN7rA3utuEZ4R8jUUkuoMm
usOe6G4TnlOiNRaR5w6a5w57nrtNeEZI11hEmztomzvsbe424Tkj3u8QTe6gTe6wN7nbhGeUB9ZY
RIw7aIw77DHuNuGCydZYRH47aH477PntNuHCxz4nFsntoMntsCe324QFH1tjEbntoLntsOe224QF
I1tjEY3toI3tsDe224QFIztqhOPQrnbYu9ptwgWRPpEsWtpBW9phb2m3CRdCuMYi+tlB+9lh72e3
CRdAtsYiitlBi9lhL2a3CRc+9LCNqGMHrWOHvY7dJlzw2FMJIocdNIcd9hx2m7Dko28CiAZ20AZ2
2BvYbcIKE/7WL8LXQcPXYQ9ftwlLTHrTEL3roL3rsPeu24QlJnxlCr2hleuwV67bhAskfExIZK2D
Zq3DnrVuE1aA+OwRikM71mHvWLcJa056+AjToeHqsIer24QvnEceMxap6qCp6rCnqtuENSbyHtGn
DtqnDnufuk1YU6JDNkWOOmmOOu056jZBYkLWTrB2lLWzs3ZrVnZfSRGgThqgTnuAuk24cB79rDpF
iTppiTrtJeo2QaCyu0uKJnXSJnXam9RtwhYV3V9ShKmThqnTHqZuE7ag5A6TIk+dNE+d9jx1m7Dl
hOfuKEBHCjraQccdUHwoTYJ3oryTnXfa46Un0yx4Z8o723nnHV720yx61Ul71WnvVbcJW1roESJW
nTRWnfZYdZuwR0pfuCJYnTRYnfZgdZuwCwxfuaJYnbRYnfZidZtwAaZrLCki1Ukj1WmPVLcJ31w+
5OSrLCmq1Emr1GmvUrcJS0q0zpKiQp20Qp32CnWbsISkKy0putNJu9Np7063CStOePYIS6Kd6bR3
ptuEJeWB1ZYUwemkwem0B6fbBIEKr6qoTietTqe9Ot0mbFEPub5oUCdtUKe9Qd0m7PHS6ysUifao
096jbhO2vMecUKSpk6ap056mbhN2gekVFsJEI9Vpj1S3CVvgw28jinB10nB12sPVbcI1ZnqdhU3R
mHXaY9ZtwhXmY0e20CtauE574bpNeBGcXnFhXDR7nfbsdZtwBfzgIS4EjNaw017DbhNeJofXXFSy
k1ay017JbhOW5GwVJkUqO2kqO+2p7DZhRYnXYVJEs5NGs9MezW4T1qQf0PUU0kXb2WlvZ7cJK0q4
FpOioZ20oZ32hnabsOakOyMpMtpJM9ppz2i3CSvSpwOoQqxoSjvtKe02YYGKVmRSdLSTdrTT3tFu
ExaM7HNokdFOmtFOe0a7TdgwolWZFDXtpDXttNe024QNJ1qXSVHTTlrTTntNu03YcKLjR8S0k8a0
0x7TbhMWmPAJ6BQt7aQt7bS3tNuEBSVbnUmR0k6a0k57SrtNWECi9ZkUHe2kHe20d7TbhAUjetBH
5LOT5rPTns9uExaI7KkIkc5Oms5Oezq7Tdgy0jcTRDo7aTo77ensNkGgwncPRDo7aTo77ensNmGL
im8owoJoPDvt8ew2YYvKXqminp20np32enabsACFjy6JcnbScnbay9ltgoCk55GoZietZqe9mt0m
KFZ4IIlidtJidtqL2W3CkvXIY9Ail500l532XHaboFCRH4lcdtJcdtpz2W2CIoWHr9AkGspOeyi7
TdhFhbzClWgnO+2d7DZB8dJ7jpAlGsxOezA7aylLhz8zF/XspPXstNezs+YdXHjnES3tpC3ttLe0
czhpXHbvEVHtpFHttEe1c+g0LLr7iLx20rx22vPaOfSalZ3HIrKdNLKd9sh2DnEFlh5UoridtLid
9uJ2DnmNmZ5WQqloeTvt5e0c6goz/MkWZkX722nvb+cwaGLoGiLAnTTAnfYAdw7jNVr8QhaCRUPc
aQ9x5zBdhaavZKFZtMad9hp3DkvNwms6IsKdNMKd9gh3niPcnz94PLCmI6rbSavbaa9u57m6faFk
azqisp20sp32ynaeK9sXSLymI7raSbvaae9q57mr/YWTnT+io520o532jnaeO9oXyiNrOiKonTSo
nfagdp6D2ktUelWFLdGqdtqr2nmuai9QD/0OIBrbSRvbaW9s57mxLXjp9RWqRHvbae9t57m3veA9
5oYivZ00vZ329Hae09sKGF5hEeFOGuFOe4Q7p9MW+PBbjiLMnTTMnfYwd07dNWZ6nYVN0Vh32mPd
OfVXmA8d2aLgnbTgnfaCd07xIji94sK4aNY77VnvnPIK+LFDXNS+k9a+0177zqleJqfXXPgYrYCn
vQKe08rH4JqOSIEnTYGnPQWe08rCDqzpiCh40ih42qPgOU1rUrSmI9rgSdvgaW+D57SSLrymIxrh
SRvhaW+E53xac+LdFZEJT5oJT3smPOeVYR1Z0xGp8KSp8LSnwnNeihVb0xGd8KSd8LR3wnNeOhT7
rFpkwpNmwtOeCc85N4xsTUfUwpPWwtNeC8+5NpxsTUfUwpPWwtNeC8952HCy40e4EI2Fpz0WnvPS
hehT1aIVnrQVnvZWeM5LD4JrOiIVnjQVnvZUeM5LDUJrOiU64UU74WXvhNdpqUDkQaASefCiefCy
58HrtHQf9JREiTR40TR42dPgdeq3jPDNhBJp8KJp8LKnwesUApW9e1AiDV40DV72NHidcosKbygl
4uBF4+Blj4PXqbao8JU6CNCBgg520KUGsceYSpTBi5bBy14Gr9MoIPF5NAnWibJOdtZJsdIDaRas
M2Wd7axLIzryqHSJHHjRHHjZc+DVnRQq8iORAy+aAy97Dry6TpGyw1eEwIuGwMseAq+u30WFvMKV
aAe87B3w6kLxwnuOCIIXDYKXPQhe3VKWjn5mXqIMXrQMXvYyeHW1gwvvPKIRXrQRXvZGeHWDxoX3
HqFPNBRe9lB4daOGZXcfoU80F172XHh1k2aF57HwJxoML3swvLr5Ciw9qEQ5vGg5vOzl8OpP15jh
aSXq4UXr4WWvh1ffXWFmP9miH160H172fnj1vSaGriHi4UXj4WWPh1cf12jxC1kIFg2Ilz0gXn1e
haavZKFZtCBe9oJ49UvNoms6JaLhRaPhZY+G1zkaPh3a0ikRCC8aCC97ILzOgfDpyJJOiRZ40RZ4
2VvgdW6BTwd3dEqEv4uGv8se/q5z+Hs6tKJTovFdtPFd9sZ3nRvf0/ENnRKd76Kd77J3vuvc+Z6O
L+iU6HwX7XyXvfNd58739Cf3c0oEv4sGv8se/K5z8Hv6k+s5JbrfRbvfZe9+17n7Pf3Z7ZwS9e+i
9e+y17/rXP+e/uxyTokEeNEEeNkT4BXDhvfw+4yiCF60CF72InjFeAWZXmXhUDQQXvZAeMW0j3zs
sBZSRYPhZQ+GV8wvccPrLQLiRQPiZQ+IV572uY8d3yIpXjQpXvakeGX3Iji94sLCaGW87JXxyqWF
sa2cEpXxopXxslfGK5fuxZdySqTGi6bGy54ar8wV6Ad0NYVq0dh42WPjlUvVois5JXrjRXvjZe+N
Vw4rTLqmUqI2XrQ2XvbaeOXSqw4s5JSIjReNjZc9Nl650Cm0j1MiMl40Ml72yHjlwpzYZ9IiL140
L172vHjVaY2ItnFKBMaLBsbLHhiv6taYaBmnRFu8aFu87G3xqn6NiU4eURUvWhUve1W8amFA9Mlp
0RMv2hMve0+8amE/bBOnREm8aEm87CXxqoX8sEUcURAvWhAve0G8aiE+6Ekf0Qwv2gwvezO8amE8
7CkIkQovmgoveyq8atog0rcORCW8aCW87JXwqnlLCt8rEIHwooHwsgfCazhtSOmdRNTBi9bBy14H
r6HbkLJXqSiDFy2Dl70MXsNCfuATSiIIXjQIXvYgeA2xZaRHkeiAF+2Al70DXkMKVHoWCQ+i+e+y
579rWHjQoUegRfa7aPa77NnvGgZBiqxIFL+LFr/LXvyuYRSg8NgVckQz32XPfNcw7ZFCXGFINPBd
9sB3DbPAhTcbEfkuGvkue+S7xoUiHf5EXMS+i8a+yx77rrHTtPCWI6rfRavfZa9+19hLWnbTEeXv
ouXvspe/awzJim47Iv9dNP9d9vx3jSlR2Uks+t9F+99l73/XWPus+IwS+kQ74GXvgNc4XEGmB5UQ
KZoCL3sKvMZxHxn+WAufoi3wsrfAa5wkMFUMYVO0A172DniN8xVY+iIWKfCiKfCyp8BrOl1jhq9i
kQIvmgIvewq8poVc4XUbEf8uGv8ue/y7Tfjm/B7igW0b0fku2vkue+e7TXjOyJZtRNG7aNG77EXv
NuE5It61EfXuovXuste724QFJTx2hC/RTnfZO91twnPGI5s2ItVdNNVd9lR3m7ABpVdU2BEtdZe9
1N0mrEEP+b4odhctdpe92N0maFp4bUW3u2i3u+zd7jZhTXvMA0W8u2i8u+zx7jZhB5deXSFHNOBd
9oB3m7DGPfyOosh5F815lz3n3SbsE9NrLMyJxr3LHvduE3aJDx3TovVdtPVd9tZ3m/ACNr3awq5o
+rvs6e82YRf74MEtZIu2wMveAm8TXuKm11u4F62Dl70O3iY854bbNSIOXjQOXvY4eJuwYPza5Zr/
+eN/AdX5CMdZcAEA
T_EOF
echo "payload bytes: $(wc -c < "$ROOT/table.json")"
python3 - "$ROOT" <<'PY_EOF'

import json, os, re, shutil, subprocess, sys, time

ROOT = sys.argv[1]
T = json.load(open(os.path.join(ROOT, "table.json")))
LANG = T["language"]
PROBES = T["probes"]
OUT = T["out"]
out = open(OUT, "w")
WORK = os.path.join(ROOT, "u")

# --- verbatim delimiter codec, copied from verbatim_diag.py ---
def esc(text):
    """make `text` safe to place in one pipe-delimited field, reversibly."""
    for raw, rep in _ENC:
        text = text.replace(raw, rep)
    return text

_ENC = [('\\', '\\\\'), ('|', '\\p'), (';', '\\s'), ('\n', '\\n'), ('\r', '\\r')]
MARKER = '#verbatim-escape v1'
out.write(MARKER + '\n')


print("op lane %s: %d candidate probes" % (LANG, len(PROBES)))
sys.stdout.flush()


def sh(cmd, cwd=None, timeout=180):
    try:
        p = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE, timeout=timeout)
        so = p.stdout.decode("utf-8", "replace")
        se = p.stderr.decode("utf-8", "replace")
        return p.returncode, so, se
    except subprocess.TimeoutExpired:
        return 124, "", "TIMEOUT after %ds" % timeout
    except OSError as e:
        return 125, "", "OSError %s" % e


# ------------------------------------------------------ objdump reading

LABEL = re.compile(r"^([0-9a-f]+)\s+<(.+)>:\s*$")
INSN = re.compile(r"^\s*([0-9a-f]+):\t(.*)$")
RELOC = re.compile(r"^\s+([0-9a-f]+): (R_\S+)\t(.+?)\s*$")


def extract(text, sym, exact):
    """the two columns for one symbol.

    bytes  every byte objdump printed, in order, flattened
    mnem   the instruction text, with objdump's own trailing `# ...`
           comment dropped -- that comment is arithmetic objdump did
           for the reader, not part of the instruction.  A relocation
           is appended to the instruction it applies to as
           ` !!reloc=<type>:<symbol>`, because in an object file the
           call displacement is literally zero and the callee's name
           lives only in the relocation.
    """
    lines = text.splitlines()
    k = -1
    for idx, ln in enumerate(lines):
        m = LABEL.match(ln)
        if not m:
            continue
        lab = m.group(2)
        hit = (lab == sym) if exact else (sym in lab)
        if hit:
            k = idx
            break
    if k < 0:
        return None
    raw = []
    mn = []
    for ln in lines[k + 1:]:
        if LABEL.match(ln):
            break
        m = INSN.match(ln)
        if not m:
            r = RELOC.match(ln)
            if r and mn:
                mn[-1] = "%s !!reloc=%s:%s" % (mn[-1], r.group(2), r.group(3))
            continue
        parts = m.group(2).split("\t")
        bs = parts[0].split()
        raw.extend(bs)
        txt = parts[1] if len(parts) > 1 else ""
        txt = txt.split("#")[0]
        txt = " ".join(txt.split())
        if txt:
            mn.append(txt)
    return raw, mn


def disasm(obj, sym, exact):
    rc, so, se = sh(["objdump", "-dr", "--disassemble=" + sym, obj])
    got = extract(so, sym, exact) if rc == 0 else None
    if got is None:
        rc, so, se = sh(["objdump", "-dr", obj], timeout=600)
        got = extract(so, sym, exact)
    return got


# --------------------------------------------------------- DWARF reading
#
# objdump --dwarf=info prints one entry per line block:
#
#   <1><2d>: Abbrev Number: 2 (DW_TAG_subprogram)
#      <2e>   DW_AT_name        : op_12
#   <2><4a>: Abbrev Number: 3 (DW_TAG_formal_parameter)
#      <4b>   DW_AT_name        : a
#      <52>   DW_AT_location    : 2 byte block: 91 7c (DW_OP_fbreg: -4)
#
# The leading <N> is the tree depth.  A formal parameter one level
# below the matching subprogram is a parameter OF that subprogram.

DIE = re.compile(r"^\s*<(\d+)><[0-9a-f]+>:\s*Abbrev Number:\s*\d+\s*\((\S+)\)")
ATTR = re.compile(r"^\s*<[0-9a-f]+>\s+(DW_AT_\w+)\s*:\s*(.*?)\s*$")


def clean(text):
    text = " ".join(text.split())
    return text


STRPREFIX = re.compile(r"^\((?:indexed string|indirect string)[^)]*\):\s*")


def dwname(text):
    """objdump prints a string attribute as `(indexed string: 0x5): a`.
    The parenthesised part is objdump telling the reader WHERE in the
    string table it found the name; the name is what follows.  Keeping
    the prefix would have put objdump's bookkeeping into the parameter
    name column."""
    return STRPREFIX.sub("", text.strip())


def dwarf_params(text, sym):
    """[(name, location)] for the subprogram named `sym`.

    More than one subprogram can carry the name.  swift's `@_cdecl`
    emits a C-entry thunk beside the real function, and the thunk has
    no DW_TAG_formal_parameter children at all, so the first match is
    not always the one holding the parameter table.  Every match is
    collected and the first one that actually has parameters wins."""
    lines = text.splitlines()
    depth = None
    tag = None
    attrs = {}
    entries = []
    for ln in lines:
        m = DIE.match(ln)
        if m:
            if tag is not None:
                entries.append((depth, tag, attrs))
            depth = int(m.group(1))
            tag = m.group(2)
            attrs = {}
            continue
        a = ATTR.match(ln)
        if a and tag is not None:
            attrs[a.group(1)] = a.group(2)
    if tag is not None:
        entries.append((depth, tag, attrs))

    hits = []
    for idx, (d, t, at) in enumerate(entries):
        if t != "DW_TAG_subprogram":
            continue
        names = []
        if "DW_AT_name" in at:
            names.append(dwname(at["DW_AT_name"]))
        if "DW_AT_linkage_name" in at:
            names.append(dwname(at["DW_AT_linkage_name"]))
        for nm in names:
            if nm == sym or sym in nm:
                hits.append(idx)
                break
    if not hits:
        return None
    best = []
    for k in hits:
        base = entries[k][0]
        got = []
        for d, t, at in entries[k + 1:]:
            if d <= base:
                break
            if d != base + 1:
                continue
            if t != "DW_TAG_formal_parameter":
                continue
            nm = clean(dwname(at.get("DW_AT_name", "(unnamed)")))
            loc = clean(at.get("DW_AT_location", "(no location)"))
            got.append((nm, loc))
        if got:
            return got
        best = got
    return best


def dwarf(obj, sym):
    rc, so, se = sh(["objdump", "--dwarf=info", obj], timeout=600)
    if rc != 0:
        return None, "objdump --dwarf=info rc=%d" % rc
    got = dwarf_params(so, sym)
    if got is None:
        return None, "no DW_TAG_subprogram named %s" % sym
    if not got:
        return None, "subprogram %s has no DW_TAG_formal_parameter" % sym
    return got, None


# ------------------------------------------------------------ compiling

GOMOD = "module opprobe\n\ngo 1.26\n"

CLANG = "/usr/bin/clang"
CLANGXX = "/usr/bin/clang++"
SWIFTC = "/persist/swift/usr/bin/swiftc"


def compile_probe(p, d, mode):
    """(rc, artifact path, diagnostic text)."""
    if LANG == "c":
        src = os.path.join(d, "unit.c")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANG, "-std=c17"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "cpp":
        src = os.path.join(d, "unit.cpp")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANGXX, "-std=c++20"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "rust":
        src = os.path.join(d, "unit.rs")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        if mode == "anchor":
            opt = ["-C", "opt-level=0", "-g"]
        else:
            opt = ["-C", "opt-level=1", "-C", "debug-assertions=off"]
        cmd = (["rustc", "--crate-type=lib", "--emit=obj"] + opt
               + ["-o", obj, src])
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "go":
        open(os.path.join(d, "go.mod"), "w").write(GOMOD)
        open(os.path.join(d, "main.go"), "w").write(p["source"])
        obj = os.path.join(d, "bin_%s" % mode)
        cmd = ["go", "build"]
        if mode == "anchor":
            cmd.append("-gcflags=-N -l")
        cmd.extend(["-o", obj, "."])
        rc, so, se = sh(cmd, cwd=d, timeout=300)
        return rc, obj, (se or so)
    if LANG == "swift":
        src = os.path.join(d, "unit.swift")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-Onone", "-g"] if mode == "anchor" else ["-O"]
        cmd = [SWIFTC] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd, timeout=300)
        return rc, obj, (se or so)
    raise KeyError(LANG)


DIAG = re.compile(r"^[^\s:]+:\d+(:\d+)?:")


def firstline(txt):
    """the compiler's own words for why it refused.

    The first line is not reliably the reason.  clang leads with a
    warning and puts the error underneath.  go leads with a banner
    naming the package -- `# opprobe` -- and its diagnostics never
    contain the word `error` at all, so a rule that only looked for
    that word recorded the banner and threw the testimony away.
    Three passes, in order: a line saying `error`, a line in the
    `file:line:col:` diagnostic shape, then the first line that is
    not a banner."""
    lines = []
    for ln in txt.splitlines():
        s = ln.strip()
        if s:
            lines.append(s)
    for ln in lines:
        if re.search(r"\berror\b", ln, re.I):
            return ln[:200]
    for ln in lines:
        if DIAG.match(ln):
            return ln[:200]
    for ln in lines:
        if not ln.startswith("#"):
            return ln[:200]
    if lines:
        return lines[0][:200]
    return "(no diagnostic)"


def write_unit(n, build, obj, sym, exact):
    got = disasm(obj, sym, exact)
    if got is None:
        rc2, so2, se2 = sh(["objdump", "-t", obj])
        near = 0
        for l in so2.splitlines():
            if sym in l:
                near += 1
        out.write("op_%d|%s|NOSYM|%s\n"
                  % (n, build, esc("symbol %s absent, %d near matches"
                                   % (sym, near))))
        return False
    raw, mn = got
    out.write("op_%d|%s|OK|%s|%s\n"
              % (n, build, " ".join(esc(x) for x in raw),
                 ";".join(esc(x) for x in mn)))
    return True


t0 = time.time()
tally = {"REFUSED": 0, "ACCEPTED": 0, "ANCHOR_OK": 0, "SHIP_OK": 0,
         "DWARF": 0}

for k, p in enumerate(PROBES):
    n = p["n"]
    sym = p["symbol"]
    exact = p["symbol_exact"]
    d = os.path.join(WORK, "n%d" % n)
    shutil.rmtree(d, ignore_errors=True)
    os.makedirs(d)

    rc, obj, err = compile_probe(p, d, "ship")
    if rc != 0 or not os.path.exists(obj):
        out.write("op_%d|REFUSED|%s\n" % (n, esc(firstline(err))))
        tally["REFUSED"] += 1
        out.flush()
        shutil.rmtree(d, ignore_errors=True)
        continue
    tally["ACCEPTED"] += 1
    if write_unit(n, "SHIP", obj, sym, exact):
        tally["SHIP_OK"] += 1

    rc, aobj, aerr = compile_probe(p, d, "anchor")
    if rc != 0 or not os.path.exists(aobj):
        out.write("op_%d|ANCHOR|BUILDFAIL|%s\n" % (n, esc(firstline(aerr))))
    else:
        if write_unit(n, "ANCHOR", aobj, sym, exact):
            tally["ANCHOR_OK"] += 1
        rows, why = dwarf(aobj, sym)
        if rows is None:
            out.write("op_%d|ANCHOR|NODWARF|%s\n" % (n, esc(why)))
        else:
            joined = ";".join("%s=%s" % (esc(a), esc(b)) for a, b in rows)
            out.write("op_%d|ANCHOR|DWARF|%s\n" % (n, joined))
            tally["DWARF"] += 1
    out.flush()
    shutil.rmtree(d, ignore_errors=True)

    if (k + 1) % 25 == 0 or (k + 1) == len(PROBES):
        el = time.time() - t0
        print("[progress] %s [%d/%d] elapsed %.1fs mean %.2fs  "
              "REFUSED %d ACCEPTED %d SHIP_OK %d ANCHOR_OK %d DWARF %d"
              % (LANG, k + 1, len(PROBES), el, el / (k + 1),
                 tally["REFUSED"], tally["ACCEPTED"], tally["SHIP_OK"],
                 tally["ANCHOR_OK"], tally["DWARF"]))
        sys.stdout.flush()

out.close()
print("done: %s -> %s" % (json.dumps(tally), OUT))

PY_EOF
echo "--- lane finished, rc=$?"
date -u +%Y-%m-%dT%H:%M:%SZ
