#!/bin/sh
# op-pipeline lane -- cpp -- generated by
# Research/op_pipeline/lane_gen.py .  Do not hand-edit.
# steps 1b/2/3: compile-or-refuse, then the ANCHOR and SHIP
# builds of every probe the compiler accepted, then objdump
# extraction, then the anchor's DWARF parameter table.
set -u
export HOME=/work
export PATH=/persist/swift/usr/bin:$PATH
export GOTOOLCHAIN=local
export GOPROXY=off
export GOFLAGS=-mod=mod
ROOT=/work/regen_cpp_c0030
export GOCACHE="$ROOT/gocache"
export GOPATH="$ROOT/gopath"
# swift's binaries want libncurses.so.6 and the image ships
# only libncursesw.so.6.6; the symlink lives in the image's
# own /usr/lib and does NOT survive a container restart.
if [ -f /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 ]; then
  ln -sf /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 \
     /usr/lib/x86_64-linux-gnu/libncurses.so.6 2>/dev/null
  ldconfig 2>/dev/null
fi
echo "=== op pipeline -- cpp -- 400 candidate probes ==="
date -u +%Y-%m-%dT%H:%M:%SZ
# refuse in seconds rather than in an hour
if ! /usr/bin/clang++ --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: /usr/bin/clang++ is not runnable in this container."
  echo "!! tried: /usr/bin/clang++ --version"
  exit 4
fi
/usr/bin/clang++ --version 2>&1 | head -2
if ! objdump --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: objdump is not runnable."
  exit 4
fi
objdump --version 2>&1 | head -1
rm -rf "$ROOT"; mkdir -p "$ROOT" "$GOCACHE" "$GOPATH"
df -Pm /work | awk 'NR==2{print "free /work: " $4 " MB"}'
FREE=`df -Pm /work | awk 'NR==2{print $4}'`
if [ "$FREE" -lt 400 ]; then
  echo "!! REFUSING TO START: only $FREE MB free on /work, need 400"
  exit 3
fi
base64 -d <<'T_EOF' | gunzip > "$ROOT/table.json"
H4sIAAAAAAAC/7Xc7YodZ3bF8VtplC8KeKKz967XJASSwNxAPkZBtOT2C8jdQpYYD8b3nkcan7eq
Vaf1L1hjsLHG1vbqOuep1adr/35/8f7+8cfP9z8+vPjXuxfvPnx48d3di6fPn7783av211cfH358
eHzT/o837w6HOvzLp98+fflHPnx8evvwa/un/vf3F4/tL5GHw6H9+q9//+Xt0/sv//bThzdff/HF
6VffPPx2/+7L7/zp4+eHL7/69Pnju69zX726+/ob/uO3ufvLX+7e/vx4//Hvd69eP/7Tz4/v3n/+
/uHu39/9+un7nx8//cfVrz398uH+48PVrz0+/K39/evHh98+PXx8vHv94r9fv7i7//zp6fXj8T/q
5U/373+4u//u7v3T44933z99fvv+4e7tP79+/P31413738eHT5/bv3p/9+ru7b+9fvzj9eOLP767
O0cNFTVw1PBHjeuoX/8EgqYKmjho+oPmKeivPz19/ERClgpZOGT5Q9Yi5Jv/fPfu8y8ka6eydjhr
58/aLbP+9WP7LyNZe5W1x1l7f9b+nPXnHx8fvr9799P9RxJ1UFEHHHXwRx2WUdtvS5KOKumIk47+
pOMyKT18JxV1wlEnf9RJRqV5Z5V3xnlnf955mZfec0KVpcBlKfxlKc5l6fPjn2nxbSdUYQpcmMJf
mCJEXHrnCVWbAtem8NemyHVceO8JVZ8C16fw16eodVh29wlVnwLXp/DXp+jWWeF5HKo/Be5P4e9P
0W+E5QeVKlKBi1T4i1QMW5nxaaUqVeBKFf5KFeNGZvrKVs0qcLMKf7OKaZ0Ydw3VqwL3qvD3qpi3
0uI3cqqClbhgpb9g5WEzNH0np6pZiWtW+mtWnmvW3770jTcopqpXietV+utV5ssvBaOl5C9gVasS
16r016qsU8j/enp6TzKqOpW4TqW/TmV3yvjX90/3n9oNHsRURSpxkUp/kcr+HJOePao5JW5O6W9O
OZxC/s/9nluL6kuJ+1L6+1KO10nxNVU9KXFPSn9Pyukq6b7yn6ooJS5K6S9KOYu49OqWqkiFK1L5
K1IdruLurISl2lHhdlT+dlSh8uLrq2pS4ZpU/ppUeZV3/+eMpUpT4dJU/tJUtREZX2XVoQp3qPJ3
qOp05H2HdalSVbhUlb9UVX8rN77eqmcV7lnl71k16Nx7j29VuwrXrvLXrhpvBsdXXLWwwi2s/C2s
zi3szdsf0PdIpbpX4e5V/u5V5+715oev3wu2fvvtQTvVujrcujp/6+oOF0E/oKvZqarV4arV+atW
d65ab35++wu8lqphdbhhdf6G1eVFzMcvL1n0iVunelWHe1Xn71XduVe9+bwnqapTHa5Tnb9Odac6
9ZZ96tap5tTh5tT5m1N3ak7wZ9KdKkkdLkmdvyR1w2XEGNiLVVWiDleizl+JuvEyZiWLqQpQhwtQ
5y9A3XQZE548qgF1uAF1/gbUnRoQfnK6V+2nx+2n97ef/tR+vpY8klGVnx6Xn95ffvpT+fn6wzgQ
URWfHhef3l98+lPxYU/69Krx9Ljx9P7G058aD3wKoldVp8dVp/dXnb67iog/OuhV4+lx4+n9jafv
r5PSzwp6VXx6XHx6f/Hph6uk/E6iuk+Pu0/v7z79eJWUvktV+elx+en95ac/lR/6hFKvqk+Pq0/v
rz79fJ0RH0WDKkADLkCDvwANh0VUehYNqgcNuAcN/h40nHrQvkegB1WHBlyHBn8dGnKRlLWiQbWi
Abeiwd+KhloEhcfuoMrRgMvR4C9HQ6eS0riqIQ24IQ3+hjT0i7j0ZjOoijTgijT4K9Jwqkj7fyI+
qJo04Jo0+GvSMK7T4luOKksDLkuDvywN0yotvemo0jTg0jT4S9Mwr7Ky286oStOIS9PoL03jYRUV
nsSjak0jbk2jvzWNobPiM2pU9WnE9Wn016cxNyLTg2pURWrERWr0F6mxdGT6slZ9asR9avT3qbFb
BaYVY1RtasRtavS3qbHfCMvfxKpWjbhWjf5aNQ5bmfG7WJWrEZer0V+uxlO54us2oypVIy5Vo79U
jdPLr8fSnn2bUdWpEdep0V+nxvmcEi7cTKpITbhITf4iNR3OIfnGzaRK1IRL1OQvUVNc5ITHz6R6
04R70+TvTVOeU+7auZlUX5pwX5r8fWmqRVR8VVVTmnBTmvxNaequo+5r/5MqSxMuS5O/LE29youv
rypKEy5Kk78oTcN13p3NcFItacItafK3pGmUgfEVVoVpwoVp8hemaboOvP9zxknVpwnXp8lfn6Z5
KzO9zrNqUzNuU7O/Tc2Hjcz7juxZ1asZ16vZX6/muBkcX3HVuGbcuGZ/45pzI/jOQ3xWBWzGBWz2
F7C5bifH11z1sRn3sdnfx+aLPkb3b2bVwmbcwmZ/C5svWtieBZxZ9a8Z96/Z37/m4TIp28CZVema
cema/aVrvihdfAVnVl1rxl1r9netebrMyTdTZtWwZtywZn/Dmi8a1p4lnFCUeGBKPPyUeBtxisq2
cEIZ4oEN8fAb4m3EKSP7EXUoPjwwHx5+PryNuMrI9nBCCeKBBfHwC+JtxFVOtogTSg8PrIeHXw9v
I65ywuOnVzF7HLP3xzx3IfoAdSgzPLAZHn4zvI04pYS7OKG48MBcePi58DbiFJIt44RywgM74eF3
wtuIU0b0AFAoGjwwDR5+GryNOEVkT0iEIsEDk+DhJ8HbiOuM9MOEUBx4YA48/Bx4G7GICj89CEWB
B6bAw0+BtxHXUfENRUHggSHw8EPgbcR1VPpOVTUIK+DhV8DbiFNQ+AxTKP07sP4dfv27jViE5OeR
qkJY/Q6/+t1GLLPiA0k1Iqx9h1/7biPOWfc8IR2K+Q7MfIef+W4jllFZP1LEd2DiO/zEdxuxTAoP
XwV7B4a9ww97txEyKs2ruhI2vcNverc/lnnpPUfB3oFh7/DD3m3EKevun5mHIr4DE9/hJ77bCBGX
3nmU9h1Y+w6/9t1GrOPCe48yvwOb3+E3v9uIdVh291H0d2D6O/z0dxuxzkrPY9WfsP4dfv27jdgI
yw8qVaSwAx5+B7yN2MqMTytVqTAGHn4MvI3YyAxf2coDD+yBh98DbyPWiWnXUBp4YA08/Bp4G7GV
Fr+RFQkemAQPPwneRmyGpu9khYIHRsHDj4K3EafQeE0nFAQeGAIPPwTeRry8vA/t2NYJpX8H1r/D
r3+3EauwbGknlPgdWPwOv/jdRqyy4t2dUM53YOc7/M53G7GOS88m1ayw7R1+27uNWIXds8kTCvoO
DH2HH/puI3Rieo2V+B1Y/A6/+N1GyMT7vmlQBnhgAzz8BngbcSM2vtqqYmETPPwmeBshY++slooI
D0yEh58IbyNu5cbXW9UuDIaHHwxvI2Tu/Z9fKkg8MCQefki8jXgmOr7qqpNhYDz8wHgbcTv6zsNd
lTQsj4dfHm8jviU/vv6qt2GSPPwkeRtxO//e417VOKyVh18rbyO+6QtAXwFKMg8smYdfMm8jVl8A
uB0UijQPTJqHnzRvI9Zh+ZJQKOA8MHAefuC8jRCBP7Crq6obts7Db523EeuwdGUolHse2D0Pv3ve
Roi4fJ1G8eeB+fPw8+dtxDrwngUixaAHZtDDz6C3EcvEcI9IOeiBHfTwO+htxDIq/Jm6otADU+jh
p9DbCBUVbhUpFT2wih5+Fb2NUHHhcpGS0QPL6OGX0dsIFZedUApHD4yjhx9HbyOWafGT4cpHD+yj
h99HbyOWYenGkSLSAxPp4SfS24hlVrh4pIz0wEZ6+I30NmIZlT3hpHj0wDx6+Hn0NmKZFD4Fonj0
wDx6+Hn0NkJGxR9lKCI9MJEefiK9jdCJ6WcXikkPzKSHn0lvI2RifgdSXQpj6eHH0tsImRi+i5WY
HlhMD7+Y3kYs89InuZSYHlhMD7+Y3kborPjIUmJ6YDE9/GJ6G7ERmZ5ZSkwPLKaHX0xvI1aRdz1C
rsj0wGR6+Mn0NmIjMWtZik0PzKaHn01vIzYC02NalS2MpocfTW8jbiWmsVXjwm56+N30NmIjNr5J
qcqFEfXwI+oxrirX/icEFKoeGFUPP6oe47ydmt6qlLIeWFkPv7Ie02EzNbxZKXE9sLgefnE9ptjM
zG5Xil8PzK+Hn1+PKTcjw5NbOeyBHfbwO+wx1e3M+CxTLntglz38LntM3TPR8YGmihkm2sNPtMfU
345OX+6qn2GrPfxWe0zDZnBaVZTXHthrD7/XHtP4TGj+Jlc1DdPt4afbY5qey47f5aqsYcI9/IR7
TKuyxtelFN4eGG8PP94eR7z9zwu6Z11Kge2Bwfbwg+1xBNsvwsJ1KWW0Bzbaw2+0x9Fov8jK16UU
zB4YZg8/zB5HmP0yLjyilMUe2GIPv8UeR4v9IuyudSnlsgd22cPvssfRZV8mxtdYdS7ss4ffZ4+j
z75IvO/bCwW2Bwbbww+2xxFsl7Hx1VaFC/vt4ffb4+i3L2LvLJpKcw+suYdfc4+j5q5zw+udinZP
TLunn3bPw0Hm3v1haCrxPbH4nn7xPQ/xTHR81VNFTxw9/dHzdvRdh3sqID4xEJ9+ID4P9S358fXv
VP4O5+/8+bvb+fcd96lI+cSkfPpJ+Tz03/QFwK+AQX0BBvwFGPxfgHWrg+tSqdT5xOp8+tX5PKy7
3I51qVQEfWKCPv0EfR4mEfgDu7qzCjvjsLM/7Lq64XWpVC59Ypc+/S59xkHExctDqXT6xDp9+nX6
jHVP27MulQqpT4zUpx+pz1jVM7YulQqpT4zUpx+pz1g1MfYj+VRMfWKmPv1MfUanorJ1qVRgfWKw
Pv1gfUav4rJ1qVRmfWKzPv1mfcag4sITSjUqrNanX63PWDUq+rB6Krc+sVuffrc+Y9Wm4LpUKrk+
sVyffrk+Y1Wm2LpUKrk+sVyffrk+c1Wk0JNRqcz6xGZ9+s36zFWDYk+IpCLrE5P16SfrM1NGxR9l
KLU+sVqffrU+s3Ri+tmFgusTw/Xph+szO5kY34GUXp9Yr0+/Xp/Zy8T0XazKFBbs0y/YZ67KFHy8
KxVgnxiwTz9gnznqrPzIUoUK+/Xp9+szp43I+MxSvQrz9enn6zNXvWrXE+ip+PrEfH36+fqsw0Zi
1rKUYJ9YsE+/YJ8VG4HhMa34+sR8ffr5+qy8lZjGVo0LA/bpB+yzaiM2vUkpzD4xZp9+zD5rVbn2
PyGgVPvEqn36Vfusfjs1vVUp3z6xb59+3z5r2ExNb1aqhGHkPv3Ifda4mRnerlQJw9R9+qn7rGkz
Mj25VQvD2H36sfus+XZmfJYp9T6xep9+9T67wzPR6YGm5PvE8n365fvs4nZ0+HJX9n1i+z799n12
uRmcVhUF3yeG79MP32dXz4Tmb3JV0zB+n378Prvuuez4Xa7KGtbv06/fZ7cqa3hdKhV4nxi8Tz94
n0fw/s8PPXesS6XS7RPr9unX7fOo21+EZetSqST7xJJ9+iX7PEr2F1nxulQqtz6xW59+tz6Pbv1l
XHhEKaM+sVGffqM+j0b9Rdg961KpoPrEUH36ofo8QvXLxPgaq86Fpfr0S/V5lOoXifd9e6HM+sRm
ffrN+jya9TI2vtqqcGG7Pv12fR7t+kXsnUVTEfaJCfv0E/Z5JOx1bny9Ve3CkH36IfvsB5l7/4eh
CrZPDNunH7bPfnwmOr7qqpNh6D790H320+3oOw93VdKwfJ9++T77+Vvy0+uvKPzEFH76KfwcDrfz
7zzulY6fWMdPv46fQ3zTFwC/AlSrw2J++sX8HNatjq5LKTI/MZmffjI/h3WX27MupeD8xHB++uH8
HDoRmK1LKTs/sZ2ffjs/h3V14+tSys9P7Oen38/PYRBx+fKQ4vMT8/np5/NzWPe0XetSis9PzOen
n8/PYVXP4LqUcvMTu/npd/NzWDUx+CN5ReYnJvPTT+bneFBR4bqUUvMTq/npV/NzDBUXrkspMT+x
mJ9+MT/HVHHZCaWw/MRYfvqx/BxXjQo/rK6c/MROfvqd/BxXbYquSykiPzGRn34iP8dVmYLrUsrG
T2zjp9/Gz3FVpNiTUYrDT8zhp5/Dz3HVoOATIorBT8zgp5/Bz3GSUfFHGYrAT0zgp5/Az3HWieln
F4q/T8zfp5+/z+kgE+M7kMLvE+P36cfvcwqZGL6LlXyfWL5Pv3yf06pM0ce7lHifWLxPv3ifU+ms
+MhS0n1i6T790n1O3UZkfGapXoWF+/QL9zmtetW+J9AVbZ+Ytk8/bZ/TsJGYtSzF2idm7dPP2uc0
bgSmx7QqWxizTz9mn9N0KzGNrRoXduzT79jnNG/EpjcphdknxuzTj9nnvKpc+58QUKp9YtU+/ap9
zrGdmt6qlG+f2LdPv2+fc26mhjcrhdwnRu7Tj9znXJuZ2e1KUfeJqfv0U/c5d5uR4cmtsPvE2H36
sfuc+9uZ+Vmm6hhW79Ov3uc8PBMdH2iqmGH5Pv3yfc7j7ej05a76Gbbv02/f5zxtBsdVRbUzDN+n
H77PeX4mNH2Tl8LvC+P35cfv63B4Ljt8l5fS7wvr9+XX7+uwKmt4XaoUeF8YvC8/eF9H8P7rn3Ys
S5Wy7Qvb9uW37eto25+islWpUop9YcW+/Ip9HRX7U1K8KFVKrC8s1pdfrK+jWH8OS4+mQUUdcNTB
H3VYRN2zJFWKpy/M05efp68jT3+dF1/fSeWdcN7Jn3cSeXd9Q1FKqS+s1Jdfqa+jUi9C0yutrPrC
Vn35rfo6WvVXoXfWSgXWFwbryw/W1xGsV6nxtVYVC6P15UfrK1Kk3v2xZynCvjBhX37CvqJuBsdX
XPUvDNqXH7Sv6G4F33egK9++sG9fft++on8+Pb72qqNh7r783H3FcCv93iNeVTbs35ffv68YvyE+
vvqqwWERv/wifsWywcFlqFIgfmEQv/wgfsWyt+1YhSqF4hdG8cuP4lceVnHRIlQpFb+wil9+Fb9y
WdPwGlQpF7+wi19+F78yV2HxSlApFL8wil9+FL9y2cn2rECVIvELk/jlJ/ErF1WMLUCVkvALS/jl
l/ArF62L/Yi9FIFfmMAvP4FfOayDsuWnUgZ+YQO//AZ+5bgOy1afSun3hfX78uv3ldM6LDyXVHvC
7H352fvKRXuiD52X8u4Le/fl9+6rFs0JLj2Vgu4LQ/flh+6rFsWJrTyV8u0L+/bl9+2rFqUJPdtU
CrQvDNqXH7SvWrQl9oRHKca+MGNffsa+qhNB8ccUCrAvDNiXH7Cv6lVe+rmEousL0/Xlp+urBpGX
33NUb8JsffnZ+qpR5KXvXlWcsFhffrG+alGc4ENZpZz6wk59+Z36qlklxQeV0ukL6/Tl1+mrO8jA
9KRSJn1hk778Jn11iw6164nxUhR9YYq+/BR9dSnzskalEPrCCH35EfrqSsaFR7OC5wvD8+WH56vr
tvPS0KpdYXG+/OJ8db0MTW9LCp0vjM6XH52vblGv9v90X9nzhe358tvz1Y1bmfHNSRUtbNCX36Cv
btrITG9PqnBhhr78DH1180ZidoNSFH1hir78FH31h43A8LRWFH1hir78FH31cSsxPsGUSF9YpC+/
SF993gxOjzFl0hc26ctv0ldft4LTF7rqYtikL79JX323EZsWE8XRF+boy8/RV9/fjMzf3KqSYZC+
/CB99cPt5PjdrYoZ9ujL79FXvyhmfH1JAfSFAfryA/RtxMt/XM89q0vKmS/szJffmW8jLmLCtSWl
yRfW5MuvybcRFyn5ypJS4wur8eVX49uIy6DwIFI2fGEbvvw2fBtxEXPXqpKi4QvT8OWn4duIZVZ8
XVWPwip8+VX4NmKRdd83CkqGLyzDl1+GbyNkYHyFVXnCNnz5bfg2YhF4Z11UOHxhHL78OHwboRPj
a6yqE8bhy4/DtxGLxPs/tFRMfGEmvvxMfBuxGZpeaQXGFwbjyw/GtxFbofcd3MqOL2zHl9+ObyNu
J8fXXHUvzMiXn5FvI7aS7zzKlSlf2JQvvynfRjwTHV911cywMF9+Yb6NuIhOV48ULl8Yly8/Lt9G
XMbcsXakcPnCuHz5cfk24ioqWzlSsnxhWb78snwbcRkTrxspV76wK19+V76NuArKV28UKF8YlC8/
KN9GXEbds2akKPnClHz5Kfk24pwVrhgpPb6wHl9+Pb6NOIeEP/BWZHxhMr78ZHwbcR0SrhYpL76w
F19+L76NuA4K14qUEl9YiS+/Et9GXAeFZ5BqRZiGLz8N30acc+JHu5UHX9iDL78H30acY9JVIoXA
F0bgy4/AtxHnlHCNSLnvhd338rvvbcQ5JHueSCHvhZH38iPvbcQ5I3yyQrHuhVn38rPubcQiJP54
QWHuhTH38mPubcQyK/08QRHuhQn38hPubcQiK76vKLq9MN1efrq9jVhkpe9WVYiw2F5+sb2NOCel
jz4po72w0V5+o72NWKbkh5IqRVhlL7/K3kaswuJTSXUj7LCX32FvIy7C7nr+WtHrhen18tPrbcQq
K2tKClwvDK6XH1xvI1ZRv+UI/r8//h9WrKmsxnYBAA==
T_EOF
echo "payload bytes: $(wc -c < "$ROOT/table.json")"
python3 - "$ROOT" <<'PY_EOF'

import json, os, re, shutil, subprocess, sys, time

ROOT = sys.argv[1]
T = json.load(open(os.path.join(ROOT, "table.json")))
LANG = T["language"]
PROBES = T["probes"]
OUT = T["out"]
out = open(OUT, "w")
WORK = os.path.join(ROOT, "u")

# --- verbatim delimiter codec, copied from verbatim_diag.py ---
def esc(text):
    """make `text` safe to place in one pipe-delimited field, reversibly."""
    for raw, rep in _ENC:
        text = text.replace(raw, rep)
    return text

_ENC = [('\\', '\\\\'), ('|', '\\p'), (';', '\\s'), ('\n', '\\n'), ('\r', '\\r')]
MARKER = '#verbatim-escape v1'
out.write(MARKER + '\n')


print("op lane %s: %d candidate probes" % (LANG, len(PROBES)))
sys.stdout.flush()


def sh(cmd, cwd=None, timeout=180):
    try:
        p = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE, timeout=timeout)
        so = p.stdout.decode("utf-8", "replace")
        se = p.stderr.decode("utf-8", "replace")
        return p.returncode, so, se
    except subprocess.TimeoutExpired:
        return 124, "", "TIMEOUT after %ds" % timeout
    except OSError as e:
        return 125, "", "OSError %s" % e


# ------------------------------------------------------ objdump reading

LABEL = re.compile(r"^([0-9a-f]+)\s+<(.+)>:\s*$")
INSN = re.compile(r"^\s*([0-9a-f]+):\t(.*)$")
RELOC = re.compile(r"^\s+([0-9a-f]+): (R_\S+)\t(.+?)\s*$")


def extract(text, sym, exact):
    """the two columns for one symbol.

    bytes  every byte objdump printed, in order, flattened
    mnem   the instruction text, with objdump's own trailing `# ...`
           comment dropped -- that comment is arithmetic objdump did
           for the reader, not part of the instruction.  A relocation
           is appended to the instruction it applies to as
           ` !!reloc=<type>:<symbol>`, because in an object file the
           call displacement is literally zero and the callee's name
           lives only in the relocation.
    """
    lines = text.splitlines()
    k = -1
    for idx, ln in enumerate(lines):
        m = LABEL.match(ln)
        if not m:
            continue
        lab = m.group(2)
        hit = (lab == sym) if exact else (sym in lab)
        if hit:
            k = idx
            break
    if k < 0:
        return None
    raw = []
    mn = []
    for ln in lines[k + 1:]:
        if LABEL.match(ln):
            break
        m = INSN.match(ln)
        if not m:
            r = RELOC.match(ln)
            if r and mn:
                mn[-1] = "%s !!reloc=%s:%s" % (mn[-1], r.group(2), r.group(3))
            continue
        parts = m.group(2).split("\t")
        bs = parts[0].split()
        raw.extend(bs)
        txt = parts[1] if len(parts) > 1 else ""
        txt = txt.split("#")[0]
        txt = " ".join(txt.split())
        if txt:
            mn.append(txt)
    return raw, mn


def disasm(obj, sym, exact):
    rc, so, se = sh(["objdump", "-dr", "--disassemble=" + sym, obj])
    got = extract(so, sym, exact) if rc == 0 else None
    if got is None:
        rc, so, se = sh(["objdump", "-dr", obj], timeout=600)
        got = extract(so, sym, exact)
    return got


# --------------------------------------------------------- DWARF reading
#
# objdump --dwarf=info prints one entry per line block:
#
#   <1><2d>: Abbrev Number: 2 (DW_TAG_subprogram)
#      <2e>   DW_AT_name        : op_12
#   <2><4a>: Abbrev Number: 3 (DW_TAG_formal_parameter)
#      <4b>   DW_AT_name        : a
#      <52>   DW_AT_location    : 2 byte block: 91 7c (DW_OP_fbreg: -4)
#
# The leading <N> is the tree depth.  A formal parameter one level
# below the matching subprogram is a parameter OF that subprogram.

DIE = re.compile(r"^\s*<(\d+)><[0-9a-f]+>:\s*Abbrev Number:\s*\d+\s*\((\S+)\)")
ATTR = re.compile(r"^\s*<[0-9a-f]+>\s+(DW_AT_\w+)\s*:\s*(.*?)\s*$")


def clean(text):
    text = " ".join(text.split())
    return text


STRPREFIX = re.compile(r"^\((?:indexed string|indirect string)[^)]*\):\s*")


def dwname(text):
    """objdump prints a string attribute as `(indexed string: 0x5): a`.
    The parenthesised part is objdump telling the reader WHERE in the
    string table it found the name; the name is what follows.  Keeping
    the prefix would have put objdump's bookkeeping into the parameter
    name column."""
    return STRPREFIX.sub("", text.strip())


def dwarf_params(text, sym):
    """[(name, location)] for the subprogram named `sym`.

    More than one subprogram can carry the name.  swift's `@_cdecl`
    emits a C-entry thunk beside the real function, and the thunk has
    no DW_TAG_formal_parameter children at all, so the first match is
    not always the one holding the parameter table.  Every match is
    collected and the first one that actually has parameters wins."""
    lines = text.splitlines()
    depth = None
    tag = None
    attrs = {}
    entries = []
    for ln in lines:
        m = DIE.match(ln)
        if m:
            if tag is not None:
                entries.append((depth, tag, attrs))
            depth = int(m.group(1))
            tag = m.group(2)
            attrs = {}
            continue
        a = ATTR.match(ln)
        if a and tag is not None:
            attrs[a.group(1)] = a.group(2)
    if tag is not None:
        entries.append((depth, tag, attrs))

    hits = []
    for idx, (d, t, at) in enumerate(entries):
        if t != "DW_TAG_subprogram":
            continue
        names = []
        if "DW_AT_name" in at:
            names.append(dwname(at["DW_AT_name"]))
        if "DW_AT_linkage_name" in at:
            names.append(dwname(at["DW_AT_linkage_name"]))
        for nm in names:
            if nm == sym or sym in nm:
                hits.append(idx)
                break
    if not hits:
        return None
    best = []
    for k in hits:
        base = entries[k][0]
        got = []
        for d, t, at in entries[k + 1:]:
            if d <= base:
                break
            if d != base + 1:
                continue
            if t != "DW_TAG_formal_parameter":
                continue
            nm = clean(dwname(at.get("DW_AT_name", "(unnamed)")))
            loc = clean(at.get("DW_AT_location", "(no location)"))
            got.append((nm, loc))
        if got:
            return got
        best = got
    return best


def dwarf(obj, sym):
    rc, so, se = sh(["objdump", "--dwarf=info", obj], timeout=600)
    if rc != 0:
        return None, "objdump --dwarf=info rc=%d" % rc
    got = dwarf_params(so, sym)
    if got is None:
        return None, "no DW_TAG_subprogram named %s" % sym
    if not got:
        return None, "subprogram %s has no DW_TAG_formal_parameter" % sym
    return got, None


# ------------------------------------------------------------ compiling

GOMOD = "module opprobe\n\ngo 1.26\n"

CLANG = "/usr/bin/clang"
CLANGXX = "/usr/bin/clang++"
SWIFTC = "/persist/swift/usr/bin/swiftc"


def compile_probe(p, d, mode):
    """(rc, artifact path, diagnostic text)."""
    if LANG == "c":
        src = os.path.join(d, "unit.c")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANG, "-std=c17"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "cpp":
        src = os.path.join(d, "unit.cpp")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANGXX, "-std=c++20"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "rust":
        src = os.path.join(d, "unit.rs")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        if mode == "anchor":
            opt = ["-C", "opt-level=0", "-g"]
        else:
            opt = ["-C", "opt-level=1", "-C", "debug-assertions=off"]
        cmd = (["rustc", "--crate-type=lib", "--emit=obj"] + opt
               + ["-o", obj, src])
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "go":
        open(os.path.join(d, "go.mod"), "w").write(GOMOD)
        open(os.path.join(d, "main.go"), "w").write(p["source"])
        obj = os.path.join(d, "bin_%s" % mode)
        cmd = ["go", "build"]
        if mode == "anchor":
            cmd.append("-gcflags=-N -l")
        cmd.extend(["-o", obj, "."])
        rc, so, se = sh(cmd, cwd=d, timeout=300)
        return rc, obj, (se or so)
    if LANG == "swift":
        src = os.path.join(d, "unit.swift")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-Onone", "-g"] if mode == "anchor" else ["-O"]
        cmd = [SWIFTC] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd, timeout=300)
        return rc, obj, (se or so)
    raise KeyError(LANG)


DIAG = re.compile(r"^[^\s:]+:\d+(:\d+)?:")


def firstline(txt):
    """the compiler's own words for why it refused.

    The first line is not reliably the reason.  clang leads with a
    warning and puts the error underneath.  go leads with a banner
    naming the package -- `# opprobe` -- and its diagnostics never
    contain the word `error` at all, so a rule that only looked for
    that word recorded the banner and threw the testimony away.
    Three passes, in order: a line saying `error`, a line in the
    `file:line:col:` diagnostic shape, then the first line that is
    not a banner."""
    lines = []
    for ln in txt.splitlines():
        s = ln.strip()
        if s:
            lines.append(s)
    for ln in lines:
        if re.search(r"\berror\b", ln, re.I):
            return ln[:200]
    for ln in lines:
        if DIAG.match(ln):
            return ln[:200]
    for ln in lines:
        if not ln.startswith("#"):
            return ln[:200]
    if lines:
        return lines[0][:200]
    return "(no diagnostic)"


def write_unit(n, build, obj, sym, exact):
    got = disasm(obj, sym, exact)
    if got is None:
        rc2, so2, se2 = sh(["objdump", "-t", obj])
        near = 0
        for l in so2.splitlines():
            if sym in l:
                near += 1
        out.write("op_%d|%s|NOSYM|%s\n"
                  % (n, build, esc("symbol %s absent, %d near matches"
                                   % (sym, near))))
        return False
    raw, mn = got
    out.write("op_%d|%s|OK|%s|%s\n"
              % (n, build, " ".join(esc(x) for x in raw),
                 ";".join(esc(x) for x in mn)))
    return True


t0 = time.time()
tally = {"REFUSED": 0, "ACCEPTED": 0, "ANCHOR_OK": 0, "SHIP_OK": 0,
         "DWARF": 0}

for k, p in enumerate(PROBES):
    n = p["n"]
    sym = p["symbol"]
    exact = p["symbol_exact"]
    d = os.path.join(WORK, "n%d" % n)
    shutil.rmtree(d, ignore_errors=True)
    os.makedirs(d)

    rc, obj, err = compile_probe(p, d, "ship")
    if rc != 0 or not os.path.exists(obj):
        out.write("op_%d|REFUSED|%s\n" % (n, esc(firstline(err))))
        tally["REFUSED"] += 1
        out.flush()
        shutil.rmtree(d, ignore_errors=True)
        continue
    tally["ACCEPTED"] += 1
    if write_unit(n, "SHIP", obj, sym, exact):
        tally["SHIP_OK"] += 1

    rc, aobj, aerr = compile_probe(p, d, "anchor")
    if rc != 0 or not os.path.exists(aobj):
        out.write("op_%d|ANCHOR|BUILDFAIL|%s\n" % (n, esc(firstline(aerr))))
    else:
        if write_unit(n, "ANCHOR", aobj, sym, exact):
            tally["ANCHOR_OK"] += 1
        rows, why = dwarf(aobj, sym)
        if rows is None:
            out.write("op_%d|ANCHOR|NODWARF|%s\n" % (n, esc(why)))
        else:
            joined = ";".join("%s=%s" % (esc(a), esc(b)) for a, b in rows)
            out.write("op_%d|ANCHOR|DWARF|%s\n" % (n, joined))
            tally["DWARF"] += 1
    out.flush()
    shutil.rmtree(d, ignore_errors=True)

    if (k + 1) % 25 == 0 or (k + 1) == len(PROBES):
        el = time.time() - t0
        print("[progress] %s [%d/%d] elapsed %.1fs mean %.2fs  "
              "REFUSED %d ACCEPTED %d SHIP_OK %d ANCHOR_OK %d DWARF %d"
              % (LANG, k + 1, len(PROBES), el, el / (k + 1),
                 tally["REFUSED"], tally["ACCEPTED"], tally["SHIP_OK"],
                 tally["ANCHOR_OK"], tally["DWARF"]))
        sys.stdout.flush()

out.close()
print("done: %s -> %s" % (json.dumps(tally), OUT))

PY_EOF
echo "--- lane finished, rc=$?"
date -u +%Y-%m-%dT%H:%M:%SZ
