#!/bin/sh
# op-pipeline lane -- c -- generated by
# Research/op_pipeline/lane_gen.py .  Do not hand-edit.
# steps 1b/2/3: compile-or-refuse, then the ANCHOR and SHIP
# builds of every probe the compiler accepted, then objdump
# extraction, then the anchor's DWARF parameter table.
set -u
export HOME=/work
export PATH=/persist/swift/usr/bin:$PATH
export GOTOOLCHAIN=local
export GOPROXY=off
export GOFLAGS=-mod=mod
ROOT=/work/regen_c_c0011
export GOCACHE="$ROOT/gocache"
export GOPATH="$ROOT/gopath"
# swift's binaries want libncurses.so.6 and the image ships
# only libncursesw.so.6.6; the symlink lives in the image's
# own /usr/lib and does NOT survive a container restart.
if [ -f /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 ]; then
  ln -sf /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 \
     /usr/lib/x86_64-linux-gnu/libncurses.so.6 2>/dev/null
  ldconfig 2>/dev/null
fi
echo "=== op pipeline -- c -- 400 candidate probes ==="
date -u +%Y-%m-%dT%H:%M:%SZ
# refuse in seconds rather than in an hour
if ! /usr/bin/clang --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: /usr/bin/clang is not runnable in this container."
  echo "!! tried: /usr/bin/clang --version"
  exit 4
fi
/usr/bin/clang --version 2>&1 | head -2
if ! objdump --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: objdump is not runnable."
  exit 4
fi
objdump --version 2>&1 | head -1
rm -rf "$ROOT"; mkdir -p "$ROOT" "$GOCACHE" "$GOPATH"
df -Pm /work | awk 'NR==2{print "free /work: " $4 " MB"}'
FREE=`df -Pm /work | awk 'NR==2{print $4}'`
if [ "$FREE" -lt 400 ]; then
  echo "!! REFUSING TO START: only $FREE MB free on /work, need 400"
  exit 3
fi
base64 -d <<'T_EOF' | gunzip > "$ROOT/table.json"
H4sIAAAAAAAC/8Wd3W5cN5ZGX0Xw3KQbSYd/e29yptHAzEW/wFyOB4LkKI4BRzJsGdNBkHcfyW2l
I/Ijz/kOSrtyk0CoKKkFFrnqmBvr11fvr27ffr56e/Pq3y9evXn17cWru8/3j//8/cPfv/948/bm
9vLN5ZsQYvzL/T/uH1/w4ePd9c2nh9f8z6+vbh/+VkoIDz/+9MvP13fvH//Vuw+Xjz979fsPL2/+
cfXm8bfef/x88/jTu88f33z5L37/54svv+7LL7n47ruL63e3Vx9/ufju4s/fv779t3e3b95//uHm
4q+f7n94d3v/l5/+1v3w+u7u/Zefvr69vLz/5cPN3Y+Xl998c/nfV/cXl3//+PBf/dOv4beHX/fN
p3dvb29+uHh/d/v28Ud/en379X/zjy++uPr24g8vvLh+eNmvr28vHv76eHP/+ePtxdXD77r+j9e3
v72+ffXbtxe/E4iAQGQJRC8CI4a4wkCySIBFYlkkDxaffrr7eP+MQ5pw+PJKgkEGDDLLIL8og8+3
X9/b5X++efP552cYco+hezFBogAShSVRnEj8/uPfSZQ5iX/+aD8JASSEJSE+JN78dPXxGQeZcnh8
KUFBAQVlKagPhYff8wyCTiE8vJJgYICBsQzMh8FwVNgUAnlOVEChshSqHwW0UdY1DHq3bIBJY5k0
Tybjltk2mJD7ZgR2GVm7jMGRSf+RiWFNhPvcROCakXXNGH14DIYV45QF6VgReGZkPTMmRw5gA4lp
Awe7g0RgnpE1z5hdqQxbSMxbVNg9BFhoZC00vqyF/t+jSF0+5zDY59cXEe8cWGdkrTOe2jq74/Tx
7YPPhgwvfkRAfyKAcUbWOKM6EPivh9c/A6AYwOPriPcPbDOythnN4f3//f3d1X3UZwgMI/j6UoIC
sM3I2masHhSG3bBOGJB7IHDLyLplbA4Evmx543bQMIZ/vXo/iwScMrFOmYIXi2FJpLBgQa6LBHwy
sT6ZohOLyRexFOdADn0TS8AuE2uXKblSGZdJ2qLCrhVgl4m1y5SdqMykO+U5lmPWnYBfJtYvU/Hl
Mi6XssmFXS/APhNrn0mcuCyeiCeZozn8bDwBM02smSZ1pzMuHN1Dh107wFsT663JvOnMDijbgejY
SQXMNrFmm+p5OI1Lqe7mxK4n4L+J9d/UvDlND7G2A9Sx0ywDO86sHedwJlLDksphPylyTWXgzpl1
5+zhzpfXPz7/Zp0nxvzlhQQB4MmZ9eTs4cmXP355ZpDqMwoTQ/79xQQJ4MaZdeOcXUh86NZCnlH4
QK0FYMGZteDsYcGX765/7lfCRH6/vpSgAJw3s86bxYXC7eMSf/7MOcuMw9cXEySA32bWb7OH315+
higmWvuvVxMsgM1m1mazg81edw+hMxbXa+oZdAaOmllHzQ6O2t97yVhHuTsvGZhnZs0zN593H7X7
ELQpgceX7qdQgFUW1ipL8KGQ03MKJUwpPL6UoACMsbDGWKIPhW4/LHEKgdoLC3DGwjpjcXDGH+4+
X7+/eYYA++I/X0gQAK5YWFcsDq74RYOfAcCq+OV1xPsHplhYUywOpvjT1fsfn719bImPLyPePTDE
whpicTDE7v5jwWpI3X0swAkL64TFwQn7S1wFyyB3d6sACyysBRbzeffgoVOxOQT2KVMBTlhYJyzV
i8XwWKnUBQvyOVIBhlhYQyzNiQU4FtucBXs2CvBEYT1RghOLfpuQMCfB7RUCTFFYUxQHUxzueAr2
RPJ+pwBLFNYSJTm9f7BZSlpgYHdLAcYorDFKdqMxbJeSVzTI/VKAPwrrj+Lgj5NxGsEaeWiiRoBN
CmuTIm4sOqkUWaGg3FKAWwrrlqJuJIazQ1coyNMDmKawpinmymIEYptASCrAOYV1TqluVMajta6I
sCcssE5hrVMcrHNxMUeweR6+k6PAPpW1Tw2eTIajVsMGE/K0VWCiypqoRkcm/XmrcU2EO3EVmKmy
ZqrJkUd35mpa46BOXQVmqqyZanak0R8zmtc4uDNGgZsq66ZanHmArVXLDiz0/gpsVVlbVXGnM26y
socOu9MCg1XWYFW96QwfKN3BhvxUAZ9V1mfVHMkM7qa2pkLamwKXVdZltXoTQRtN3QOG3mmA3Spr
t9r8+YxbTdvFh9xrDJiusaZrDqYLBmMNGy49HWvAbI01W3sZs302HDx+aCwOLz4yHWvAZY11WUsO
BPrpWEsYADcda8BejbVXyw7vH0zHWsYI6OlYA85qrLNa8aDQb45WJgzI3RB4qbFeauJAAE/HmmAM
R6ZjDViosRZq6sViXBK6YMGuC+CdxnqnmROLyTc5szmQQ9/iDLinse5p1ZXKuEzqFhV2rQDjNNY4
rTlRmdm4tTmWYyZegWlW1jRr8OUyLJcaNrmQ66UC+6ysfdboxGXxEL7GOZrDT+IrMNPKmmlN7nTG
hZP20GHXDvDWynprzd50JgdUzTsQHTqpKjDbypptLefhNC6lspsTu56A/1bWf6t4c5odYlV2gDp4
mgE7rqwdVz0TqXFJ6X5S7JoC7lxZd64e7jxMx9aJMZPTsRV4cmU9uXp4MpyOrRNDPjAdW4EbV9aN
a3Mh0U3H1jajQE3HNmDBjbXg5mHBYDq2TeSXno5twHkb67wtulAAI6EtzjjQE6EN+G1j/bZ5+C2e
jm0TrT0yHduAzTbWZpuDzfbTsQ2LKzcd24CjNtZRm4Oj9tdqGtZR7jZNA+bZWPNs4vPu++nYJlMC
3HRsA1bZWKts6kOhn45tOqXATcc2YIyNNcZmPhT6/dCmELi9EDhjY52xOTjjOAbUsC+yE0ANuGJj
XbE5uOIwHduwKnLTsQJ6SsL2lCQ4mGI3HSsBWyI1HSugpSRsS0mCgyE+v1QpAashc5dSQDtJ2HaS
BAcn7G58ScAySN3xElBNEraaJCH7vPvxoZOEPIdAPmUS0E0StpskoXix6B8rSSgLFtxzJAHlJGHL
SRLEicVwLEqQOQvybBTQTxK2nyRBnVgM24TOSZB7hQEOxnJwMMX+GqgE7Inc7U8B9SRh60kSqtP7
R5tlXWCgd8sGaDSWRnOjMW6XbUWD3C9BMUnYYpJEB3/E0zoSsUYemdURUEsStpYkMbqx6KQyxhUK
yi1BL0nYXpLE5EaiPztiWqHgTg9QSRK2kiQxu7IYgeRNICQV4JxsJUlicaMyHK2xrIiQJywoJwlb
TpLoYJ3zizkSsXkevZMjoKUkbEtJonoyGY7aqBtM2NMWmCjbV5JojkyG89bWRMgTF5gpW1qSWB15
9GduXePgTl1gpmx1SWJzpDEcM22NgztjQHlJ2PKSpODMA2ytKezAwu6voMUkbItJUnSnM2yyKe6h
Q+60oMkkbJNJUvKm03+gUtrBhvxUAZ9lu0ySsiOZwd1SXlMh7Q0UmYQtMkkq3kTQRlP2gKF3GmC3
bJlJkvjzGbca2cWH3WuA6bJtJkkOpjtOx0rChstOxwooMAlbYJKTF5j6zwkcj5Wn3tKzTwc/Hyug
riRsXUlOXleCDLoBWXlKKQ0IqAlZAd0kYbtJcvJuEiQwjsjKUyZpgMDOyAqoIglbRZKTV5Ewh36P
fEogjRS4XRH0joTtHcnJe0eQARyTlafq0QDiwJysgPaRsO0jOXn7aE5jXBZpRYNdG8BB2f6RnLx/
NKUx+Vr3lEKCSA59pwNVJGGrSHLyKtIGl3GplE0u7HoBBsp2kuTknaQpl5meP/WSIJhjbg66ScJ2
k+Tk3aQtMuOS0W0y7JoBRspWlCSbF5nFk/lsCziHn8+DzpKwnSXJ1Z/PuHjqLj7s+gEuy5aYJDd3
PrPDqu2BdOjUArUmYWtNUsKZSA3LqYT9pMg1BYpOwhadpER3UrMDrcQ9qI6dbKD8JGz5SUo6F6tx
WSWCFbuugE+zjSgpLj7dj89KmVk0Nz8roBMlbCdKios7owFaKTNr5idoBVSjhK1GSREfFh+69SBT
Dh+o9QDMmK1HSXEx43GIVspMiNkpWgEdKWE7UlLMh8M4OyrFpiTY2VEBHSlhO1JSXJwXDtJKmanu
gUlaASUpYUtSUjwMtxullTKRWWqWVkA9Sth6lIiHt/a3cGSiqNztG1CNErYaJRKd3n83TisS5wyo
eVoB9Shh61EiyYlDN1ArkuYcqIlaAd0oYbtRItmJQ7czSp5joHZF0IsSthcl4uGR4/SQTBySnRwC
nShhO1EiHv7Yj9WKTPSRnKsFfShh+1AiHvbYD9bKxBy5yVrQhBK2CSXiYY3djUyZ6CJ1ExO0n4Rt
P4l4eGJ/YUwmgsjdEQO1J2FrTyLN6f2DB1PSFhjYJ1Gg8yRs50k0uNEYHj1pWNEgnzWBwpOwhSfR
6EVjPCQ1LmiwJyXoOwnbdxJNXjT67ULTggW3Z4C2k7BtJ1EPexzuk+rEHcl7pKDmJGzNSbR4EQDb
ppYVCHrfBBbJ9ptExY/HuHHKkge7cwKnZItNoh5OORn+0YlaHpr9AZUmYStNouZHoxNNtSUMyjdB
n0nYPpNo9WMxnCN1CYM8SYB9sjUm0eZLY0TStpFwXECFSdgKk1jw4zIctBaWTMjzFhSZhC0yiXmY
6OJyj01s9PC9HlBpErbSJJZcqQwHr6UtKuTZC9pNwrabxLInlf70tbzBhDt/QcdJ2I6TWPEk0p3A
VjaAUGcwqDoJW3USE08e/ZFjsgGEPG+Ar7JtJzH1JoI2Wd0Dht5pgcGyvScx8+czbre2iw+75wKr
ZctPYtWdz/CxqnvokJ8t4Lhs/0msebIZba5tcCF9DrSfhG0/SQ3uTMCGU8MuNOyOAypQwlagpMYz
EBq2nBr3ESL3HFCCErYEJdXDfsEwbp1YLz2NC4pPwhafpL6Q7a5jtVLz+Ooj07ig5iRszUlq8WDQ
T+PWMkHATeOCTpOwnSap4kEATONWmUCgp3FBhUnYCpNUdeEwbJM6o0Dui8BV2b6SVPNggKdxq01A
HJnGBa0lYVtLUqsbjXFZ1BUNdm0AF2V7S1KbF43Jd7zaFkgOfb8DFSZhK0zSgi+XYam0sMmFXC+g
yyRsl0la9OIyc/QWF2CO+TnoNAnbaZKWnMmMSyZtk2HXDDBSttokLXuRWTywb3kB5/BTe9B1Erbr
JK348xkXT9nFh10/wGXZ8pM0ceczOaya7IF07NQCtsvWoaTpmUiNy0n3k2LXFHBitiAlzdxJTQ80
24Pq4MkGjJktTUmr52I1LqtKsGLXFfBptkklzcWnh2ncNrNobhpXQZdK2S6VBhd3RtO4GmbWzE/j
KqhUKVup0hB9WDyfxtUQpxw+UOshAQaJZeBixuM0roaZELPTuAq6Vcp2qzRkHw7jAKqGPCXBzp8q
6FYp263S4OK8cBpXw0x1D0zjKihXKVuu0uBhuN00roaJzFLTuApqVcrWqjR4eGt3MUfDRFGp+zgK
KlXKVqo0mNP776ZxNdicATWNq6BWpWytSkN14tBN42qocw7UNK6CTpWynSoNzYlDvzO2OQZqVwR9
KmX7VBo9PHIYNNI4cUhyxkhBl0rZLpVGD3/sp3E1TvSRm8ZV0KNStkel0cMeu2lcjRNzpKZxFTSo
lG1QafSwxudXNDVOdJG5mamgNaVsa0qjhyd2N8c0TgSRuiumoC6lbF1Kozi9//HBlEZZYCCfRCno
SinbldKobjT6R08adUWDe9akoCilbFFKo3nRAIekLWjQJyVwR7YnpbF60Ri2i7pgQe4ZwB7ZlpRG
D3vsr5VqnLgjd5tUQT1K2XqUpuBFAGybKaxAsPsm6EUp24vSFP14DBtnikse5M4JClHKFqI0eTgl
ngfSNFHLI9NACqpQylahNGU/Gp1opryEQfkm6EEp24PSVPxY9OdIKksY3EkC6k/K1p80iS+NEYls
IyG5AA9lq0+a1I/LcNAmXTJhz1tgomwBSpOHic4v92ia2OjRez0KmlDKNqE0VVcq48Fbt6iwZy+w
U7YTpal5UhlO37bBhDt/QTFK2WKU5uBJpDuBc9gAQp3BoB6lbD1Kc/Tk0R85OW4A4c4bUJBStiCl
OXkTAZtsTnvAsDstaEop25TSnP35DNttzrv4kHsuaEsp25bSXNz5DB+rsocO+dkCjsv2pTSLJ5vB
5rJscCF9DpSllC1LaVZ3JmjD0V1o6B0HGC9bmNJsZyA0bjm2jxC75wD7ZRtTmj3sd5zG1TyxXnYa
V0FJStmSlJ68JAW+BcGBXH0qR/XfgfiZXAWlKGVLUXryUtSMRDeWq09hKASCmsxV0IFStgOlJ+9A
zTiMw7n6FH5CKNj5XAWlJ2VLT3ry0tOURr93PoWdIAtuvwQdJ2U7TnryjtOMBBzU1aeeE8JxYFZX
QddJ2a6TnrzrtGQyLpGywYRdJ8BX2b6TnrzvtGIy+Sr4FHuagTn0TRCUn5QtP+nJy0/bdMZlo3vo
sGsHWCvbg9KT96BWdGZa/1SGmuE5ZvWgEaVsI0pP3ojawWdcPnUXH3b9AJtlq1FamiOfxfP+0taI
Dj/3B20pZdtSKuEslIaFJGEvJXItgQKVsgUqlXgOSpMDTeJOVIdONlCqUrZUpZLOx2tcWonixa4v
4NNs0Uoln4PX7NCTvBPYsdMP1K+UrV+plDMSG5dY4Yixawy4ONvKUvFy8X7gV2Vh4OTML2hmKdvM
UvHybjj2KwvjPjD5Cypayla0VMyNSDf8K7aiQc3/gqKWskUtFS+rBiPAspBpegoY9LWU7WupNDca
YPZV2ooHPf0KGlvKNrZUvXwZjwPrQpOPTASD0paypS1VJzvuh4J1LsLcXDAobClb2FJ1ct7+lpDO
9Za7HwTqWsrWtVSzH4V+QFjzkgQ3IwxKW8qWtlSLH41+TFjLkgY3KQw6W8p2tlTFj0a/b8oSBrdn
AgdlG1uqTg46TkPp3D/ZWSjQ11K2r6Xq5J7D4LDO1ZOcHQZtLWXbWqpO5tmPD+vcOrkJYtDUUrap
pepknN3NUp2rJnWnFPSzlO1nqTk5Zn/tzeZyyd11A9UsZatZatGPAngIZnENg33qBZpZyjaz1JIn
k+Exl6UNJuRzLVDMUraYpZYdmYzHqeU1E/ZMBc0sZZtZasWRybCNlDURci8B5sk2s9SczHO4MWtz
7yTvyoJSlrKlLDV15IA2Vd3AQe+qwEDZPpaauVIZt1XbosLuq8BH2SqWmpOPToafbK6lh6afQA1L
2RqWWnNl0kmqtS0klKuCFpayLSytwZVIf9bUsIWEO21A/UrZ+pXW6M5kBBN3gSHpAIdly1dakyud
4UiuaYsMeTKDEpayJSytTha7uKhU5yZ7+I4SKGQpW8jSWrzZDEd0LTvYkKc0aGcp287SKs5s+nO6
yjYZ7qQGLS1lW1pa1ZlLd1ZX3cbCndbAdNm6llZzpjIcS7aNhTyTgOuynS2t9Qxc0BZcd+Kh92Fg
v2x/S2s7C6VxM257KZE7MqhxKVvj0hbOQan/oLWwkxH3aQNdLmW7XNqiM6HBAVvcpkNaIOhyKdvl
0pbOQQZsRC3tBcTuRKDSpWylS1s+D6dhK2p5Nyd2LwLmzNa6tDmZMxhtbnNjpqebQZlL2TKXtpcz
5XVuWJvAf+HIdDMobylb3tKmTiT66eamcxDcdDPoainb1dJmThzAdHOzOQp6uhmUs5QtZ2mrXjSG
TbQuWJC7JvBctoulrTmRwNPNrc1xHJhuNtDJMraTZSF4MumXiIWwwYRbJwZ6Wcb2sixERyb4G6OF
uAZz5NuigZKWsSUtC8mdzrhs0h467NrJgE5m6WRHOhPLt5DXeA4ZvoHmlrHNLQvFn8+4fMouPuz6
EcBHWD7iyGf+hwYWZI3o6J8cGGh1GdvqsqBnoTQuJN1LiV1LBigZS8nOQWl2oNlOVMdOtgp4VZZX
PR+vcWlVihe7vhrg1Vhe7Ry8pode2wns2OkHamLG1sQshjMSG5ZYDBwxco2B9pix7TGLXi7eTzdb
XBg4N91soEFmbIPMopd3o+lmiwvj5qebDVTJjK2SWcxuRD50ayOvaHyg1gawarZQZtHLqsfpZosL
mWanmw30yoztlVkUNxrjKK9FWfFgJ3kNNMuMbZZZ9PJlON1scaHJB6abDZTLjC2XWXSy42662eJc
hKnpZgPFMmOLZRadnLe7XmRxrrfUrSIDtTJja2UWmx+FbrrZYluSoKabDZTLjC2XWQp+NLrpZkth
SYOabjbQLTO2W2Yp+tHo9s0UlzCoPRM0y4xtlllyctBhHMvS3D/JSSwDvTJje2WWnNyzn262NFdP
brrZQKvM2FaZJSfz7KabLc2tk5puNtAoM7ZRZsnJOJ9fRrU0V03mDqqBHpmxPTJLTo7Z3YizNJdL
6g6cgQqZsRUyS+ZHATwES7aGwT71Ag0yYxtklqonk+ExV6obTMjnWqBAZmyBzFJzZAKO07Zmwp6p
oEFmbIPMcnBk0m8jOayJcHsJaJAZ2yCz7GSe/TVay3Pv5G7PGiiPGVses5wcOYBNNacNHOyuCnpj
xvbGLGdXKsO2mvMWFXJfBZUxYytjlp18FE9NWZ5r6ZGZKQN1MWPrYpbFlUknqVm2kFCuCtpixrbF
LKsrkeGs0S0k5GkDzJWtiVk2dyYjGNsFhqQDHJYtiVmurnTGI7lukWFPZmCxbFnMspPFLi4q5bnJ
Hr6jBFpjxrbGrARvNsMRXcIONuQpDfpjxvbHrERnNv05XeI2Ge6kBiUyY0tkVpIzl+6sLmkbC3Va
gyqZsVUyK9mZSn8slbyNhTuTQJnM2DKZlXIGLmALLmUnHnofBvbLtsqsyFkojZux7KXE7sjAiNlm
mRU9B6Xhg6Y7GZGfNuDHbLfMijkTGhyw2DYd0gJBsczYYpmVeg4yaCOqewHROxGwZbZcZqWdh9O4
FbXdnMi9CLTLjG2XmTiZ8zjdbDI3Zna62UChzNhCmb1coaw7zOGIsw1Nsj+e4/ycs4EKmbEVMnu5
Chli0g0725Ad65FQE88GOmPGdsbs5TpjiMg49mxDWqyHws4+G6iJGVsTs5eriUEu/T475MMGKuTu
CnyY7YXZy/XCEBM4Cm1DOawHc2QeGjTEjG2I2cs1xKZ0xmWje+iwawc4MNsTs5fric3oTL5yDnkx
hOjQd05QGzO2NmYvVxtbcxqXUt3NiV1PwIjZDpm9XIdsxmn21WFokiFQx747gD6ZsX0ye7k+2Qap
YUkNqbIFKXJNgWqZsdUy0+hNavGnExp3wDr85xSgb2Zs38w0nY/XuLgSxYtdX8C12RKaaT4br8lh
qJmBduhUBNU0Y6tppuXM5MblVnhy7JoDzs4W1kzlbORmB6YKg+7gyQmMni2ymeq52Y3LTg+wY9cd
8H224Wbq6vvDCLZuWT45hw16bsb23Exd3R4OY+uW1R+YyAaVN2Mrb6bNl003lq1tkws1mw2qb8ZW
38xczR0MaNuWsNNT2qADZ2wHziz6cgFzyRY3ydCzyaAHZ2wPzszVyfHQtm2p+JHJbVCGM7YMZ+Zp
4P34tm3INjfDDapwxlbhzDy9ur9JZRsKzd2iAlU4Y6twZuLMox/pNtlmws11g0qcsZU4M3Xm0g93
m25z4Sa8QSfO2E6cmTlz6Xda28bC7bLAc9lOnJmn544TarbhuOyEGujEGduJM/P022H02zb0lpz/
Bp04YztxVj3tth8Crxtmy02Cg0acsY04q55W293erRs6S93cBU04Y5twVj09tr9MWDcElrtDCGpw
xtbgrGZnHuDBXc07sLBP6kAPztgenNXiTmd4NFfLHjrkszhQhDO2CGdVvOmMh3KVHXTYkxl04Yzt
wllVbzrDdqM72JB7DrBbtg1n1dNuhzvLdcNtyfvKoApnbBXOavUmgrbhugcMvQ8Dy2V7cFabP59x
I267+JA7MSjBGVuCs+bpvJMBtrahvodm2EAFztgKnLXoT6cT4RZ3waF8GHTgjO3AWUv+bPpzqqVd
cLiTCtTfjK2/WcvnoTMiyvsRkZyAJ7P1N2vFn9NwsLeyixF5voMinLFFOGuepry4/NU2bPnwvS9Q
izO2FmdNz0JpOOib7qXEnvXAntmWnDU7B6XhtLedjMjzHtg025ezVs9BqD/x605A3JkPbJqtzllr
5+AzHGltJ6A959n//vb/Kc5XvtKtAQA=
T_EOF
echo "payload bytes: $(wc -c < "$ROOT/table.json")"
python3 - "$ROOT" <<'PY_EOF'

import json, os, re, shutil, subprocess, sys, time

ROOT = sys.argv[1]
T = json.load(open(os.path.join(ROOT, "table.json")))
LANG = T["language"]
PROBES = T["probes"]
OUT = T["out"]
out = open(OUT, "w")
WORK = os.path.join(ROOT, "u")

# --- verbatim delimiter codec, copied from verbatim_diag.py ---
def esc(text):
    """make `text` safe to place in one pipe-delimited field, reversibly."""
    for raw, rep in _ENC:
        text = text.replace(raw, rep)
    return text

_ENC = [('\\', '\\\\'), ('|', '\\p'), (';', '\\s'), ('\n', '\\n'), ('\r', '\\r')]
MARKER = '#verbatim-escape v1'
out.write(MARKER + '\n')


print("op lane %s: %d candidate probes" % (LANG, len(PROBES)))
sys.stdout.flush()


def sh(cmd, cwd=None, timeout=180):
    try:
        p = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE, timeout=timeout)
        so = p.stdout.decode("utf-8", "replace")
        se = p.stderr.decode("utf-8", "replace")
        return p.returncode, so, se
    except subprocess.TimeoutExpired:
        return 124, "", "TIMEOUT after %ds" % timeout
    except OSError as e:
        return 125, "", "OSError %s" % e


# ------------------------------------------------------ objdump reading

LABEL = re.compile(r"^([0-9a-f]+)\s+<(.+)>:\s*$")
INSN = re.compile(r"^\s*([0-9a-f]+):\t(.*)$")
RELOC = re.compile(r"^\s+([0-9a-f]+): (R_\S+)\t(.+?)\s*$")


def extract(text, sym, exact):
    """the two columns for one symbol.

    bytes  every byte objdump printed, in order, flattened
    mnem   the instruction text, with objdump's own trailing `# ...`
           comment dropped -- that comment is arithmetic objdump did
           for the reader, not part of the instruction.  A relocation
           is appended to the instruction it applies to as
           ` !!reloc=<type>:<symbol>`, because in an object file the
           call displacement is literally zero and the callee's name
           lives only in the relocation.
    """
    lines = text.splitlines()
    k = -1
    for idx, ln in enumerate(lines):
        m = LABEL.match(ln)
        if not m:
            continue
        lab = m.group(2)
        hit = (lab == sym) if exact else (sym in lab)
        if hit:
            k = idx
            break
    if k < 0:
        return None
    raw = []
    mn = []
    for ln in lines[k + 1:]:
        if LABEL.match(ln):
            break
        m = INSN.match(ln)
        if not m:
            r = RELOC.match(ln)
            if r and mn:
                mn[-1] = "%s !!reloc=%s:%s" % (mn[-1], r.group(2), r.group(3))
            continue
        parts = m.group(2).split("\t")
        bs = parts[0].split()
        raw.extend(bs)
        txt = parts[1] if len(parts) > 1 else ""
        txt = txt.split("#")[0]
        txt = " ".join(txt.split())
        if txt:
            mn.append(txt)
    return raw, mn


def disasm(obj, sym, exact):
    rc, so, se = sh(["objdump", "-dr", "--disassemble=" + sym, obj])
    got = extract(so, sym, exact) if rc == 0 else None
    if got is None:
        rc, so, se = sh(["objdump", "-dr", obj], timeout=600)
        got = extract(so, sym, exact)
    return got


# --------------------------------------------------------- DWARF reading
#
# objdump --dwarf=info prints one entry per line block:
#
#   <1><2d>: Abbrev Number: 2 (DW_TAG_subprogram)
#      <2e>   DW_AT_name        : op_12
#   <2><4a>: Abbrev Number: 3 (DW_TAG_formal_parameter)
#      <4b>   DW_AT_name        : a
#      <52>   DW_AT_location    : 2 byte block: 91 7c (DW_OP_fbreg: -4)
#
# The leading <N> is the tree depth.  A formal parameter one level
# below the matching subprogram is a parameter OF that subprogram.

DIE = re.compile(r"^\s*<(\d+)><[0-9a-f]+>:\s*Abbrev Number:\s*\d+\s*\((\S+)\)")
ATTR = re.compile(r"^\s*<[0-9a-f]+>\s+(DW_AT_\w+)\s*:\s*(.*?)\s*$")


def clean(text):
    text = " ".join(text.split())
    return text


STRPREFIX = re.compile(r"^\((?:indexed string|indirect string)[^)]*\):\s*")


def dwname(text):
    """objdump prints a string attribute as `(indexed string: 0x5): a`.
    The parenthesised part is objdump telling the reader WHERE in the
    string table it found the name; the name is what follows.  Keeping
    the prefix would have put objdump's bookkeeping into the parameter
    name column."""
    return STRPREFIX.sub("", text.strip())


def dwarf_params(text, sym):
    """[(name, location)] for the subprogram named `sym`.

    More than one subprogram can carry the name.  swift's `@_cdecl`
    emits a C-entry thunk beside the real function, and the thunk has
    no DW_TAG_formal_parameter children at all, so the first match is
    not always the one holding the parameter table.  Every match is
    collected and the first one that actually has parameters wins."""
    lines = text.splitlines()
    depth = None
    tag = None
    attrs = {}
    entries = []
    for ln in lines:
        m = DIE.match(ln)
        if m:
            if tag is not None:
                entries.append((depth, tag, attrs))
            depth = int(m.group(1))
            tag = m.group(2)
            attrs = {}
            continue
        a = ATTR.match(ln)
        if a and tag is not None:
            attrs[a.group(1)] = a.group(2)
    if tag is not None:
        entries.append((depth, tag, attrs))

    hits = []
    for idx, (d, t, at) in enumerate(entries):
        if t != "DW_TAG_subprogram":
            continue
        names = []
        if "DW_AT_name" in at:
            names.append(dwname(at["DW_AT_name"]))
        if "DW_AT_linkage_name" in at:
            names.append(dwname(at["DW_AT_linkage_name"]))
        for nm in names:
            if nm == sym or sym in nm:
                hits.append(idx)
                break
    if not hits:
        return None
    best = []
    for k in hits:
        base = entries[k][0]
        got = []
        for d, t, at in entries[k + 1:]:
            if d <= base:
                break
            if d != base + 1:
                continue
            if t != "DW_TAG_formal_parameter":
                continue
            nm = clean(dwname(at.get("DW_AT_name", "(unnamed)")))
            loc = clean(at.get("DW_AT_location", "(no location)"))
            got.append((nm, loc))
        if got:
            return got
        best = got
    return best


def dwarf(obj, sym):
    rc, so, se = sh(["objdump", "--dwarf=info", obj], timeout=600)
    if rc != 0:
        return None, "objdump --dwarf=info rc=%d" % rc
    got = dwarf_params(so, sym)
    if got is None:
        return None, "no DW_TAG_subprogram named %s" % sym
    if not got:
        return None, "subprogram %s has no DW_TAG_formal_parameter" % sym
    return got, None


# ------------------------------------------------------------ compiling

GOMOD = "module opprobe\n\ngo 1.26\n"

CLANG = "/usr/bin/clang"
CLANGXX = "/usr/bin/clang++"
SWIFTC = "/persist/swift/usr/bin/swiftc"


def compile_probe(p, d, mode):
    """(rc, artifact path, diagnostic text)."""
    if LANG == "c":
        src = os.path.join(d, "unit.c")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANG, "-std=c17"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "cpp":
        src = os.path.join(d, "unit.cpp")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANGXX, "-std=c++20"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "rust":
        src = os.path.join(d, "unit.rs")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        if mode == "anchor":
            opt = ["-C", "opt-level=0", "-g"]
        else:
            opt = ["-C", "opt-level=1", "-C", "debug-assertions=off"]
        cmd = (["rustc", "--crate-type=lib", "--emit=obj"] + opt
               + ["-o", obj, src])
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "go":
        open(os.path.join(d, "go.mod"), "w").write(GOMOD)
        open(os.path.join(d, "main.go"), "w").write(p["source"])
        obj = os.path.join(d, "bin_%s" % mode)
        cmd = ["go", "build"]
        if mode == "anchor":
            cmd.append("-gcflags=-N -l")
        cmd.extend(["-o", obj, "."])
        rc, so, se = sh(cmd, cwd=d, timeout=300)
        return rc, obj, (se or so)
    if LANG == "swift":
        src = os.path.join(d, "unit.swift")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-Onone", "-g"] if mode == "anchor" else ["-O"]
        cmd = [SWIFTC] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd, timeout=300)
        return rc, obj, (se or so)
    raise KeyError(LANG)


DIAG = re.compile(r"^[^\s:]+:\d+(:\d+)?:")


def firstline(txt):
    """the compiler's own words for why it refused.

    The first line is not reliably the reason.  clang leads with a
    warning and puts the error underneath.  go leads with a banner
    naming the package -- `# opprobe` -- and its diagnostics never
    contain the word `error` at all, so a rule that only looked for
    that word recorded the banner and threw the testimony away.
    Three passes, in order: a line saying `error`, a line in the
    `file:line:col:` diagnostic shape, then the first line that is
    not a banner."""
    lines = []
    for ln in txt.splitlines():
        s = ln.strip()
        if s:
            lines.append(s)
    for ln in lines:
        if re.search(r"\berror\b", ln, re.I):
            return ln[:200]
    for ln in lines:
        if DIAG.match(ln):
            return ln[:200]
    for ln in lines:
        if not ln.startswith("#"):
            return ln[:200]
    if lines:
        return lines[0][:200]
    return "(no diagnostic)"


def write_unit(n, build, obj, sym, exact):
    got = disasm(obj, sym, exact)
    if got is None:
        rc2, so2, se2 = sh(["objdump", "-t", obj])
        near = 0
        for l in so2.splitlines():
            if sym in l:
                near += 1
        out.write("op_%d|%s|NOSYM|%s\n"
                  % (n, build, esc("symbol %s absent, %d near matches"
                                   % (sym, near))))
        return False
    raw, mn = got
    out.write("op_%d|%s|OK|%s|%s\n"
              % (n, build, " ".join(esc(x) for x in raw),
                 ";".join(esc(x) for x in mn)))
    return True


t0 = time.time()
tally = {"REFUSED": 0, "ACCEPTED": 0, "ANCHOR_OK": 0, "SHIP_OK": 0,
         "DWARF": 0}

for k, p in enumerate(PROBES):
    n = p["n"]
    sym = p["symbol"]
    exact = p["symbol_exact"]
    d = os.path.join(WORK, "n%d" % n)
    shutil.rmtree(d, ignore_errors=True)
    os.makedirs(d)

    rc, obj, err = compile_probe(p, d, "ship")
    if rc != 0 or not os.path.exists(obj):
        out.write("op_%d|REFUSED|%s\n" % (n, esc(firstline(err))))
        tally["REFUSED"] += 1
        out.flush()
        shutil.rmtree(d, ignore_errors=True)
        continue
    tally["ACCEPTED"] += 1
    if write_unit(n, "SHIP", obj, sym, exact):
        tally["SHIP_OK"] += 1

    rc, aobj, aerr = compile_probe(p, d, "anchor")
    if rc != 0 or not os.path.exists(aobj):
        out.write("op_%d|ANCHOR|BUILDFAIL|%s\n" % (n, esc(firstline(aerr))))
    else:
        if write_unit(n, "ANCHOR", aobj, sym, exact):
            tally["ANCHOR_OK"] += 1
        rows, why = dwarf(aobj, sym)
        if rows is None:
            out.write("op_%d|ANCHOR|NODWARF|%s\n" % (n, esc(why)))
        else:
            joined = ";".join("%s=%s" % (esc(a), esc(b)) for a, b in rows)
            out.write("op_%d|ANCHOR|DWARF|%s\n" % (n, joined))
            tally["DWARF"] += 1
    out.flush()
    shutil.rmtree(d, ignore_errors=True)

    if (k + 1) % 25 == 0 or (k + 1) == len(PROBES):
        el = time.time() - t0
        print("[progress] %s [%d/%d] elapsed %.1fs mean %.2fs  "
              "REFUSED %d ACCEPTED %d SHIP_OK %d ANCHOR_OK %d DWARF %d"
              % (LANG, k + 1, len(PROBES), el, el / (k + 1),
                 tally["REFUSED"], tally["ACCEPTED"], tally["SHIP_OK"],
                 tally["ANCHOR_OK"], tally["DWARF"]))
        sys.stdout.flush()

out.close()
print("done: %s -> %s" % (json.dumps(tally), OUT))

PY_EOF
echo "--- lane finished, rc=$?"
date -u +%Y-%m-%dT%H:%M:%SZ
