#!/bin/sh
# op-pipeline lane -- cpp -- generated by
# Research/op_pipeline/lane_gen.py .  Do not hand-edit.
# steps 1b/2/3: compile-or-refuse, then the ANCHOR and SHIP
# builds of every probe the compiler accepted, then objdump
# extraction, then the anchor's DWARF parameter table.
set -u
export HOME=/work
export PATH=/persist/swift/usr/bin:$PATH
export GOTOOLCHAIN=local
export GOPROXY=off
export GOFLAGS=-mod=mod
ROOT=/work/regen_cpp_c0167
export GOCACHE="$ROOT/gocache"
export GOPATH="$ROOT/gopath"
# swift's binaries want libncurses.so.6 and the image ships
# only libncursesw.so.6.6; the symlink lives in the image's
# own /usr/lib and does NOT survive a container restart.
if [ -f /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 ]; then
  ln -sf /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 \
     /usr/lib/x86_64-linux-gnu/libncurses.so.6 2>/dev/null
  ldconfig 2>/dev/null
fi
echo "=== op pipeline -- cpp -- 400 candidate probes ==="
date -u +%Y-%m-%dT%H:%M:%SZ
# refuse in seconds rather than in an hour
if ! /usr/bin/clang++ --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: /usr/bin/clang++ is not runnable in this container."
  echo "!! tried: /usr/bin/clang++ --version"
  exit 4
fi
/usr/bin/clang++ --version 2>&1 | head -2
if ! objdump --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: objdump is not runnable."
  exit 4
fi
objdump --version 2>&1 | head -1
rm -rf "$ROOT"; mkdir -p "$ROOT" "$GOCACHE" "$GOPATH"
df -Pm /work | awk 'NR==2{print "free /work: " $4 " MB"}'
FREE=`df -Pm /work | awk 'NR==2{print $4}'`
if [ "$FREE" -lt 400 ]; then
  echo "!! REFUSING TO START: only $FREE MB free on /work, need 400"
  exit 3
fi
base64 -d <<'T_EOF' | gunzip > "$ROOT/table.json"
H4sIAAAAAAAC/72d3a4cN3aFX+VAuZkAk7gXySK5kyBAEiAvkMsoECRZ8BjwHBmyhJnBYN49PLJH
P12rurV2AcsXFnRs1dbazSI/NDfw/fXZTy8ff/jw8oc3z/7l4dnrn39+9vuHZ28/vH/63Xfr1+/e
vfnhzeOL9R9evL6gj39+/+f3T//Lz+/evnrzy/q//vevzx7XL73Py2X9/Je//PHV25+e/vTbn198
/OGzTz998ebPL18/Pfn9uw9vnn769sO71x/rfvfdw8cH/vqYh3/6p4dXPz6+fPeX9cv7l4/fP3/8
hx8fX//04fs3D//2+pf33//4+P7fv/rZ2z/+/PLdm69+9vjmT+v3zx/f/Pn9m3ePD8+f/dfzZw8v
P7x/+/zx73+z3/309vGHhxf/8fr1hz8+vPz9w8fffvzXq398/vjX548P6593b95/WH/+5W9/lYdX
//r88W/PH5/97fcPn5ODJYecHKbkuE7+yx/evnsvpy4sdZFTF1PqwlP/9ns1fGXhqxy+msLXg/D/
/W79LeXwjYVvcvhmCt924X/84fHN9w+v//DynZx9Y9k3Oftmyr4dZF9Pl6N3Fr3L0bspej+Intri
B8s+5OzDlH3cyp5qwGQNmHIDpqkB86ABuaMuWPiQw4cpfFyH//D4W/zcaQeGdpDRDia0w+U4f+rA
AwM8yIAHE+ABh/kzRx4Y6EEGPZhAD+UwfeLQAwM9yKAHE+ihHobP7PpgpAeZ9GAiPbTb6ZO7H0M+
yMgHE/Jhu9OE3BbI4A8y/MEEf+i3m5B6GRgDQmZAmBgQ47AFKQgCI0DIBAgTAWLeiZ/cDBgKQkZB
mFAQca8Lqd2gMCAsMhAWExCWHRD+6QmEXui5GQgWGQSLCQTL30Hw1w955c4t+sIIsMgEWEwEWMou
9n++ffuTnJqhX5HRr5jQr9Rd6ty7zZivyMxXTMxX2i72/7zM7u6FoV6RUa+YUK9sPHvuc2eEV2TC
KybCK51mP8H5hfFdkfmumPiujBsNyK0ARnhFJrxiIrwyaQPO0F1hdFdkuismuitxqwOpNVAZ2VWZ
7KqJ7OqFduDk952VYV6VMa+aMK/iThNyK4FBX5Whr5qgr5bbTThxMFQGglUGwWoCwVq/pRO5NcHY
sMpsWE1sWNvtTpw5KipDxSqjYjWhYt2+qRW5VcHIscrkWE3kWPfk+GI9GGXqXwhUxoxVZsZqYsa6
Z8YXH9LZGS5WGRerCRfrDhdfJb4UqIwQq0yI1USIdUeImRvAxqCwyVDYTFDYLiw0ur7EGwPBJoNg
M4FgAwteSyI4g78mw18zwV8rLHhiT2sM9ZqMes2Eem2Heokr7sagrslQ10xQ13ZQl7nMawzfmoxv
zYRvbaOhc+jaGK81mdeaidda59lTrNoYsDUZ2JoJ2Nqg2VMrnuFak3GtmXCt7XAtdWvdGK81mdea
idda8NS5F31j3LbJ3LaZuG27HIRPvekbY7dNZrfNxG7bjt1OjOxtDN82Gd82E75t5SB7gmY2RnCb
THCbieC2ehA9s8VvjOQ2meQ2E8lt7Vb2VAMY1W0y1W0mqtu2gwakjrqNYd0mY91mwrpth3Unb202
hnabjHabCe22cZw/d+AxwNtkwNtMgLfNw/ypI4+B3iaD3mYCvS0O0ycOvc5Ar8ug102g1y+H4TO7
fmek12XS6ybS67idPrf7dYZ8XUa+bkK+Xu40IbUFdgZ/XYa/boK/Xm83IfUyMAbsMgN2EwP2dtiC
FAR1RoBdJsBuIsC+3Ymf3AwYCnYZBbsJBXu/14XcbsCAsMtA2E1A2HdAmJxS7wwEuwyC3QSC/TcQ
/Piv9Ix6Z/zXZf7rJv7rcRU6M6E+GPYNGfuGCfvG5Spz6q0ejPaGTHvDRHsDV6Hz0+mDId6QEW+Y
EG8Uljz3mTOuGzLXDRPXjUqSn2D7wZhuyEw3TEw32mH83KfPmG7ITDdMTDc2Ev8MzQ1Gc0OmuWGi
udGP8+c+f8ZxQ+a4YeK4MUj+k99tDoZ0Q0a6YUK6MW+2ILcKGOANGfCGCfBG3GrBicNgMuibMvRN
E/TNy/0+pNbDZBw4ZQ6cJg6cuNWHM8fDZFg4ZSycJiyc5RsakVsRjBKnTInTRInzmhLTU+iT8eGU
+XCa+HBe82F+Bn0yNJwyGk4TGs4rNMxMoE9Gg1OmwWmiwXlFg5m7vckAcMoAOE0AOMc+cmb6fDLo
mzL0TRP0zbmPnZk9nwz0pgx60wR6M/axEztZMKwLGevChHVxhXWJS+tgABcywIUJ4OIK4DKXc8FQ
LWRUCxOqRSGRc5AajM1CZrMwsVlUljxFpcHgLGQ4CxOcRSPJU2udoVnIaBYmNIsrNEvdPgdjs5DZ
LExsFp1lTr7gjNFCZrQwMVoMGj33hjNOC5nTwsRpccVpJ4bugqFayKgWJlSLoMl1dgkmuwhZdhEm
2UVcLjR4YlsPJrsIWXYRJtlFXHCcPBW/sPhFjl9M8QuNnzncgjkvQnZehMl5EZcrhDt3AxNMehGy
9CJM0ou4tKP0mSMumPYiZO1FmLQXcdkO0icOuWDei5C9F2HyXsSlH2TPHHODRR9y9GGKPg6ip3b6
ybJPOfs0ZZ+3sif3vGAtCLkFYWpB3GxBauNj6ouQ1RdhUl8ELrdakHkNmPsiZPdFmNwXARw0IIU8
TH0RsvoiTOqLQLkZPrcJMANGyAaMMBkwAvV2D3K7AIM/2YMRJg9G4Ar+cnPkwcQXIYsvwiS+WHV+
9+tnnJ0hDya5CFlyESbJxarzReDE/Hgwo0XIRoswGS1WnS/y5t5jxnSywyJMDotV54vA6bnxYM6K
kJ0VYXJWrDrXqVOfNXNUhOyoCJOjYtW5Sn2C25mmImRNRZg0FasOjZ771BmxyaqKMKkqVp2r6GdI
jQkrQhZWhElYserw7LnPnRGabK0Ik7Vi1bnKfvLbSSauCFlcESZxxapzGD/36TNwk90VYXJXrDpH
8c9s+gzmZH1FmPQVq87tHuTWAeM72WARJoPFqnPUg1PHAMM9WWIRJonFqnOnCamVwDwWIXsswuSx
WHW+aEJ2DjyYtyJkb0WYvBWrzpehP6RTM+STRRVhElWsOp9TJ+a/g9koQrZRhMlGsep8jpu5fWPK
iZCVE2FSTqw6X8dNzH0HU0uErJYIk1pi1fk6cmLmO5hCImSFRJgUEqvO15EzuxbDNdkcESZzxKrz
OXHiIpm5IkJ2RYTJFbHqfE6buTRjloiQLRFhskSsOldxc+DJNBEhayLCpIlYda5Tp0iTOSJCdkSE
yRGx6lylzqxvpocIWQ8RJj3EqvM5c+oemGkhQtZChEkLsepc502+0Iy9ZDNEmMwQq84udu6NZvwl
uyHC5IZYdb6InR9zY1aIkK0QYbJCrDq71AkuYTqIkHUQYdJBrDq70Kntm9GYrIIIkwpi1eGpU9EZ
mck+iDD5IFadXfTUAcZMECGbIMJkglh1Psc+eTPCNBAhayDCpIFYdVjy1DHGJBAhSyDCJIFYdUjy
zEHGDBAhGyDCZIBYdUjuxFHG5A8hyx/CJH9YdUjszI7OnA8hOx/C5HxYdY5yJ/c3hm2y9SFM1odV
5zB+bpNjACdLH8IkfVh1juKnlj7jONn4ECbjw6pDwudwhlGcLHsIk+xh1TkMnnvpme8hZN9DmHwP
q85x/tRbz4wPIRsfwmR8WHU+50/OYjO9Q8h6hzDpHVad3321vtMj2czoELLRIUxGh1Vnnzszmc0s
DiFbHMJkcVh19rFzLzaDOVnfECZ9w6qzz52f02bWhpCtDWGyNqw6B+FznzwDOVnWECZZw6rDw58g
eaZtCFnbECZtw6pzqwO5NcCwTnY4hMnhsOrwDpwhO6Z0CFnpECalw6pzswWpVcAEDyELHsIkeFh1
eAtOfm/JZA8hyx7CJHtYde51IbcWGP7J4ocwiR9WnTtdOHE8MAlEyBKIMEkgVp1vakVuVTBKlIUQ
YRJCrDp3WnHqwGDQKMshwiSHWHW+rRe5dcEYUhZFhEkUserse5Ge/WaGiJANEWEyRKw6JHt6BJy5
IUJ2Q4TJDbHq7MJnJsGZCSJkE0SYTBCrzi515nqPeR9C9j6Eyfuw6tDUmblwJnoIWfQQJtHDqkOT
Z8bDmdkhZLNDmMwOqw5NntjYmNkhZLNDmMwOq84ueOImm0kdQpY6hEnqsOrsQmcu85jXIWSvQ5i8
DqsOT52jWGZ4CNnwECbDw6pzED6FrczzELLnIUyeh1WHh08tegZusushTK6HVWcXPXV/zWQPIcse
wiR7WHUOYudediZ+CFn8ECbxw6pzlD71tjMHRMgOiDA5IFadffr8bB7TQISsgQiTBmLVOQqfwBom
gghZBBEmEcSqc5Q9s9EzG0TINogw2SBWnZvhUx1gfCe7IcLkhlh1jjqQO/EY4Ml6iDDpIVadXfqT
9zlMEhGyJCJMkohV50YDcuceQz3ZFREmV8Sqc9wA/eQbF2KMePqhFv/pTzjiP9U5ji+ffetxYOkh
p4cpPY7T63v/el5h8Yscv5jilzvxM1vgemxlXahyF6qpC/VeFxL74HpsY11ocheaqQvtThdS78PG
erDJPdhMPdiOe5CgofXAzvJ3OX835e/38ic3hMHaMOQ2DFMbxt025HaEydow5TZMUxv2aJgaal9P
ChY85OBhCv4JCX/9mJND7eMCxoKQWRAmFsRln1sfal/PYRAIGQJhgkBgHzv1foPRH2T6g4n+UPa5
s0Pt62kM+iBDH0zQh3oQPvfJM9aDzHowsR4aD3+C+cFIDzLpwUR6nxwStAO5NcBYDzLrwcR6n6QS
Vx04w3lgnAeZ82DivE+eCd6C3CpgjAeZ8WBivE/miasWnPoSdD2WAR9k4IMJ+BD3upBaC4XhX5Hx
r5jwr1zudOHE8VAYEhYZCYsJCQu+qRW5VcEosciUWEyUWMqdVpw5MAqDxiJDYzFBY6nf1ovcumAM
WWSGLCaGLIQhk0Pt62GMHotMj8VEj4XQY3aofT2NgWORwbGYwLHswfFV4kuCwlixyKxYTKxY9qyY
uR0sDA+LjIfFhIdl0tT6UPt6FEPCIiNhMSFhCZpcH2ofl8owsMoYWE0YWC80eWJjqwz6qgx91QR9
dQ99iRvwyvCuynhXTXhX93iXueirDOSqDHLVBHK18tQ5iq2M3KpMbtVEbrUdhE9ha2XoVmV0qyZ0
qxsPn1r0DNyqDG7VBG51D26pS+3KyK3K5FZN5FbHQezky84IrsoEV00EV+dR+tzbziiuyhRXTRRX
9xR3YrSvMZBrMsg1E8i1y1H4BNY0xnJNZrlmYrmGo+yZjb4xpmsy0zUT07VyM3yqA4zvmsx3zcR3
rR51IHXiNQZ4TQa8ZgK8tge8k/c5jUFekyGvmSCvbTcakDr3GkO9JqNeM6Fe68cNSJ18DPmajHzN
hHxtHMfPnH0M+ZqMfM2EfG0ep0/t/Yz5msx8zcR8Le7Ez22BG4O/TYa/zQR/2+VeF1L74MYwcJMx
cDNh4IY7Xci8DxujwU2mwc1Eg1s57kGKhjbGgpvMgpuJBbd6L39yQ2BQuMlQuJmgcGt325DbERga
bjIabiY03PZomBxq3xgSbjISbiYkfBJyfAGA6Zn2jaHgJqPgZkLBJxHHVezMSPvGEHCTEXAzIeCT
geMqde7lZui3yei3mdDvyb9xFTs/0N4Z8HUZ+LoJ+J7cGyx76nPvDPO6jHndhHlP3g2S/QTtd8Z4
XWa8bmK8Jw3HYQNyK4BBXpchr5sg78nHQRpwhu8647su81038d2TmuO4A7k1wNCuy2jXTWj3JOkg
HTj51WdnmNdlzOsmzOv9ThNyK4FBX5ehr5ugr4/bTThzMDAQ7DIIdhMI9vktncitCcaGXWbDbmLD
Hrc7ceaoGAwVh4yKw4SK4/JNrUitisHIccjkOEzkOPbkmB5iH4wZh8yMw8SMY8+M+Rn2wXBxyLg4
TLg4driYGWEfjBCHTIjDRIhjR4iZq8DBoHDIUDhMUDg2FjozwD4YCA4ZBIcJBEdnwTPz64PB35Dh
b5jgbwwWPLOnMdQbMuoNE+qNHeolrroHg7ohQ90wQd3YQV3mQm8yfJsyvk0Tvs0LDZ1D18l4bcq8
Nk28NsGzp1h1MmCbMrBNE7DNQrOnVjzDtSnj2jTh2tzhWuriejJemzKvTROvzcZTJ190xm1T5rZp
4ra5HYTPvemM3abMbtPEbnPHbidm9ybDtynj2zTh2xwH2RM0MxnBTZngpong5jyIntriGclNmeSm
ieRm3MqeaUAwqguZ6sJEdXE5aEDqqAuGdSFjXZiwLnZYd/LWJhjahYx2YUK7KMf5UwdeMMALGfDC
BHhRD/NnjrxgoBcy6IUJ9KIdpk8cesFAL2TQCxPoxXYYPrXrM9ILmfTCRHrRb6dP7n4M+UJGvjAh
X4w7TchtgQz+Qoa/MMFfzNtNSL0MjAFDZsAwMWDEYQsyEASm4oCs4oBJxYHL5U781GYApuSArOSA
ScmBC+51IbMbgJk5IJs5YDJz4LIDwtyUOpiLA7KLAyYXBy6fQPCJfLJD6mDuDcjuDZjcG7i069SJ
GXUw2QZk2QZMsg1ctuvQuRe7s9RdTt1Nqft16vSEOphWA7JWAyatBi6DRs996pNFn3L0aYo+WfQ8
4YMZNSAbNWAyauASx/lTnz8za0A2a8Bk1gAuLP8ZqmOODciODZgcGwBuNCC3AhjQybINmGQbQGEN
OPctJ5hzA7JzAybnBlBv9yC3DhjqyeoNmNQbQLvZgxNHAjNwQDZwwGTgALZvaERuRTAilEUcMIk4
gH6zEacOCQaIso8DJh8HML6lE7k1wXhR1nLApOUAdryYnUoHU3FAVnHApOIAdqSYHkoH829A9m/A
5N9AuYbExEw6mGgDsmgDJtEGyjUXJq77wIwakI0aMBk1UArJnJhIB7NnQLZnwGTPQKkkd2IgHcyU
AdmUAZMpA6WR3JntjAGeLMmASZKBcg14+l02mBoDshoDJjUGyjXKJS7twMQYkMUYMIkxUAbLnONV
ZseAbMeAyY6BMmn0FKAyPQZkPQZMegyUYNEzy53ZMSDbMWCyY6BeQ1rqZpqZMSCbMWAyY6CChs69
5EyQAVmQAZMgA7Xw7Km3nGkyIGsyYNJkoF4TW34mD0ySAVmSAZMkA7Xx6AmIYYYMyIYMmAwZqBtP
ntrcGb/JhgyYDBmo/Ub0VH7GcrIqAyZVBurg+XNnHIM5WZQBkygD9RrmTt7NMFMGZFMGTKYM1DiM
nzrpmCsDsisDJlcG2uUofuasY7IMyLIMmGQZaDgKnzjtmCsDsisDJlcGWjnKntnvmSYDsiYDJk0G
Wr0ZPrfxMVkGZFkGTLIMtHa7B7ndjyGf7MuAyZeBtt3sQepNYOQnCzNgEmag9aMOpNiH+TIg+zJg
8mWgjdvpkxsBA0BZmwGTNgNt3mlCbidgGCjLM2CSZ6BdY2By7JzZMiDbMmCyZWD7hH8f97r03DnT
Y0DWY8Ckx8CGXezM4DkTYkAWYsAkxMBWdqlTrzbzYED2YMDkwcBWd7Hzo+dMfgFZfgGT/AJb49lz
nzuDO9l4AZPxAttGs58gfGa+gGy+gMl8gc/mC9KA3ApgeCc7MGByYOCzA+OrBpxhO+bDgOzDgMmH
gc8+DNaB3BpgYCerMWBSY+CzGuOrDpz8kpM5MiA7MmByZKBf7jQhtRKYLAOyLAMmWQY6bjfhxMHA
rBmQrRkwWTPQy7d0IrcmGBvK+gyY9Bno9XYnzhwVzKMB2aMBk0cDvX1TK3KrgpGjLNSASaiBvifH
9Bg602hA1mjApNFA3zNjfg6d2TMg2zNgsmeg73AxM4jORBmQRRkwiTLQd4SYufhjTgzITgyYnBjo
wUJnRtGZAQOyAQMmAwbGhQXPzKIz3wVk3wVMvgsMsOCJPY3JLiDLLmCSXWDsUC9xtc0kF5AlFzBJ
LjB2UJe5yGOSC8iSC5gkFxiNhs6hK3NdQHZdwOS6wNh49hSrMt0FZN0FTLoLjE6zp1Y8wzXZdwGT
7wJjh2upK2tmu4Bsu4DJdoExeerki864TdZewKS9wIiD8Kk3nekvIOsvYNJfYO7Y7cSkHtNfQNZf
wKS/wMRB9gTNMPsFZPsFTPYLzHIQPbPFM/8FZP8FTP4LzHore6oBjOpkFQZMKgzMdtCA1FHHVBiQ
VRgwqTAwd1h38taG2TAg2zBgsmFg9uP8uQOPAZ5sxIDJiIE5DvOnjjwGerIUAyYpBuY8TJ859Bjo
yVYMmKwYmHEYPrPrMyUGZCUGTEoMxOV2+tzux9QYkNUYMKkxELjThNQWyPwYkP0YMPkxEOV2E1Iv
A2NAWZEBkyIDUQ9bkIIg5siA7MiAyZGBaHfiJzcDhoKyLAMmWQZiu9eF3G7AgFCWZsAkzUDsgDA5
pc48GZA9GTB5MhBfg+C5UXWmx4Csx4BJj4GYPHtmXp1pMSBrMWDSYiCCR//2V/3//vb/WIMPwACM
AQA=
T_EOF
echo "payload bytes: $(wc -c < "$ROOT/table.json")"
python3 - "$ROOT" <<'PY_EOF'

import json, os, re, shutil, subprocess, sys, time

ROOT = sys.argv[1]
T = json.load(open(os.path.join(ROOT, "table.json")))
LANG = T["language"]
PROBES = T["probes"]
OUT = T["out"]
out = open(OUT, "w")
WORK = os.path.join(ROOT, "u")

# --- verbatim delimiter codec, copied from verbatim_diag.py ---
def esc(text):
    """make `text` safe to place in one pipe-delimited field, reversibly."""
    for raw, rep in _ENC:
        text = text.replace(raw, rep)
    return text

_ENC = [('\\', '\\\\'), ('|', '\\p'), (';', '\\s'), ('\n', '\\n'), ('\r', '\\r')]
MARKER = '#verbatim-escape v1'
out.write(MARKER + '\n')


print("op lane %s: %d candidate probes" % (LANG, len(PROBES)))
sys.stdout.flush()


def sh(cmd, cwd=None, timeout=180):
    try:
        p = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE, timeout=timeout)
        so = p.stdout.decode("utf-8", "replace")
        se = p.stderr.decode("utf-8", "replace")
        return p.returncode, so, se
    except subprocess.TimeoutExpired:
        return 124, "", "TIMEOUT after %ds" % timeout
    except OSError as e:
        return 125, "", "OSError %s" % e


# ------------------------------------------------------ objdump reading

LABEL = re.compile(r"^([0-9a-f]+)\s+<(.+)>:\s*$")
INSN = re.compile(r"^\s*([0-9a-f]+):\t(.*)$")
RELOC = re.compile(r"^\s+([0-9a-f]+): (R_\S+)\t(.+?)\s*$")


def extract(text, sym, exact):
    """the two columns for one symbol.

    bytes  every byte objdump printed, in order, flattened
    mnem   the instruction text, with objdump's own trailing `# ...`
           comment dropped -- that comment is arithmetic objdump did
           for the reader, not part of the instruction.  A relocation
           is appended to the instruction it applies to as
           ` !!reloc=<type>:<symbol>`, because in an object file the
           call displacement is literally zero and the callee's name
           lives only in the relocation.
    """
    lines = text.splitlines()
    k = -1
    for idx, ln in enumerate(lines):
        m = LABEL.match(ln)
        if not m:
            continue
        lab = m.group(2)
        hit = (lab == sym) if exact else (sym in lab)
        if hit:
            k = idx
            break
    if k < 0:
        return None
    raw = []
    mn = []
    for ln in lines[k + 1:]:
        if LABEL.match(ln):
            break
        m = INSN.match(ln)
        if not m:
            r = RELOC.match(ln)
            if r and mn:
                mn[-1] = "%s !!reloc=%s:%s" % (mn[-1], r.group(2), r.group(3))
            continue
        parts = m.group(2).split("\t")
        bs = parts[0].split()
        raw.extend(bs)
        txt = parts[1] if len(parts) > 1 else ""
        txt = txt.split("#")[0]
        txt = " ".join(txt.split())
        if txt:
            mn.append(txt)
    return raw, mn


def disasm(obj, sym, exact):
    rc, so, se = sh(["objdump", "-dr", "--disassemble=" + sym, obj])
    got = extract(so, sym, exact) if rc == 0 else None
    if got is None:
        rc, so, se = sh(["objdump", "-dr", obj], timeout=600)
        got = extract(so, sym, exact)
    return got


# --------------------------------------------------------- DWARF reading
#
# objdump --dwarf=info prints one entry per line block:
#
#   <1><2d>: Abbrev Number: 2 (DW_TAG_subprogram)
#      <2e>   DW_AT_name        : op_12
#   <2><4a>: Abbrev Number: 3 (DW_TAG_formal_parameter)
#      <4b>   DW_AT_name        : a
#      <52>   DW_AT_location    : 2 byte block: 91 7c (DW_OP_fbreg: -4)
#
# The leading <N> is the tree depth.  A formal parameter one level
# below the matching subprogram is a parameter OF that subprogram.

DIE = re.compile(r"^\s*<(\d+)><[0-9a-f]+>:\s*Abbrev Number:\s*\d+\s*\((\S+)\)")
ATTR = re.compile(r"^\s*<[0-9a-f]+>\s+(DW_AT_\w+)\s*:\s*(.*?)\s*$")


def clean(text):
    text = " ".join(text.split())
    return text


STRPREFIX = re.compile(r"^\((?:indexed string|indirect string)[^)]*\):\s*")


def dwname(text):
    """objdump prints a string attribute as `(indexed string: 0x5): a`.
    The parenthesised part is objdump telling the reader WHERE in the
    string table it found the name; the name is what follows.  Keeping
    the prefix would have put objdump's bookkeeping into the parameter
    name column."""
    return STRPREFIX.sub("", text.strip())


def dwarf_params(text, sym):
    """[(name, location)] for the subprogram named `sym`.

    More than one subprogram can carry the name.  swift's `@_cdecl`
    emits a C-entry thunk beside the real function, and the thunk has
    no DW_TAG_formal_parameter children at all, so the first match is
    not always the one holding the parameter table.  Every match is
    collected and the first one that actually has parameters wins."""
    lines = text.splitlines()
    depth = None
    tag = None
    attrs = {}
    entries = []
    for ln in lines:
        m = DIE.match(ln)
        if m:
            if tag is not None:
                entries.append((depth, tag, attrs))
            depth = int(m.group(1))
            tag = m.group(2)
            attrs = {}
            continue
        a = ATTR.match(ln)
        if a and tag is not None:
            attrs[a.group(1)] = a.group(2)
    if tag is not None:
        entries.append((depth, tag, attrs))

    hits = []
    for idx, (d, t, at) in enumerate(entries):
        if t != "DW_TAG_subprogram":
            continue
        names = []
        if "DW_AT_name" in at:
            names.append(dwname(at["DW_AT_name"]))
        if "DW_AT_linkage_name" in at:
            names.append(dwname(at["DW_AT_linkage_name"]))
        for nm in names:
            if nm == sym or sym in nm:
                hits.append(idx)
                break
    if not hits:
        return None
    best = []
    for k in hits:
        base = entries[k][0]
        got = []
        for d, t, at in entries[k + 1:]:
            if d <= base:
                break
            if d != base + 1:
                continue
            if t != "DW_TAG_formal_parameter":
                continue
            nm = clean(dwname(at.get("DW_AT_name", "(unnamed)")))
            loc = clean(at.get("DW_AT_location", "(no location)"))
            got.append((nm, loc))
        if got:
            return got
        best = got
    return best


def dwarf(obj, sym):
    rc, so, se = sh(["objdump", "--dwarf=info", obj], timeout=600)
    if rc != 0:
        return None, "objdump --dwarf=info rc=%d" % rc
    got = dwarf_params(so, sym)
    if got is None:
        return None, "no DW_TAG_subprogram named %s" % sym
    if not got:
        return None, "subprogram %s has no DW_TAG_formal_parameter" % sym
    return got, None


# ------------------------------------------------------------ compiling

GOMOD = "module opprobe\n\ngo 1.26\n"

CLANG = "/usr/bin/clang"
CLANGXX = "/usr/bin/clang++"
SWIFTC = "/persist/swift/usr/bin/swiftc"


def compile_probe(p, d, mode):
    """(rc, artifact path, diagnostic text)."""
    if LANG == "c":
        src = os.path.join(d, "unit.c")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANG, "-std=c17"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "cpp":
        src = os.path.join(d, "unit.cpp")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANGXX, "-std=c++20"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "rust":
        src = os.path.join(d, "unit.rs")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        if mode == "anchor":
            opt = ["-C", "opt-level=0", "-g"]
        else:
            opt = ["-C", "opt-level=1", "-C", "debug-assertions=off"]
        cmd = (["rustc", "--crate-type=lib", "--emit=obj"] + opt
               + ["-o", obj, src])
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "go":
        open(os.path.join(d, "go.mod"), "w").write(GOMOD)
        open(os.path.join(d, "main.go"), "w").write(p["source"])
        obj = os.path.join(d, "bin_%s" % mode)
        cmd = ["go", "build"]
        if mode == "anchor":
            cmd.append("-gcflags=-N -l")
        cmd.extend(["-o", obj, "."])
        rc, so, se = sh(cmd, cwd=d, timeout=300)
        return rc, obj, (se or so)
    if LANG == "swift":
        src = os.path.join(d, "unit.swift")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-Onone", "-g"] if mode == "anchor" else ["-O"]
        cmd = [SWIFTC] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd, timeout=300)
        return rc, obj, (se or so)
    raise KeyError(LANG)


DIAG = re.compile(r"^[^\s:]+:\d+(:\d+)?:")


def firstline(txt):
    """the compiler's own words for why it refused.

    The first line is not reliably the reason.  clang leads with a
    warning and puts the error underneath.  go leads with a banner
    naming the package -- `# opprobe` -- and its diagnostics never
    contain the word `error` at all, so a rule that only looked for
    that word recorded the banner and threw the testimony away.
    Three passes, in order: a line saying `error`, a line in the
    `file:line:col:` diagnostic shape, then the first line that is
    not a banner."""
    lines = []
    for ln in txt.splitlines():
        s = ln.strip()
        if s:
            lines.append(s)
    for ln in lines:
        if re.search(r"\berror\b", ln, re.I):
            return ln[:200]
    for ln in lines:
        if DIAG.match(ln):
            return ln[:200]
    for ln in lines:
        if not ln.startswith("#"):
            return ln[:200]
    if lines:
        return lines[0][:200]
    return "(no diagnostic)"


def write_unit(n, build, obj, sym, exact):
    got = disasm(obj, sym, exact)
    if got is None:
        rc2, so2, se2 = sh(["objdump", "-t", obj])
        near = 0
        for l in so2.splitlines():
            if sym in l:
                near += 1
        out.write("op_%d|%s|NOSYM|%s\n"
                  % (n, build, esc("symbol %s absent, %d near matches"
                                   % (sym, near))))
        return False
    raw, mn = got
    out.write("op_%d|%s|OK|%s|%s\n"
              % (n, build, " ".join(esc(x) for x in raw),
                 ";".join(esc(x) for x in mn)))
    return True


t0 = time.time()
tally = {"REFUSED": 0, "ACCEPTED": 0, "ANCHOR_OK": 0, "SHIP_OK": 0,
         "DWARF": 0}

for k, p in enumerate(PROBES):
    n = p["n"]
    sym = p["symbol"]
    exact = p["symbol_exact"]
    d = os.path.join(WORK, "n%d" % n)
    shutil.rmtree(d, ignore_errors=True)
    os.makedirs(d)

    rc, obj, err = compile_probe(p, d, "ship")
    if rc != 0 or not os.path.exists(obj):
        out.write("op_%d|REFUSED|%s\n" % (n, esc(firstline(err))))
        tally["REFUSED"] += 1
        out.flush()
        shutil.rmtree(d, ignore_errors=True)
        continue
    tally["ACCEPTED"] += 1
    if write_unit(n, "SHIP", obj, sym, exact):
        tally["SHIP_OK"] += 1

    rc, aobj, aerr = compile_probe(p, d, "anchor")
    if rc != 0 or not os.path.exists(aobj):
        out.write("op_%d|ANCHOR|BUILDFAIL|%s\n" % (n, esc(firstline(aerr))))
    else:
        if write_unit(n, "ANCHOR", aobj, sym, exact):
            tally["ANCHOR_OK"] += 1
        rows, why = dwarf(aobj, sym)
        if rows is None:
            out.write("op_%d|ANCHOR|NODWARF|%s\n" % (n, esc(why)))
        else:
            joined = ";".join("%s=%s" % (esc(a), esc(b)) for a, b in rows)
            out.write("op_%d|ANCHOR|DWARF|%s\n" % (n, joined))
            tally["DWARF"] += 1
    out.flush()
    shutil.rmtree(d, ignore_errors=True)

    if (k + 1) % 25 == 0 or (k + 1) == len(PROBES):
        el = time.time() - t0
        print("[progress] %s [%d/%d] elapsed %.1fs mean %.2fs  "
              "REFUSED %d ACCEPTED %d SHIP_OK %d ANCHOR_OK %d DWARF %d"
              % (LANG, k + 1, len(PROBES), el, el / (k + 1),
                 tally["REFUSED"], tally["ACCEPTED"], tally["SHIP_OK"],
                 tally["ANCHOR_OK"], tally["DWARF"]))
        sys.stdout.flush()

out.close()
print("done: %s -> %s" % (json.dumps(tally), OUT))

PY_EOF
echo "--- lane finished, rc=$?"
date -u +%Y-%m-%dT%H:%M:%SZ
