#!/bin/sh
# op-pipeline lane -- c -- generated by
# Research/op_pipeline/lane_gen.py .  Do not hand-edit.
# steps 1b/2/3: compile-or-refuse, then the ANCHOR and SHIP
# builds of every probe the compiler accepted, then objdump
# extraction, then the anchor's DWARF parameter table.
set -u
export HOME=/work
export PATH=/persist/swift/usr/bin:$PATH
export GOTOOLCHAIN=local
export GOPROXY=off
export GOFLAGS=-mod=mod
ROOT=/work/regen_c_c0044
export GOCACHE="$ROOT/gocache"
export GOPATH="$ROOT/gopath"
# swift's binaries want libncurses.so.6 and the image ships
# only libncursesw.so.6.6; the symlink lives in the image's
# own /usr/lib and does NOT survive a container restart.
if [ -f /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 ]; then
  ln -sf /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 \
     /usr/lib/x86_64-linux-gnu/libncurses.so.6 2>/dev/null
  ldconfig 2>/dev/null
fi
echo "=== op pipeline -- c -- 400 candidate probes ==="
date -u +%Y-%m-%dT%H:%M:%SZ
# refuse in seconds rather than in an hour
if ! /usr/bin/clang --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: /usr/bin/clang is not runnable in this container."
  echo "!! tried: /usr/bin/clang --version"
  exit 4
fi
/usr/bin/clang --version 2>&1 | head -2
if ! objdump --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: objdump is not runnable."
  exit 4
fi
objdump --version 2>&1 | head -1
rm -rf "$ROOT"; mkdir -p "$ROOT" "$GOCACHE" "$GOPATH"
df -Pm /work | awk 'NR==2{print "free /work: " $4 " MB"}'
FREE=`df -Pm /work | awk 'NR==2{print $4}'`
if [ "$FREE" -lt 400 ]; then
  echo "!! REFUSING TO START: only $FREE MB free on /work, need 400"
  exit 3
fi
base64 -d <<'T_EOF' | gunzip > "$ROOT/table.json"
H4sIAAAAAAAC/8Wd245cR3JFf6VBv2gGM6OT14gYGwbsB/+AHy2jQVLUBaCaBEXCI2j0766mqO7q
jJ2neh92BudFYk+RpVjKith1lIH167PXz2++//D8+1fP/n717OWzv1w9e/Ph/e3ff33669fvXn3/
6ub65fXLbav1b+//8f72BW/fvXnx6ufTa/7n12c3p78k6dt2+vnPv/z04s3r29/75u31xx8+u/vp
9at/PH95++e+f/fh1e1P33x49/Lje37956uPf+Dvf8zVX/969eLHm+fvfrn65z+v/vz1Nzf/8uPN
y9cfvn119W8/v//2x5v3f/vh34cfvnjz5vXHn35zc339/pe3r958d3391Vev39x8f/Xtmw8vXr/6
06/bb7d/3lfX//Hy5Yefbn/5p29u/vinPH/l1fO/XP3+oqsXp5f8+s3N1el/7169//Du5ur57Z/x
4l+/ufntm5tnv/3l6r78hMpPdPlpdfn/eXrtw+qTq/72NVTxGRWf6eLz6uL/6/Wb5+9Tf1h/dvV/
ehmFoCAEhUZQliN4d/rHeAigeAC3L6LKr6j8SpdfV5f/38/fX6EWUB2D+1dSIBoC0WgQLQQEOAwN
g+BPREcgOg2iR4D4+H+gY9EhjbOXU0gEIREaicQhAQdEdpDwp0QREqWRaASSn3948w53D4VMzl9P
QTEExWgoFggFHBTbg0KflITyZaLzZdoioHy4+fnH729efYsOS9ogl+G3UGhQ9kx09kwpFo0/Mild
QMOfGpRME51MUw5FMxtHKe/zOTiXEsquic6uqXwBSOAQlcdA4k8SSriJTriphkKajqxU9ykdnV0J
5d9E59/UvgQmcJjaozDxpwml40Sn47Q8HV+/+G74vpx8Jv74Iqp8lIQTnYTT8iR8/d3HRwFZHyLw
GfjuhRQGlH4TnX6TrsfwdjwFChC8JU8ByrmJzrlpec69/vHFT+4M+Hj76WUMgoxSbaZTbd7WI7i5
Pd3XD9tj3gCETy+kMKAEm+kEm5cn2OsPmIMPrvevpECgvJrpvJpX59UX41Pk7KLpC/IhckYpNNMp
NK9OoS9/eP7uYekucN6+hCodZctMZ8tcA0pPfTz7FZV/+zIKAcqNmc6NuQUgKHlE0BCC25dRCFAm
zHQmzD0AgWuAHRFgmx9KhZlOhXl1Krz/5X39LhF++jumfJQGM50G8+o0+DHpPqzehcGPr6GKR1kw
01kwr86CPzx//d3D2l0OvH0JU3pBGbDQGbCszoCn3/+g8uLC3+kVVOEo9RU69ZXVqe/2Zw8rd3Hv
4y+Z0lHOK3TOKzmgdPT4qGRIgH9eVFDqK3TqKyUEhH9AVAoGQT8RKigDFjoDlhoBAkzAUiEIfgwW
lAQLnQRLiwDhW0ODGOj+gLJgobNgWZ0FPz7/fAjAJcHfn5EyxaMcWOgcWCSieNgdBTM40B5RJix0
JiwagwL0R52g4BskSoiFTohldUL89F8G3GOC4oLi2SsZEBXlxUrnxbrFgBhjY90mHMj0WFF6rHR6
rCkGg5sUNU04sLOioixZ6SxZcxwIQCPv0aCRoFRZ6VRZSwwSP0VrmeCgh2lFubLSubKuzpV7V2aq
y5afcVumonxZ6XxZWxgQP1VrmwOhB2tFWbPSWbP2KCButNY+xUEPV5Q9K509q0TBcONVpizYAYuy
Z6WzZ9UoFH6o6JQFPVFQ+qx0+qwWCQP2UttnwjfUhvJoo/No22LR+K7atgto6NbaUEZtdEZtKRSN
+xy1tA+G/TA1lFgbnVhbjsLiA1rLUyR0RGsorTY6rbYSigM1l1YuUDnQXVB+bXR+bTUYDmgv9RIc
vr+gLNvoLNtWZ9n/u41hw38ybi7DfnoVBQBl10Zn1/bk2fWPHjrbOW39/nXHNk4bSqqNTqpN1pbu
9k2bDJWz26YN5dJG59KmawtHu6ZNh9oPbJo2lEQbnUSbLS7f9z8bi2fbXUdJs9NJs29rS5/smPZt
qP/YhmlHmbLTmbKnAAj+EPSEIPAnASXITifIntdDmH0R6xmQOPgVrKME2ekE2UsUDnAwyhQHfzpQ
Zux0Zux1PY5plO4V8DgaojvKiZ3Oib2FAQEHpM2B8CcE5cZO58be1wPZezDeO2DyGc/GO8qUnc6U
XSKxgKMiu1j404ISZ6cTZ9dALNOxo3tsjs4flEk7nUm7hQMCh8cuA6JPkKDkKnRylS0Q0HQ0ybZH
6OiMEpRrhc61kuIR+UMk6RGI+FOEUq/QqVcWp16/Mypj1qU3RgUlXKETrixOuHhfVMZse2hbVFCq
FTrVSl2NYNwVlerKJzdFBeVXofOrLM6vaE9Uxth6YEtUUFoVOq1KX10+2o2U7gAcWIwUlEyFTqay
OJlO9kNlDKTHtkMF5VChc6iszaFuN1SGyMluhgpKl0KnS1mbLt2tFBmCJHsVRVFmVDoz6ra8bLcT
qpsvnd0IVZQHlc6DmpaX7/ZBNfny2W1QRVlP6ayneXn5Y7PT7KsnG52itKd02tO1aQ9sweiQ9Pj1
F0UpT+mUp2tTnt8B1SHk0RugijKe0hlP12Y8t/+pQ75jtz8VZTuls52uzXbjLUMdQh15tVBRmlM6
zenaNOfuQekQ49h7T4rym9L5TXV52eixjyqonn/OoyjNKZ3m1AIg+Ac7aggC/STHULYzOtvZth4C
mHK2AQj8qDOU8IxOeJbWQ3CtwBJAwPYDQxnP6IxnazOev/xoQ8KjbzwayndG5zsr6wtHndAKqp9v
hYayntFZz2oEBt8LrUIMfDNEyc/o5Gdrk99s+cSGAHhw8cRQDjQ6B1qPgDDGQeuQAZkKDaVCo1Oh
SQQCPxEEMqBnAsqIRmdE0ygIgITOSdA4UFo0Oi2aReAAk9IgCnZgCrLrCG3XkW1tXty5qiLbkBmP
31IR5NoR2rUjWwqC4SanbGkGgx2egtw7Qrt3ZMsxMMbxKVueoCAHqCADj9AGHtlKDIhhhMpWJhy4
ISrIxCO0iUe2GoNhHB6y1QkHcnIIMvEIbeKRrcWBgH2z7fE40Dw7wtJpLD0SC+igfRcL30YFYREa
iwRi8Z8d2YNCf4AUIVEaicYgceFLNp3g4OOXIRRGo7BAFLCZ2C4RvpsgK4/QVh5JWygY307Stg+G
7ifIySO0k0fS2owK9jIlDdmU38oUZN0R2rojT2rduWsPk43M07t9etJ1ZBtTkENHaIeOPKlDZyh5
3MQ8vdlZxeQWpiAfjtA+HHlSH85QMNjAPL3fWc389qUgv43Qfht5Ur/NWLbvbu28aLqVocRIu2rk
SV01Q8l44/L0lmd1H9q2FGSqEdpUI09qqkHFg3/pMhbP/5tHCZD208iT+mlA8bOvTkkHAge/MiFP
jdCeGnlST80UAzgIBjHQpwG5aoR21ciTumoAhmn4zdvA4WjoRbYaoW018qS2mjkIfyBywiD4E4Fy
Hm2rkZzXgth7LJ3zwOIznksjg43QBhvJJQoHOBplioM/HSgh0lYbyTUIx2yM5DpjcnCeINeN0K4b
yS0UDDgsbR8Mf2JQ0qQNOJJ7EJj5qOkzModnDsqhtBtHssSiAYdGLqDhTw1KqbQ3R/LClOo2Ik/v
doaB3YYUZMsR2pYjeWEihZuQp3c8L/vAFqQgW47Qthwp28rShw3I07s9KJvbfhTkyRHakyNlYd4E
m4+n9zsvmt56FOTIEdqRIyWvLBts+53e8UHh/KKfICuO0FYcKQuTJN50PL3lee0fDhWPciNtwpGy
LjeOG46n97qvmtxuFOS7Edp3I2VdGnR3NspZ8GOvaSCzjdBmGyl9abnjRuPp/R6WTG4zCnLaCO20
kSJLyx43GU/v97BscotRkL9GaH+NFF1atmti+rBqtoGhdEabaqSsS2d+p+P0bvc106scgpw0Qjtp
pK5LZW5j8fRm9xWz24qC7DNC22ekrstk46bi6b3u6yW3FAU5ZoR2zEhdl8XG+3T1LISRV+iQPUZo
e4zUdenL3fypZ7GLveeDDDFCG2Kk1qXloscstQ5V889VkA1GaBuM1La4eP8gpbaxePrJCTK/CG1+
kdrXFg+mVe1D8QdGFkpktOlFqqwt3n/UZSid/ryjTEZ7XaSuy2T+Kl89S2T07T3kbhHa3SLV1hYM
O5yNdfMtDvlZhPazSNtWl+97XNtc+XSTQw4WoR0s0tYltdlqRDsLbAeXIpBpRWjTirS8uvgxvrXs
aidTHLKqCG1VkVZWl+46fCuudrbHI2uK0NYUaTWieECgYgI0BpTuaD+KtLYag594rTkE9OBDdhSh
7SjS1uW7vasZ7SzjfcatDORJEdqTIk0CIIAJKAgCPwRR5qOdKdJ0PQQ/BhUgoAchyoC0NUWarQfg
RqGB+slhiMwpQptTpG/ry3fDoG+gfnYSIGuK0NYU6SkGAOqHPc048E0R+VOE9qdIz1E4fGfseYqD
bo/InyK0P0V6CcLhPyNlBoP+oKDkSLtTpNf1KHxo6hVgoGMTsqUIbUuR3oIQwGbRpiQOdAuUI2lb
ivQeBgS0iz4HwvcLlClpT4r0dZkSbfb1syx5YKsPWVCEtqBIf/IMeXb+Z8t9XR+89NiOH7KcCG05
kW7LAbhVv26+fnbjDzlMhHaYiGzLy0eLf7J5Agf2/5ClRGhLiUhaD8G1QEkAAdv6kINEaAeJSF4O
YLIUKNlTOLYbiJwkQjtJREoMCnAgygQFfypQaqTdJCI1BMXsG5ZUzOPglyxkLRHaWiLSAqGAQ9L2
oPAnBWVJ2mUi0kOgTPO1dEzlaMRGfhOh/SYiEokFHBbZxcKfFpQ5aeOJiIZg2XuaLYrJfMaTbeRF
EdqLImLBcMCxsUtw6JOD7ClC21NEt1g4s9Gk2wVCB2cUsqwIbVkRTV8Ckz9Imh6FiT9NKPXSNhbR
HItpOr40X+B0dI4hc4vQ5hbR8kVAgQNVHgeKP1EoMdOeF9H1idkvLyrIyfQOI/K9CO17EV2fjvEq
o4JcfGijERlghDbAiPYAEONio3YEgdxvRDYYoW0wouuzL1pzVBB5D2w7IjeM0G4YUQ2AgBb/VBGG
A+t/yA8jtB9GdH2qnaxAKgizxzYhkSVGaEuM2PIM6xYizcdVdi8S2WGEtsOILU+m7sKK+RDKXldB
ZhihzTBiOaJ4tyxpGQJgdyaRJUZoS4xYiYDgVietQAjsBiVyxAjtiBGrERDGVmgVMmDbIEqKtB9G
bHlSBIsq5lMiv6qC3DBCu2HElidEv2RpPiDSu5bICyO0F0ZseT50K5fmsyG7eYl8MEL7YMSW58Lx
2qL5QEheWkTuF6HdL2LLk6C7jmU+ApL3sBQZX5Q2vui2RRQPHjGd3hkzoJ8pKfK9KO170S3FoHAP
kU7vPEHBPjVSZHtR2vaiWw5B4efh6Z0xCnooKvK9KO170a2EoBhbxOl9MQi6T1SEodIYludDd1vz
9J4OAXtXU5HlRWnLi24tpHzYJ9uEwoFG2RGMTsPoQTBAp+wzGHyrFARDaBjLU+Nk7+X0zp7FoeUX
RSYXpU0uumkQiiFKnt54RoJLlIo8Lkp7XHSzIBB+atiMBDs3kLlFaXOLpi0QheeRtl0eNBSUNGlr
i6YUBMXP1JRmQOjRiiwuSltcNC3PmjvXbjT5vHn8xo0iy4vSlhdNJQ6Jn7Gp7CChxyzywCjtgdFU
w5C4QZvqHAg7apEfRmk/jKYWhmMctqnNaZDjFpljlDbHaOphMPyA6XMa9HRBiZR2yWiSUBywq8oF
KgdaK8qotGtGkwbDAf1VL8HhmyzKrbSBRpPFwvGfJruAhv1IISeN0k4azVsYGB/Z8jaHQoc25KZR
2k2jOcUCQU0mp0tc+C6DjDVKG2s052g8vs3kfBEP3WeQwUZpg43m5fkWrLdq9rmW33JVZK1R2lqj
eUGevTsDky1XvTPVfPo3f2TLVZGdRmk7jea2HMC45ap3Qpqz+sktV0UOGqUdNJr78vLBlqveiWfO
CPBbropsM0rbZjTLegi+LwpAQDdClEZpp4xmXQ4Ab7nqnV/mjMKhLVdFrhmlXTOaLQYFOBA2QUGf
CuSeUdo9o2ULQTH78nYnoxl4HPzihuw0SttptKRAKP6Q3MlqIBT+pKCcSbtrtOQQKNMIfmeyGagc
jd/Ia6O010ZLicQCDkvZxcKfFpQ5aeONlhqCZe9xe6mYzGc8c0d+HKX9OFpaMBxwbNolOPzJQWmV
tulo6bFwpqOpXyB0dEahPEvbd7TIl8AEDpI8ChN/mlDqpW09WjQW03x86QVOh+cYysS04UeLfRFQ
4EDZ40DRJwp5gZT2Amldn5jdlqtWkJPZLVdFniClPUFa16djuOWqFeTiI1uuigxCShuEtOYAEG/H
k5ARhLfkSUDZl7YKaV2ffcGWq1YQefktV0WuIaVdQ1prAASw26m1Igz8aqci75DS3iGt61Mt3nLV
CsLsoS1XRRYipS1EWpdn2HHLVauPq+SWqyILkdIWIq3Lk6m7NVN9CGUvyyATkdImIq0aUfy45apV
IQByy1WRnUhpO5FWi4AwbrlqNQiB3HJV5ChS2lGkbYuAMLbCtkEGZBtEniKlPUXalidFsNXTfErk
F3qQq0hpV5G25QnRbblq8wGR3XJV5CtS2lekbXk+HLdctflsSG65KvIVKe0r0rY8F463JZsPhOQl
SeQoUtpRpG15EnS3uZqPgOz9LWQoUtpQpK1HFI8eMbWOGfDPlJCnSGlPkTaJQeEfIjWZoKCfGiFb
kdK2Im0aggLNQ8UoDgxFlA5pb5E2C0HhW4RhEGyfQP4ipf1F2pfnQ3+9s/t0SN/qRPYipe1F2lNI
+ahP9jShwDdK5C5S2l2kPQfB8J2y5xkMulUic5HS5iLty1PjbPmm+/B4cPUGmYuUNhdpr0EoxijZ
64wEmSiRv0hpf5H2FgTCTY3eZiTouYHyJW0u0t4DUQAefZcHDQUlTdpepF2CoICZKjMg/GhFWZO2
GmlfnjX3rt10nzc/48YN8hwp7TnSbnFIwIy1HST0mEXuI6XdRypbGBI3aGWbA2FHLbIgKW1BUklh
OMZhK2lOgxy3yIiktBFJJYfBcANG8pwGO12QFUlpK5JKCcWBuqqUC1T41oo8SUp7klRqMBzfX6Ve
gsM3WZRbaV+SSouF4z9N7QIa+iOFUiztTFLpYWB8ZJM+h0KHNmRLUtqWpCKxQGCTkUtcDnQZlGlp
a5KKRuMBbUYv4uH7DMq3tDdJZXm+RVuu4nPtgS1XZEdS2o6kT2tHehhcZ0uutyaks9R6aMcVWY+U
th7p01qPUPluxfVWcDRUz264IpeR0i4jfVqXESoeLbjeiouG+g/styJLkdKWIn1aSxFE4BrirZBo
BMA2QOQeUto9pE/rHkLlT5Zbb/1DA4Nju63IQaS0g0if1kE0BQEOQ8Mg+BOBEibtINKndRDNQMy+
r93KiACNg1/VkJVIaSuRPq2VaB8JOCCyg4Q/JShX0o4ifVpH0QzJNHHfmooAk6NhG/mKlPYV6dP6
ii5AAQfF9qDQJwWZi5Q2F6ltEVD2nqzbBrl8xtN15DVS2muklmLR+CNj6QIa/tSgZEpbj9RyKJrZ
OLK8z+fgXEJWJKWtSGrlC0ACh6g8BhJ/klDCpa1JajUU0nRkWd2ndHR2IbOS0mYltfYlMIHD1B6F
iT9NKB3T/iW15enYL7Gaz8T0DivyLyntX1JbnoTxCqv5DHxogxWZmJQ2ManpegzjAqspQEDuryIb
k9I2JrXlORetr5qPt/z2qiEnk9FOJtu29QjAyqZtG4DAL2wa8jEZ7WOybXmCxaurtvngemhz1ZCN
yWgbk22r8+q4uGqbi6bk3qoh+5LR9iXbVqfQ8RqMbS5wkpdfDBmXjDYu2VYDSh+XVm2rqHxyZ9WQ
dclo65JtLQDBuLJqW0MIyI1VQ64lo11LtvUABK4BdkSAbX6CAAgNYHUq9Os5trlESC/mGHIqGe1U
sm11GnTLqra5MMjuqhryKBntUbJtdRYcV1VtczmQ3FQ15E0y2ptkaXUGHC48WnLhj7vmaMiNZLQb
ydLq1Ddex7Lk4h55/8qQCcloE5KlHFA6eHxkKUMC9PMiQ/4jo/1HlkoICPeAyFLBINgnQoasR0Zb
jyzVCBBgAqYKQfBjEPmOjPYdWWoRIHxraBAD3R9QFqQ9R5ZWZ0F3K9OSS4LsXUxDViOjrUaWJKJ4
2B0FMzjQHlEmpB1GljQGBeiPOkHBN0iUEGljkaXVCXGyLWPJBcVjqzKGDEVGG4osbzEgxtiYtwkH
Mj0iL5HRXiLLKQaDmxQ5TTiwswIZiIw2EFnOcSAAjbxHg0aCUiVtHbJcYpD4KZrLBAc9TJF9yGj7
kOXVuXLnyoxlly2P35YxZCMy2kZkuYUB8VM1tzkQerAiP5HRfiLLPQqIG625T3HQwxVlT9pTZFmi
YLjxKlMW7IBF2ZM2FlnWKBR+qOiUBT1RUPqknUWWLRIG7KW2z4RvqMhhZLTDyMoWi8Z31bJdQEO3
VmQyMtpkZCWFonGfo5L2wbAfJuQyMtplZCVHYfEBreQpEjqiIYeR0Q4jKyUUB2oupVygcqC7oPxK
m4ys1GA4oL3US3D4/oKyLG0ysrI6y4K1Uysuw/Jbp4ZsRUbbiqwsyK6fgtlk6dRKP3vhoZ1TQw4i
ox1EVmRx8ePKqRUZayc3Tg15hYz2ClnRxaWDhVMrOlbP75sa8gUZ7QuyYqsB+DZorny27SEHkNEO
IKvb4uLxsqnVbSRwaNfUkAnIaBOQ1RSBwR+EmiAG/jSgNEl7gKzmAAyzb2U1IxYHv5AhL5DRXiCr
JQwIOBxlDoQ/IShD0o4gqzUAyDRb14qIHI3VyBZktC3IaotDAg5J20HCnxKUJWlrkNUegGTvaXnt
iMpnPDFHRiGjjUJWJRQMOC6yD4Y/MSiF0rYhqxoJZjqCdJfO0VmEcirtIrJq8YjAAbJHIKJPETIV
GW0qsrZFIpqOqbbtMjo6r5DLyGiXkbX0BSD5g9TSYyDxJwklYdp3ZG11EnZLpdZc/mV3Sg3Zjoy2
HVlbnXrhSqk1l3ePbJQash4ZbT2yVpdDeDuegOoBvCVPAMq0tPfI2upMC9ZJrbkoe2CbFLmPjHYf
WevLAaAlytY9ggMrlMh6ZLT1yNrqtDpZJW0upB7bJEXGI6ONR9YWZ1O3SNrGGMrukSK/kdF+I2uL
E6e7xNLGcMleXUFGI6ONRta39YW7JdK+geLZHVLkNDLaaWQ9rQfgVkh7AgDYDVLkMTLaY2Q9rwcw
tr2eQf1ky0PmIqPNRdYXJ0CwPNPH9MevzSBXkdGuIuuLk59fHu1j8KN3R5GdyGg7kfXFuc+tjvYx
87Gbo8hFZLSLyPrivDdeUexj0CMvJiLbkNG2IeuLE567RtXHaMfem0JmIaPNQtZ1feHo0VBXVD//
LAjZhIy2CVm3CAz+4U83iIF+2oMMQkYbhEy2AAxg5smGMPCDD5mDjDYHmaQADK4lSEIQ2L6AfEFG
+4JMFuc+f4tSxtRH351EbiCj3UAmJaB01BOlQAJ8U0QeIKM9QCY1BITvilIxCL4tojRIO39MFqfB
2S6LjKHw4CILMvwYbfgx6SEYxogoHVMgkyKy+hht9TGREAh+OgimQM8HlBtpe4+JhmEALHSHBQ0E
JUja12NiIUDA3DQMgx6fyNpjtLXHdHGG3LvuomOO/IybLsjiY7TFxzRF4fBzVNMUBz1KkdfHaK+P
aQ7C4Yap5hkMdpwiv4/Rfh/TEoRiHKhaZiTIkYpMP0abfkxrEAg3SLTOSLBTBLl+jHb9mLZAFLCD
tl0iB9ooyp60+8e0h4IBvbTvg+EbKsqjtAHIVCLB+E+Q7GKhP0YondIOIFMNguLjmOoMCB/IUDKl
3T+mFgkDNhXbZ8J3FWQAMtoAZLbFovFtxbYLaOi+ggxARhuAzBbnVrQGamNePbAFiiw/Rlt+bIXl
54/mOVsDvVf6fGybh/ZAkb/HaH+PrfD3PCzfLYLeu3ruqmc3QZGXx2gvj63w8jwsHq2C3lt47uo/
sAuKnDtGO3dshXNnQOBbYfMA6OaH0ibt0rEVLp2H5U/WQe+FOncMju2DIquO0VYdW2HVASDAYRAM
gj8RKFHSXh1b4dXxIGbfyu4NOw9oHPxKhlw7Rrt2bIVrZ4YEHBDbQfK4U/K/v/0/7GfuWJ6eAQA=
T_EOF
echo "payload bytes: $(wc -c < "$ROOT/table.json")"
python3 - "$ROOT" <<'PY_EOF'

import json, os, re, shutil, subprocess, sys, time

ROOT = sys.argv[1]
T = json.load(open(os.path.join(ROOT, "table.json")))
LANG = T["language"]
PROBES = T["probes"]
OUT = T["out"]
out = open(OUT, "w")
WORK = os.path.join(ROOT, "u")

# --- verbatim delimiter codec, copied from verbatim_diag.py ---
def esc(text):
    """make `text` safe to place in one pipe-delimited field, reversibly."""
    for raw, rep in _ENC:
        text = text.replace(raw, rep)
    return text

_ENC = [('\\', '\\\\'), ('|', '\\p'), (';', '\\s'), ('\n', '\\n'), ('\r', '\\r')]
MARKER = '#verbatim-escape v1'
out.write(MARKER + '\n')


print("op lane %s: %d candidate probes" % (LANG, len(PROBES)))
sys.stdout.flush()


def sh(cmd, cwd=None, timeout=180):
    try:
        p = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE, timeout=timeout)
        so = p.stdout.decode("utf-8", "replace")
        se = p.stderr.decode("utf-8", "replace")
        return p.returncode, so, se
    except subprocess.TimeoutExpired:
        return 124, "", "TIMEOUT after %ds" % timeout
    except OSError as e:
        return 125, "", "OSError %s" % e


# ------------------------------------------------------ objdump reading

LABEL = re.compile(r"^([0-9a-f]+)\s+<(.+)>:\s*$")
INSN = re.compile(r"^\s*([0-9a-f]+):\t(.*)$")
RELOC = re.compile(r"^\s+([0-9a-f]+): (R_\S+)\t(.+?)\s*$")


def extract(text, sym, exact):
    """the two columns for one symbol.

    bytes  every byte objdump printed, in order, flattened
    mnem   the instruction text, with objdump's own trailing `# ...`
           comment dropped -- that comment is arithmetic objdump did
           for the reader, not part of the instruction.  A relocation
           is appended to the instruction it applies to as
           ` !!reloc=<type>:<symbol>`, because in an object file the
           call displacement is literally zero and the callee's name
           lives only in the relocation.
    """
    lines = text.splitlines()
    k = -1
    for idx, ln in enumerate(lines):
        m = LABEL.match(ln)
        if not m:
            continue
        lab = m.group(2)
        hit = (lab == sym) if exact else (sym in lab)
        if hit:
            k = idx
            break
    if k < 0:
        return None
    raw = []
    mn = []
    for ln in lines[k + 1:]:
        if LABEL.match(ln):
            break
        m = INSN.match(ln)
        if not m:
            r = RELOC.match(ln)
            if r and mn:
                mn[-1] = "%s !!reloc=%s:%s" % (mn[-1], r.group(2), r.group(3))
            continue
        parts = m.group(2).split("\t")
        bs = parts[0].split()
        raw.extend(bs)
        txt = parts[1] if len(parts) > 1 else ""
        txt = txt.split("#")[0]
        txt = " ".join(txt.split())
        if txt:
            mn.append(txt)
    return raw, mn


def disasm(obj, sym, exact):
    rc, so, se = sh(["objdump", "-dr", "--disassemble=" + sym, obj])
    got = extract(so, sym, exact) if rc == 0 else None
    if got is None:
        rc, so, se = sh(["objdump", "-dr", obj], timeout=600)
        got = extract(so, sym, exact)
    return got


# --------------------------------------------------------- DWARF reading
#
# objdump --dwarf=info prints one entry per line block:
#
#   <1><2d>: Abbrev Number: 2 (DW_TAG_subprogram)
#      <2e>   DW_AT_name        : op_12
#   <2><4a>: Abbrev Number: 3 (DW_TAG_formal_parameter)
#      <4b>   DW_AT_name        : a
#      <52>   DW_AT_location    : 2 byte block: 91 7c (DW_OP_fbreg: -4)
#
# The leading <N> is the tree depth.  A formal parameter one level
# below the matching subprogram is a parameter OF that subprogram.

DIE = re.compile(r"^\s*<(\d+)><[0-9a-f]+>:\s*Abbrev Number:\s*\d+\s*\((\S+)\)")
ATTR = re.compile(r"^\s*<[0-9a-f]+>\s+(DW_AT_\w+)\s*:\s*(.*?)\s*$")


def clean(text):
    text = " ".join(text.split())
    return text


STRPREFIX = re.compile(r"^\((?:indexed string|indirect string)[^)]*\):\s*")


def dwname(text):
    """objdump prints a string attribute as `(indexed string: 0x5): a`.
    The parenthesised part is objdump telling the reader WHERE in the
    string table it found the name; the name is what follows.  Keeping
    the prefix would have put objdump's bookkeeping into the parameter
    name column."""
    return STRPREFIX.sub("", text.strip())


def dwarf_params(text, sym):
    """[(name, location)] for the subprogram named `sym`.

    More than one subprogram can carry the name.  swift's `@_cdecl`
    emits a C-entry thunk beside the real function, and the thunk has
    no DW_TAG_formal_parameter children at all, so the first match is
    not always the one holding the parameter table.  Every match is
    collected and the first one that actually has parameters wins."""
    lines = text.splitlines()
    depth = None
    tag = None
    attrs = {}
    entries = []
    for ln in lines:
        m = DIE.match(ln)
        if m:
            if tag is not None:
                entries.append((depth, tag, attrs))
            depth = int(m.group(1))
            tag = m.group(2)
            attrs = {}
            continue
        a = ATTR.match(ln)
        if a and tag is not None:
            attrs[a.group(1)] = a.group(2)
    if tag is not None:
        entries.append((depth, tag, attrs))

    hits = []
    for idx, (d, t, at) in enumerate(entries):
        if t != "DW_TAG_subprogram":
            continue
        names = []
        if "DW_AT_name" in at:
            names.append(dwname(at["DW_AT_name"]))
        if "DW_AT_linkage_name" in at:
            names.append(dwname(at["DW_AT_linkage_name"]))
        for nm in names:
            if nm == sym or sym in nm:
                hits.append(idx)
                break
    if not hits:
        return None
    best = []
    for k in hits:
        base = entries[k][0]
        got = []
        for d, t, at in entries[k + 1:]:
            if d <= base:
                break
            if d != base + 1:
                continue
            if t != "DW_TAG_formal_parameter":
                continue
            nm = clean(dwname(at.get("DW_AT_name", "(unnamed)")))
            loc = clean(at.get("DW_AT_location", "(no location)"))
            got.append((nm, loc))
        if got:
            return got
        best = got
    return best


def dwarf(obj, sym):
    rc, so, se = sh(["objdump", "--dwarf=info", obj], timeout=600)
    if rc != 0:
        return None, "objdump --dwarf=info rc=%d" % rc
    got = dwarf_params(so, sym)
    if got is None:
        return None, "no DW_TAG_subprogram named %s" % sym
    if not got:
        return None, "subprogram %s has no DW_TAG_formal_parameter" % sym
    return got, None


# ------------------------------------------------------------ compiling

GOMOD = "module opprobe\n\ngo 1.26\n"

CLANG = "/usr/bin/clang"
CLANGXX = "/usr/bin/clang++"
SWIFTC = "/persist/swift/usr/bin/swiftc"


def compile_probe(p, d, mode):
    """(rc, artifact path, diagnostic text)."""
    if LANG == "c":
        src = os.path.join(d, "unit.c")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANG, "-std=c17"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "cpp":
        src = os.path.join(d, "unit.cpp")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANGXX, "-std=c++20"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "rust":
        src = os.path.join(d, "unit.rs")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        if mode == "anchor":
            opt = ["-C", "opt-level=0", "-g"]
        else:
            opt = ["-C", "opt-level=1", "-C", "debug-assertions=off"]
        cmd = (["rustc", "--crate-type=lib", "--emit=obj"] + opt
               + ["-o", obj, src])
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "go":
        open(os.path.join(d, "go.mod"), "w").write(GOMOD)
        open(os.path.join(d, "main.go"), "w").write(p["source"])
        obj = os.path.join(d, "bin_%s" % mode)
        cmd = ["go", "build"]
        if mode == "anchor":
            cmd.append("-gcflags=-N -l")
        cmd.extend(["-o", obj, "."])
        rc, so, se = sh(cmd, cwd=d, timeout=300)
        return rc, obj, (se or so)
    if LANG == "swift":
        src = os.path.join(d, "unit.swift")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-Onone", "-g"] if mode == "anchor" else ["-O"]
        cmd = [SWIFTC] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd, timeout=300)
        return rc, obj, (se or so)
    raise KeyError(LANG)


DIAG = re.compile(r"^[^\s:]+:\d+(:\d+)?:")


def firstline(txt):
    """the compiler's own words for why it refused.

    The first line is not reliably the reason.  clang leads with a
    warning and puts the error underneath.  go leads with a banner
    naming the package -- `# opprobe` -- and its diagnostics never
    contain the word `error` at all, so a rule that only looked for
    that word recorded the banner and threw the testimony away.
    Three passes, in order: a line saying `error`, a line in the
    `file:line:col:` diagnostic shape, then the first line that is
    not a banner."""
    lines = []
    for ln in txt.splitlines():
        s = ln.strip()
        if s:
            lines.append(s)
    for ln in lines:
        if re.search(r"\berror\b", ln, re.I):
            return ln[:200]
    for ln in lines:
        if DIAG.match(ln):
            return ln[:200]
    for ln in lines:
        if not ln.startswith("#"):
            return ln[:200]
    if lines:
        return lines[0][:200]
    return "(no diagnostic)"


def write_unit(n, build, obj, sym, exact):
    got = disasm(obj, sym, exact)
    if got is None:
        rc2, so2, se2 = sh(["objdump", "-t", obj])
        near = 0
        for l in so2.splitlines():
            if sym in l:
                near += 1
        out.write("op_%d|%s|NOSYM|%s\n"
                  % (n, build, esc("symbol %s absent, %d near matches"
                                   % (sym, near))))
        return False
    raw, mn = got
    out.write("op_%d|%s|OK|%s|%s\n"
              % (n, build, " ".join(esc(x) for x in raw),
                 ";".join(esc(x) for x in mn)))
    return True


t0 = time.time()
tally = {"REFUSED": 0, "ACCEPTED": 0, "ANCHOR_OK": 0, "SHIP_OK": 0,
         "DWARF": 0}

for k, p in enumerate(PROBES):
    n = p["n"]
    sym = p["symbol"]
    exact = p["symbol_exact"]
    d = os.path.join(WORK, "n%d" % n)
    shutil.rmtree(d, ignore_errors=True)
    os.makedirs(d)

    rc, obj, err = compile_probe(p, d, "ship")
    if rc != 0 or not os.path.exists(obj):
        out.write("op_%d|REFUSED|%s\n" % (n, esc(firstline(err))))
        tally["REFUSED"] += 1
        out.flush()
        shutil.rmtree(d, ignore_errors=True)
        continue
    tally["ACCEPTED"] += 1
    if write_unit(n, "SHIP", obj, sym, exact):
        tally["SHIP_OK"] += 1

    rc, aobj, aerr = compile_probe(p, d, "anchor")
    if rc != 0 or not os.path.exists(aobj):
        out.write("op_%d|ANCHOR|BUILDFAIL|%s\n" % (n, esc(firstline(aerr))))
    else:
        if write_unit(n, "ANCHOR", aobj, sym, exact):
            tally["ANCHOR_OK"] += 1
        rows, why = dwarf(aobj, sym)
        if rows is None:
            out.write("op_%d|ANCHOR|NODWARF|%s\n" % (n, esc(why)))
        else:
            joined = ";".join("%s=%s" % (esc(a), esc(b)) for a, b in rows)
            out.write("op_%d|ANCHOR|DWARF|%s\n" % (n, joined))
            tally["DWARF"] += 1
    out.flush()
    shutil.rmtree(d, ignore_errors=True)

    if (k + 1) % 25 == 0 or (k + 1) == len(PROBES):
        el = time.time() - t0
        print("[progress] %s [%d/%d] elapsed %.1fs mean %.2fs  "
              "REFUSED %d ACCEPTED %d SHIP_OK %d ANCHOR_OK %d DWARF %d"
              % (LANG, k + 1, len(PROBES), el, el / (k + 1),
                 tally["REFUSED"], tally["ACCEPTED"], tally["SHIP_OK"],
                 tally["ANCHOR_OK"], tally["DWARF"]))
        sys.stdout.flush()

out.close()
print("done: %s -> %s" % (json.dumps(tally), OUT))

PY_EOF
echo "--- lane finished, rc=$?"
date -u +%Y-%m-%dT%H:%M:%SZ
