#!/bin/sh
# op-pipeline lane -- c -- generated by
# Research/op_pipeline/lane_gen.py .  Do not hand-edit.
# steps 1b/2/3: compile-or-refuse, then the ANCHOR and SHIP
# builds of every probe the compiler accepted, then objdump
# extraction, then the anchor's DWARF parameter table.
set -u
export HOME=/work
export PATH=/persist/swift/usr/bin:$PATH
export GOTOOLCHAIN=local
export GOPROXY=off
export GOFLAGS=-mod=mod
ROOT=/work/regen_c_c0051
export GOCACHE="$ROOT/gocache"
export GOPATH="$ROOT/gopath"
# swift's binaries want libncurses.so.6 and the image ships
# only libncursesw.so.6.6; the symlink lives in the image's
# own /usr/lib and does NOT survive a container restart.
if [ -f /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 ]; then
  ln -sf /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 \
     /usr/lib/x86_64-linux-gnu/libncurses.so.6 2>/dev/null
  ldconfig 2>/dev/null
fi
echo "=== op pipeline -- c -- 400 candidate probes ==="
date -u +%Y-%m-%dT%H:%M:%SZ
# refuse in seconds rather than in an hour
if ! /usr/bin/clang --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: /usr/bin/clang is not runnable in this container."
  echo "!! tried: /usr/bin/clang --version"
  exit 4
fi
/usr/bin/clang --version 2>&1 | head -2
if ! objdump --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: objdump is not runnable."
  exit 4
fi
objdump --version 2>&1 | head -1
rm -rf "$ROOT"; mkdir -p "$ROOT" "$GOCACHE" "$GOPATH"
df -Pm /work | awk 'NR==2{print "free /work: " $4 " MB"}'
FREE=`df -Pm /work | awk 'NR==2{print $4}'`
if [ "$FREE" -lt 400 ]; then
  echo "!! REFUSING TO START: only $FREE MB free on /work, need 400"
  exit 3
fi
base64 -d <<'T_EOF' | gunzip > "$ROOT/table.json"
H4sIAAAAAAAC/8Wd3Y4cR3KFX2VAA4tdY3dV+RMRmbZhwL7wC/jSMgYkRf0A3CFBkfAuBL27ayj2
dFfFySZPsSO1FyuR02LpnM7O/LpUge+XZ6+fP/zw4fkPr579y92zl8/+fPfszYf3j3//zfrXb969
+uHVw/3L+5fLIumv7//+/vEFb9+9efHq5/U1//PLs4f1L3mpy7L+/s//+NuLN68f/9k3b+8//uaz
p9+9f/X35y8f/9z37z68evzdNx/evfx4zW/++e7jH/jbH3P3l7/cvfjp4fm7f9z94Q93//zNtw//
9NPDy9cfvnt1928/v//up4f3f/3x33e/+eLNm9cff/fbh/v79/94++rN9/f3f/zj96/fPH//p1+W
Xx//pD/e/8fLlx/+9vjLP337cPr3++01d8//fPfbj+9erD/85duHu/V/7169//Du4e754z/94l+/
ffj124dnv/757hw5ociJjpziIv/n+qpt4nSR+PGnVOCMAmc6cI4L/F+Pv0y6zZwvMn96ARW7oNiF
jl0CY79b/wW2octl6McfU5ErilzpyDUu8n+v2dBHul7kPr+GCi8ovNDhJTg8eNNlH55/5xWFVzq8
xoZ//ebhB/j2666BixdSNRiqwegabEYNYCEYrIFfDQ3V0OgaWmwNP//45h3eDdquh8tXUkV0VESn
i+hTigALouMi6BWREOclmvPSElvEh4eff/rh4dV3aFGkZdfF7sVUHYgBE82AKc2qwy+NlIZ18KsD
EWKiCTHlSXWMjpGUR50cPE8SYshEM2QqU4sBi6VcL4ZfMYg0E02aqU4qZnjUpDpq5uiZkxCHJppD
k8ytBiwa+Uw1/KpBlJpoSk2BlHr/4vvd99B0yaYff0xFRkSaaCJNgUR6//HXKbdt7EsWfXoJFR1R
aKIpNLXI6G/373bbxH5LvtuINxPNmymQN+9/evE3915fYuanFzCxM6LLTNNlXiJjPzyu3/vtFpeX
TfBPL6GiI5LMNEnmQJK8/4CzXwLk+TVUeMSNmebGHMeNL/Z3UvMFIr4gb6RmRIOZpsEcR4Mvf3z+
bhv3Avwef0jFRYyXacbLNTRu0v26rtvIjy+gYiN+yzS/ZQmNXfI+tmxjP76Aio3YLNNsljU0ttvE
dJua3cAQnWWaznIcnX335sOL16+2mS/I7LcfU5ERlWWaynIclT396pz4Asp++xsmMGKyTDNZjmOy
H5+//n6b94LHHn/IxC2IxQrNYiWOxdZ/cpO2XEDY+jMqLKKvQtNXiaOvx/sr27QX2PXx5gsTF/FW
oXmr5NC46DZLybvU/H2Vguir0PRVSnB4fyOllH14+s5JQSxWaBYrNTY8OK1K3YXnj6yCiKzQRFYk
Nrz/qMsuOv15R0xWaCYrcUz28U7gNvQFkf12n5AJjHis0DxWLDYw3OFsn/vAFofYrNBsVlp0fLDH
NRef3+QQqRWa1EocqX26/+2+ZpcLYLt4DRO+Im6rNLfVJTr8Ht/q4rKTFFcRxVWa4mqKju52+Jpc
dnaPr4jpKs10Nc8IDxrIuAG6BkR3laa7WqJr8CdeLa4C+uCriO8qzXc1ju+uPZpRLxjvK57KqIjz
Ks15VSaU4E/AKqgE+hCsiPkqzXxV40twx2BVUAF9ECIGrDQDVosvwB2FBvKzhyFiwEozYG3x8f1h
0EB++iRAFFhpCqx9TgFwP+yjHvhNURAXCs2Fssyqw++MsgzroLdHQawoNCtKmlSH+4xIGpXBflAE
kaPQ5Cg5vgoPTZJBDTQ2CaJGoalRyqQK0GYhZdjEgd0CcaTQHCl1WiFgu6jjQvj9AjGl0EwpcUz5
f4+AtPvPmnLBkp9+ToVGDCk0Q8otGfL0H7lGQ32iH19ybKZPEDMKzYxiYYHdSJ/YOS870SeIEYVm
RGlhcdFAn7Rz4gPzfIK4UGgulB4X2m9l/SIyu3UpIj+lyU+XsMCDYT5dzqmPzfIpojylKU9TbHT/
hmvaReffdUR1SlOd5tDoo28+mrf5D37pUcR1SnOdlgklgEVQUAn8SkAspzTLaQ0tYci1WrctHEVa
RQSnNMGpzKgBLAaBNfCrATGd0kynGlrDtbvEqtsmvuJOsSLeU5r31CaVAZaFjcrgVwaiQaVpUNuc
MoZHRxs0cvQMQbyoNC9qn1kLWCj9ai30ajFElUZTpS1zahkeL7YMejl6zhhiTqOZ09LUYvyCsXS9
GH7FICI1mkgtjkj90J5dcCg9s2eIPo2mT4ujTzyyZxfceWhizxBxGk2cVgOD7wf2rF6GJuf1DLGl
0WxpcWyJxvXsAikPTOsZIkmjSdI0MDQaWDO9jH1gXM0QNRpNjRZHjYNRPbuAxWOTeoYY0WhGtDBG
dIN6dsZBdk7PEPkZTX4WRn7uwQk7Qx77uERDPNdonmtLZFg3pNeWTWB2Rq8hVms0q7UUGdqN6LW0
Cc1O6DXEYY3msJYjQ++3rpY3mcltqyESazSJtTASAwMP7Uxh/KhDQwTWaAJrYQTmh/PaGcDo2byG
+KvR/NXC+MuN5rUze7GTeQ1xV6O5q4Vx1/5xtnYGLvIhtoZIq9Gk1cJIyz2W086IxT6H0xBbNZqt
WosMi26htLbNzN8zaYi0Gk1arcdG9zdJWt9Fp++KdMRdneauvoRGB+dTX7bR+UOqI/rqNH31FBrd
fcR72gZnP+cd8Ven+auH8Zd/yq6f6Yt+tq4j9uo0e/USGhfta73sUvMbW0cc1mkO6zU4vN/Zet2H
57c2RGWdprIeRmWj+YN+hrODwwcdMVqnGa1rcPQ9qnXdJyeJrSNi6zSxdQsO7nd12yen93XEb53m
t94mRAf5G8xPl4BIrtMk13twCeCM6/sC2KNOkAVDaAuGLGEsd+WxivWqT/mPP1EhyIohtBVDlhRf
gTvz1quCCthjT5AnQ2hPhiw5vIL9wbde0xdAHn2CfBlC+zJkKeHxd4ffekmfnjv+BJkzhDZnyFLD
w+8PgPWaPj25+wtyZwjtzpBFpsSHu6AMWjiwFSoqQ+kydFIZYD/UURn8pmioDKPLsDll+E+HDaqg
PyINFdHoIlp4EQ6R1ov6EnhI6qiAThfQ5xQAN4k+6oHfJZBRQ2ijhqRlVh1+m0jLsA56n0BGDaGN
GpLC+BGM2a1XeyqAn7ITZM0Q2pohN7VmfEKjwZDdeq3HVxyasRPkwhDahSE3dWFs4u5H7NZLPaUl
J+wE+S2E9lvITf0Wm7BgwG692lNefr5OkLdCaG+F3NRbsY3sNzA5B6Y3LER5tItCbuqi2MTFw3Xr
BZ8yH5qtE2SkENpIITc1Uvjg4M22bXD+HUcER/so5KY+Chd89P0mtU36g19tkJ9CaD+F3NRPMagA
LIAOKqBXAXJVCO2qkJu6KlwFQ4LNy6aDo/CKrBVCWyvkptaKUQl+IeSESuBXAuI32l4hOUeWcO3O
b86bHr7i7i8yWwhttpBc5lQBlkQZVMGvCkR+tPVCcp1Sxei4yBX3cfDcQE4MoZ0YkmViKWCRyLVS
+JWCCJI2ZkjWKaWMjxTFrRw+WxBf0k4NyTazFrBY7Got/GpB9El7NySH0acboluv9VQBO0MnyLoh
tHVDchhpwhG69XrnyAcm6ATZN4S2b0hZ4mLvBujWa11E5ubnBPk3hPZvSAnjSDA+t17tHJienhPk
4BDawSElx0UGI2Tr9S5C8wNkguwbQts3pIQRIh6dWy94zv3hUHDEg7R5Q0oUD+4H59YrnRKTc3OC
PBtCezakRFGee+yhPAEd+7ADMmsIbdaQooFR90Nz69Uu45Izc4LcGkK7NaRYYOT9yNx6tcvI5MSc
IJ+G0D4NKS0wstuw2mVidrNC1EUbNKREUZcfR1ivdcpLDyIIcmYI7cyQGkVbblhuvdQpLTsrJ8iS
IbQlQ2oUa+1H5dYrnbKSk3KCnBhCOzGkRjHW/gG0+gRX5GNnyHohtPVCahRVucdp6hNOsc/PIMOF
0IYLqTUwKro9UusmMX8/BFkthLZaSJXQ4P4GSJVtcPqOBzJZCG2ykKqRwcGJVHUT/MCxhEiLNlhI
tcjg/qNtm9j05xuxFu2tkBrFWv6puPpEWvSzcMhRIbSjQmqPDAt3s77NzG9nyEchtI9CZImN7vcz
WXbR6Q0NuSeEdk+IRBHYaDpAnkDs4GgAMk0IbZoQybHB91gmeZebpDNklxDaLiFSYmO7nVzKLje7
lyOLhNAWCZEaHxykryg9XQGiNtobISKxFfhTTWQXnz7ckD1CaHuESBS3XXskQp7Y7SuehkA2CaFt
EiIWXgA45cwXwB90iOVov4RIiy7AH3XNxacPO8R2tGdCpEeHd8ddd9nJAw8ZJ4Q2Togu0dHdpq+L
y87u+Mg5IbRzQjTNCI/2Pk24A34DRA4KoR0UonlOFX4X1Dyogt4KkYlCaBOFaJlShf9cFFwE/eFA
REi7KERrdA0eiLS6CmgkQg4KoR0UojIlPtwcZNDCgd0B8SFtohDVSWWA7UFHZfD7A2JF2kQhGsWK
aOxNnxjxwNQbsk0IbZuQm9omTtveaOxN22/3PA/NvSGPhNAeCbmpR2Ib2A2+aT/nZSffkB9CaD+E
3NQPsY2LRt9sOSc+MPuG3A9Cux/kpu6HXWi3iVm6iMxuW8jpILTTQW7qdNgGHoy/WT6nPjb/huwO
Qtsd5KZ2BxAdvOFlF51/1xHF0X4HuanfwUcffb+xus1/8MsNcj4I7XyQmzofRiWARSCoBH4lIIaj
HRByUweEL2FIs6bbFo6iLDJCCG2EkJsaIYY1gMVgsAZ+NSCmo+0QYi20hmv3fa1tm/iKu7/IHiG0
PUKsTyoDLIs+KoNeGcguIbRdQtoyp4zR0dGWQSMHzxDknxDaPyEtzazFL5SWrtbCrxZElbShQlqe
U8vweGl50MvRcwZ5LIT2WEgrU4sBC6ZcL4ZfMYhIad+FtDgi9WNx7YJD6bk4ZLwQ2nghLY4+8WBc
u+DOQ5NxyH4htP1CmgYG34/GNb0MTc7GIQeG0A4MaXFsiYbj2gVSHpiOQy4MoV0Y0lpgaDQm1tpl
7ANjYsiEIbQJQ1ocNQ4G5NoFLB6bkEMmDKFNGNLDGNGNyPUzDrIzcsh9IbT7QnoY+blHIvoZ8thH
IZDxQmjjhfQcGdaNyfW8CczOySHvhdDeC+klMrQblOtlE5qdlEO+C6F9F9JrZOj91tXrJjO7bSES
oy0X0sNIDIwm9DOF8WMJyG0htNtCehiB+XG5fgYwel4OGS2ENlpID+MvNzDXz+zFTswhh4XQDgvp
Ydy1f1itn4GLfEgNmSqENlVIDyMt9xBOPyMW+dyNIjOF0mYKXZbIsOAWynrFbWb6nokiI4XSRgpd
Umx0d5NkveIuOntXRJGJQmkThS45NLo/n9YrbqPTh5QiC4XSFgpdSmj0/Ud8vd42OP05ryh2pWOH
8Zd7rm691lNk9nk6Rb4JpX0TukhoXLivyS71gY1NUXilw2tweLCz6T48v7UZCm90+DAqG0wWrFc8
Zz80WKDIIKG0QUKXFhx9h2rrBffJOWJTZI5Q2hyhSw8O7nf1vk/O7uvIEqG0JULTMiG6z58WmJ8u
AZEc7YbQlIJL8GdcSvsC6KMOWSKUtkRoCmO5K49VrFd9yn/8iQpF5gilzRGaSnwF/sxLBVRAH3vI
J6G0T0JTDa/AHXyp+gLYow+5JZR2S2iS8Pj7wy+JT08ef8g0obRpQpOGh/cHgPr09O6PiI/2TWiy
KfHhLmiDFg5shYgBaQeFpjapDLAftlEZ/KaIuJC2UWjqc8rwn44+qIL9iCAnhdJOCs1LeBEekfLi
S6AhCfkolPZRaE5zCkCbRE6jHvhdApkplDZTaM6z6vDbRM7DOuh9AtkplLZTaA7jRzBkt17tqQB+
yk6RhUJpC4XmW/PixcofDNut17x85aGZO0W+CaV9E5olOv5+9G69pEtPTuAp8koo7ZXQrNHhwSDe
elWXn5/HU+SQUNohodnCK/Abn/kC6A0PUSLtitDcouPjIb31wq6DQ7N6iiwSSlskNPcpRYDF0HER
9IpAXgmlvRJalhlFjL5HlQW2cfCrFHJPKO2e0JLmVeIXSElXKuFXCeJG2k2hJc+oZEjSJcNOjsI0
Mlcoba7QUiaWAhZKuVYKv1IQX9JWCy11RinX7lCXCnv5irvVyIKhtAVDi8ytBiwZ+Uw1/KpBZEpb
M7To1GqGx5Fe7+fouYTYlfZsaLHfoSSwiOxLSuJXEiJc2syhpU0taXxktestHT67EP/SPg8t/feo
CSym/kU10asJeUCU9oBoDadjN0y4XtNVws4UKjKDKG0G0RpOwnC0cL2ur+DAhKEia4jS1hCtOb6G
t/tVkEEFb8lVgDiXdoloDedcMHa4XtUXQE8fKnKMKO0Y0VrjKwCjeOt1QQn8QJ4i44jSxhGt4QSL
RxLXC/sePhwqAvEqbSDRGs2r+wHF9Yr7Bsg5RUUOEqUdJFqjKdQ9blIdcLIPmyATidImEq1tQvT9
8OJ6VRSfnGFU5CdR2k+itU+oYD/KuF4VVUBONCrylCjtKVFZJlSw3wBlQQ2Qmx+ylShtK1GJpkIw
RiKOCPlBEuQsUdpZohJNg27ocb3kPj07+6jIXKK0uUQlmgX3I5DrFffZyUlIRe4Spd0lKtEMuH/Q
UBz8kY8ZImOJ0sYSlWjqc49RicM99vkpZCxR2liiohOio9tHorAB/n4RMpcobS5RsSlF+BtEYrgI
+o4QMpgobTBRaTOKQCdgg0UcOAYRCdI2E5U+owi/NXRYA7s/IK+J0l4T1WgW9E9XqiNB+tlK5DVR
2muimmaER7ujJtwBvz0ir4nSXhPVPKcKvz9qHlRBb5DIa6K010Q1mhBHUynqQPHgaAoymyhtNlGt
c4rYY6PWQQ8kPSLDidKGE1WZU4M7KVQGPdBnBWJJ2m6iqvOKAG3otTboShBV0o4TVZtTCThFbVAH
f5girqTtJ6rRXHntkRl1bPkVT8sgO4rSdhTVPq0QcKr2cSH0wYr8KUr7U9SWWYW4o9WWYR3s4Yq8
Kkp7VdTSrDL2x6ulYRfkAYuMK0obV9TyrCrcoWJ52AV7oiAHi9IOFrUyswy0l1q53gm/oSJHi9KO
FrU6txq/q1r9TDX81ooYlTa3qMnUavznSK4XQ3+YELHSLhc1nVWLBzTTYSU0oiGni9JOFzWbWgfc
XOwzrRzYXRC/0qYXtTa5HLC9tM+Vw+8viGVp84taNMuicVNzDHtg6hTZXpS2vWi7Pbs+vf+jqdOT
4eXTu35o6hRZXZS2umhL0fHd1OlJ5HKRnp06Re4Wpd0t2nJ0eDR1ehK2XOQ/MHWKLC1KW1q0lfAK
3G54ErNcFsBuf8jForSLRVuNjj+YOj15WS46ODZ1ihwtSjtatMmUIsBiEFwEvyIQWdLOFm06o4jR
V7STxGXXxsGvZ8jqorTVRZvNqwQsELtSCb9KEFPSzhdtbUYlQ9g+GWB2nRwFbeSDUdoHo61PLAUs
lH6tFHqlIFOM0qYY7cuMUq7dQu8L7OUr7qMjr4zSXhntaW41fsn09Jlq+FWDyJS20GjPU6sZHUc9
X+/n4LmErDVKW2u0l9+hJLCIypeUxK8kRLi05UZ7nVrS8Mjq9XpLR88uZMZR2oyjXX6PmsBiki+q
iV9NiI5pn472cDr2U6fdMzE9dYr8Okr7dbSHkzCeOu2egQ9NnSLzjtLmHe0tvob91GlvoAJy6hTZ
eJS28WgP51w0ddo93vJTp4YcPUY7emxZ4isA05a2LKAEftjSkK/HaF+PLeEEi6dObfHgemjq1JC9
x2h7jy3RvLqfOrXFoSk5dWrI3mO0vceWaArdP/NiiwNO8lEXQwYfow0+ttQJ0fdTp7ZUFJ+cOjVk
9THa6mOLTKhgP3Vqi6AKyKlTQ24fo90+tuiECtwGqKgBdvMzVIDRBURToZ+5scURIT1uY8jxY7Tj
x5ZoGnRTp7Y4GGSnTg15foz2/NgSzYL7qVNbHAeSU6eGPD9Ge34sRTPg7vlGSw7+uMcaDbl9jHb7
WIqmvv1TWJYc7pHPXRky+xht9rGUJ0QHt48sZdgAfb/IkN/HaL+PpTKlCHeDyFLBRbB3hAxZfoy2
/FiqM4oAJ2CqsAj+GES+H6N9P5ZkRhF+axBYA70/IBakvT+WolnQPY5pyZEg+xSmIeuP0dYfSzYj
PNwdDXdwYHtETEg7fyy1OVWA/bENquA3SESItPHHUjQhDkZjLDlQPDYYY8j4Y7Txx/Iyp4g9NuZl
0ANJj8j7Y7T3x3KaU4M7KXIa9MCeFcj4Y7Txx3KeVwRoI19rg64EUSVt/bFc5lTiT9FcBnXQhymy
ARltA7IczZVXHpmx7Njy+NMyhvxARvuBLMu0QvypmmVcCH2wImeQ0c4gyzqrEHe0Zh3WQR+uiD1p
e5Blm1WGO15t2AV7wCL2pE1CltusKvyh0oZd0CcKok/aJmS5zywD7qX9eif8hor8Qkb7hawsc6vx
u2pZPlMNvbUiz5DRniEraWo17nNU0vVi2A8Tcg0Z7RqykmfV4gGt5GElNKIhy5DRliErZWodaHMp
5TOtHNhdEL/StiErdXI5YHupnyuH318Qy9K+ISvRLAumTq04huWnTg1ZhYy2CtntrULnO+SDqVM7
KYQ+3SE/MnVqyBdktC/Ibu8L2sffT53ayQ10kZ6cOjXkATLaA2S39wDtw4OpUztZfy7y81Onhhw/
Rjt+7PaOH1eB3w27L4Dd/pC7x2h3j93e3bOPj6dO7STwuejg0NSpIYuP0RYfu73FBxbhF8NJ47Mv
gl8RiCxpj4/d3uODihh9RTsZfXZtHPx6htw+Rrt97PZun3ElYIGUK5XwqwQxJe36sdu7flAlQ9g+
KX92nRwFbWT+Mdr8Y7c3/1wpBSwUuVYKv1IQX9IWIKs6o5Rrt9Crwl6+4j46sgQZbQmyanOrAUvG
PlMNv2oQmdIWIattajXD46hd7+fouYTYlfYMWe2/Q0lgEfUvKYleSchEZLSJyGSZWtLwyJLlektH
zy7kKzLaV2SSfo+a/GKS9EU18asJ0THtNTIJp2M3dWrimZidOjVkNjLabGQSTsJw6tTEM/CRqVND
liOjLUcmNb6Gt/tVUEEFb8lVgDiXdh2ZhHMumDo18Xh7YOoUOY+Mdh6ZaHwFaNpSFJRwYNgSGY+M
Nh6ZhBPsYOpUPLgemzpFxiOjjUcm0bzqpk7FoSk7dYocR0Y7jkyiKdQ98yIOONlHXZDZyGizkeky
IbqbOtUFxWenTpHfyGi/kWmaUIGbOtWEKmCnTpHXyGivkWmeUMF+A9SMGiA3P2QzMtpmZBpNhWDm
Rh0R8uM2yGFktMPINJoG/dSpOhikp06Ruchoc5FpNAu6qVN1HMhOnSJXkdGuItNoBtw/36gO/sjH
GpGRyGgjkWk09bmnsNThHvvcFTIQGW0gMm0ToqPbR9pgA/z9ImQeMto8ZNqnFOFvEGnHRdB3hJBx
yGjjkNkyowhwAtoCi+CPQWQbMto2ZJZmFOG2BkuwBnZ/QJ4hoz1DZtEs6B/HNEeC9FOYyCtktFfI
rMwIj3ZHK7gDfntEHiGjPUJmdU4Vfn+0OqiC3yARIdLeILNoQhyNxpgDxYODMcgUZLQpyEznFLHH
RtNBDyQ9IkOQ0YYgM5tTgz8pbNADfVYglqRtQGZtXhGgjXatDboSRJW0A8isz6kEnKJ9UAd9mCIb
kNE2IGvRXHntkZnm2PIrnpZBfiCj/UDW0rRC/Kna0rgQ+mBFziCjnUHW8qxC3NHa8rAO9nBF9iCj
7UHWyqwy9sdrK8MuyAMWmYSMNglZq7OqcIdKq8Mu2BMF2YSMtglZk5llwL1UrndyYENFPEr7hazp
3GrArqqfqYbfWhGj0p4haza1Gv85suvF0B8mRKy0a8ham1WLB7TWhpXwiIZolbYMWetT64CbS/9M
K/zugmxDRtuGrC+Ty/HbS18+Vw69vyDfkNG+IevRLIumTrtj2ANTp8gqZLRVyG5vFTrtoaOZ05NA
6OP/HZo4Ra4go11BdntX0Da6mzc9WYGekrPTpsj/Y7T/x27v/9kGR7OmJ9fPU/YDk6bI62O018du
7/XZxff7n+zD09sdIk3a1WO3d/Vsow9mTE+6nqf8xyZMkbHHaGOP3d7YA0oAi8BQCfxKQARJ+3rs
9r4eX8Loi9jJ27Np4uBXMOTvMdrfY7f394zqAAujD+v4stXxv7/+P7eFXztOlQEA
T_EOF
echo "payload bytes: $(wc -c < "$ROOT/table.json")"
python3 - "$ROOT" <<'PY_EOF'

import json, os, re, shutil, subprocess, sys, time

ROOT = sys.argv[1]
T = json.load(open(os.path.join(ROOT, "table.json")))
LANG = T["language"]
PROBES = T["probes"]
OUT = T["out"]
out = open(OUT, "w")
WORK = os.path.join(ROOT, "u")

# --- verbatim delimiter codec, copied from verbatim_diag.py ---
def esc(text):
    """make `text` safe to place in one pipe-delimited field, reversibly."""
    for raw, rep in _ENC:
        text = text.replace(raw, rep)
    return text

_ENC = [('\\', '\\\\'), ('|', '\\p'), (';', '\\s'), ('\n', '\\n'), ('\r', '\\r')]
MARKER = '#verbatim-escape v1'
out.write(MARKER + '\n')


print("op lane %s: %d candidate probes" % (LANG, len(PROBES)))
sys.stdout.flush()


def sh(cmd, cwd=None, timeout=180):
    try:
        p = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE, timeout=timeout)
        so = p.stdout.decode("utf-8", "replace")
        se = p.stderr.decode("utf-8", "replace")
        return p.returncode, so, se
    except subprocess.TimeoutExpired:
        return 124, "", "TIMEOUT after %ds" % timeout
    except OSError as e:
        return 125, "", "OSError %s" % e


# ------------------------------------------------------ objdump reading

LABEL = re.compile(r"^([0-9a-f]+)\s+<(.+)>:\s*$")
INSN = re.compile(r"^\s*([0-9a-f]+):\t(.*)$")
RELOC = re.compile(r"^\s+([0-9a-f]+): (R_\S+)\t(.+?)\s*$")


def extract(text, sym, exact):
    """the two columns for one symbol.

    bytes  every byte objdump printed, in order, flattened
    mnem   the instruction text, with objdump's own trailing `# ...`
           comment dropped -- that comment is arithmetic objdump did
           for the reader, not part of the instruction.  A relocation
           is appended to the instruction it applies to as
           ` !!reloc=<type>:<symbol>`, because in an object file the
           call displacement is literally zero and the callee's name
           lives only in the relocation.
    """
    lines = text.splitlines()
    k = -1
    for idx, ln in enumerate(lines):
        m = LABEL.match(ln)
        if not m:
            continue
        lab = m.group(2)
        hit = (lab == sym) if exact else (sym in lab)
        if hit:
            k = idx
            break
    if k < 0:
        return None
    raw = []
    mn = []
    for ln in lines[k + 1:]:
        if LABEL.match(ln):
            break
        m = INSN.match(ln)
        if not m:
            r = RELOC.match(ln)
            if r and mn:
                mn[-1] = "%s !!reloc=%s:%s" % (mn[-1], r.group(2), r.group(3))
            continue
        parts = m.group(2).split("\t")
        bs = parts[0].split()
        raw.extend(bs)
        txt = parts[1] if len(parts) > 1 else ""
        txt = txt.split("#")[0]
        txt = " ".join(txt.split())
        if txt:
            mn.append(txt)
    return raw, mn


def disasm(obj, sym, exact):
    rc, so, se = sh(["objdump", "-dr", "--disassemble=" + sym, obj])
    got = extract(so, sym, exact) if rc == 0 else None
    if got is None:
        rc, so, se = sh(["objdump", "-dr", obj], timeout=600)
        got = extract(so, sym, exact)
    return got


# --------------------------------------------------------- DWARF reading
#
# objdump --dwarf=info prints one entry per line block:
#
#   <1><2d>: Abbrev Number: 2 (DW_TAG_subprogram)
#      <2e>   DW_AT_name        : op_12
#   <2><4a>: Abbrev Number: 3 (DW_TAG_formal_parameter)
#      <4b>   DW_AT_name        : a
#      <52>   DW_AT_location    : 2 byte block: 91 7c (DW_OP_fbreg: -4)
#
# The leading <N> is the tree depth.  A formal parameter one level
# below the matching subprogram is a parameter OF that subprogram.

DIE = re.compile(r"^\s*<(\d+)><[0-9a-f]+>:\s*Abbrev Number:\s*\d+\s*\((\S+)\)")
ATTR = re.compile(r"^\s*<[0-9a-f]+>\s+(DW_AT_\w+)\s*:\s*(.*?)\s*$")


def clean(text):
    text = " ".join(text.split())
    return text


STRPREFIX = re.compile(r"^\((?:indexed string|indirect string)[^)]*\):\s*")


def dwname(text):
    """objdump prints a string attribute as `(indexed string: 0x5): a`.
    The parenthesised part is objdump telling the reader WHERE in the
    string table it found the name; the name is what follows.  Keeping
    the prefix would have put objdump's bookkeeping into the parameter
    name column."""
    return STRPREFIX.sub("", text.strip())


def dwarf_params(text, sym):
    """[(name, location)] for the subprogram named `sym`.

    More than one subprogram can carry the name.  swift's `@_cdecl`
    emits a C-entry thunk beside the real function, and the thunk has
    no DW_TAG_formal_parameter children at all, so the first match is
    not always the one holding the parameter table.  Every match is
    collected and the first one that actually has parameters wins."""
    lines = text.splitlines()
    depth = None
    tag = None
    attrs = {}
    entries = []
    for ln in lines:
        m = DIE.match(ln)
        if m:
            if tag is not None:
                entries.append((depth, tag, attrs))
            depth = int(m.group(1))
            tag = m.group(2)
            attrs = {}
            continue
        a = ATTR.match(ln)
        if a and tag is not None:
            attrs[a.group(1)] = a.group(2)
    if tag is not None:
        entries.append((depth, tag, attrs))

    hits = []
    for idx, (d, t, at) in enumerate(entries):
        if t != "DW_TAG_subprogram":
            continue
        names = []
        if "DW_AT_name" in at:
            names.append(dwname(at["DW_AT_name"]))
        if "DW_AT_linkage_name" in at:
            names.append(dwname(at["DW_AT_linkage_name"]))
        for nm in names:
            if nm == sym or sym in nm:
                hits.append(idx)
                break
    if not hits:
        return None
    best = []
    for k in hits:
        base = entries[k][0]
        got = []
        for d, t, at in entries[k + 1:]:
            if d <= base:
                break
            if d != base + 1:
                continue
            if t != "DW_TAG_formal_parameter":
                continue
            nm = clean(dwname(at.get("DW_AT_name", "(unnamed)")))
            loc = clean(at.get("DW_AT_location", "(no location)"))
            got.append((nm, loc))
        if got:
            return got
        best = got
    return best


def dwarf(obj, sym):
    rc, so, se = sh(["objdump", "--dwarf=info", obj], timeout=600)
    if rc != 0:
        return None, "objdump --dwarf=info rc=%d" % rc
    got = dwarf_params(so, sym)
    if got is None:
        return None, "no DW_TAG_subprogram named %s" % sym
    if not got:
        return None, "subprogram %s has no DW_TAG_formal_parameter" % sym
    return got, None


# ------------------------------------------------------------ compiling

GOMOD = "module opprobe\n\ngo 1.26\n"

CLANG = "/usr/bin/clang"
CLANGXX = "/usr/bin/clang++"
SWIFTC = "/persist/swift/usr/bin/swiftc"


def compile_probe(p, d, mode):
    """(rc, artifact path, diagnostic text)."""
    if LANG == "c":
        src = os.path.join(d, "unit.c")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANG, "-std=c17"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "cpp":
        src = os.path.join(d, "unit.cpp")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANGXX, "-std=c++20"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "rust":
        src = os.path.join(d, "unit.rs")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        if mode == "anchor":
            opt = ["-C", "opt-level=0", "-g"]
        else:
            opt = ["-C", "opt-level=1", "-C", "debug-assertions=off"]
        cmd = (["rustc", "--crate-type=lib", "--emit=obj"] + opt
               + ["-o", obj, src])
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "go":
        open(os.path.join(d, "go.mod"), "w").write(GOMOD)
        open(os.path.join(d, "main.go"), "w").write(p["source"])
        obj = os.path.join(d, "bin_%s" % mode)
        cmd = ["go", "build"]
        if mode == "anchor":
            cmd.append("-gcflags=-N -l")
        cmd.extend(["-o", obj, "."])
        rc, so, se = sh(cmd, cwd=d, timeout=300)
        return rc, obj, (se or so)
    if LANG == "swift":
        src = os.path.join(d, "unit.swift")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-Onone", "-g"] if mode == "anchor" else ["-O"]
        cmd = [SWIFTC] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd, timeout=300)
        return rc, obj, (se or so)
    raise KeyError(LANG)


DIAG = re.compile(r"^[^\s:]+:\d+(:\d+)?:")


def firstline(txt):
    """the compiler's own words for why it refused.

    The first line is not reliably the reason.  clang leads with a
    warning and puts the error underneath.  go leads with a banner
    naming the package -- `# opprobe` -- and its diagnostics never
    contain the word `error` at all, so a rule that only looked for
    that word recorded the banner and threw the testimony away.
    Three passes, in order: a line saying `error`, a line in the
    `file:line:col:` diagnostic shape, then the first line that is
    not a banner."""
    lines = []
    for ln in txt.splitlines():
        s = ln.strip()
        if s:
            lines.append(s)
    for ln in lines:
        if re.search(r"\berror\b", ln, re.I):
            return ln[:200]
    for ln in lines:
        if DIAG.match(ln):
            return ln[:200]
    for ln in lines:
        if not ln.startswith("#"):
            return ln[:200]
    if lines:
        return lines[0][:200]
    return "(no diagnostic)"


def write_unit(n, build, obj, sym, exact):
    got = disasm(obj, sym, exact)
    if got is None:
        rc2, so2, se2 = sh(["objdump", "-t", obj])
        near = 0
        for l in so2.splitlines():
            if sym in l:
                near += 1
        out.write("op_%d|%s|NOSYM|%s\n"
                  % (n, build, esc("symbol %s absent, %d near matches"
                                   % (sym, near))))
        return False
    raw, mn = got
    out.write("op_%d|%s|OK|%s|%s\n"
              % (n, build, " ".join(esc(x) for x in raw),
                 ";".join(esc(x) for x in mn)))
    return True


t0 = time.time()
tally = {"REFUSED": 0, "ACCEPTED": 0, "ANCHOR_OK": 0, "SHIP_OK": 0,
         "DWARF": 0}

for k, p in enumerate(PROBES):
    n = p["n"]
    sym = p["symbol"]
    exact = p["symbol_exact"]
    d = os.path.join(WORK, "n%d" % n)
    shutil.rmtree(d, ignore_errors=True)
    os.makedirs(d)

    rc, obj, err = compile_probe(p, d, "ship")
    if rc != 0 or not os.path.exists(obj):
        out.write("op_%d|REFUSED|%s\n" % (n, esc(firstline(err))))
        tally["REFUSED"] += 1
        out.flush()
        shutil.rmtree(d, ignore_errors=True)
        continue
    tally["ACCEPTED"] += 1
    if write_unit(n, "SHIP", obj, sym, exact):
        tally["SHIP_OK"] += 1

    rc, aobj, aerr = compile_probe(p, d, "anchor")
    if rc != 0 or not os.path.exists(aobj):
        out.write("op_%d|ANCHOR|BUILDFAIL|%s\n" % (n, esc(firstline(aerr))))
    else:
        if write_unit(n, "ANCHOR", aobj, sym, exact):
            tally["ANCHOR_OK"] += 1
        rows, why = dwarf(aobj, sym)
        if rows is None:
            out.write("op_%d|ANCHOR|NODWARF|%s\n" % (n, esc(why)))
        else:
            joined = ";".join("%s=%s" % (esc(a), esc(b)) for a, b in rows)
            out.write("op_%d|ANCHOR|DWARF|%s\n" % (n, joined))
            tally["DWARF"] += 1
    out.flush()
    shutil.rmtree(d, ignore_errors=True)

    if (k + 1) % 25 == 0 or (k + 1) == len(PROBES):
        el = time.time() - t0
        print("[progress] %s [%d/%d] elapsed %.1fs mean %.2fs  "
              "REFUSED %d ACCEPTED %d SHIP_OK %d ANCHOR_OK %d DWARF %d"
              % (LANG, k + 1, len(PROBES), el, el / (k + 1),
                 tally["REFUSED"], tally["ACCEPTED"], tally["SHIP_OK"],
                 tally["ANCHOR_OK"], tally["DWARF"]))
        sys.stdout.flush()

out.close()
print("done: %s -> %s" % (json.dumps(tally), OUT))

PY_EOF
echo "--- lane finished, rc=$?"
date -u +%Y-%m-%dT%H:%M:%SZ
