#!/bin/sh
# op-pipeline lane -- cpp -- generated by
# Research/op_pipeline/lane_gen.py .  Do not hand-edit.
# steps 1b/2/3: compile-or-refuse, then the ANCHOR and SHIP
# builds of every probe the compiler accepted, then objdump
# extraction, then the anchor's DWARF parameter table.
set -u
export HOME=/work
export PATH=/persist/swift/usr/bin:$PATH
export GOTOOLCHAIN=local
export GOPROXY=off
export GOFLAGS=-mod=mod
ROOT=/work/regen_cpp_c0138
export GOCACHE="$ROOT/gocache"
export GOPATH="$ROOT/gopath"
# swift's binaries want libncurses.so.6 and the image ships
# only libncursesw.so.6.6; the symlink lives in the image's
# own /usr/lib and does NOT survive a container restart.
if [ -f /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 ]; then
  ln -sf /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 \
     /usr/lib/x86_64-linux-gnu/libncurses.so.6 2>/dev/null
  ldconfig 2>/dev/null
fi
echo "=== op pipeline -- cpp -- 400 candidate probes ==="
date -u +%Y-%m-%dT%H:%M:%SZ
# refuse in seconds rather than in an hour
if ! /usr/bin/clang++ --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: /usr/bin/clang++ is not runnable in this container."
  echo "!! tried: /usr/bin/clang++ --version"
  exit 4
fi
/usr/bin/clang++ --version 2>&1 | head -2
if ! objdump --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: objdump is not runnable."
  exit 4
fi
objdump --version 2>&1 | head -1
rm -rf "$ROOT"; mkdir -p "$ROOT" "$GOCACHE" "$GOPATH"
df -Pm /work | awk 'NR==2{print "free /work: " $4 " MB"}'
FREE=`df -Pm /work | awk 'NR==2{print $4}'`
if [ "$FREE" -lt 400 ]; then
  echo "!! REFUSING TO START: only $FREE MB free on /work, need 400"
  exit 3
fi
base64 -d <<'T_EOF' | gunzip > "$ROOT/table.json"
H4sIAAAAAAAC/73d3Y4cR3YE4FcZ0Dc2oLW6KuJkZtmGAdvAvoAvTYMgqdEPQM0QFInVQtC7m9Tu
eFfsyOqKIhC6ETiSRoys6syYZp3+fnn25uXDdx9efnf/7F/unr1++/bZV3fPHj+8//Srrz/+/et3
99/dP7z4+A9evL4sGP/8/uf3n/6Vt+8eX93/9PHf+p9fnj18/FvVerl8/PpPf/7x1eObT//149sX
v33x2f9/9cX9zy9ff/rO7999uP/01ccP717/9v/9+uu7377hX77N3R/+cPfqh4eX7/589/ju+cM/
/PDw+s2Hb+7v/u31T++/+eHh/b//7muPP759+e7+d197uP/Tx18/f7j/+f39u4e758/+6/mzu5cf
3j8+f3j6Xf3ji/9++f7uxX+8fv3hx7uXX929ePHxGy/rePH+7tU/PX/45fnD3ce/3t2///DxG7z8
+Pu4e/Wvzx9+ff7w7Nev7v4WeVGRFzvyEoi8XEf+cCrzqjKvduY1kHn9PPOrx8c3VliosLDDIhAW
n4d9/f3Ld1ZYqrC0wzIQlirs0sxbuVTgsgNXIHCpwFjNwE0FbnbgFgjcVGB3r+oqb7fz9kDe/nne
bx4/vHpzb8UdKu6w445A3PF53G/fPL70Lu6m0m522i2Qdvs87fcv33zrhF1UuVrscrUEytVyVa4+
flsrq2pVi92qlkCrWq5a1ZvHh++ssKpOLXadWgJ1alll2L/+0smsWtVit6ol0KoW6Mx/fPfxN2hl
VuVqscvVEihXC2Vm/zxaVL9a7H61BPrVUjKz/WpWBWuxC9YSKFjLVcH66fvHd949rerVYterJVCv
lq7Tnti8VMla7JK1BErWMiah/d1Lda3F7lpLoGstV13rpx++e7j/xv5xeFWVa7Ur1xqoXOtlktls
XqtqXqvdvNZA81qXSWR3y15VAVvtArYGCti67mW2g6sWttotbA20sBWT4PaRtaoatto1bA3UsPWq
hn14+Gts/9RaVRVb7Sq2BqrYWvPc9sG1qkK22oVsDRSytU1z20eXKmarXczWQDFb+zS1e3ipYrba
xWwNFLN1TEPbu7hqZqvdzNZAM1u3/dT+rgZV0WBXNAQqGi43wttbG1RZg13WEChrWPbDuzc9VGeD
3dkQ6GxYp9Ht8gLV2GA3NgQaG3Aj9okXu6pusKsbAtUNvJXef7WrAge7wCFQ4HBV4P70qcB4f3QH
VdxgFzcEihueittfLuqnRyv8m1s1NtiNDYHGhn4V9z/NxyqgqhrsqoZAVcO4SvvHT39SuTQrsGpp
sFsaAi0N23Vgd7Oi6mW0exkDvYyXq7h/t3c5mVUdo13HGKhjXHRm/zqrHka7hzHQw7jKzCd/8KBq
YrSbGANNjNgJ7l9xVcJolzAGShgpg5+tn1QFjHYBY6CAsfaS+9dcVTHaVYyBKsYmk3/BG6dUxYx2
MWOgmLHfCO9fedXTaPc0Bnoax374sxu9Km60ixsDxY3bkRWw74FSXa7sLleBLleX/RU4u/WXqnZl
V7sKVLtaDi2Bfxeopld206tA06vrpvfi1bfez2ul+l3Z/a4C/a6u+92L356lXdZhRVbNruxmV4Fm
VxSR35pXWNW5sutcBepcXde5Fz+8+tG9vqrFld3iKtDiqonAJ0aVSnW3srtbBbpbXXe3c+NZpSpb
2ZWtApWtriqbO55Vqp2V3c4q0M7qqp25f6jfVBFrdhFrgSLWLiqsO57VVO1qdu1qgdrVFhXYHc9q
qmQ1u2S1QMlqqwps7lVNtaxmt6wWaFntqmX5j8M31bCa3bBaoGG1q4Zlj2c1VbCaXbBaoGC1q4Ll
jmc1Va6aXa5aoFy1q3JlPmfVVKtqdqtqgVbVrlqV+6RJU3Wq2XWqBepUGzKs/3ZHU62q2a2qBVpV
23Rm+/2NrspVt8tVD5SrfpGZ/fOoq37V7X7VA/2qLzKz+2ruqmB1u2D1QMHqVwXLflysq3rV7XrV
A/WqQ6f1N6+uSla3S1YPlKzOSWh/91Jdq9tdqwe6Vr/qWiefce+qcnW7cvVA5eptktlsXl01r243
rx5oXr1PIttbtipg3S5gPVDA+tjLbAdXLazbLawHWljfJsHtI2uoGjbsGjYCNWxc1bAveMpgqCo2
7Co2AlVsLPPc9sE1VCEbdiEbgUI21mlu9+gaqpgNu5iNQDEbmKY2D6+hitmwi9kIFLPBaWh3Fx+q
mQ27mY1AMxu1n/rErqYq2rAr2ghUtNFuhPe3NlXWhl3WRqCsjb4f3r7pVWcbdmcbgc42xjS6X15U
Yxt2YxuBxja2G7H9F/umqttmV7ctUN22y6309qt9UwVuswvcFihw21WBOzGetanittnFbQsUt+2v
xe3vD7FTM1qbqm2bXdu2QG3boDO7g1qbKm2bXdq2QGnbqCOfmNbaVGnb7NK2BUrbVpPU9gamutpm
d7Ut0NW2pjOfm9vaVE/b7J62BXra1neC+1dctbTNbmlboKVtYx785M8mmyprm13WtkBZ27Zb6d1r
D/VZ/bA/qx+Bz+rH02f1q/QnuyrU5/bD/tx+BD63H0+f278T37/6q4q/2vHXQPx1Hv/8+61Qn+sP
+3P9Efhcf1xwZAX8e4BqBWivAAMrwAMrcO4YgCIAYBMACBAAuNThZfDvhqaWodnL0ALL0A4sw+mD
oat16PY69MA69OPr4N8PQ63DsNdhBNZh0g3dmS8oTwC2J4CAJ4DLpBGeGfyCogVg0wII0AJYLrPc
3vQXFDEAmxhAgBjAMimA/ggYlDUA2xpAwBrAss5S+zNRUN4AbG8AAW8Ay6TtnRoGg0IHYKMDCKAD
WHTJMyfCoMgB2OQAAuQAFt3nzIcJoMgB2OQAAuQAljZNbM6GQdEDsOkBBOgBLH2a2hwQg7IHYNsD
CNgDWMY0tbuJqV5m2wMI2ANYdC+zH82Hsgdg2wMI2ANYdSdz58Wg7AHY9gAC9gBWXcnMoTEoeQC2
PICAPIBV1zHvETAocQC2OICAOIBV9zDzSRgobgA2N4AAN4CV88T+GynKG4DtDSDgDWCtneD2OycK
HIANDiAADmBt8+AnjizVyGxzAAFzAGufB7df4aqS2eoAAuoAVl3J3OfcoMgB2OQAAuQA1m0nsr+r
KW8AtjeAgDcAXPaS29uawgZgYwMIYAOAbmfnntWHogZgUwMIUAPAuhfc7GrKGoBtDSBgDQDYy+1u
6IoZgM0MIMAMALwZ3E6vepvNDCDADAC1l94+1RQ4ABscQAAcAHRx+4LnIRQ/AJsfQIAfAPqN8P7Z
piqcrREgoBEAYz+8fbqpKme7BAi4BMC2H9083xRRAJsoQIAoAC/7yd09XkkFsKUCBKQCcDkQ3d/u
lFsA2y1AwC0A1yMrYO95CjCADRggABiAOLAC9mtAtTzbMUDAMQC5n99uOkoygC0ZICAZgHUk+4kN
QJU9mzRAgDQA26El8HcAVfls2AAB2ADUlc8fW4MCDWCDBgiABuDvqt55WgyKMIBNGCBAGICbzmyO
rUGZBbDNAgTMAtRFR/bH1qCYAthMAQJMAWqZpHZ3MeUSwHYJEHAJUKvOfGpsDUoogC0UICAUoLAT
3L/iqrnZTgECTgGK8+Anf3JRbAFstgABtgBVt9L7117VNtswQMAwQLV5+rOtVXkGsD0DBDwDVL8Z
37/6qrzZtAECtAFqzON/wdu0yjuA7R0g4B2gtiMrYN8DCkGAjSAggCCgXQ6swMljQNEIsGkEBGgE
tOXwMvh3g2p/NpiAAJiAth5YhrMHg4IUYEMKCEAKaDi+Dv79oLqhLSwgICygTbqhPbamnAXYzgIC
zgLapBGeGltT5AJscgEBcgGtzXKbY2uKXoBNLyBAL6BNCuCJsTVlMMA2GBAwGNDGLPWJ6S3lMMB2
GBBwGNAmbe/c2JrCGGBjDAhgDOi65Llja4pigE0xIEAxoOs+5z55oCgG2BQDAhQD+jpN7I6tKZIB
NsmAAMmAjmlqd2xNmQywTQYETAZ0TlO7m5jqZbbJgIDJgK57mT8DoEwG2CYDAiYDuu5k9tiaMhlg
mwwImAzoupK5Y2tKZIAtMiAgMqDrOmY+KqYkBtgSAwISA7ruYe7TMYphgM0wIMAwYFzmif03UpTD
ANthQMBhwFh2gtvvnCiIATbEgADEgLHOg/tHlrIYYFsMCFgMGJgHt1/hqpLZGgMCGgOGrmT2Y2+K
YoBNMSBAMWDUTuQTu5qqZbbDgIDDgNH2kvvbmmpnNsKAAMKAodvZyQf7FcEAm2BAgGDAGHvBza6m
DAbYBgMCBgPGtpfb3dAVvwCbX0CAX8B2uRncTq96m80vIMAvYFv20tunmoIYYEMMCEAM2HRx+4Ln
IZTIAFtkQEBkwIYb4e2zTdkMsG0GBGwGbNwP755uCmiADTQgADRgq/3o5vmmmAbYTAMCTAO2tp/c
3uNVl7OhBgSgBmz9QPQT250qdbbYgIDYgG0cWQF/z1P1zlYbEFAbsG0HVsB8DVC5DbTdBgbcBl4u
+/ndpkOFNtBGGxhAG3hZjmS3NwAquIE23MAA3MDLemgJ3B2ASm6gLTcwIDfwoiufP7ZGhTXQxhoY
wBr4hDX87hY/M7dGRTPQphkYoBn4RDNchTYH16gcBtoOAwMOA58chqvM/uQaFbtAm11ggF3gE7tw
HdveyYYKPezQIxB6TEKfml2jkhZoSwsMSAt8khZ0cvuaK2uBtrXAgLXAJ2tBJj/3AwwVu0CbXWCA
XeATu7AT37/6qr7Z/gID/gKf/AUZ/2x9VQ4DbYeBAYeBTw7DXn7/+qsaZ3MMDHAMXLiT//w7tlQ+
A22fgQGfgUsdWgL/LlAdzwYbGAAbuLQjS3D2MFClzyYcGCAcuPTj6+DfD6oH2qgDA6gDl3FkHU4f
D6oW2tADA9ADl81YCPuOUPoDbf2BAf2B66wlunNsVP4Dbf+BAf+B66wbnhlko2IgaDMQDDAQXNdp
8Lfm1VZV0KYgGKAguM6qoD/KRuVB0PYgGPAguHIa2x/povIgaHsQDHgQXGe979QwGxUIQRuEYACE
4Dqpe+Y0GxUFQZuCYICC4DppduYTCVQMBG0GggEGguuYRzbn2agoCNoUBAMUBNdtHtscaKNyIGg7
EAw4EMRlHtvcyZQBQduAYMCAICYNzZ4PoPIfaPsPDPgPxKSduTNtVPYDbfuBAfuBmJQzc6iNSn2g
rT4woD4Qk2LmPUlGJT3Qlh4YkB6ISSNzn55RxANt4oEB4oFoO5H9t1aU70Dbd2DAdyD6XnL7vRSF
O9DGHRjAHYixk/zEyaW6mW07MGA7ENtOcvdVrmQH2rIDA7IDOSln9rNxinSgTTowQDqQy15mf2tT
lgNty4EBy4Fcd6Pbe5tCHGgjDgwgDuSkp50bAKDiG2jzDQzwDSR3k5utTdkNtO0GBuwGsnaD29u6
Km822cAA2UC228nt+KrB2VwDA1wD2Xfj+4ebqnA22sAA2kBOKtwXPDGh+AbafAMDfAO53UpvH3FK
cqAtOTAgObAuN9K7h5zyHGh7Dgx4DqzlRnbzmFOsA23WgQHWgbXeiO7u9Ep2oC07MCA7sHAku7/n
KeOBtvHAgPHA4qEl8Dc+VfRs6IEB6IFVR5bAfhmovmdbDwxYD6x2YwHsyqOkB9rSAwPSA6sfCn9i
E1C1z+YeGOAeWOPYGvi7gCp/NvjAAPjAmpS/E+NuCnmgjTwwgDyw/b70nWfaqEgH2qQDA6QD2zIJ
7Y67Kb+Btt/AgN/Atk4ynxh3U1wDba6BAa6BDbPY7lambAbaNgMDNgMbJ6HPjbspoYG20MCA0MBW
e8n9a646nG00MGA0sLWd5Cd/jFFcA22ugQGuga3fjO9ffVXgbLeBAbeBbezEP1tgld9A229gwG9g
227nt6+/YhxoMw4MMA7sl538X/DmrXIdaLsODLgO7MuhJfDvAtXxbOiBAeiBfT2yBCcPA0U/0KYf
GKAf2HF8Hfz7QfVAG4NgAINg55F1OHs8KCCCNhDBABDBXsZC+HeEaom2GsGAGsE+a4n2uJtyI2i7
EQy4Eeyzbnhq3E3xEbT5CAb4CPYxDW6OuylCgjYhwQAhwT6rgifG3ZQjQduRYMCR4LhMY58Y+lKO
BG1HggFHgmPW+86NuylIgjYkwQAkwTGpe+64myIkaBMSDBASHJNm5z6aoPgI2nwEA3wEB+eR3XE3
RUjQJiQYICQ4ah7bHXdTfgRtP4IBP4KjzWO7O5lqaLYdwYAdwTFpaP7QgHIjaLsRDLgRHJN2Zo+7
KTOCthnBgBnBMSln7rib0iJoaxEMaBHcJsXMfKJMCRG0hQgGhAhuk0bmPkGjaAjaNAQDNAS3dSey
/9aKciFouxAMuBDcsJfcfi9FoRC0UQgGUAhu3Enun1zKhKBtQjBgQnCrneT2q1yVM1uEYECE4DYp
Z/bjcYqCoE1BMEBBcOt7mU9sbaqg2QYEAwYEt7Eb3d/bVE+z8QcG8Aduk552bhKgFPtQNvtQAfah
Lpfd5F5rK2U+lG0+VMB8qMuyG9zc1ktRD2VTDxWgHuqy3k5ux4eKDzs+AvGxG9893EphD2VjDxXA
HuoyqXDnn5gopT6UrT5UQH2oS91K7x5xpfyHsv2HCvgPdWk30tuHXFfZu529B7L3G9ndY26o6MOO
PgLRx43o9k6/qeybnX0LZN+OZPf3PKVClK1CVECFqOVyaAnsjU/JEGXLEBWQIWpZjiyB+zJQNkTZ
NkQFbIha1hsLYFceBUOUDUNUAIaoBYfCn9gEVO2zcYgK4BC18Nga+LuAKn+2DlEBHaKWSfnzx91K
gRBlgxAVACHqCYT4vOCfmXgrBUCUDUBUAICoJwBC5TaH3kp5D2V7DxXwHurJe1Cx/bm3UsBD2cBD
BYCHegIeZHJ3W1OeQ9meQwU8h3ryHFTuU9NvpVyHsl2HCrgO9eQ6TMP7V161Ott2qIDtUE+2wyz8
yZ9tFPRQNvRQAeihnqCH/RXw7wFV7GzzoQLmQz2ZD7MVONttlf5Qtv5QAf2hnvSHG0vg3wWq5NkM
RAUYiFrb/hJ8wbu7SoYoW4aogAxRaz+6Cv69oBqgjUVUAIuodRxchbPHg6qENiBRAUCi1s1aCvuu
UKhE2ahEBVCJwuXgUpw9MBQ1UTY1UQFqorB4a+HfF6pD2gJFBQSKwk6HdCfkSikUZSsUFVAoCjvN
8cyQXCmOomyOogIcRYF72d+a11wVRRulqABKUdgpiv6oXCmbomybogI2RaHtJfdnxkrpFGXrFBXQ
KQo7rfDUwFwpoKJsoKICQEVhXgbNmblSOEXZOEUFcIrCvPe5jzgomqJsmqICNEXxspvanJwrBVSU
DVRUAKgoLrvJzeG5Uj5F2T5FBXyK4rqb3NzYlE5Rtk5RAZ2iOO9v9iBCKZuibJuiAjZFcd7d3Cm6
UjJF2TJFBWSK4ry6mYN0pVSKslWKCqgUxXltMx9XUxZF2RZFBSyK4ryvuU/oKIaibIaiAgxFceyn
9t+QUQpF2QpFBRSK4nYjvP0OjEIoykYoKoBQVF32w/vHmVIoylYoKqBQVC374d1XvFIoylYoKqBQ
VM2rm/00ngIoygYoKgBQVOFGbH+nU/ZE2fZEBeyJKt5K7291qsXZ7EQF2ImqeYs7OYGgyImyyYkK
kBNV7VZ4s9MpcaJscaIC4kRVv5Xd3uhVtbOpiQpQE1XjUHh7BVS/s6GJCkATVdutFbBPPAVOlA1O
VACcqDYveF/wXIbCJ8rGJyqAT1RbDiyAfe4piaJsiaICEkW19fYCuCefEinKFikqIFJUw+345tmn
aIqyaYoK0BTVeDu9u/crn6Jsn6ICPkW1Ohj/xBaoyp9tVVTAqqjWjq6Cvw+qGmiTFRUgK6r1g6tg
vx5UG7Tdigq4FdXG7TXw25DqgrZbUQG3otp2NL+/ISi+omy+ogJ8RfXL4WWwdwRFWJRNWFSAsKg+
r4YnxvIUXFE2XFEBuKL6VSU8D9GVgirKhioqAFVUxzy3O5anXIqyXYoKuBTVOY99YixPQRRlQxQV
gCiq105ye2dTjc92JyrgTlRv89znxvKUP1G2P1EBf6J6vxHev/Kq4dkGRQUMiupjP/zJn3YUSFE2
SFEBkKL6dmQF7HtA2RRl2xQVsClqXPZX4GzDVUpF2UpFBZSKGsuhJfDvAlXybK6iAlxFjXV/Cb7g
7V8lWJQtWFRAsKiBo6vg3wuqAdqoRQVQixo8uAonjwcFXZQNXVQAuqhR1lL4d4VqiTZ+UQH8okY7
uBSnDwxVGm0SowIkRo3urYV/X6gOaUsZFZAyaux0SHssT2kZZWsZFdAyauw0x1NjeYrNKJvNqACb
UdtlL7s5lqfwjLLxjArgGbXtFMUTY3nK0Cjb0KiAoVHbupf8xGSaUjTKVjQqoGjUttMKz43lKUij
bEijApBGbfMy6I7lKUSjbESjAohGbfPe5z79oAiNsgmNChAatbXd1O5YnoI0yoY0KgBp1NZ3k7tj
ecrRKNvRqICjUdvYTe5ubKq/2YpGBRSN2ub97eAcw//++n/ZnBvT4YYBAA==
T_EOF
echo "payload bytes: $(wc -c < "$ROOT/table.json")"
python3 - "$ROOT" <<'PY_EOF'

import json, os, re, shutil, subprocess, sys, time

ROOT = sys.argv[1]
T = json.load(open(os.path.join(ROOT, "table.json")))
LANG = T["language"]
PROBES = T["probes"]
OUT = T["out"]
out = open(OUT, "w")
WORK = os.path.join(ROOT, "u")

# --- verbatim delimiter codec, copied from verbatim_diag.py ---
def esc(text):
    """make `text` safe to place in one pipe-delimited field, reversibly."""
    for raw, rep in _ENC:
        text = text.replace(raw, rep)
    return text

_ENC = [('\\', '\\\\'), ('|', '\\p'), (';', '\\s'), ('\n', '\\n'), ('\r', '\\r')]
MARKER = '#verbatim-escape v1'
out.write(MARKER + '\n')


print("op lane %s: %d candidate probes" % (LANG, len(PROBES)))
sys.stdout.flush()


def sh(cmd, cwd=None, timeout=180):
    try:
        p = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE, timeout=timeout)
        so = p.stdout.decode("utf-8", "replace")
        se = p.stderr.decode("utf-8", "replace")
        return p.returncode, so, se
    except subprocess.TimeoutExpired:
        return 124, "", "TIMEOUT after %ds" % timeout
    except OSError as e:
        return 125, "", "OSError %s" % e


# ------------------------------------------------------ objdump reading

LABEL = re.compile(r"^([0-9a-f]+)\s+<(.+)>:\s*$")
INSN = re.compile(r"^\s*([0-9a-f]+):\t(.*)$")
RELOC = re.compile(r"^\s+([0-9a-f]+): (R_\S+)\t(.+?)\s*$")


def extract(text, sym, exact):
    """the two columns for one symbol.

    bytes  every byte objdump printed, in order, flattened
    mnem   the instruction text, with objdump's own trailing `# ...`
           comment dropped -- that comment is arithmetic objdump did
           for the reader, not part of the instruction.  A relocation
           is appended to the instruction it applies to as
           ` !!reloc=<type>:<symbol>`, because in an object file the
           call displacement is literally zero and the callee's name
           lives only in the relocation.
    """
    lines = text.splitlines()
    k = -1
    for idx, ln in enumerate(lines):
        m = LABEL.match(ln)
        if not m:
            continue
        lab = m.group(2)
        hit = (lab == sym) if exact else (sym in lab)
        if hit:
            k = idx
            break
    if k < 0:
        return None
    raw = []
    mn = []
    for ln in lines[k + 1:]:
        if LABEL.match(ln):
            break
        m = INSN.match(ln)
        if not m:
            r = RELOC.match(ln)
            if r and mn:
                mn[-1] = "%s !!reloc=%s:%s" % (mn[-1], r.group(2), r.group(3))
            continue
        parts = m.group(2).split("\t")
        bs = parts[0].split()
        raw.extend(bs)
        txt = parts[1] if len(parts) > 1 else ""
        txt = txt.split("#")[0]
        txt = " ".join(txt.split())
        if txt:
            mn.append(txt)
    return raw, mn


def disasm(obj, sym, exact):
    rc, so, se = sh(["objdump", "-dr", "--disassemble=" + sym, obj])
    got = extract(so, sym, exact) if rc == 0 else None
    if got is None:
        rc, so, se = sh(["objdump", "-dr", obj], timeout=600)
        got = extract(so, sym, exact)
    return got


# --------------------------------------------------------- DWARF reading
#
# objdump --dwarf=info prints one entry per line block:
#
#   <1><2d>: Abbrev Number: 2 (DW_TAG_subprogram)
#      <2e>   DW_AT_name        : op_12
#   <2><4a>: Abbrev Number: 3 (DW_TAG_formal_parameter)
#      <4b>   DW_AT_name        : a
#      <52>   DW_AT_location    : 2 byte block: 91 7c (DW_OP_fbreg: -4)
#
# The leading <N> is the tree depth.  A formal parameter one level
# below the matching subprogram is a parameter OF that subprogram.

DIE = re.compile(r"^\s*<(\d+)><[0-9a-f]+>:\s*Abbrev Number:\s*\d+\s*\((\S+)\)")
ATTR = re.compile(r"^\s*<[0-9a-f]+>\s+(DW_AT_\w+)\s*:\s*(.*?)\s*$")


def clean(text):
    text = " ".join(text.split())
    return text


STRPREFIX = re.compile(r"^\((?:indexed string|indirect string)[^)]*\):\s*")


def dwname(text):
    """objdump prints a string attribute as `(indexed string: 0x5): a`.
    The parenthesised part is objdump telling the reader WHERE in the
    string table it found the name; the name is what follows.  Keeping
    the prefix would have put objdump's bookkeeping into the parameter
    name column."""
    return STRPREFIX.sub("", text.strip())


def dwarf_params(text, sym):
    """[(name, location)] for the subprogram named `sym`.

    More than one subprogram can carry the name.  swift's `@_cdecl`
    emits a C-entry thunk beside the real function, and the thunk has
    no DW_TAG_formal_parameter children at all, so the first match is
    not always the one holding the parameter table.  Every match is
    collected and the first one that actually has parameters wins."""
    lines = text.splitlines()
    depth = None
    tag = None
    attrs = {}
    entries = []
    for ln in lines:
        m = DIE.match(ln)
        if m:
            if tag is not None:
                entries.append((depth, tag, attrs))
            depth = int(m.group(1))
            tag = m.group(2)
            attrs = {}
            continue
        a = ATTR.match(ln)
        if a and tag is not None:
            attrs[a.group(1)] = a.group(2)
    if tag is not None:
        entries.append((depth, tag, attrs))

    hits = []
    for idx, (d, t, at) in enumerate(entries):
        if t != "DW_TAG_subprogram":
            continue
        names = []
        if "DW_AT_name" in at:
            names.append(dwname(at["DW_AT_name"]))
        if "DW_AT_linkage_name" in at:
            names.append(dwname(at["DW_AT_linkage_name"]))
        for nm in names:
            if nm == sym or sym in nm:
                hits.append(idx)
                break
    if not hits:
        return None
    best = []
    for k in hits:
        base = entries[k][0]
        got = []
        for d, t, at in entries[k + 1:]:
            if d <= base:
                break
            if d != base + 1:
                continue
            if t != "DW_TAG_formal_parameter":
                continue
            nm = clean(dwname(at.get("DW_AT_name", "(unnamed)")))
            loc = clean(at.get("DW_AT_location", "(no location)"))
            got.append((nm, loc))
        if got:
            return got
        best = got
    return best


def dwarf(obj, sym):
    rc, so, se = sh(["objdump", "--dwarf=info", obj], timeout=600)
    if rc != 0:
        return None, "objdump --dwarf=info rc=%d" % rc
    got = dwarf_params(so, sym)
    if got is None:
        return None, "no DW_TAG_subprogram named %s" % sym
    if not got:
        return None, "subprogram %s has no DW_TAG_formal_parameter" % sym
    return got, None


# ------------------------------------------------------------ compiling

GOMOD = "module opprobe\n\ngo 1.26\n"

CLANG = "/usr/bin/clang"
CLANGXX = "/usr/bin/clang++"
SWIFTC = "/persist/swift/usr/bin/swiftc"


def compile_probe(p, d, mode):
    """(rc, artifact path, diagnostic text)."""
    if LANG == "c":
        src = os.path.join(d, "unit.c")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANG, "-std=c17"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "cpp":
        src = os.path.join(d, "unit.cpp")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANGXX, "-std=c++20"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "rust":
        src = os.path.join(d, "unit.rs")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        if mode == "anchor":
            opt = ["-C", "opt-level=0", "-g"]
        else:
            opt = ["-C", "opt-level=1", "-C", "debug-assertions=off"]
        cmd = (["rustc", "--crate-type=lib", "--emit=obj"] + opt
               + ["-o", obj, src])
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "go":
        open(os.path.join(d, "go.mod"), "w").write(GOMOD)
        open(os.path.join(d, "main.go"), "w").write(p["source"])
        obj = os.path.join(d, "bin_%s" % mode)
        cmd = ["go", "build"]
        if mode == "anchor":
            cmd.append("-gcflags=-N -l")
        cmd.extend(["-o", obj, "."])
        rc, so, se = sh(cmd, cwd=d, timeout=300)
        return rc, obj, (se or so)
    if LANG == "swift":
        src = os.path.join(d, "unit.swift")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-Onone", "-g"] if mode == "anchor" else ["-O"]
        cmd = [SWIFTC] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd, timeout=300)
        return rc, obj, (se or so)
    raise KeyError(LANG)


DIAG = re.compile(r"^[^\s:]+:\d+(:\d+)?:")


def firstline(txt):
    """the compiler's own words for why it refused.

    The first line is not reliably the reason.  clang leads with a
    warning and puts the error underneath.  go leads with a banner
    naming the package -- `# opprobe` -- and its diagnostics never
    contain the word `error` at all, so a rule that only looked for
    that word recorded the banner and threw the testimony away.
    Three passes, in order: a line saying `error`, a line in the
    `file:line:col:` diagnostic shape, then the first line that is
    not a banner."""
    lines = []
    for ln in txt.splitlines():
        s = ln.strip()
        if s:
            lines.append(s)
    for ln in lines:
        if re.search(r"\berror\b", ln, re.I):
            return ln[:200]
    for ln in lines:
        if DIAG.match(ln):
            return ln[:200]
    for ln in lines:
        if not ln.startswith("#"):
            return ln[:200]
    if lines:
        return lines[0][:200]
    return "(no diagnostic)"


def write_unit(n, build, obj, sym, exact):
    got = disasm(obj, sym, exact)
    if got is None:
        rc2, so2, se2 = sh(["objdump", "-t", obj])
        near = 0
        for l in so2.splitlines():
            if sym in l:
                near += 1
        out.write("op_%d|%s|NOSYM|%s\n"
                  % (n, build, esc("symbol %s absent, %d near matches"
                                   % (sym, near))))
        return False
    raw, mn = got
    out.write("op_%d|%s|OK|%s|%s\n"
              % (n, build, " ".join(esc(x) for x in raw),
                 ";".join(esc(x) for x in mn)))
    return True


t0 = time.time()
tally = {"REFUSED": 0, "ACCEPTED": 0, "ANCHOR_OK": 0, "SHIP_OK": 0,
         "DWARF": 0}

for k, p in enumerate(PROBES):
    n = p["n"]
    sym = p["symbol"]
    exact = p["symbol_exact"]
    d = os.path.join(WORK, "n%d" % n)
    shutil.rmtree(d, ignore_errors=True)
    os.makedirs(d)

    rc, obj, err = compile_probe(p, d, "ship")
    if rc != 0 or not os.path.exists(obj):
        out.write("op_%d|REFUSED|%s\n" % (n, esc(firstline(err))))
        tally["REFUSED"] += 1
        out.flush()
        shutil.rmtree(d, ignore_errors=True)
        continue
    tally["ACCEPTED"] += 1
    if write_unit(n, "SHIP", obj, sym, exact):
        tally["SHIP_OK"] += 1

    rc, aobj, aerr = compile_probe(p, d, "anchor")
    if rc != 0 or not os.path.exists(aobj):
        out.write("op_%d|ANCHOR|BUILDFAIL|%s\n" % (n, esc(firstline(aerr))))
    else:
        if write_unit(n, "ANCHOR", aobj, sym, exact):
            tally["ANCHOR_OK"] += 1
        rows, why = dwarf(aobj, sym)
        if rows is None:
            out.write("op_%d|ANCHOR|NODWARF|%s\n" % (n, esc(why)))
        else:
            joined = ";".join("%s=%s" % (esc(a), esc(b)) for a, b in rows)
            out.write("op_%d|ANCHOR|DWARF|%s\n" % (n, joined))
            tally["DWARF"] += 1
    out.flush()
    shutil.rmtree(d, ignore_errors=True)

    if (k + 1) % 25 == 0 or (k + 1) == len(PROBES):
        el = time.time() - t0
        print("[progress] %s [%d/%d] elapsed %.1fs mean %.2fs  "
              "REFUSED %d ACCEPTED %d SHIP_OK %d ANCHOR_OK %d DWARF %d"
              % (LANG, k + 1, len(PROBES), el, el / (k + 1),
                 tally["REFUSED"], tally["ACCEPTED"], tally["SHIP_OK"],
                 tally["ANCHOR_OK"], tally["DWARF"]))
        sys.stdout.flush()

out.close()
print("done: %s -> %s" % (json.dumps(tally), OUT))

PY_EOF
echo "--- lane finished, rc=$?"
date -u +%Y-%m-%dT%H:%M:%SZ
