#!/bin/sh
# op-pipeline lane -- swift -- generated by
# Research/op_pipeline/lane_gen.py .  Do not hand-edit.
# steps 1b/2/3: compile-or-refuse, then the ANCHOR and SHIP
# builds of every probe the compiler accepted, then objdump
# extraction, then the anchor's DWARF parameter table.
set -u
export HOME=/work
export PATH=/persist/swift/usr/bin:$PATH
export GOTOOLCHAIN=local
export GOPROXY=off
export GOFLAGS=-mod=mod
ROOT=/work/regen_swift_c0006
export GOCACHE="$ROOT/gocache"
export GOPATH="$ROOT/gopath"
# swift's binaries want libncurses.so.6 and the image ships
# only libncursesw.so.6.6; the symlink lives in the image's
# own /usr/lib and does NOT survive a container restart.
if [ -f /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 ]; then
  ln -sf /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 \
     /usr/lib/x86_64-linux-gnu/libncurses.so.6 2>/dev/null
  ldconfig 2>/dev/null
fi
echo "=== op pipeline -- swift -- 400 candidate probes ==="
date -u +%Y-%m-%dT%H:%M:%SZ
# refuse in seconds rather than in an hour
if ! /persist/swift/usr/bin/swiftc --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: swiftc is not runnable in this container."
  echo "!! tried: /persist/swift/usr/bin/swiftc --version"
  exit 4
fi
/persist/swift/usr/bin/swiftc --version 2>&1 | head -2
if ! objdump --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: objdump is not runnable."
  exit 4
fi
objdump --version 2>&1 | head -1
rm -rf "$ROOT"; mkdir -p "$ROOT" "$GOCACHE" "$GOPATH"
df -Pm /work | awk 'NR==2{print "free /work: " $4 " MB"}'
FREE=`df -Pm /work | awk 'NR==2{print $4}'`
if [ "$FREE" -lt 400 ]; then
  echo "!! REFUSING TO START: only $FREE MB free on /work, need 400"
  exit 3
fi
base64 -d <<'T_EOF' | gunzip > "$ROOT/table.json"
H4sIAAAAAAAC/6WdXY9cx3VF/8qATzagj1sf55wqw7CDJAiQ1wD9FAYESVOCAGYoUCRiQ/B/z5Cc
Jru7ds2+u65fZA3p8TpAzVlVbXPp92dvX97//PHlz2+e/enu2W//98tPH559d/fs3ccPn/7+x4e/
/vj+zc9v7l98/qUXr7dt8x8+/P3zb/r1/btXb357+H3//fuz+4e/5LptD1/+7R//++rd20//8Xe/
vvj0tWdfv/jizd9fvv70nX96+fa3N5++/O7j+9ef/6t//PHu8/f7/F3uvv/+7tUv9y/f/+Pur399
fv/rx1dvf3l999PH+9d3j9/zDy/uXv7p7vSf9x+Sf3f34u7Vl7/x+se77//y+PW735/f3z386/2b
Dx/f39+9fPhed6+e3//z+f2zf35395U5AeYkMyfKnCbMTUfOADnLyJki52/IJT8i/+u7d2+/Epe8
k7gA4iITF0pcAPG/v3v4bW905gqYq8xcKXMFzP/x9t3LDzqyAWSTkY0i2ww5uQ7tANplaKfQPoNu
mw4dADpk6KDQAaAf/r0O3ABwk4EbBW4YOOWmM3fA3GXmTpn7hFk/zAkYMMkGTNSAacPIJevIQIBJ
FmCiAkwJI184ezcyEGCSBZioAFPGyPpRTkCASRZgogJMSICnlYWRgP6SrL9E9ZfqhHhlYyQgwCQL
MFEBJptBL6wM4L8k+y9R/yWfMK/sDKC/JOsvUf2lmDCvLA1gwCQbMFEDpjZhXjjOQIAJCfDD+49z
4lv//cuL13978/rtH56fv+HzZ39Ec1xY0Su6/XvdN0YGUsybOEbenh4jb3iMvIExbp4EuwcBqsxJ
HSSRQdJkkAQGuX4n7J4D+DNndY5M5siTOfJsjovluXsS4NVc1EkKmaRMJimzSS5eFLsnAb7NVZ2k
kknqZJIKJrm8NeyeAgg4mzqFkSlsMoXhKS5vErsHAVbOrg7iZBCfDOKTQRZ+QICpc6hzBJkjJnME
nuPixrF7DmDv3NQ5GpmjTeZoeI6LW8juOYDSs6r0TJSeJ0rPHc+h/3gUoPSiKr0QpZeJ0gtS+mll
XRUg9KIKvRChl4nQS5qMsbKvClB6UZVeiNLLROklzybRF1YBRi+q0QsxepkYvZTJIAsbqwChF1Xo
hQi9TIRe6mSQhZVVgNOL6vRCnF4mTi82GWThRwQovcgP7UIf2uXC3g29m9pOXqDuIj+yC31klxh5
bx5Ie4mBpIv8xC70iV3aSHz9EtoLDGxc5E+YC/2EufQJ8MWC3IlcgXmr/AlzpZ8w122CfPG22YsM
LFvlT5gr/YS5phH58lawFxeotMqfLlf66XLNEPfS/nuJgTOr/OlypZ8u14KJ9UMM3FjlD5cr/XC5
Vgh8YfO9wMCBVf5gudIPlqtB4Atr7wUGsquy7CqVXXUIrB9hILsqy65S2VUgu9PKkgCqq7LqKlVd
bZh3ZUsA2VVZdpXKrvYJsrwmDLjOZNcZdZ1tmFjfEwZUZ7LqjKrOEibWF4UB25lsO6O2s4yJ5WNs
QHYmy84uZffDD39GxI+2+3R3v73G/9fL+5/f/PnT3/5loH74bggbKM9k5Vnl2HXAvrjNL4AD9Zms
PjMObgP4t0v9AjcwoMkGNOfcjrkf990COXChyS604OSByR+v+AvkwIomW9EaJ28D+VniC9RAjCaL
0Tqn7oj6rHId3IEfXfajbxTcNwi+esAdWNJlS3ri3AlxP2p9gRu40mVXeubcGXE/yn2BGyjTZWU6
V6YXxL18vIEyXVamc2X6qMzT+jpxIEyXhelcmG4Q+8A+Acp0WZnOlemOyZcXCjCmy8Z0bkwPCL6+
UYAwXRamc2F6g+DrKwU402VnOnemdwi+esQDKDNkZQZXZjwq88vdG78fvvzabnRgzZCtGdyakQD6
8IYQ4YE6Q1ZncHVGBvC37wiRHegzZH0G12eUGfvVZhTpgUVDtmhwi0ad0V+9J0R6INOQZRpcpmGA
/voSIJIDmYYs0+AyDcfk1/cAER4INWShBhdqxAT+wIEHTg3ZqcGdGg2zX90GRHag1ZC1Glyr0TH7
1YVAY29ArU1Wa+NqbRtmXz/uDai1yWptXK0NqfV0ZM00INYmi7VxsbY8QT+yZxpQa5PV2rhaW5nR
ry+aBszaZLM2btZWJ/AHNk0DYm2yWBsXa7MJ/JFVA9zaZLc27tbmE/gDRx6otclqbVyt7VGtn69g
+AHy+Zd2gwOvNtmrjXu1tRF8eH5o6ECrTdZq41ptfUS/fXxI5B1ItctS7VyqfZuQXy1IjR1YtctW
7dyqPU3Yrx4eGjvQape12rlWex7Zr+8DGjcQapeF2rlQe4Hc15cBDR3otMs67VynvWL09YMOXNpl
l3bu0m6Q/OoaoJEDkXZZpJ2LtDskv7oDaORAo13WaOca7QHJ14850GiXNdq5RjvQ6OnIagES7bJE
O5do7xh8fbcYKBOZXCayjWrUtm3C7svoCaAnGT1x9ITRl7eLgVCRyaEi2zJHzxh9eb0YKBaZXCyy
rXD0gtHXj3oF5FUmr5z8UqNfk1bohZF8N7wBeJPhjcMbgsevDAHfAb7L+M7xHeHDl4ZAH4A+ZPrg
9DGlH/ekwN8Af5P5G+dvU/7xxSHwd8DfZf7O+TviB1eD/ewgfGRy+MgSF2zaJuzgdiDgA8nKESRL
XLIpzfAPHHzQQzK5h2SJezblCf14RxDogWrlNpIlrtpUJvTjNUGgB7qVO0mWuG5TndAfOfZAt3Iv
yRLXbYK6PR1bOUC2cjjJEpdt8hn8sZ0DdCtHlCxx3aaY8h9ZOsC2ck/JErdtajP8Q1sHyDbJsk1c
tqnP8I+sHdBUsiz7NnPf5m2Gf+Dog5CSZVm3mes2X+r20/9APX2jtG03PLBtlm2buW1zRvD4jSLg
A91mWbeZ6zYXhA/fKAI90G2WdZu5bnOd0o9bU+AHxs2ycTM3brYp//hGEfiBdLMs3cylmx3xgwuD
wA6Em2XhZi7cHBN2cF8Q8IFwsyzczIWb2wz/yMEHvs2ybzP3be4T+vG2sJ8e9I6syLotXLdlm9CP
lwWBHui2yLotXLclTegPHHtQNrIi67Zw3Rao29OhlQNqRlZk2RYu21Jm8Id2DogYWZF1W7huS53y
H1g6IF1kRbZt4bYtNsM/tHWAbOVikRUu2+Iz/ENrB/hWDhhZ4b4tMcM/cvSBbuWYkRWu23PN6AEX
v08efmE3NLCsHDSywi17Lhp9gx7eJQI2iBqZHDWyyvV6rhp9w759jyjUQKty18gq1+o5bHRDfbUZ
FW5gVDlwZJUb9Vw4uuG+en8o3ECmcubIKpfpuXP0jfv6EqAwA4HKpSOrXKDn1NEV87X7FWwgTrl3
ZJWL8xw8usZePdjAl3L0yCr35bl6dEV9ZXqFGmhSTh9Z5Zo8t4+uqK8Er1ADPcoBJKtcj7UB6tVj
DfQoJ5Cscj3WQY+n5RUCKkgmV5DMuBxtQ9DLOwS0kExuIZlxPVqC3ItLBASRTA4imXE7WkbYq1sE
ZJFMziIZzyKZFYS9ukZAFsnkLJLxLJJZRdirRxvoUW4iGW8imX3TY8pt+jx4+LXd6MCRchbJeBbJ
zAE6eiQo8ECVchnJeBnJLAA8eCoo7ECYchvJeBvJrM3Yb1eiQg/MKTeSjDeSzPqM/vbZINCDUJLJ
oSTjoSTzDdAP5lfIgUTlVJLxVJJ5wuSD/hV4oFK5l2S8l2SeJ/DrBx40k0xuJhlvJpkXzH57EVDY
gVTlcJLxcJJ5xey3twGFHahVricZryeZG2Y/cNyBWuV8kvF8kjlS6+nQmgFilQNKxgNK5jFBP7Rn
gFrlipLxipJ5m9EfWDTArHJJyXhJybxP4A9sGpBTMjmnZDynZLFN4A+sGhBUMjmoZDyoZJEm8OtH
HvSUTO4pGe8pWVyo1ecPkN3/1y8QUzI5pmQ8pmRRRnD4/NiPDrQql5SMl5Qs6oiOHh/7yYFU5YqS
8YqShU3IhwW5nx1YVe4oGe8oWfiEfXh47GcHWpUzSsYzShYxso/3gf3cQKhyQsl4QsmiQe7xMrAf
HehULigZLyhZdIy+fNBBP8nkfpLxfpK1DZIP14D95ECkcj7JeD7JWoLkwx1gPznQqFxPMl5PspYh
+fIxB+Ekk8NJxsNJ1oBGTwdWC4gmmRxNMh5NslYx+IHdAppJJjeTjDeTrNmEfX25AIvKxSTjxSRr
jtEPbBcgUTmYZDyYZC0w+oH1AjwqJ5OMJ5OsNYy+ftSBRuVikvFikrVvGv36T0sf3xcl7wUHwSST
g0nGg0nWtxEcvS8EdKBRuZdkvJdkPY3o4H0hkAONyrUk47Uk63lCfrsZBXZgUrmYZLyYZL1M2G/f
FwI7kKmcTDKeTLJeR/bhEiBwA5HKwSTjwSTrBrmHO4CADkQqF5OMF5OsO0ZfP+jAo3IxyXgxyXpA
8tsbgEAONConk4wnk6w3SH57ARDIgUblZpLxZpL1DslXj7mDYJLLwSTnwSTfgEZP66vFQS7J5VyS
81ySbwmDr+8WB70kl3tJzntJvuUJuy+jF4BeZPTC0QtGX94uDoJJLgeTnAeTfKsYfXm9OMgluZxL
cp5L8s0w+vpRd0DuMrlz8m8a/frPDx/fF153gwcADxk8OHiM4Oh9IaA3gN5k9MbR24gO3hcCeQfk
XSbvnLxPyG834352UEZyuYzkvIzkaZuw374vBHYgUzmL5DyL5CmN7MMlQOAGIpWDSM6DSJ4y5B7u
AAI6EKlcQ3JeQ/JUMPr6QQcelUtIzktIniokv70BCORAo3IGyXkGyZNB8tsLgEAONCo3kJw3kDw5
JF8/5kCjcvzIefzIE9Do6chqARKVs0fOs0eeGgY/sluARuXmkfPmkac+YV9eLqB35HLvyHnvyPOG
0de3C4gduRw7ch478pww+vp6Aakjl1NHzlNHnjNGXz7qoHLkcuXIeeXI8zeNzv98RtuNDRwq542c
54081wEbPS72gwOFyl0j510jzzaAg6fFfm4gULln5Lxn5Nkx9+1K3E8ODCrXjJzXjDwHJr99Vuwn
BwqVQ0bOQ0ae20A+mH8/NZCnHDByHjDy3BH1oP3d4KBd5HK7yHm7yMsGwVcPOKgWuVwtcl4t8pIQ
963w93MDacrBIufBIi8Zcd/afj83UKbcKnLeKvJSEPfy8QbKlBNFzhNFXkZlntbXCUgTuZwmcp4m
8mIQ+8A+AcqUq0TOq0ReHJMvLxRgTLlH5LxH5CUg+PpGAcKUU0TOU0ReGgRfXynAmXKOyHmOyEuH
4KtHHPSIXO4ROe8R+blHdJrGn077/1i6gyCRy0Ei50EiPweJTk/knyRwoEy5SOS8SOTnItFpHoCS
uIEy5SKR8yKRn4tEp6cSUBI5sKbcJXLeJfJzl+j0VARKIgfilNNEztNEfk4TnWYZKIkaSFNOEzlP
E/k5TXR6IgQlgQNpynUi53UiP9eJTvMUlMQNnCn3iZz3ifzcJzrNY1ASN1CmnChynijyc6LoNM9B
KdygUuRypch5pchtQ9yrxxtEilyOFDmPFLmNyjytrxMQKXI5UuQ8UuSWIfb6PgGdIpc7Rc47RW4F
k68uFFAqcrlU5LxU5FYh+PJGAbEil2NFzmNFbgbB11cKcKacKnKeKnJzCL58xIEy5UqR80qR24Uy
p3mok/QHyx1kilzOFDnPFLk1BA+fEQo+0KfcKXLeKXLrCB89JgR60ClyuVPkvFPkvk3phwWp8AOb
yrUi57Ui9zTlHx4WCj/Qqhwsch4scs+If7wPKOxArHKwyHmwyL1M2MdLgYIP9Co3i5w3i9zrDP/I
wQeOlatFzqtF7jahH64HCj0QrRwuch4ucvcJ/XBHUOiBbuV2kfN2kXtM6I8ce6BbOV3kPF3kDnV7
OrZygGzldJHzdJF7n8Ef2jmgXuRyvch5vchjm/IfWDqgX+Ryv8h5v8gjzfCPbB2QMHI5YeQ8YeSR
Z/hH1g4IGbkcMnIeMvIoM/wjRx/oVm4ZOW8ZeVzq1p94ovhudOBaOWbkPGbkYQAdP1D2wwPVyjUj
5zUjDwfw8Hmynx2IVq4ZOa8ZecSMfVyX++mBaeWmkfOmkUeb0Y9Pk/30QLVy1sh51sijA3pwS9hN
DrJGLmeNnGeNvG2YHFwR9sMDxcplI+dlI29pAr9+4EHbyOW2kfO2kbeM2cfLwX52IFc5b+Q8b+St
YPbxZrCfHahVLhw5Lxx5q5j9wHEHapUDR84DR96QWk+H1gwQqxw4ch448uYT9EN7BqhVbhw5bxx5
ixn9gUUDzCpXjpxXjry1CfyRTQPEKoeOnIeOvPUJ/IFVA2JHLseOnMeOvG8T+PUjD2pHLteOnNeO
vF+odZaYOkl/eB3kjlzOHTnPHXnPAB2+QAR4oFa5d+S8d+S9AHj0AhHYgVrl3pHz3pH3OmMf9qRA
D+wqV4+cV4+824x+eIEI9ECwcvjIefjIuwP68WogkAO5yuEj5+Ej74HJx5uBAA/kKrePnLePvLcJ
/IEDD9wq14+c14+8d8w+3At2swcIIIUcQAoeQIptw+zDtUBgT4A9yeyJsyfM3tbRM0DPMnrm6Eit
pwNrJkACKeQEUvAEUmxlgn5gzwSoIIVcQQpeQYqtzuh9Hd4AvMnwxuFtAn9k0ziAdxneObxP4I+s
mgDwIcMHh48J/IEj3wB7k9kbZ79Q6yxCdVL+eHuAIFLIQaTgQaTYOkCHL5D98KCIFHIRKXgRKdIG
4NELRGAHapWLSMGLSJHSjH3YkwI9sKvcRQreRYqUZ/TDC0SgB4KV00jB00iRCqAfrwYCOZCrnEYK
nkaKVDH5eDMQ4IFc5TpS8DpSJJvAHzjwwK1yHyl4HymSY/bhXiCwA7XKiaTgiaRIgdmHa4HADtQq
V5KCV5IiNcx+4LgDtcqRpOCRpEhIracjawZEkkKOJAWPJEXeJuhH9gzoJIXcSQreSYqcZvTriwaU
kkIuJQUvJUXOE/gDmwbEkkKOJQWPJUUuE/gDqwYkk0JOJgVPJkWuE/gDRx6oVa4mBa8mRb5Q6xN/
TqTtBgdelbNJwbNJkX0Eh8+P/ehAq3I3KXg3KXKM6OjxsZ8cSFXuJgXvJkVuE/JhQe5nB1aV60nB
60mR+4R9eHjsZgcBpZADSsEDSlG2kX28D+znBkKVA0rBA0pREuQeLwP70YFO5YZS8IZSlIzRlw86
qCiFXFEKXlGKUiD5cA3YTw5EKoeUgoeUolRIPtwB9pMDjcotpeAtpSgGydePOdConFIKnlKKAjR6
OrJagETllFLwlFKUwOBHdgvQqFxTCl5TitIm7OvLBVhU7ikF7ylF6Rh9fbuApFLISaXgSaWoG0Zf
Xy8gqxRyVil4VilqwujLRx10lULuKsVNV+kHRP6o0U9vitvnxb+9fffbm799of/0RQT/A4IHJpXj
SnETV4LwZYC/eGIs4wOdyoWluCksQfw64H97ZizTA6XKlaW4qSxBesP0j0tymR+YVe4txU1vCfI7
5n98bizzA8HK2aW4yS5B/hj4z/eCZXYgWDm9FDfpJcjeEPv5arCMDyQrF5jipsAE8TvEP3bwQYcp
5A5T3HSYEP25w3RN/3hBWKYHqpVzTHGTY4L0CdE/3hGW6YFu5SpTGNetZUR/7NiDMFPIYaYwrlsb
dXs6unJAnCnkOFMYl61VCH9054BGU8iNpjCuWzPMf3DpANvKpaYwbltziH906wDZysGmMC5bC4h/
dO0A38rJpjDuW2sQ/+DRB7qVi01hXLfnYtOXu/1Tr5Qvv2PvACDaFHK0KZwb9xxtuhpg8lIRRwDa
lbtN4Vy7527T1Qj4tSJOANQrl5vCuXrP5aZxArBDxRmAgeWCUzg38LngNM4AXi3iDEDEcsYpnIv4
nHG6mgFdI0R+IGI55BTORXwOOd3yo5uEOAKQsVxzCucyPtechhEO/yAAH8tFp3Du43PR6XYCcJ8Q
JwBKlrNO4VzJ56zT7QTgSiFOALQst53CuZa94wmO/hiAuFPIcacIruVAWj4dX0Ug7xRy3imCSznS
ZIDjuwg0nkJuPEVwLUeezXB0GYHOU8idpwhu5SiTEQ5vIxB7Cjn2FMGlHHUywuF1BKJPIUefIriX
wyYjHP5RAFqWy08RXMvn8tPnC91Tz5zPv2E3PnCyHH+K4E4+x58u8SePHG0AoGS5/xTBlXzuP10O
gJ84Gj8QslyAiuBCPhegBn6wSqUJQAkq5BJUNG7kcwlqmAA8b7QJgJLlHFQ0ruRzDupyAnSj0OiB
jOUgVDQu43MQ6oYeXSe0AYCK5SpUNK7icxXqdoCjPwDAw3IZKhr38LkMdcMPLhIaP5CwnIeKxiV8
zkPd8INbhMYPFCw3oqJxBTeH/EePP1CwHImKxhXcgIJPx9cPELCciYrGBdwaxj++f4CC5VZUNK7g
1icTHFxAoBcVci8qOjdw3/AARzcQiEaFHI2KzgXcEx7g6AoC6aiQ01HRuYN7xgMc/BEA9aiQ61HR
uYL7pYLHcPAwAA6PwRGAheWIVHRu4V7RCE+9ZYQhgIrlllR0ruJuaIgn3jPCDEDHclEqOtdx9+kM
s40qTAGsLNelonMr95hOMXvXCFMAOcuZqehczr2hKaaXC2ECIGc5NhWdy7n3yQTT+wUb4n/++f+1
A2YtiCUBAA==
T_EOF
echo "payload bytes: $(wc -c < "$ROOT/table.json")"
python3 - "$ROOT" <<'PY_EOF'

import json, os, re, shutil, subprocess, sys, time

ROOT = sys.argv[1]
T = json.load(open(os.path.join(ROOT, "table.json")))
LANG = T["language"]
PROBES = T["probes"]
OUT = T["out"]
out = open(OUT, "w")
WORK = os.path.join(ROOT, "u")

# --- verbatim delimiter codec, copied from verbatim_diag.py ---
def esc(text):
    """make `text` safe to place in one pipe-delimited field, reversibly."""
    for raw, rep in _ENC:
        text = text.replace(raw, rep)
    return text

_ENC = [('\\', '\\\\'), ('|', '\\p'), (';', '\\s'), ('\n', '\\n'), ('\r', '\\r')]
MARKER = '#verbatim-escape v1'
out.write(MARKER + '\n')


print("op lane %s: %d candidate probes" % (LANG, len(PROBES)))
sys.stdout.flush()


def sh(cmd, cwd=None, timeout=180):
    try:
        p = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE, timeout=timeout)
        so = p.stdout.decode("utf-8", "replace")
        se = p.stderr.decode("utf-8", "replace")
        return p.returncode, so, se
    except subprocess.TimeoutExpired:
        return 124, "", "TIMEOUT after %ds" % timeout
    except OSError as e:
        return 125, "", "OSError %s" % e


# ------------------------------------------------------ objdump reading

LABEL = re.compile(r"^([0-9a-f]+)\s+<(.+)>:\s*$")
INSN = re.compile(r"^\s*([0-9a-f]+):\t(.*)$")
RELOC = re.compile(r"^\s+([0-9a-f]+): (R_\S+)\t(.+?)\s*$")


def extract(text, sym, exact):
    """the two columns for one symbol.

    bytes  every byte objdump printed, in order, flattened
    mnem   the instruction text, with objdump's own trailing `# ...`
           comment dropped -- that comment is arithmetic objdump did
           for the reader, not part of the instruction.  A relocation
           is appended to the instruction it applies to as
           ` !!reloc=<type>:<symbol>`, because in an object file the
           call displacement is literally zero and the callee's name
           lives only in the relocation.
    """
    lines = text.splitlines()
    k = -1
    for idx, ln in enumerate(lines):
        m = LABEL.match(ln)
        if not m:
            continue
        lab = m.group(2)
        hit = (lab == sym) if exact else (sym in lab)
        if hit:
            k = idx
            break
    if k < 0:
        return None
    raw = []
    mn = []
    for ln in lines[k + 1:]:
        if LABEL.match(ln):
            break
        m = INSN.match(ln)
        if not m:
            r = RELOC.match(ln)
            if r and mn:
                mn[-1] = "%s !!reloc=%s:%s" % (mn[-1], r.group(2), r.group(3))
            continue
        parts = m.group(2).split("\t")
        bs = parts[0].split()
        raw.extend(bs)
        txt = parts[1] if len(parts) > 1 else ""
        txt = txt.split("#")[0]
        txt = " ".join(txt.split())
        if txt:
            mn.append(txt)
    return raw, mn


def disasm(obj, sym, exact):
    rc, so, se = sh(["objdump", "-dr", "--disassemble=" + sym, obj])
    got = extract(so, sym, exact) if rc == 0 else None
    if got is None:
        rc, so, se = sh(["objdump", "-dr", obj], timeout=600)
        got = extract(so, sym, exact)
    return got


# --------------------------------------------------------- DWARF reading
#
# objdump --dwarf=info prints one entry per line block:
#
#   <1><2d>: Abbrev Number: 2 (DW_TAG_subprogram)
#      <2e>   DW_AT_name        : op_12
#   <2><4a>: Abbrev Number: 3 (DW_TAG_formal_parameter)
#      <4b>   DW_AT_name        : a
#      <52>   DW_AT_location    : 2 byte block: 91 7c (DW_OP_fbreg: -4)
#
# The leading <N> is the tree depth.  A formal parameter one level
# below the matching subprogram is a parameter OF that subprogram.

DIE = re.compile(r"^\s*<(\d+)><[0-9a-f]+>:\s*Abbrev Number:\s*\d+\s*\((\S+)\)")
ATTR = re.compile(r"^\s*<[0-9a-f]+>\s+(DW_AT_\w+)\s*:\s*(.*?)\s*$")


def clean(text):
    text = " ".join(text.split())
    return text


STRPREFIX = re.compile(r"^\((?:indexed string|indirect string)[^)]*\):\s*")


def dwname(text):
    """objdump prints a string attribute as `(indexed string: 0x5): a`.
    The parenthesised part is objdump telling the reader WHERE in the
    string table it found the name; the name is what follows.  Keeping
    the prefix would have put objdump's bookkeeping into the parameter
    name column."""
    return STRPREFIX.sub("", text.strip())


def dwarf_params(text, sym):
    """[(name, location)] for the subprogram named `sym`.

    More than one subprogram can carry the name.  swift's `@_cdecl`
    emits a C-entry thunk beside the real function, and the thunk has
    no DW_TAG_formal_parameter children at all, so the first match is
    not always the one holding the parameter table.  Every match is
    collected and the first one that actually has parameters wins."""
    lines = text.splitlines()
    depth = None
    tag = None
    attrs = {}
    entries = []
    for ln in lines:
        m = DIE.match(ln)
        if m:
            if tag is not None:
                entries.append((depth, tag, attrs))
            depth = int(m.group(1))
            tag = m.group(2)
            attrs = {}
            continue
        a = ATTR.match(ln)
        if a and tag is not None:
            attrs[a.group(1)] = a.group(2)
    if tag is not None:
        entries.append((depth, tag, attrs))

    hits = []
    for idx, (d, t, at) in enumerate(entries):
        if t != "DW_TAG_subprogram":
            continue
        names = []
        if "DW_AT_name" in at:
            names.append(dwname(at["DW_AT_name"]))
        if "DW_AT_linkage_name" in at:
            names.append(dwname(at["DW_AT_linkage_name"]))
        for nm in names:
            if nm == sym or sym in nm:
                hits.append(idx)
                break
    if not hits:
        return None
    best = []
    for k in hits:
        base = entries[k][0]
        got = []
        for d, t, at in entries[k + 1:]:
            if d <= base:
                break
            if d != base + 1:
                continue
            if t != "DW_TAG_formal_parameter":
                continue
            nm = clean(dwname(at.get("DW_AT_name", "(unnamed)")))
            loc = clean(at.get("DW_AT_location", "(no location)"))
            got.append((nm, loc))
        if got:
            return got
        best = got
    return best


def dwarf(obj, sym):
    rc, so, se = sh(["objdump", "--dwarf=info", obj], timeout=600)
    if rc != 0:
        return None, "objdump --dwarf=info rc=%d" % rc
    got = dwarf_params(so, sym)
    if got is None:
        return None, "no DW_TAG_subprogram named %s" % sym
    if not got:
        return None, "subprogram %s has no DW_TAG_formal_parameter" % sym
    return got, None


# ------------------------------------------------------------ compiling

GOMOD = "module opprobe\n\ngo 1.26\n"

CLANG = "/usr/bin/clang"
CLANGXX = "/usr/bin/clang++"
SWIFTC = "/persist/swift/usr/bin/swiftc"


def compile_probe(p, d, mode):
    """(rc, artifact path, diagnostic text)."""
    if LANG == "c":
        src = os.path.join(d, "unit.c")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANG, "-std=c17"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "cpp":
        src = os.path.join(d, "unit.cpp")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANGXX, "-std=c++20"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "rust":
        src = os.path.join(d, "unit.rs")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        if mode == "anchor":
            opt = ["-C", "opt-level=0", "-g"]
        else:
            opt = ["-C", "opt-level=1", "-C", "debug-assertions=off"]
        cmd = (["rustc", "--crate-type=lib", "--emit=obj"] + opt
               + ["-o", obj, src])
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "go":
        open(os.path.join(d, "go.mod"), "w").write(GOMOD)
        open(os.path.join(d, "main.go"), "w").write(p["source"])
        obj = os.path.join(d, "bin_%s" % mode)
        cmd = ["go", "build"]
        if mode == "anchor":
            cmd.append("-gcflags=-N -l")
        cmd.extend(["-o", obj, "."])
        rc, so, se = sh(cmd, cwd=d, timeout=300)
        return rc, obj, (se or so)
    if LANG == "swift":
        src = os.path.join(d, "unit.swift")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-Onone", "-g"] if mode == "anchor" else ["-O"]
        cmd = [SWIFTC] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd, timeout=300)
        return rc, obj, (se or so)
    raise KeyError(LANG)


DIAG = re.compile(r"^[^\s:]+:\d+(:\d+)?:")


def firstline(txt):
    """the compiler's own words for why it refused.

    The first line is not reliably the reason.  clang leads with a
    warning and puts the error underneath.  go leads with a banner
    naming the package -- `# opprobe` -- and its diagnostics never
    contain the word `error` at all, so a rule that only looked for
    that word recorded the banner and threw the testimony away.
    Three passes, in order: a line saying `error`, a line in the
    `file:line:col:` diagnostic shape, then the first line that is
    not a banner."""
    lines = []
    for ln in txt.splitlines():
        s = ln.strip()
        if s:
            lines.append(s)
    for ln in lines:
        if re.search(r"\berror\b", ln, re.I):
            return ln[:200]
    for ln in lines:
        if DIAG.match(ln):
            return ln[:200]
    for ln in lines:
        if not ln.startswith("#"):
            return ln[:200]
    if lines:
        return lines[0][:200]
    return "(no diagnostic)"


def write_unit(n, build, obj, sym, exact):
    got = disasm(obj, sym, exact)
    if got is None:
        rc2, so2, se2 = sh(["objdump", "-t", obj])
        near = 0
        for l in so2.splitlines():
            if sym in l:
                near += 1
        out.write("op_%d|%s|NOSYM|%s\n"
                  % (n, build, esc("symbol %s absent, %d near matches"
                                   % (sym, near))))
        return False
    raw, mn = got
    out.write("op_%d|%s|OK|%s|%s\n"
              % (n, build, " ".join(esc(x) for x in raw),
                 ";".join(esc(x) for x in mn)))
    return True


t0 = time.time()
tally = {"REFUSED": 0, "ACCEPTED": 0, "ANCHOR_OK": 0, "SHIP_OK": 0,
         "DWARF": 0}

for k, p in enumerate(PROBES):
    n = p["n"]
    sym = p["symbol"]
    exact = p["symbol_exact"]
    d = os.path.join(WORK, "n%d" % n)
    shutil.rmtree(d, ignore_errors=True)
    os.makedirs(d)

    rc, obj, err = compile_probe(p, d, "ship")
    if rc != 0 or not os.path.exists(obj):
        out.write("op_%d|REFUSED|%s\n" % (n, esc(firstline(err))))
        tally["REFUSED"] += 1
        out.flush()
        shutil.rmtree(d, ignore_errors=True)
        continue
    tally["ACCEPTED"] += 1
    if write_unit(n, "SHIP", obj, sym, exact):
        tally["SHIP_OK"] += 1

    rc, aobj, aerr = compile_probe(p, d, "anchor")
    if rc != 0 or not os.path.exists(aobj):
        out.write("op_%d|ANCHOR|BUILDFAIL|%s\n" % (n, esc(firstline(aerr))))
    else:
        if write_unit(n, "ANCHOR", aobj, sym, exact):
            tally["ANCHOR_OK"] += 1
        rows, why = dwarf(aobj, sym)
        if rows is None:
            out.write("op_%d|ANCHOR|NODWARF|%s\n" % (n, esc(why)))
        else:
            joined = ";".join("%s=%s" % (esc(a), esc(b)) for a, b in rows)
            out.write("op_%d|ANCHOR|DWARF|%s\n" % (n, joined))
            tally["DWARF"] += 1
    out.flush()
    shutil.rmtree(d, ignore_errors=True)

    if (k + 1) % 25 == 0 or (k + 1) == len(PROBES):
        el = time.time() - t0
        print("[progress] %s [%d/%d] elapsed %.1fs mean %.2fs  "
              "REFUSED %d ACCEPTED %d SHIP_OK %d ANCHOR_OK %d DWARF %d"
              % (LANG, k + 1, len(PROBES), el, el / (k + 1),
                 tally["REFUSED"], tally["ACCEPTED"], tally["SHIP_OK"],
                 tally["ANCHOR_OK"], tally["DWARF"]))
        sys.stdout.flush()

out.close()
print("done: %s -> %s" % (json.dumps(tally), OUT))

PY_EOF
echo "--- lane finished, rc=$?"
date -u +%Y-%m-%dT%H:%M:%SZ
