#!/bin/sh
# op-pipeline lane -- c -- generated by
# Research/op_pipeline/lane_gen.py .  Do not hand-edit.
# steps 1b/2/3: compile-or-refuse, then the ANCHOR and SHIP
# builds of every probe the compiler accepted, then objdump
# extraction, then the anchor's DWARF parameter table.
set -u
export HOME=/work
export PATH=/persist/swift/usr/bin:$PATH
export GOTOOLCHAIN=local
export GOPROXY=off
export GOFLAGS=-mod=mod
ROOT=/work/regen_c_c0031
export GOCACHE="$ROOT/gocache"
export GOPATH="$ROOT/gopath"
# swift's binaries want libncurses.so.6 and the image ships
# only libncursesw.so.6.6; the symlink lives in the image's
# own /usr/lib and does NOT survive a container restart.
if [ -f /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 ]; then
  ln -sf /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 \
     /usr/lib/x86_64-linux-gnu/libncurses.so.6 2>/dev/null
  ldconfig 2>/dev/null
fi
echo "=== op pipeline -- c -- 400 candidate probes ==="
date -u +%Y-%m-%dT%H:%M:%SZ
# refuse in seconds rather than in an hour
if ! /usr/bin/clang --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: /usr/bin/clang is not runnable in this container."
  echo "!! tried: /usr/bin/clang --version"
  exit 4
fi
/usr/bin/clang --version 2>&1 | head -2
if ! objdump --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: objdump is not runnable."
  exit 4
fi
objdump --version 2>&1 | head -1
rm -rf "$ROOT"; mkdir -p "$ROOT" "$GOCACHE" "$GOPATH"
df -Pm /work | awk 'NR==2{print "free /work: " $4 " MB"}'
FREE=`df -Pm /work | awk 'NR==2{print $4}'`
if [ "$FREE" -lt 400 ]; then
  echo "!! REFUSING TO START: only $FREE MB free on /work, need 400"
  exit 3
fi
base64 -d <<'T_EOF' | gunzip > "$ROOT/table.json"
H4sIAAAAAAAC/8Wd3Y4cR3KFX2VA32gXu6v8i4hM2zBgX+wL+NI0BiRF/QDUDEGR8AqC3t0zJJfN
rjhZ3acwGdKFpB2VuIrD7IivCxn4fnv25sXdDx9e/PD62b/ePHv17C83z+4/vH/8+28f/vrtu9c/
vL67fXX7KqWa//b+H+8fH3j77v7l618envmf357dPfwll5bSw89/+fXnl/dvHv/d+7e3H3/47MtP
b1//48Wrx1/3/bsPrx9/ev/h3auP/5/f/vnm4y/46Ze5+etfb17+dPfi3a833978+dvnd//y092r
Nx++e33z77+8/+6nu/d/+/E/Nj98eX//5uNPn9/d3r7/9e3r++9vb7/55pcf79+9/9Nv6feHX+ib
N/d3P9zc/v3dw3/D44/+9Pzun/+Jn567efGXm6+euXn58MRvz+9uHv549/r9h3d3Ny8efpmX//b8
7vfnd89+/8vNqfKMKs905Xll5d/df3j55vV55XlT+adnmMoLqrzQlZeVlT/+6bzusqn745+Iqiuq
utJV10VVf/kfp4rrqeJPf0NU21C1ja62raz25vY/X7368PN50W1b9KeHmNoF1S507bK2dtDUxNVO
dzVFtStdu66q/acf7l5/d/PqxxfvzkvXr0o/PcNUbqhyoyu3tZU//PvnhZsr/OERpu6O6u503X1t
3b6fd1c429EHqnzQlY/1lYPyBy6fzCAjfss0v+W0NgM/3HJy9bMzLiOCyzTB5VUE9+Huc2FgzOWv
KG7zHJMAIrlMk1wuyxPwwy4XlAA77zKiukxTXa6rE3ATL1dQPznzMqK8TFNebqur30693EDx3NzL
iPIyTXlZVtfuWn8WUDzb9xHnZZrzskZUDxugzkLguyAiv0yTX7aYLEArtGkWdD9ENJhpGsw9JAv/
0eizJNjPB2LDTLNhHqtzAGQ0QAYsGxXEhYXmwpJC6kcNoqRpDHSHKIgUC02KJQel4VtEyfM02B5R
EDUWmhrLKmr8v0cKut3U/xUtfv7nTMWIEgtNieWpKfGrc/9YOPoU1LMnH8vnTz+ixEJTYmmLq/+v
h2fPi2+++MeHmNoRJRaaEossrv3vb+5fvM96Xr748j8/xySASLHQpFh0dQK+5ymon+11iA0LzYbF
Flf/3y/wEDQfwelRJgfEhYXmwtIjcgBHoU9yoM8D4sJCc2EZATnMvjqVgcM49u2pIlKsNCnWFJaI
Px417SXCnpGKaLHStFhzQCJTfK4ZR3KQoCtixkozYy1xmYBjUnYzoc8JospKU2WtAZnsvYuuFcdy
/L10RcRZaeKsLTQZcGDapWToM4N4tNI8WiUymdkgqnIhnoMTCRFrpYm1anxG4AjpVRnR5whxbaW5
tlpkRvNhZRdCOjq1EPVWmnpr/wNSAkepX5cSfZYQE1eaietqJr59+f3mG3IFJPzxKaL6hvi30fzb
VvPv7fcfv/qXfpZAA+T75UkmBcS8jWbelpen8HZzBlpGCbzlzgCi20bTbVtNt7c/vfzZnQAAtZ+f
YxJALNtolm11eQJ3jyd783a4VZTB5yeZFBC3Nppb22puvf2AYwC4enqUyQFRaqMptS2m1JfbF8bN
A+lL7n1xQ+zZaPZsi9nT3SZpHjPJuyQNEWWjibLZ+sqzbg++weofn2MSQLTYaFpsfX0CtWwT6DCB
x+eYBBAJNpoE21ifgOt9AwbA9T1BLCg0C8piFgRbIeI5kN4LEcSAQjOgLGbAj3R7XrxHwI8PMbUj
AhSaAGUxAf744s3356V7+nt8hqkckZ/Q5CeLyW97g1A88nH3BwWxntCsJ4tZz12REg955N0oQXQn
NN2JrK8cvSwSwQHQb4cEsZ7QrCcakYN/HSQ6yYF9/yOI/IQmP7GAHNDoM5wDP/8Q/wnNf9IDcvBt
oeMU2N6ACFBoApTFBOhvTYrnP/bOpCL6U5r+NAXUjhqjpkkEdGdURIJKk6DmkCR8a9Q8S4LtjYq4
UGku1MVcOFsyUY+HxzZNFFGi0pSoNSSHLSxqncXAMaMiZlSaGbWFpOBmhLZZDOSUUESQShOkSlgO
IAzZDYNNBLGk0iypGpKIH5+qszToKYpoUmma1MU0uXchRj1RHr8Lo4gqlaZK7VF5gHHad/KgJyoi
TKUJU0dQHn6mjnka5FQ1RJxGE6eloCy2c9XSPApushoiTqOJ03JQEm6cWJ5HQc4SQ8xpNHNaCcwC
tVErFyKhe6khCjWaQq2GJuMbqtVLybBd1RCZGk2m1iKT8R+idiEX9pOEONVoTjUJSsVzmck8EZbM
DDGq0YxqGpkGbCx6KRS+syBqNZpazWKzAa3FLmZD9xZEsEYTrC0mWLQ2ap5c+e1RQ8RqNLHa0xPr
l9/+yfaojbMnD22PdsSonWbUnhZX77ZHe/LFk9ujHVFpp6m058W1o+3Rnn35/PZoRyzaaRbtZXUC
rhH2AuonO19HvNlp3ux1cfWT7dFefQSHtkc7ostO02VvETmAo9AmOdDnAfFkp3myS0AOs29lXXAY
x76RdcSUnWbKrmGJgOOhe4nQZwSRZKdJsltAIlPC7oYjOUjXHRFkpwmy97hMwDHpu5nQ5wRRZaep
so+ATPZelveBYzn+xnwg4hw0cY4Umow/MCNdSoY9MwPx6KB5dOTIZGaDaOQL8RybSAMR66CJdZT4
jMARKldlRJ8jxLWD5tpRIzOaDqtRL4R0cGoNRL2Dpt7R/oCUwFFq16VEnyXExINm4rGaif326AAk
zG6PDsS/g+bfsZp/8fboAOR7ZHt0IOYdNPMOW57Cdnt0GEqA2x4diG4HTbdjNd2i7dEBoJbfHh2I
ZQfNsmMsTwCtTY6BMqC3JgW5dIR26Uhaza14e1QSwNUj26OCzDpCm3UkLabU7faoJA+k3PaoILOO
0GYdSYvZc3ulRZLHTO4miyC7jtB2HUl1feXb7VFJFVbPbY8KMu4IbdyR1NYnsN0eldRgAtz2qCDv
jtDeHUmyPgHX+wQGQPY9RfUrXf9iFvQrNJI8B7LbM4L8O0L7dyQtZkC3PSrJIyC5PSrIwSO0g0fS
YgLcbo9K8vTHbY8KcvAI7eCRtJj8NhcXJXnko+4rCvLuCO3dkbyY9bY3rCR7yOPuVAmy7ght3ZGc
11cOXhZJzjgA9u2QIPeO0O4dySUiB/c6SHKZ5EC+/xFk4BHawCO5BuQARl+uOAd6/iEXj9AuHskt
IAffFhpOge0NiABpJ4/kxQTorllK9vxH3q4UZOQR2sgjWQNqh41RJxHwnRGRIO3jkWwhSYDWaLMk
6N6IuJC28UhezIWTTRfJHg8P7bkIsvEIbeORPEJy2MJiHrMYOGZETh6hnTxSUkgKbkaUNIuBnBLI
xiO0jUdKDssBhJF3w2ATQSxJG3mklJBE/PgsZZYGO0WRqUdoU4+UxTS5cyFGiifKw3dhBLl7hHb3
SGlRefhxWtpOHuxERT4foX0+UiQoDzdTi8zTIKcqMvsIbfaRokFZbOdq0XkU5GRFxElbfqRYUBJ+
nNg8CnaWIOakTT9SemAWsI32C5HwvRRRKO3+kTJCkwENdVxKhu2qyAEktANIaopMxn2IarqQC/lJ
Qh4goT1AUnNQKp7Lap4nwpIZMgAJbQCSWiLTQI2llkuh0J0FmYCENgFJrbHZ+NZS68Vs6N6CCJZ2
AUldTLBge1SqJ1d6e1SQ8Udo4488qfHnnE3x8qg82n2+4tIDu6OCTD5Cm3zkSU0+oPbt6qg8Sns2
pXObo4L8PEL7eeRJ/TygcrA4Ko8ynk3x9N6oIPOO0OYdeVLzDqrfd8Duq2c7HuJM2qcjT+rTAbXj
pVF5dOpsAjiyMyrIqyO0V0ee1KszS8Efg0evDkqBPQvIqyO0V0ee1KszSWH2RexRsAOiOPYdDJl2
hDbtyJOadnbzAEej7ORBnw9EjrR3R57UuzPJYwrUj/YdEMhBlkYOHqEdPPKkDp79RMARaXuJ0GcE
ESRt45Em6xPZey/eBIZy/N04cvUI7eqRppG5gMOiF3KhzwtiT9rkI80Cc5kOH9sP5+AUQnRKm36k
9fCEwPHp1yREnyHEsLQJSNoITGg+oMZ+RAcnFbIFCW0LEknxGfljJOmqjNhzhJxCQjuFRBbzr1sO
FfHUS+6GCnIKCe0UElnMunA1VMRT7oHNUEF2IaHtQiJ1dQZvt7//FdT/lvv9RyRLG4ZEFpMsWAsV
8QBLb4UK8gwJ7RkSkdX1o21IEZAAvwuJHENCO4ZEFjPqZCVUPJoe2ghFhiGhDUMia4nULYSKg09y
HxQZhYQ2Coms5Ux3R0UcUpI3U5BFSGiLkMhYXrdbBpWBaid3QZFJSGiTkGhaXr9bBdWE6ic3QZE/
SGh/kGheXv+242lG5XPdDjmDhHYGia7lPrALo4756C0Y5AkS2hMkupb3/BKoOtxjd0CRG0hoN5Do
WtpzK6DqSI/cAEUuIKFdQKJrKW9791Ad3nE3DpHvR2jfj+harnNXpNQBHXknCtl9hLb7iNryutGL
IDVYPv3mBzl9hHb6iPaAFPyrHu04BfbdDjL5CG3yER3rU0DDbsAU6ImHHD5CO3zE0voUXDuwBDMg
ewJy9wjt7hFbS3v+dqQ51mPvRCJTj9CmHrGyvnLUDq3gAOh+iLw8Qnt5xGpEDr4hWp3kwHZEZOER
2sIjtpYBZ6sp5lDw2F4Ksu4Ibd0Rk4gUtmBoMgmB40Pk2hHatSOmERn4uaCTENjJgGiRtuqIWVQK
IArbi4LNA3EjbdIR6xF5gIHZJ1nQcxORI23UEVtLjnuXWczR4/F7LMiwI7RhR3oKSsMP0J7mabAz
FDl3hHbuSM8xabgp2vM0C3KOIveO0O4d6SUmie0k7WUaBDdLkYVHaAuP9BqTgxshvU6DIOcH8vAI
7eGR3uKSQM2zt/1A+A6KiJP28kiXyFxAG5ULudC9FFEobeeRroG5+I+P7qfCfoYQk9J+HukWk4mn
sG7TPFgOQ14eob080ntgFrCh9AuR8B0FESpt55E+QpMBLWVcSobtKcjOI7SdR8ZaWkXrnMNRKr/N
iQw8Qht4ZDw9nX7Gr8ky58hfPXdolxN5dYT26sgoSyt3q5yjbAsnNzmRK0doV46MurRutMg56rZ0
fo8TOXCEduDIaGurd31vNFc72+cQU9JeGxmytPLJEueQbfmHdjiR3UZou40MXZ8BOAIKM6DPAeJF
2m0jw5ZnMPu6NQwFceybFnLdCO26kdGD0gDHos/ToM8GokTaeyNjLE9jis5joDiOUbMiA47SBhxN
KSoPdzw0pZ08yPOhyISjtAlHU16ex867bk0ZRXL4fbciS47SlhxNJTAVcFDKfir0WakolUqnUuNS
mQwcTXU3mkOTR5FfR2m/jqYWnQ84Ou2KfOjzIygfofORuHxmQ0mT7AZ0dDopSkjphDQ8IXCE9JqE
6DNkKCGjE1rLum5ZU5MjXHJXU5HBR2mDj6a1XAtXNTU5oj2wqanI5KO0yUfTWJzA2+3v/fDVU3ua
ilw+Srt8NK+lVrCmqdnBKr2lqcjno7TPR3NeXD3YT9Scff30dqIik4/SJh/Na3kUr2hqdhh6ZENT
kcVHaYuP5qX0uV3Q1LwFTW4/U5GzR2lnj+alTLm9YaJ5i4/cvRJFlh6lLT2aZXXV2+VMzQIq53Yz
FXl6lPb0aNbV1W9XMzUrqJ7bzFTk5lHazaPZVlfv+pyB4skehxiPtvFoXsp4flNF85bv2B0VRf4d
pf07mpeynVvK1LxFO3InU5FxR2njjpalZLddydSypTpuI1ORX0dpv46WpUS3uS2oZYty1B1BRQYd
pQ06WpYy3PZqk5YtvHF3mRTZcpS25Wipq6tGL3lKRcXTb3WQIUdpQ46Wtj4D/xqnNJgB+94GWXGU
tuJokeUZgPFWBGVAzzhkw1HahqNFl2fg24CiBNhegMiOduBoWUp27jajli3XkXcYFflulPbdaOnL
64ZNsMPy+S6ICI9222gZASmANjhwCmwfRB4bpT02Wpfy3mRxROsW+w5tjSiy1ihtrdGaAzLYQmDN
OAKOBZGpRmlTjdYSkICbBbXgCMhpgIw0ShtptNagDEAQdScINg3EiLSDRmsLSMOPyNpwEuykRCYa
pU00WpdS4t5FlLolxeN3UJCZRmkzjVaNycKPzKrTLOipiciRdtVotZAs/Ny0WRLs5EQkSTtrtPaQ
HNzs7LMYyOmJSJK212gdISn4sTFmMZAzA/lrlPbXaEthOaCW2dJuHHTfRD4bpX022nJgKr55tryf
CttBkdVGaauNthKXivvgtLKbCfvpQfxJe2201ZBEPHO1OkuDpS7ks1HaZ6OtxSUBG0nbD4TvJIhG
aauNNonMBbQSuZAL3UsQmdJWG21LyRSsV2rbEim9XanIXKO0uUYXmGv+2S7xeqWeNDUf++SB/UpF
ThqlnTS6wElzVvt2wVJP/pkvpXMblopcM0q7ZnSBa+ascrBiqSezzJfi6R1LRR4ZpT0yusAjc16/
630nZ8yperLbIT+M0n4YXeCHOasdr1nqSRLzJYAje5aKTDFKm2J0gSnGpwCOQcEp0GcBMSPtitEF
rhiXwuzr1skacxbFse9ayB+jtD9GF/hjJnmAo9F28qDPByJG2iejC3wyLo8pRp+0MmeBHGRoZJdR
2i6jC+wys0TAEdG9ROgzggiSNs2o2PpE9t50i8FQjr/vRiYapU00Kj0yF3BY+oVc6POC2JM21aiM
wFymw2fsh3NsCiGXjdIuG9UUnpA/PpquSYg9Q8h2o7TtRjUHJjQdUJr3Izo4qZATR2knjmqJzwgc
o3JVRvQ5QvxLu3NUF/OvX79UT73s/iWy5yhtz1FdzLp4AVM95R7ZwEQmHaVNOqqyOoPtCqYKqJ/b
wUQ+HaV9OqqLSRYtYaoHWH4LE3l1lPbqqNrq+tEOohpIgN9BRFYdpa06qosZdbKIqR5ND21iIquO
0lYd1bVE6lYx1cEnuYuJPDpKe3TU1nKmu31iDinJWyfInqO0PUctL6/brWNaRrWT+5jIoaO0Q0et
LK/fLWRaQfWTG5nInaO0O0etLq9/2/GsovK5boeMOUobc9TWch/YWjHHfPTGCvLkKO3JUVvLe34t
0xzusXuZyI6jtB1HbS3tucVMc6RHbmYiH47SPhy1tZS3vVloDu+4G4XIeqO09UZtLde5C1HmgI68
A4UsN0pbbtTG8rrRiyAbsHz6zQ+y2yhtt9GeAlLwr3p6wimw73aQ1UZpq432vD4FMOx6hinQEw8Z
bZQ22mgv61Nw7aAXmAHZE5DLRmmXjfa1tOfvQ3bHeuw9SOSuUdpdo72trxy1w95wAHw/RNRHu2q0
S0QOoCHKJAe6IyIGpN002tcy4GzppDsUPLZzgmw0SttotFtEClsw7DYJgeNDZKFR2kKjvUdk4OdC
n4TATgZEi7RxRvuISgFEMfaiIPNAnhmlPTM6UkQefmCONMmCnZvIOKO0cUbHWnLcu8wyHD0ev8eC
LDRKW2h0lKA0/AAdZZ4GO0ORm0ZpN42OGpOGm6KjTrMg5yjy1CjtqdHRYpLYTtLRpkFwsxRZa5S2
1uiQmBzcCBkyDYKdH4gvaXeNDo1LAjZP3Q+E76CIOGmfjQ6LzAW0UbuQC91LEYXSZhsdPTAX//Hp
+6mwnyHEpLTfRseIyQRQ2JjmQXKYIbeN0W4bSykwC9BQLKULkbAdxZDlxmjLjaUcmoxrKZbypWTI
nmLIdGO06cbSWloFy5yWHKXS25yGjDZGG20sraHTCyudlqp7+shepyFvjdHeGkstIIXtcqelhkPg
NjwNuWmMdtNYkoAMwJqnJcEx0Luehhw0RjtoLGlEEr5D6iQHti8aSsHoFCwgBbz6aclwFEf2Pw3Z
Z4y2z1jqUXmAo9F38qDPx0B5DDqPEZTH5MubpTEP5dC3N0OuGqNdNZZTaDL+uOR0KRn2zCCPjdEe
G8s5KJkpoOc8j+YgoSPDjdGGG8slNhtwbMrFbOhzgyiVNt9YrkHZ7Lxpt1zn8Rx+527IkmO0Jcdy
C08IHKB2TUL0GUJ8Sxt1LEt0QrPBleWKmA5OMETAtH/Hsv4xWYEjpVdnRZ8rxMm0rceyRWc1H252
RVhHpxyiaNrvY7n/QWmBo9WvT4s+W4ixaSeQ5QjGdiunlidkTe6dGjIEGW0IshLB03D51MqEpA9s
oBoyBxltDrKSQ9LYrKFaybMk3nJnAtEy7RKyEkHLYCHVygSS6a1UQ34ho/1CVmpIEmAr00qdZUFv
ZhoyDRltGrISwcF4SdXKBH+PbKoasg4ZbR2yEkC923VVKxhwuZ1VQ84ho51DVgJYdnv3xgrGVu7e
jSHrkNHWISsWk8B2hdWKTVPg9lgNeYiM9hBZ6TFJbJdZrfRpEtxGqyEXkdEuIisjJgnXI8c0CK4/
IhuR0TYiqwFs6Xd+rGKuZHd+DPmIjPYRWQ1gSrfqahUjJbnvashIZLSRyGoAUW6XXq1imuQ2Xw35
iIz2EVkNIMnN3UyrGCGpe5mGDERGG4isBrDj9lKZVQyN3F0yQ/Yho+1DViUmAfTyqso8CPptFTIQ
GW0gsqpRefjXU1V38mDfRyELkdEWIqsWlAcamTbPg5+biCdpG5HVHpSHbxt9ngbbOxBR0k4iqwFE
6e6gWsU8yd4/RT4io31E1lJQBqiBtrQTBd1BkYvIaBeRtRyWiG+hLe8lwvZQ5CEy2kNkLYAzJytB
1jBuHtoKMmQhMtpCZK2G5bGFz1b34uAYFJmIjDYRWWthabiZ0tpeHORUQQYiow1E1iQ0DxCKXAyF
TQaxKe0gsqZhyfix23QvFXr6IjqlzUTWAuh074JQw4R6/G4QshYZbS2y1iNzAWO4X8iFnsSIWGmn
kbURmIufxWM/FXIaI8+R0Z4jkxSYyXYeS9qPhJvIyH5ktP3IJAcm4saP5P1IyNmDXEhGu5BMSnAm
qN1KuSIauuciT5LRniSTGp6Qb7xSr0mI7b7InGS0OcmkRSfkP1ztinzYTxjiXtqjZCKB6Xi+E9lP
hiU85FIy2qVkotGpwMaj14TDdx5EwbRdycTiMwKtx67KiO49iIhp05JJABGjxV/BJMxv/yKzktFm
JVtgVvrSSyabvyeP0qcjcGTrF1mTjLYm2QJr0nn1buP3pEg6FU9u+yIfktE+JFvgQzqvHW36nvRH
p/L5LV9kOzLadmQLbEebBFxTPKmNvqqf7IDIY2S0x8gWeIzOq59s9p5sRqcIDm31IqeR0U4jW+A0
AjmAo9AmOdDnAfEm7TWyBV4jn8Psm9xJcXQexrFvcMh2ZLTtyBbYjmaJgOOhe4nQZwSRJe0/sgX+
I5/IlLpPHqTzSA7SNvIhGe1DsgU+pGkm4Jj03Uzoc4KokrYjmY6ATPZexOvAsRx/E4/8SUb7k8xS
aDL+wFi6lAx7ZpBhyWjDklmOTGY2iCxfiOfYREIWJqMtTGYlPiNwhMpVGdHnCHEtbWoyq5EZTYeV
1QshHZxayOhktNHJrP0BKYGj1K5LiT5LiIlp95PZaib2m7cGSJjdukX+J6P9T2ar+Rdv3Bog3yPb
tsgGZbQNysyWp7DdtDVDCXBbtsgKZbQVymw13aINWwNQy2/XIj+U0X4os7E8AbRKagNlwG+RIj+U
0X4o66u5dbJR2wGuHtqmRYYoow1R1hdTqtuk7R5IyS1aZIUy2gplfTF7uusx3WMmeSMG2aCMtkFZ
r+srd5uzvcLqya1ZZIUy2gplva1PwG3M9gYTILdlkQ/KaB+UdVmfgOt9AgMg+x5iQdoDZX0xC4J1
n+45kN7yQf4no/1P1hczoN+M7R4B2a1Y5H0y2vtkfTEBuo3Y7umP3IZFriejXU/WF5Pf9vJj98jH
3XdETiejnU42FrOeu4U1POSRd66Qxcloi5ONvL5y9LJoZBwA/XYI+ZuM9jfZKBE5+NdBo0xyYN//
IHOT0eYmGzUgBzD6RsU50PMPeZuM9jbZaAE5+LbQcApsb0AESDubbCwmQH8Fc3j+Y29dIkuT0ZYm
GxpQO2yMOomA74yIBGkvkw0LSQK0RpslQfdGxIW0icnGYi6cbc0Mj4fH9mWQfclo+5KNEZLDFhbH
mMVwBTP+7+//DyHvSdngngEA
T_EOF
echo "payload bytes: $(wc -c < "$ROOT/table.json")"
python3 - "$ROOT" <<'PY_EOF'

import json, os, re, shutil, subprocess, sys, time

ROOT = sys.argv[1]
T = json.load(open(os.path.join(ROOT, "table.json")))
LANG = T["language"]
PROBES = T["probes"]
OUT = T["out"]
out = open(OUT, "w")
WORK = os.path.join(ROOT, "u")

# --- verbatim delimiter codec, copied from verbatim_diag.py ---
def esc(text):
    """make `text` safe to place in one pipe-delimited field, reversibly."""
    for raw, rep in _ENC:
        text = text.replace(raw, rep)
    return text

_ENC = [('\\', '\\\\'), ('|', '\\p'), (';', '\\s'), ('\n', '\\n'), ('\r', '\\r')]
MARKER = '#verbatim-escape v1'
out.write(MARKER + '\n')


print("op lane %s: %d candidate probes" % (LANG, len(PROBES)))
sys.stdout.flush()


def sh(cmd, cwd=None, timeout=180):
    try:
        p = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE, timeout=timeout)
        so = p.stdout.decode("utf-8", "replace")
        se = p.stderr.decode("utf-8", "replace")
        return p.returncode, so, se
    except subprocess.TimeoutExpired:
        return 124, "", "TIMEOUT after %ds" % timeout
    except OSError as e:
        return 125, "", "OSError %s" % e


# ------------------------------------------------------ objdump reading

LABEL = re.compile(r"^([0-9a-f]+)\s+<(.+)>:\s*$")
INSN = re.compile(r"^\s*([0-9a-f]+):\t(.*)$")
RELOC = re.compile(r"^\s+([0-9a-f]+): (R_\S+)\t(.+?)\s*$")


def extract(text, sym, exact):
    """the two columns for one symbol.

    bytes  every byte objdump printed, in order, flattened
    mnem   the instruction text, with objdump's own trailing `# ...`
           comment dropped -- that comment is arithmetic objdump did
           for the reader, not part of the instruction.  A relocation
           is appended to the instruction it applies to as
           ` !!reloc=<type>:<symbol>`, because in an object file the
           call displacement is literally zero and the callee's name
           lives only in the relocation.
    """
    lines = text.splitlines()
    k = -1
    for idx, ln in enumerate(lines):
        m = LABEL.match(ln)
        if not m:
            continue
        lab = m.group(2)
        hit = (lab == sym) if exact else (sym in lab)
        if hit:
            k = idx
            break
    if k < 0:
        return None
    raw = []
    mn = []
    for ln in lines[k + 1:]:
        if LABEL.match(ln):
            break
        m = INSN.match(ln)
        if not m:
            r = RELOC.match(ln)
            if r and mn:
                mn[-1] = "%s !!reloc=%s:%s" % (mn[-1], r.group(2), r.group(3))
            continue
        parts = m.group(2).split("\t")
        bs = parts[0].split()
        raw.extend(bs)
        txt = parts[1] if len(parts) > 1 else ""
        txt = txt.split("#")[0]
        txt = " ".join(txt.split())
        if txt:
            mn.append(txt)
    return raw, mn


def disasm(obj, sym, exact):
    rc, so, se = sh(["objdump", "-dr", "--disassemble=" + sym, obj])
    got = extract(so, sym, exact) if rc == 0 else None
    if got is None:
        rc, so, se = sh(["objdump", "-dr", obj], timeout=600)
        got = extract(so, sym, exact)
    return got


# --------------------------------------------------------- DWARF reading
#
# objdump --dwarf=info prints one entry per line block:
#
#   <1><2d>: Abbrev Number: 2 (DW_TAG_subprogram)
#      <2e>   DW_AT_name        : op_12
#   <2><4a>: Abbrev Number: 3 (DW_TAG_formal_parameter)
#      <4b>   DW_AT_name        : a
#      <52>   DW_AT_location    : 2 byte block: 91 7c (DW_OP_fbreg: -4)
#
# The leading <N> is the tree depth.  A formal parameter one level
# below the matching subprogram is a parameter OF that subprogram.

DIE = re.compile(r"^\s*<(\d+)><[0-9a-f]+>:\s*Abbrev Number:\s*\d+\s*\((\S+)\)")
ATTR = re.compile(r"^\s*<[0-9a-f]+>\s+(DW_AT_\w+)\s*:\s*(.*?)\s*$")


def clean(text):
    text = " ".join(text.split())
    return text


STRPREFIX = re.compile(r"^\((?:indexed string|indirect string)[^)]*\):\s*")


def dwname(text):
    """objdump prints a string attribute as `(indexed string: 0x5): a`.
    The parenthesised part is objdump telling the reader WHERE in the
    string table it found the name; the name is what follows.  Keeping
    the prefix would have put objdump's bookkeeping into the parameter
    name column."""
    return STRPREFIX.sub("", text.strip())


def dwarf_params(text, sym):
    """[(name, location)] for the subprogram named `sym`.

    More than one subprogram can carry the name.  swift's `@_cdecl`
    emits a C-entry thunk beside the real function, and the thunk has
    no DW_TAG_formal_parameter children at all, so the first match is
    not always the one holding the parameter table.  Every match is
    collected and the first one that actually has parameters wins."""
    lines = text.splitlines()
    depth = None
    tag = None
    attrs = {}
    entries = []
    for ln in lines:
        m = DIE.match(ln)
        if m:
            if tag is not None:
                entries.append((depth, tag, attrs))
            depth = int(m.group(1))
            tag = m.group(2)
            attrs = {}
            continue
        a = ATTR.match(ln)
        if a and tag is not None:
            attrs[a.group(1)] = a.group(2)
    if tag is not None:
        entries.append((depth, tag, attrs))

    hits = []
    for idx, (d, t, at) in enumerate(entries):
        if t != "DW_TAG_subprogram":
            continue
        names = []
        if "DW_AT_name" in at:
            names.append(dwname(at["DW_AT_name"]))
        if "DW_AT_linkage_name" in at:
            names.append(dwname(at["DW_AT_linkage_name"]))
        for nm in names:
            if nm == sym or sym in nm:
                hits.append(idx)
                break
    if not hits:
        return None
    best = []
    for k in hits:
        base = entries[k][0]
        got = []
        for d, t, at in entries[k + 1:]:
            if d <= base:
                break
            if d != base + 1:
                continue
            if t != "DW_TAG_formal_parameter":
                continue
            nm = clean(dwname(at.get("DW_AT_name", "(unnamed)")))
            loc = clean(at.get("DW_AT_location", "(no location)"))
            got.append((nm, loc))
        if got:
            return got
        best = got
    return best


def dwarf(obj, sym):
    rc, so, se = sh(["objdump", "--dwarf=info", obj], timeout=600)
    if rc != 0:
        return None, "objdump --dwarf=info rc=%d" % rc
    got = dwarf_params(so, sym)
    if got is None:
        return None, "no DW_TAG_subprogram named %s" % sym
    if not got:
        return None, "subprogram %s has no DW_TAG_formal_parameter" % sym
    return got, None


# ------------------------------------------------------------ compiling

GOMOD = "module opprobe\n\ngo 1.26\n"

CLANG = "/usr/bin/clang"
CLANGXX = "/usr/bin/clang++"
SWIFTC = "/persist/swift/usr/bin/swiftc"


def compile_probe(p, d, mode):
    """(rc, artifact path, diagnostic text)."""
    if LANG == "c":
        src = os.path.join(d, "unit.c")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANG, "-std=c17"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "cpp":
        src = os.path.join(d, "unit.cpp")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANGXX, "-std=c++20"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "rust":
        src = os.path.join(d, "unit.rs")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        if mode == "anchor":
            opt = ["-C", "opt-level=0", "-g"]
        else:
            opt = ["-C", "opt-level=1", "-C", "debug-assertions=off"]
        cmd = (["rustc", "--crate-type=lib", "--emit=obj"] + opt
               + ["-o", obj, src])
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "go":
        open(os.path.join(d, "go.mod"), "w").write(GOMOD)
        open(os.path.join(d, "main.go"), "w").write(p["source"])
        obj = os.path.join(d, "bin_%s" % mode)
        cmd = ["go", "build"]
        if mode == "anchor":
            cmd.append("-gcflags=-N -l")
        cmd.extend(["-o", obj, "."])
        rc, so, se = sh(cmd, cwd=d, timeout=300)
        return rc, obj, (se or so)
    if LANG == "swift":
        src = os.path.join(d, "unit.swift")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-Onone", "-g"] if mode == "anchor" else ["-O"]
        cmd = [SWIFTC] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd, timeout=300)
        return rc, obj, (se or so)
    raise KeyError(LANG)


DIAG = re.compile(r"^[^\s:]+:\d+(:\d+)?:")


def firstline(txt):
    """the compiler's own words for why it refused.

    The first line is not reliably the reason.  clang leads with a
    warning and puts the error underneath.  go leads with a banner
    naming the package -- `# opprobe` -- and its diagnostics never
    contain the word `error` at all, so a rule that only looked for
    that word recorded the banner and threw the testimony away.
    Three passes, in order: a line saying `error`, a line in the
    `file:line:col:` diagnostic shape, then the first line that is
    not a banner."""
    lines = []
    for ln in txt.splitlines():
        s = ln.strip()
        if s:
            lines.append(s)
    for ln in lines:
        if re.search(r"\berror\b", ln, re.I):
            return ln[:200]
    for ln in lines:
        if DIAG.match(ln):
            return ln[:200]
    for ln in lines:
        if not ln.startswith("#"):
            return ln[:200]
    if lines:
        return lines[0][:200]
    return "(no diagnostic)"


def write_unit(n, build, obj, sym, exact):
    got = disasm(obj, sym, exact)
    if got is None:
        rc2, so2, se2 = sh(["objdump", "-t", obj])
        near = 0
        for l in so2.splitlines():
            if sym in l:
                near += 1
        out.write("op_%d|%s|NOSYM|%s\n"
                  % (n, build, esc("symbol %s absent, %d near matches"
                                   % (sym, near))))
        return False
    raw, mn = got
    out.write("op_%d|%s|OK|%s|%s\n"
              % (n, build, " ".join(esc(x) for x in raw),
                 ";".join(esc(x) for x in mn)))
    return True


t0 = time.time()
tally = {"REFUSED": 0, "ACCEPTED": 0, "ANCHOR_OK": 0, "SHIP_OK": 0,
         "DWARF": 0}

for k, p in enumerate(PROBES):
    n = p["n"]
    sym = p["symbol"]
    exact = p["symbol_exact"]
    d = os.path.join(WORK, "n%d" % n)
    shutil.rmtree(d, ignore_errors=True)
    os.makedirs(d)

    rc, obj, err = compile_probe(p, d, "ship")
    if rc != 0 or not os.path.exists(obj):
        out.write("op_%d|REFUSED|%s\n" % (n, esc(firstline(err))))
        tally["REFUSED"] += 1
        out.flush()
        shutil.rmtree(d, ignore_errors=True)
        continue
    tally["ACCEPTED"] += 1
    if write_unit(n, "SHIP", obj, sym, exact):
        tally["SHIP_OK"] += 1

    rc, aobj, aerr = compile_probe(p, d, "anchor")
    if rc != 0 or not os.path.exists(aobj):
        out.write("op_%d|ANCHOR|BUILDFAIL|%s\n" % (n, esc(firstline(aerr))))
    else:
        if write_unit(n, "ANCHOR", aobj, sym, exact):
            tally["ANCHOR_OK"] += 1
        rows, why = dwarf(aobj, sym)
        if rows is None:
            out.write("op_%d|ANCHOR|NODWARF|%s\n" % (n, esc(why)))
        else:
            joined = ";".join("%s=%s" % (esc(a), esc(b)) for a, b in rows)
            out.write("op_%d|ANCHOR|DWARF|%s\n" % (n, joined))
            tally["DWARF"] += 1
    out.flush()
    shutil.rmtree(d, ignore_errors=True)

    if (k + 1) % 25 == 0 or (k + 1) == len(PROBES):
        el = time.time() - t0
        print("[progress] %s [%d/%d] elapsed %.1fs mean %.2fs  "
              "REFUSED %d ACCEPTED %d SHIP_OK %d ANCHOR_OK %d DWARF %d"
              % (LANG, k + 1, len(PROBES), el, el / (k + 1),
                 tally["REFUSED"], tally["ACCEPTED"], tally["SHIP_OK"],
                 tally["ANCHOR_OK"], tally["DWARF"]))
        sys.stdout.flush()

out.close()
print("done: %s -> %s" % (json.dumps(tally), OUT))

PY_EOF
echo "--- lane finished, rc=$?"
date -u +%Y-%m-%dT%H:%M:%SZ
