#!/bin/sh
# op-pipeline lane -- cpp -- generated by
# Research/op_pipeline/lane_gen.py .  Do not hand-edit.
# steps 1b/2/3: compile-or-refuse, then the ANCHOR and SHIP
# builds of every probe the compiler accepted, then objdump
# extraction, then the anchor's DWARF parameter table.
set -u
export HOME=/work
export PATH=/persist/swift/usr/bin:$PATH
export GOTOOLCHAIN=local
export GOPROXY=off
export GOFLAGS=-mod=mod
ROOT=/work/regen_cpp_c0173
export GOCACHE="$ROOT/gocache"
export GOPATH="$ROOT/gopath"
# swift's binaries want libncurses.so.6 and the image ships
# only libncursesw.so.6.6; the symlink lives in the image's
# own /usr/lib and does NOT survive a container restart.
if [ -f /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 ]; then
  ln -sf /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 \
     /usr/lib/x86_64-linux-gnu/libncurses.so.6 2>/dev/null
  ldconfig 2>/dev/null
fi
echo "=== op pipeline -- cpp -- 400 candidate probes ==="
date -u +%Y-%m-%dT%H:%M:%SZ
# refuse in seconds rather than in an hour
if ! /usr/bin/clang++ --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: /usr/bin/clang++ is not runnable in this container."
  echo "!! tried: /usr/bin/clang++ --version"
  exit 4
fi
/usr/bin/clang++ --version 2>&1 | head -2
if ! objdump --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: objdump is not runnable."
  exit 4
fi
objdump --version 2>&1 | head -1
rm -rf "$ROOT"; mkdir -p "$ROOT" "$GOCACHE" "$GOPATH"
df -Pm /work | awk 'NR==2{print "free /work: " $4 " MB"}'
FREE=`df -Pm /work | awk 'NR==2{print $4}'`
if [ "$FREE" -lt 400 ]; then
  echo "!! REFUSING TO START: only $FREE MB free on /work, need 400"
  exit 3
fi
base64 -d <<'T_EOF' | gunzip > "$ROOT/table.json"
H4sIAAAAAAAC/72d3W4kV3KEX4Wgb8aA1mJVZtaPd2HANuAX8KXHIDgjajTAqDmmSKwWgt7dSYpk
96mK6kFkCbE3kmYlheJU96mPNZXn++3yy83h0+PNp9vLf724/Pj16+V3F5d3jw9Pf/V9/vH7+9tP
t4fr/D+uP151o/3Lw68PT3/L1/u7D7e/5N/1P79dHvIPw9xfXeWv//KPnz/cfXn6p+++Xj//4uXb
r17f/nrz8enf/HD/ePv0q3eP9x+fc7///uL5X/jHv+biL3+5+PD5cHP/j4vD3cP17f+9P/zT58PH
L48/3F787eMvDz98Pjz8W/Nrdz9/vbm/bX7tcPv3/Ov3h9tfH27vDxfvL//z/eXFzePD3fvD63/Z
u48/3dx3w/XDxc13F9f/cXf35eLDP78//Pb+cJH/u799eMx/8Oblv+Hiw1/fH35/f7j8/buLY+UO
Ve7oyp2octdW/q8vdzcP3UC37lHrnm7di1r3i9b3+R9HdzbU2ejOJupsbef/vnm4uP73jx8ff6aL
OyrudHEXFXdQvHbFAxUPuniIise6+Je7w6fqZR9Q+4FuP4jaD1vta9d+RO1Huv0oaj+u2//y0919
+Ts/ofoTXX8S1Z8269eu/ozqz3T9WVR/Xtd/PPzy+dPh9ofiB6BDKNfRKNeJUK67OrcCpc9Ah8iu
o8muE5Fd151ZgR23gQ6hXkejXidCva7/5jLUPg2I/jqa/joR/XV2Zhn23Bg6BIMdDYOdCAY7//Y6
1D4PiA07mg07ERt2Cza8/vAj/1Nfh4iwo4mwExFhtyDC6x+ff9jtJ7o3YsGOZsFOxILduOz9tXCt
EQB2NAB2IgDsFgB4/fnDz5Urjbivo7mvE3FfNy9bH54+39f0btYj2utp2utFtNcvaO/6sVwcQV5P
Q14vgry+hbwPhQeWPeK5nua5XsRzfctzT39ON0bo1tPo1ovQrbdV4+c/Z1sjUOtpUOtFoNb7qrX1
hdYIy3oay3oRlvWxal3ZxBCX9TSX9SIu61su++Hu8cOXW7ozYrKeZrJexGR9y2TPJEpXRkjW00jW
i5Csb5Hsp5svP9KNEY71NI71IhzrWxzLfydb2BCHGc1hJuIwazns+fEK2xgBmNEAZiIAs27duPYg
xRCHGc1hJuIw60Hx0pMTQzhmNI6ZCMfM1sVrtyxDRGY0kZmIyMzXxUvfcIRkRiOZiZDMWiT74xkh
WxkBmdFAZiIgswFULu5qCMuMxjITYZmNqHltW0N0ZjSdmYjOrKWzlyfilR+vDUGa0ZBmIkizGRUv
sJojVnOa1VzEan6Felc2dEfI5jSyuQjZvNssXmqPuM1pbnMRt3mP2pfuao7AzWlwcxG4eQtuO9+H
cARvTsObi+DNfaN86d7mCOGcRjgXIZwHLl+5uzlCOadRzkUo5wOuXrm/IZRzGuVchHI+4ualPR6x
nNMs5yKW8+lM9eJ2h6DOaahzEdT5fG4FSnteILwLGu9ChHdxdWYFKt+BQJQXNOWFiPKiw/1LpBOI
8YJmvBAxXvTnutc2gECwFzTshQj2ws4uQW0HQMgXNPKFCPmiRb6/P/0F/3uJgVAvaNQLEerFH6j3
/FvFT2+C1D7riPGCZrwQMV4MbefK2FoguAsa7kIEdzG2lYtja4G4LmiuCxHXxbRoXdrFEMkFTXIh
IrmY2871sbUBAdxAA9wgArjhChQvXfEBkdtAk9sgIrehWxff8ZPLgNhtoNltELHb0G+1r117hG0D
jW2DCNsGW7ffQ60DQraBRrZBhGyDb9avXX0EbwMNb4MI3oZY19/5mHZAKDfQKDeIUG4Yzq1A7TOA
yG6gyW4Qkd0wnlmBPbcBhHoDjXqDCPWG6ZvLUPs0IPobaPobRPQ3zGeWYc+NYUQwONIwOIpgcLz6
9jqUPg8jYsORZsNRxIbjgg1LY2sjIsKRJsJRRITjggjLY2sjYsGRZsFRxIKjLXsXxtZGBIAjDYCj
CADHBQAWx9ZGxH0jzX2jiPvGWLYuTm+NiPZGmvZGEe2NC9qrj62NCPJGGvJGEeSNLeRVxtZGxHMj
zXOjiOfGlucqbx6MCN1GGt1GEbqN86pxZWxtQqA20aA2iUBtulq1roytTQjLJhrLJhGWTd2qdWET
mxCXTTSXTSIum1ouq80ATIjJJprJJhGTTS2TlcbWJoRkE41kkwjJphbJKmNrE8KxicaxSYRjU4tj
hVfFJsRhE81hk4jDppbDKm/HTAjAJhrAJhGATeO6ce1ByoQ4bKI5bBJx2DSB4qUnJxPCsYnGsUmE
Y9O8Ll67Zc2IyGaayGYRkc1X6+KVb/iMkGymkWwWIdncIlnptbcZAdlMA9ksArK5B5Vru9qMsGym
sWwWYdlsqHlpW5sRnc00nc0iOptbOtvxYv+MIG2mIW0WQdocqHiB1WbEajPNarOI1eYB9S5t6AjZ
ZhrZZhGyzeNm8VJ7xG0zzW2ziNvmCbWv3dUQuM00uM0icJtbcNv3PoQhI4PRRgYTGRns6mqjfOXe
ZsjNYLSbwURuBrvqcPnC3c2QoMFoQYOJBA121ePq/P3NkKbBaE2DiTQNdmW4eWGPNyRqMFrUYCJR
g135merF7S7QCgS9AiFagTi3ArU9b0ArMNArMIhWYDizAqXvwIj6j3T/UdR/xP0rpGNI2mC0tMFE
0ga7ms51L24AM1qCmV6CWbQE89klKO0AyNxgtLnBROYG61rkq42tGZI1GC1rMJGswV5kDdOOqTVD
YgajxQwmEjPYi5hhqg+tGXIwGO1gMJGDwV4cDNOumTVDwgWjhQsmEi7Yi3Bh2jGyZsitYLRbwURu
BXtxK0x7J9YM+RWM9iuYyK9gL36Fae/AmiG/gtF+BRP5FezFrzD9KfNqhkQLRosWTCRasBfRwvSn
jKsZ8i0Y7VswkW/BXnwL058zrWbIumC0dcFE1gV7sS5Mf86wmiH1gtHqBROpF6zvVu13PptFJgaj
TQwmMjFY359ZgNonAPEcLWYwkZjBettegB03ACRqMFrUYCJRg/X+rVWofRYQ89HiBhOJG6yP7VXY
dUtACEirHEykcrB++OYy1D4NiAhpu4OJ7A7Wt0RYmVIzZHcw2u5gIruD9S0HVofUDCkejFY8mEjx
YP28qM3PqBmSPBgteTCR5MGsxb7aiJohz4PRngcTeR7MukXp2qCWIcuD0ZYHE1kezFrGKw+oGZI8
GC15MJHkwaxBu8J8miG5g9FyBxPJHcwaiqu8YYC0DkZrHUykdTCLZeHCdJohsYPRYgcTiR3MhmXp
wnCaIaeD0U4HEzkdzMZl6cr+hWiMtjmYyOZg1tBY6T1/Qx4Hoz0OJvI4mDUkVplMM2RwMNrgYCKD
g3kDYoXBNEPmBqPNDSYyN5g3EFZ4Fwy5Gox2NZjI1WDe0Ffl7RekaDBa0WAiRYO5rQrXHpsgO4PR
dgYT2RnMfd279JwEiRmMFjOYSMxgHqvetXsVsjIYbWUwkZXBfFj1Ln27EYjRRgYTGRnMGxArvdGG
RAxGixhMJGIwn9aNixsagjHav2Ai/4L5DIqXdjSkXTBau2Ai7YJFw2Q7XthHugWjdQsm0i1YdKB3
gdCQacFo04KJTAsWPahd2cqRXsFovYKJ9AoWttW7VB7RGi1WMJFYwcJB+dLtDMkVjJYrmEiuYNHg
2s63HZBkwWjJgokkCxYD7l67qSFwo20LJrItWIywe+m2hgCONi6YyLhgMcHmlRsbAjhau2Ai7YLF
DItXdnfkXTDau2Ai74INV9vNazsd8i8Y7V8wkX/Bhu7MApS2O6RgMFrBYCIFgw399gKUvgCI7WgH
g4kcDDYYrF8CHORfMNq/YCL/gg1+pnrxy48Qj1YwmEjBYEOcW4Hatx+BHq1gMJGCwYYG9IrjZ0i6
YLR0wUTShcx59/LctTx9hvwKRvsVTORXyJzTxpXhM2RSMNqkYCKTQuacFi7OniFrgtHWBBNZEzKn
6VzZvJAfwWg/gon8CJlz2rg+eYYUCUYrEkykSMicVe3a1UakRhsSTGRIyJxl7R0/pSBTgtGmBBOZ
EjIHd69ddwRptC/BRL6EzFl230OoSJpgtDTBRNKEzNkoX7vyCNRocYKJxAmZsyy/8yks0igYrVEw
kUYhc7b7164/ojhaqmAiqULmbPbfsfUjx4LRjgUTORYy5xuLUPokIOWC0coFEykXMmdzEfbcDJCD
wWgHg4kcDJnzrVWofRYQB9JWBhNZGTLndBVK02ZIymC0lMFEUobMaRpXh82QmMFoMYOJxAyZ07Yu
zJohM4PRZgYTmRkyp2lcGzVDbgaj3QwmcjNkTtu5OHGFxAxGixlMJGbInKZ1edAMaRmM1jKYSMuQ
OSe1K3NmyMZgtI3BRDaGzDnpW3mBAGkYjNYwmEjDkDmLvpUpM+RhMNrDYCIPQ+YsOleGzJCBwWgD
g4kMDJmz6FzYupB6wWj1gonUC5lzUrn22j5yLhjtXDCRcyFzThqXJsyQbMFo2YKJZAuZc1K4MmCG
HAtGOxZM5FjInJO+hZe8kFTBaKmCiaQKmXNSt/JmC1IpGK1SMJFKIXOWfUsPSRxJFJyWKLhIopA5
q9qVpyKO9AlO6xNcpE/InGXt0k3KkTrBaXWCi9QJmbOsXfhmO7ImOG1NcJE1IXNOSlfeVHPkSnDa
leAiV0LmrAoX97JAvYPuHaLese5d28wG1Hugew+i3qckVn//3pEOwWkdgot0CJmzrs1zmSMRgtMi
BBeJEDJn3bq0ic+o9kzXnkW1543ale7IeuC09cBF1oPMWXcv3ceQ+MBp8YGLxAeZc9J737sMjgQI
TgsQXCRAyBxYvXQ3QyYEp00ILjIhZA6qXrmfIRuC0zYEF9kQMgcVL9zRkBLBaSWCi5QImYN6l/Z1
xG20E8FFToTM2Sxe3OQQwNFuBBe5ETJnu39tp0MoR+sRXKRHyJzN/qVPPyI62o/gIj9C5qD2Ja5B
bgSn3QguciNkznbz2hcf6RGc1iO4SI+QOWcWoPTNR3oEp/UILtIjZM7JAtTGyBwJEZwWIrhIiJA5
7/74XbHqFJkj94HT7gMXuQ8y56RwYYjMkeXAacuBiywHmXPStzZD5sho4LTRwEVGg8w5rVzatxCx
0e4CF7kLMuekcHmCzJG+wGl9gYv0BZmzbF271ojPaHuBi+wFmbNoveMHE2QxcNpi4CKLQebA6qWr
jlwGTrsMXOQyyJxF9T1YioQGTgsNXCQ0yBzcvXbdEZ7RUgMXSQ0yZ9F95/NWpDhwWnHgIsVB5mzW
r119xG608MBFwoPM2aq/Z9NHMEf7D1zkP8ic82tQ+xwgvqN1CC7SIWTO1hrsug0g3KP9CC7yI2TO
Nxah9klA9EcbE1xkTMick0WoTI05EiY4LUxwkTAhc04LF4fGHEkTnJYmuEiakDlN6a+Fq4wQj7Ym
uMiakDmnhUsjY468CU57E1zkTcicpnJtdMqRNMFpaYKLpAmZc1r6sdwaYRytTHCRMiFzjq0L82KO
TAlOmxJcZErInGPdyvsBSJHgtCLBRYqEzGnrFqbFHDkSnHYkuMiRkDlt5cKwmCM7gtN2BBfZETKn
rVzYtZAWwWktgou0CJlzbFx7Cx/5EJz2IbjIh5A5x8KVSTFHIgSnRQguEiFkzrFvYVDMkf/Aaf+B
i/wHmXOsW3h7CwkPnBYeuEh4kDnHtpW3VpDmwGnNgYs0B5mzqFt7JIIEB04LDlwkOMicZevSMxCk
NnBabeAitUHmLFoX706IuWitgYu0BpmzaF36ViPooo0GLjIaZM6xc+kNNOQxcNpj4CKPQeYs+9a2
MWQvcNpe4CJ7Qeasapf2MeQscNpZ4CJnQeac1K6/To9UBU6rClykKsicVesCjSFJgdOSAhdJCjJn
VbqyfSMxgdNiAheJCTIHty5VR2RGGwlcZCTInFX12g0MoRktJXCRlCBzjrV3vqmA5AROywlcJCfI
HNS8dhtDkEZbClxkKcgc0LxyI0OmAqdNBS4yFWQO6F24lSFdgdO6AhfpCjIH1K7s6MhX4LSvwEW+
gszZ6l3b35C3wGlvgYu8BZmzWb+0ySF1gdPqAhepCzJnq37po484jnYXuMhdkDmgfAlnkLfAaW+B
i7wFmbNZvPilRzhHqwtcpC7InO3+tW89gjpaXeAidUHmHPsXx8GQrMBpWYGLZAWZ8+75t4LK02DI
S+C0l8BFXoLMOfatDIMhA4HTBgIXGQgy51i3OAuGbANO2wZcZBvInJPGlS0LeQWc9gq4yCuQOce+
9UkwpBZwWi3gIrVA5ixK1640ojLaLOAis0DmtKV3/CyCDANOGwZcZBjIHNS8ds0RkNGeARd5BjKn
bb6HRZFswGnZgItkA5kDq9euOoIyWjjgIuFA5rTVdz5ZRfoBp/UDLtIPZM5W+9K1RzICp2UELpIR
ZM5G+x3bPXITOO0mcJGbIHPOLkHtU4CojlYVuEhVkDkbS7DnBoDcBU67C1zkLsic82tQ+xwg5qNt
Bi6yGWTOcQ1K019IZuC0zMBFMoPMOelbHf5CQgOnhQYuEhpkzmnnwuwXMho4bTRwkdEgc0761ka/
kNPAaaeBi5wGmXPauDYDFUhoELTQIERCg8w56fxYLt2h0h1duhOVPsJbYe4rkMUgaItBiCwGmfPW
tvDb/4H0BUHrC0KkL8icpm1h6iuQvyBof0GI/AWZ0zQuDH0FMhcEbS4Ikbkgc5rGlQ1rQIUHuvAg
KnzkrdJL9YFcBUG7CkLkKsict76Via9AkoKgJQUhkhRkzlvdwsBXIDdB0G6CELkJMuetLf9aViAZ
QdAyghDJCDLnrWzhjZRACoKgFQQhUhBkTtu29AAkkHwgaPlAiOQDmbMoXXniEUg7ELR2IETagcxp
S9duS0g5ELRyIETKgcxpS5e+0Qi1aNtAiGwDmfNWufJmWSDHQNCOgRA5BjJnUbe4gyHcos0CITIL
ZM6ydW0LQ9RF+wRC5BPInGPr8tvxgTQCQWsEQqQRyJxl6QKDIYFA0AKBEAkEMmfZubJxI2lA0NKA
EEkDMgeWLjVHPEbbAkJkC8icZfPSnQsJA4IWBoRIGJA5b633vYcQSBwQtDggROKAzAHFS/cvZBAI
2iAQIoNA5qyLV+5gyCIQtEUgRBaBzFnXrtzDEKLRKoEQqQQyZ926tJcjRqNdAiFyCWTORu3i1oZg
jXYKhMgpkDlb7Uv7G9IKBK0VCJFWIHM22lc+98grELRXIERegcxZdy9RDHIKBO0UCJFTIHO2ete+
8EgrELRWIERagczZrF/7xiOUo7UCIdIKZM5b/dpYVyCRQNAigRCJBDLn3RO6VKe6AjkDgnYGhMgZ
kDlvdQtDXYHsAEHbAUJkB8ict7a1ma5AJoCgTQAhMgFkzrFwabdCdEaf+R+iM/8z561ueaIr0LH/
QR/7H6Jj/zOn7Vy6zujU/6BP/Q/Rqf+Z03Te8eMHOv0/6NP/Q3T6f+aA4rUrjjCMdgCEyAGQOU3x
PQCKRABBiwBCJALIHNS8ds0RitEygBDJADKnab7zGSpSAwStBgiRGiBzNsrXrjziNFoUECJRQObg
8ns2egRutDcgRN6AzDm3ArXPAGI5WiMQIo1A5uAV2LP1I69A0F6BEHkFMufsEpQ+Bcg0ELRpIESm
gcx5W4LKFFcg0UDQooEQiQYy51i3OMQVSDYQtGwgRLKBzDmp/LVwhRHO0baBENkGMudYtzTCFcg3
ELRvIES+gcw5KVwcZkKygaBlAyGSDWTOsXJ5gAupBoJWDYRINZA5r50r81vIMBC0YSBEhoHMeS1b
+d19pBYIWi0QIrVA5pyWrUxvIbdA0G6BELkFMue0cGV4C1kFgrYKhMgqkDmnhQt7FdIJBK0TCJFO
IHNe+9bekUcegaA9AiHyCGTOa93S5BYSCAQtEAiRQCBzXttWBreQNyBob0CIvAGZ81q28L4VEgUE
LQoIkSggc167Vt42QXqAoPUAIdIDZE5Ttva4A4kBghYDhEgMkDlt59LzDaQECFoJECIlQOY0nWv3
I6QDCFoHECIdQOY0nSvfZmQCCNoEECITQOa8Ni69MYbO/w/6/P8Qnf+fOW3b2uaFTv0P+tT/EJ36
nzmL0qXdC531H/RZ/yE66z9z3krXX3ZHR/wHfcR/iI74z5xF5wJ5ocP9gz7cP0SH+2fOonJpy0YA
Rh/oH6ID/TMHdS4VRxRGn+QfopP8M2dRvHbLQhhGH+YfosP8M+e19M63DNCh/kEf6h+iQ/0zZ927
dONCp/sHfbp/iE73z5xV78qtC53wH/QJ/yE64T9zVq0LNy90zH/Qx/yH6Jj/zFmVruzi6Jz/oM/5
D9E5/5mDWxd3NYRo9Hn/ITrvP3M2yte2NgRr9JH/ITryP3Nw+dKHHjEbfeZ/iM78z5xV9RK8oPP+
gz7vP0Tn/WfORu3ilx2hG33kf4iO/M+crfalbzs68j/oI/9DdOR/5ry2L45noUP+gz7kP0SH/GfO
u+eNrDyfhU70D/pE/xCd6J85x76VAS10en/Qp/eH6PT+zDnWLU5oobP6gz6rP0Rn9WfOSePShoXY
jD6XP0Tn8mfOsW99Rgsdzh/04fwhOpw/cxala1ca0Rh9On+ITufPnLb0jp8/0Dn9QZ/TH6Jz+jMH
Na9dcwRj9Hn9ITqvP3Pa5jSH/u/v/w8FxkyMoYMBAA==
T_EOF
echo "payload bytes: $(wc -c < "$ROOT/table.json")"
python3 - "$ROOT" <<'PY_EOF'

import json, os, re, shutil, subprocess, sys, time

ROOT = sys.argv[1]
T = json.load(open(os.path.join(ROOT, "table.json")))
LANG = T["language"]
PROBES = T["probes"]
OUT = T["out"]
out = open(OUT, "w")
WORK = os.path.join(ROOT, "u")

# --- verbatim delimiter codec, copied from verbatim_diag.py ---
def esc(text):
    """make `text` safe to place in one pipe-delimited field, reversibly."""
    for raw, rep in _ENC:
        text = text.replace(raw, rep)
    return text

_ENC = [('\\', '\\\\'), ('|', '\\p'), (';', '\\s'), ('\n', '\\n'), ('\r', '\\r')]
MARKER = '#verbatim-escape v1'
out.write(MARKER + '\n')


print("op lane %s: %d candidate probes" % (LANG, len(PROBES)))
sys.stdout.flush()


def sh(cmd, cwd=None, timeout=180):
    try:
        p = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE, timeout=timeout)
        so = p.stdout.decode("utf-8", "replace")
        se = p.stderr.decode("utf-8", "replace")
        return p.returncode, so, se
    except subprocess.TimeoutExpired:
        return 124, "", "TIMEOUT after %ds" % timeout
    except OSError as e:
        return 125, "", "OSError %s" % e


# ------------------------------------------------------ objdump reading

LABEL = re.compile(r"^([0-9a-f]+)\s+<(.+)>:\s*$")
INSN = re.compile(r"^\s*([0-9a-f]+):\t(.*)$")
RELOC = re.compile(r"^\s+([0-9a-f]+): (R_\S+)\t(.+?)\s*$")


def extract(text, sym, exact):
    """the two columns for one symbol.

    bytes  every byte objdump printed, in order, flattened
    mnem   the instruction text, with objdump's own trailing `# ...`
           comment dropped -- that comment is arithmetic objdump did
           for the reader, not part of the instruction.  A relocation
           is appended to the instruction it applies to as
           ` !!reloc=<type>:<symbol>`, because in an object file the
           call displacement is literally zero and the callee's name
           lives only in the relocation.
    """
    lines = text.splitlines()
    k = -1
    for idx, ln in enumerate(lines):
        m = LABEL.match(ln)
        if not m:
            continue
        lab = m.group(2)
        hit = (lab == sym) if exact else (sym in lab)
        if hit:
            k = idx
            break
    if k < 0:
        return None
    raw = []
    mn = []
    for ln in lines[k + 1:]:
        if LABEL.match(ln):
            break
        m = INSN.match(ln)
        if not m:
            r = RELOC.match(ln)
            if r and mn:
                mn[-1] = "%s !!reloc=%s:%s" % (mn[-1], r.group(2), r.group(3))
            continue
        parts = m.group(2).split("\t")
        bs = parts[0].split()
        raw.extend(bs)
        txt = parts[1] if len(parts) > 1 else ""
        txt = txt.split("#")[0]
        txt = " ".join(txt.split())
        if txt:
            mn.append(txt)
    return raw, mn


def disasm(obj, sym, exact):
    rc, so, se = sh(["objdump", "-dr", "--disassemble=" + sym, obj])
    got = extract(so, sym, exact) if rc == 0 else None
    if got is None:
        rc, so, se = sh(["objdump", "-dr", obj], timeout=600)
        got = extract(so, sym, exact)
    return got


# --------------------------------------------------------- DWARF reading
#
# objdump --dwarf=info prints one entry per line block:
#
#   <1><2d>: Abbrev Number: 2 (DW_TAG_subprogram)
#      <2e>   DW_AT_name        : op_12
#   <2><4a>: Abbrev Number: 3 (DW_TAG_formal_parameter)
#      <4b>   DW_AT_name        : a
#      <52>   DW_AT_location    : 2 byte block: 91 7c (DW_OP_fbreg: -4)
#
# The leading <N> is the tree depth.  A formal parameter one level
# below the matching subprogram is a parameter OF that subprogram.

DIE = re.compile(r"^\s*<(\d+)><[0-9a-f]+>:\s*Abbrev Number:\s*\d+\s*\((\S+)\)")
ATTR = re.compile(r"^\s*<[0-9a-f]+>\s+(DW_AT_\w+)\s*:\s*(.*?)\s*$")


def clean(text):
    text = " ".join(text.split())
    return text


STRPREFIX = re.compile(r"^\((?:indexed string|indirect string)[^)]*\):\s*")


def dwname(text):
    """objdump prints a string attribute as `(indexed string: 0x5): a`.
    The parenthesised part is objdump telling the reader WHERE in the
    string table it found the name; the name is what follows.  Keeping
    the prefix would have put objdump's bookkeeping into the parameter
    name column."""
    return STRPREFIX.sub("", text.strip())


def dwarf_params(text, sym):
    """[(name, location)] for the subprogram named `sym`.

    More than one subprogram can carry the name.  swift's `@_cdecl`
    emits a C-entry thunk beside the real function, and the thunk has
    no DW_TAG_formal_parameter children at all, so the first match is
    not always the one holding the parameter table.  Every match is
    collected and the first one that actually has parameters wins."""
    lines = text.splitlines()
    depth = None
    tag = None
    attrs = {}
    entries = []
    for ln in lines:
        m = DIE.match(ln)
        if m:
            if tag is not None:
                entries.append((depth, tag, attrs))
            depth = int(m.group(1))
            tag = m.group(2)
            attrs = {}
            continue
        a = ATTR.match(ln)
        if a and tag is not None:
            attrs[a.group(1)] = a.group(2)
    if tag is not None:
        entries.append((depth, tag, attrs))

    hits = []
    for idx, (d, t, at) in enumerate(entries):
        if t != "DW_TAG_subprogram":
            continue
        names = []
        if "DW_AT_name" in at:
            names.append(dwname(at["DW_AT_name"]))
        if "DW_AT_linkage_name" in at:
            names.append(dwname(at["DW_AT_linkage_name"]))
        for nm in names:
            if nm == sym or sym in nm:
                hits.append(idx)
                break
    if not hits:
        return None
    best = []
    for k in hits:
        base = entries[k][0]
        got = []
        for d, t, at in entries[k + 1:]:
            if d <= base:
                break
            if d != base + 1:
                continue
            if t != "DW_TAG_formal_parameter":
                continue
            nm = clean(dwname(at.get("DW_AT_name", "(unnamed)")))
            loc = clean(at.get("DW_AT_location", "(no location)"))
            got.append((nm, loc))
        if got:
            return got
        best = got
    return best


def dwarf(obj, sym):
    rc, so, se = sh(["objdump", "--dwarf=info", obj], timeout=600)
    if rc != 0:
        return None, "objdump --dwarf=info rc=%d" % rc
    got = dwarf_params(so, sym)
    if got is None:
        return None, "no DW_TAG_subprogram named %s" % sym
    if not got:
        return None, "subprogram %s has no DW_TAG_formal_parameter" % sym
    return got, None


# ------------------------------------------------------------ compiling

GOMOD = "module opprobe\n\ngo 1.26\n"

CLANG = "/usr/bin/clang"
CLANGXX = "/usr/bin/clang++"
SWIFTC = "/persist/swift/usr/bin/swiftc"


def compile_probe(p, d, mode):
    """(rc, artifact path, diagnostic text)."""
    if LANG == "c":
        src = os.path.join(d, "unit.c")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANG, "-std=c17"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "cpp":
        src = os.path.join(d, "unit.cpp")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANGXX, "-std=c++20"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "rust":
        src = os.path.join(d, "unit.rs")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        if mode == "anchor":
            opt = ["-C", "opt-level=0", "-g"]
        else:
            opt = ["-C", "opt-level=1", "-C", "debug-assertions=off"]
        cmd = (["rustc", "--crate-type=lib", "--emit=obj"] + opt
               + ["-o", obj, src])
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "go":
        open(os.path.join(d, "go.mod"), "w").write(GOMOD)
        open(os.path.join(d, "main.go"), "w").write(p["source"])
        obj = os.path.join(d, "bin_%s" % mode)
        cmd = ["go", "build"]
        if mode == "anchor":
            cmd.append("-gcflags=-N -l")
        cmd.extend(["-o", obj, "."])
        rc, so, se = sh(cmd, cwd=d, timeout=300)
        return rc, obj, (se or so)
    if LANG == "swift":
        src = os.path.join(d, "unit.swift")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-Onone", "-g"] if mode == "anchor" else ["-O"]
        cmd = [SWIFTC] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd, timeout=300)
        return rc, obj, (se or so)
    raise KeyError(LANG)


DIAG = re.compile(r"^[^\s:]+:\d+(:\d+)?:")


def firstline(txt):
    """the compiler's own words for why it refused.

    The first line is not reliably the reason.  clang leads with a
    warning and puts the error underneath.  go leads with a banner
    naming the package -- `# opprobe` -- and its diagnostics never
    contain the word `error` at all, so a rule that only looked for
    that word recorded the banner and threw the testimony away.
    Three passes, in order: a line saying `error`, a line in the
    `file:line:col:` diagnostic shape, then the first line that is
    not a banner."""
    lines = []
    for ln in txt.splitlines():
        s = ln.strip()
        if s:
            lines.append(s)
    for ln in lines:
        if re.search(r"\berror\b", ln, re.I):
            return ln[:200]
    for ln in lines:
        if DIAG.match(ln):
            return ln[:200]
    for ln in lines:
        if not ln.startswith("#"):
            return ln[:200]
    if lines:
        return lines[0][:200]
    return "(no diagnostic)"


def write_unit(n, build, obj, sym, exact):
    got = disasm(obj, sym, exact)
    if got is None:
        rc2, so2, se2 = sh(["objdump", "-t", obj])
        near = 0
        for l in so2.splitlines():
            if sym in l:
                near += 1
        out.write("op_%d|%s|NOSYM|%s\n"
                  % (n, build, esc("symbol %s absent, %d near matches"
                                   % (sym, near))))
        return False
    raw, mn = got
    out.write("op_%d|%s|OK|%s|%s\n"
              % (n, build, " ".join(esc(x) for x in raw),
                 ";".join(esc(x) for x in mn)))
    return True


t0 = time.time()
tally = {"REFUSED": 0, "ACCEPTED": 0, "ANCHOR_OK": 0, "SHIP_OK": 0,
         "DWARF": 0}

for k, p in enumerate(PROBES):
    n = p["n"]
    sym = p["symbol"]
    exact = p["symbol_exact"]
    d = os.path.join(WORK, "n%d" % n)
    shutil.rmtree(d, ignore_errors=True)
    os.makedirs(d)

    rc, obj, err = compile_probe(p, d, "ship")
    if rc != 0 or not os.path.exists(obj):
        out.write("op_%d|REFUSED|%s\n" % (n, esc(firstline(err))))
        tally["REFUSED"] += 1
        out.flush()
        shutil.rmtree(d, ignore_errors=True)
        continue
    tally["ACCEPTED"] += 1
    if write_unit(n, "SHIP", obj, sym, exact):
        tally["SHIP_OK"] += 1

    rc, aobj, aerr = compile_probe(p, d, "anchor")
    if rc != 0 or not os.path.exists(aobj):
        out.write("op_%d|ANCHOR|BUILDFAIL|%s\n" % (n, esc(firstline(aerr))))
    else:
        if write_unit(n, "ANCHOR", aobj, sym, exact):
            tally["ANCHOR_OK"] += 1
        rows, why = dwarf(aobj, sym)
        if rows is None:
            out.write("op_%d|ANCHOR|NODWARF|%s\n" % (n, esc(why)))
        else:
            joined = ";".join("%s=%s" % (esc(a), esc(b)) for a, b in rows)
            out.write("op_%d|ANCHOR|DWARF|%s\n" % (n, joined))
            tally["DWARF"] += 1
    out.flush()
    shutil.rmtree(d, ignore_errors=True)

    if (k + 1) % 25 == 0 or (k + 1) == len(PROBES):
        el = time.time() - t0
        print("[progress] %s [%d/%d] elapsed %.1fs mean %.2fs  "
              "REFUSED %d ACCEPTED %d SHIP_OK %d ANCHOR_OK %d DWARF %d"
              % (LANG, k + 1, len(PROBES), el, el / (k + 1),
                 tally["REFUSED"], tally["ACCEPTED"], tally["SHIP_OK"],
                 tally["ANCHOR_OK"], tally["DWARF"]))
        sys.stdout.flush()

out.close()
print("done: %s -> %s" % (json.dumps(tally), OUT))

PY_EOF
echo "--- lane finished, rc=$?"
date -u +%Y-%m-%dT%H:%M:%SZ
