#!/bin/sh
# op-pipeline lane -- cpp -- generated by
# Research/op_pipeline/lane_gen.py .  Do not hand-edit.
# steps 1b/2/3: compile-or-refuse, then the ANCHOR and SHIP
# builds of every probe the compiler accepted, then objdump
# extraction, then the anchor's DWARF parameter table.
set -u
export HOME=/work
export PATH=/persist/swift/usr/bin:$PATH
export GOTOOLCHAIN=local
export GOPROXY=off
export GOFLAGS=-mod=mod
ROOT=/work/regen_cpp_c0080
export GOCACHE="$ROOT/gocache"
export GOPATH="$ROOT/gopath"
# swift's binaries want libncurses.so.6 and the image ships
# only libncursesw.so.6.6; the symlink lives in the image's
# own /usr/lib and does NOT survive a container restart.
if [ -f /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 ]; then
  ln -sf /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 \
     /usr/lib/x86_64-linux-gnu/libncurses.so.6 2>/dev/null
  ldconfig 2>/dev/null
fi
echo "=== op pipeline -- cpp -- 400 candidate probes ==="
date -u +%Y-%m-%dT%H:%M:%SZ
# refuse in seconds rather than in an hour
if ! /usr/bin/clang++ --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: /usr/bin/clang++ is not runnable in this container."
  echo "!! tried: /usr/bin/clang++ --version"
  exit 4
fi
/usr/bin/clang++ --version 2>&1 | head -2
if ! objdump --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: objdump is not runnable."
  exit 4
fi
objdump --version 2>&1 | head -1
rm -rf "$ROOT"; mkdir -p "$ROOT" "$GOCACHE" "$GOPATH"
df -Pm /work | awk 'NR==2{print "free /work: " $4 " MB"}'
FREE=`df -Pm /work | awk 'NR==2{print $4}'`
if [ "$FREE" -lt 400 ]; then
  echo "!! REFUSING TO START: only $FREE MB free on /work, need 400"
  exit 3
fi
base64 -d <<'T_EOF' | gunzip > "$ROOT/table.json"
H4sIAAAAAAAC/73d347d1n3F8VeZqjctkNT8rUVubvYf0BbIC/SyKgRJntgG5BlBlhAHQd69I8eT
xj5rk1wUsHoTREkVL54z5HcOzsbnTy/evX745tPrb+5f/PPdi7fv37/4zd2Lx08fP/+7r57+9asP
99/cP7x6+g9evZ2mPv3Txx8/fv6vvP/w+Ob+h6f/1v/86cXD078Q0zQ9/fkPf/z+zeO7z//fj+9f
/fSHL/76p6/uf3z99vPf/PHDp/vPf/r46cPbn/53v/rq7qe/8C9/zd1vf3v35ruH1x/+ePd3//by
4e+/e3j77tPX93f/+vaHj19/9/Dx33/xZ4/fv3/94f4Xf/Zw/4enf//y4f7Hj/cfHu5evvivly/u
Xn/6+Pjy4fmf6h9e/ffrj3ev/uPt20/f373+zd2nhx++++bh/uu7H759/PD0H/zuw9M/6t2bf3z5
8KeXD3dP//fh/uOnp7/r9dM/0t2bf3n58OeXDy/+/Ju7/19fan3Z6yuwvn69/g9vv3394ZW3F2ov
7L0I7MXPe//yoj7t/Xm5M5dqLu25DMzlzdz/fHx8Z62d1drZXjsH1s43a3/37vH1x2rW4EUNXuzB
S2DwcjvYvlk1NbfZc1tgbruZ+zf3Lmfzqjav9uY1sHnVm/3XuavN3d7cA5u73Pzu8eGbKy/2poZv
9vAtMHzbGW6/4qUirOwIq0CE1SSH/xxg9kteKsDKDrAKBFjV3nL/NVcpVnaKVSDFCnL5X+v7wsuu
wqzsMKtAmBUPxvuvvOq0sjutAp1W8/74izf6UuFWdrhVINxqOXMF/PeAarmyW64CLVdt/wpcvvWr
tCs77SqQdrWeugT+u0CVXtmlV4HSq9vSe/Xm997va6X6ruy+q0Df1W3fvfr9T7+hojuTocoOdtkh
UHaYxOT33isMlXOwcw6BnMNtzr367s337uurKg52xSFQcYAY/PD5De19hgjVbrDbDYF2w227vfp0
abNKNtjJhkCy4SbZ3pifI0LVGew6Q6DOcFNnnz8Tt8aqEIMdYgiEGJoaW818K6vsgp1dCGQXVjWY
MAeryIIdWQhEFroa7N6rVGXBriwEKgs3lfX146c37+6duVSFRbuwGCgs3hTWT0lprVWBRTuwGAgs
3gTWt6/f/d4aq+KKdlwxEFe8iaunv9baqqqKdlUxUFW8qaqfPgRxxqqcop1TDOQUZznW/7iDqqpo
VxUDVcVFb7Y/36CKK9pxxUBcscnNF55Hqq9o9xUDfcVVbrZ/mlVg0Q4sBgKLN4H1l4/unLUqr2jn
FQN5xU2v9W9es4qs2Y6sORBZ8zQYbd+9ZtVas91ac6C15pvW+vmTaffX4Vkl12wn1xxIrhmDzWZ5
zaq8Zru85kB5zRxMdm/Zswqw2Q6wORBg87y32R6uKmy2K2wOVNi8DIbbj6xZZdhsZ9gcyLD5JsO+
4FsGs0qx2U6xOZBi8zre7T+4VJDNdpDNgSCb+3C3/ehSYTbbYTYHwmzehqvNh9eiwmyxw2wJhNky
DUe7d/FFldlil9kSKLOl9lf7d7VFJdpiJ9oSSLQFB+PtW9uiYm2xY20JxNrC/fH2m14122I32xJo
tmUeTrfjZVHFttjFtgSKbVkOZl/4YVfpttjptgTSbWlH6/2fdhVwix1wSyDglpuAu3A8a1Hhttjh
tgTCbfk53P72IXbpjNaism2xs20JZNuy6c3uQa2moq3Z0dYC0dYmPfnCaa2moq3Z0dYC0dZqsNq9
gTXVas1utRZotQa9+dq5raY6rdmd1gKd1rgz3H/FVaU1u9JaoNLaPB5+8XeTpmKt2bHWArHWlqP1
/muvYq3ZsdYCsdbaeP3VVm2q1ppday1Qa209nO+/+iremh1vLRBvrY/nf8HnrU2lXLNTrgVSrm1n
roD9HlhV2a122a2BslunE1fg4mNgVam32qm3BlJvrdOXwX83qPpb7fpbA/W34sRluPpgWFUMrnYM
roEYXHn+OvjvB9WGq92Ga6AN10Eb2me+VlWEq12Ea6AI10ERXjr4taoWXO0WXAMtuLbRbvP016oC
cLUDcA0E4DoIwAtHwFbVfavdfWug+9Y+Wn3hTNSqam+1a28N1N46qL1rh8G6irxuR14PRF7Xkeee
COuq57rdcz3Qc133nPtlgq7Srdvp1gPp1jFc7J4N6yrUuh1qPRBqncPV7gGxrrKs21nWA1nW5+Fq
9yamuqzbXdYDXdZ1l/lfze+qybrdZD3QZF03mX1erKsk63aS9UCSdZ1k7qGxrnKs2znWAznWdY6Z
XwHrqsO63WE90GFdd5j7TZhNBdhmB9gWCLBtGi/2P0jZVIdtdodtgQ7bame4/cnJpnJss3NsC+TY
hvFw/5G1qSLb7CLbAkW2cTzc/glXSbbZSbYFkmzTSWZ/z21TQbbZQbYFgmxbdiZfuKupLNvsLNsC
Wba1veX+bU3V2WbX2Raos03X2cXv6m8q0jY70rZApG19b7jZaptqtc1utS3Qatu2t9u8oZdiBspm
BirADNQ0HQ6315daX/b6CqyvvfXuU60UOFA2OFABcKAmHW7Xvw9Rih8omx+oAD9QEw/Gu8+2UhpB
2RpBBTSCmub98ebTrZRLULZLUAGXoKZlf7r3fCtFFJRNFFSAKKip7S+37/Grmr7a09fA9PXE9Au3
u66uQLevQA9cgX7mCvj3vE1dgc2+AlvgCmwnroD7M6Acg7Idgwo4BlXT/n67dJRkULZkUAHJoKrO
bPdvAIo0KJs0qABpUIVTl8C+AyjYoGzYoAKwQZVOPv/YWinQoGzQoAKgQdUvUu86LVaKMCibMKgA
YVC16M3msbVSZkHZZkEFzIKqpif7x9ZKMQVlMwUVYAqq1sFq+y6mSs52CSrgElR1vfnSsbVSQkHZ
QkEFhIKqbWe4/Yorp6Bsp6ACTkFhGg+/+JuLYgvKZgsqwBYU6mi9/9qrbLMNgwoYBgWM11+tVuUZ
lO0ZVMAzKPBwvv/qq3izaYMK0AaFeTz/Cz6mVd5B2d5BBbyDwnLmCvjvAVV2NoJQAQSh0E5cgauP
AZV6No1QARqhsJ6+DP67QdWfDSZUAEwo9BOX4fKDQcWgDSlUAFIobOevg/1+UMJC2cJCBYSF4qAN
3WNrpZyFsp2FCjgLxUERXjm2VopcKJtcqAC5UMRo93vztVYBaNMLFaAXioMA9I+tlTIYyjYYKmAw
FOfRav/0VimHoWyHoQIOQ3FQe5eOrZXCGMrGGCqAMRR15JnH1kpRDGVTDBWgGIq659xvHiiKoWyK
oQIUQ7EPF5vH1kqRDGWTDBUgGYrbcLV5bK2UyVC2yVABk6HmabjavIkpk6Fsk6ECJkPNusvsMwCl
TIayTYYKmAw16yZzj62VMhnKNhkqYDLUrJPMPLZWSmQoW2SogMhQs84x86tiSmIoW2KogMRQs+4w
99sximEom2GoAMNQcxsv9j9IUQ5D2Q5DBRyGmted4fYnJwpiKBtiqADEUHMfD7/wyFJFZlsMFbAY
at7Gw92fcKUxlK0xVEBjqEUnmf21N0UxlE0xVIBiqKV2Jvt3NeUwlO0wVMBhqAV7y+3bmkIYykYY
KoAw1KLr7OIX+xXBUDbBUAGCoZZ5b7jZaspgKNtgqIDBUMuyt9u+oatks/mFCvALtbTD4fZ61W02
v1ABfqGWdW+9/1RT4WZDDBWAGGrR4fYF34dQIkPZIkMFRIZatoPx9rNN2Qxl2wwVsBmqTfvj3aeb
AhrKBhoqADRUq/3p5vNNMQ1lMw0VYBqqYX+5e49XUEPZUEMFoIZqPDHdv90psaFssaECYkO1+cwV
8O95Ku9staECakO15cQVsH8GVOXZbkMF3IZqbX+/XToKbSgbbagA2lBtPbP9wg1AxZ4NN1QAbqjW
T10C/w6gks+WGyogN1TTyXfh2JrCGsrGGiqANdQz1vCLt/ilc2uKZiibZqgAzVDPNMPNaPfgmnIY
ynYYKuAw1LPDcLP5wsk1xS6UzS5UgF2oZ3bhdrZ7J1PGQtnGQgWMhXo2Fm5GXzu7pqSFsqWFCkgL
9Swt6OX+a676zbYWKmAt1LO1IJdf/AVGsQtlswsVYBfqmV3Yme+/+irfbH+hAv5CPfsLcv7VfFUO
Q9kOQwUchnp2GPb226+/4hjK5hgqwDFUn3b2f8EntspnKNtnqIDPUL1OXQL/XaAazwYbKgA2VMeZ
S3DxYaAIh7IJhwoQDtV5/jr47wfVgTbqUAHUofp85jpcfTwo6KFs6KEC0EP1xbgQ/jtCVaKtP1RA
f6g+qkT7HJvyH8r2HyrgP1QfteGlg2yKgSibgagAA1G9D4ebJ9kUBVE2BVEBCqL6KAUvHGVTHkTZ
HkQFPIjapuHsC0e6lAdRtgdRAQ+itlH3XTvMpkCIskGICoAQtQ1yzz3NpiiIsimIClAQtQ3Kzv1G
gmIgymYgKsBA1DaPJ7vn2RQFUTYFUQEKorZlPNs90KYciLIdiAo4ELW18Wz3TqYKzTYgKmBA1DYo
NP98gPIfyvYfKuA/1DaoM/tMm7IfyrYfKmA/1DaIM/NQG5T6AFt9QEB9wDQIM++bZFDSA2zpAQHp
AdOgyMxvz0ARD7CJBwSIB0zYmWx/tALlO8D2HRDwHTBxb7n7WQoU7gAbd0AAd8A07yy3n1xQtgNs
2wEB2wHTsrPc/ilvanezd7fA7kGcud+NgyIdYJMOCJAOmNa9zRdubV1N7/b0Hpjed6f797ZNTd/s
6Vtg+qDTrh0AgOIbYPMNCPANqGl3uVltym6AbTcgYDegane4e1tXZANssgEBsgGF4+X2fFVwNteA
ANeA4u58++Gm0AbYaAMCaANqkHDXvzEBxTfA5hsQ4BtQy9F6+xGnJAfYkgMCkgOqHay3H3Iq6mzP
AQHPAbUebHcfcyrqbNYBAdYB1Q+m23d6VXW27ICA7IDazmz373nKeIBtPCBgPADTqUtg3/gU9AAb
ekAAegDqzCVwfwyU9QDbekDAegBwcAHs5FHSA2zpAQHpAeCp8RduAir7bO4BAe4BmM9dA/8uoOLP
Bh8QAB+AQfz5x92gkAfYyAMCyAPwy+i7zrRBkQ6wSQcESAdgHYw2j7tB+Q2w/QYE/AagDzb7x92g
uAbYXAMCXAOwjWa7tzJlM8C2GRCwGcBpMPrScTcooQG20ICA0ADW3nL/NVcNZxsNCBgNIHaWX/w1
RnENsLkGBLgGkIfz/VdfBZztNiDgNoDzzvyrAav8Bth+AwJ+A7gc7/dff5VxNuOAAOMAtp39X/Dh
rXIdYLsOCLgO4HrqEvjvAtV4NvSAAPQA9jOX4OrDQEWfTT8gQD+A2/nrYL8fFAYBG4NAAIPAPJ25
DlcfDwqIgA1EIABEYC7jQvjvCFWJthqBgBqBeVSJ7nE3KDcCthuBgBuBedSGV467QfERsPkIBPgI
zPNw+Hvz1VYpaBMSCBASmEcp6B93g3IkYDsSCDgSmNtwtn/oC8qRgO1IIOBIYB5136XjblCQBGxI
AgFIAvMg98zjblCEBGxCAgFCAvOg7NyvJig+AjYfgQAfgWUaTzaPu0ERErAJCQQICSw1nm0ed4Py
I2D7EQj4EVgwnm3eyZQdAduOQMCOwDIoNP/QgHIjYLsRCLgRWAZ15h53gzIjYJsRCJgRWAZx5h53
U1oEbC0CAS0CyyDMzG+UKSECthCBgBCBZVBk7jdoFA0Bm4ZAgIbA0ncm+x+tKBcCtguBgAuBZdtb
bn+WolAI2CgEAigE2rSz3H9yKRMCtgmBgAmBVjvL3Z9yJULAFiEQECHQBnFmfz1OURCwKQgEKAg0
7m32b23KgIBtQCBgQKDNu9P9e5vqNBt/QAB/QBt02sWTAIp9gM0+IMA+oLXd5Wa1KfMBtvmAgPmA
tu4Ot2/rKt5s6gEB6gGtHy+356uCs5kHBJgHtG13vv1wU9gDbOwBAewB6yDhvuAbE0p9gK0+IKA+
YK2j9fYjTvkPsP0HBPwHrDhY7z7kFAIBG4FAAIHAyoPt5mNOURCwKQgEKAis88F0906vMAjYGAQC
GATW5cz2C/c8lXe2CoGACoG1nboE/o1PhZ4tQyAgQ2Bdz1wC+8dA9Z5tQyBgQ2DtBxfATx5VezYM
gQAMgXU7Nd6/CSgcAjYOgQAOgT6duwb2XUDpELB1CAR0CPRB/F047qZACNggBAIgBJ5BiF8H/qUT
bwqAgA1AIABA4BmAULvdQ2/Ke4DtPSDgPeDZe1CzL5x7U8ADbOABAeABz8CDXG7f1lTf2Z4DAp4D
nj0Htfva6TflOsB2HRBwHfDsOgzH+6+8qjrbdkDAdsCz7TAaf/F3GwU9wIYeEIAe8Aw97F8B+z2g
zAfY5gMC5gOezYfRFbjatkp/gK0/IKA/4Fl/OLgE/rtARZ7NQCDAQGDD/iX4gk93lQwBW4ZAQIbA
xrNXwX8vqAK0sQgEsAhs88mrcPHxoAAJ2IAEAoAEtsW6FP67QlWijUoggEpgaycvxeUHhopGm5pA
gJrAtnrXwn9fqIa0BQoEBApsOw1pn5BTCgVshQIBhQLbTjleOSRHxVHQ5igY4Cg4TXvbvXNyVCgF
bZSCAZSC004o+kflqGwK2jYFAzYFJ+wt98+MUekUtHUKBnQKTjtVeOnAHBVQQRuoYACo4DSOQfPM
HBVOQRunYACn4DTuPvMrDlQ0BW2aggGaglPbXW2enKMCKmgDFQwAFZzW3eXm4Tkqn4K2T8GAT8Gp
7y53b2ybGr7Zw7fA8HG/2QcRqGwK2jYFAzYFa9xu7ik6KpmCtkzBgEzBGqebeZCOSqWgrVIwoFKw
xtnmfV2NyqKgbVEwYFGwxr1mfkOHiqGgzVAwwFCw5v3V9gcyVAoFbYWCAYWCtRyMdz+BoUIoaCMU
DCAUrLY//sLjTJWbrVAwoFCw1v3x9k+8SjdboWBAoWCN0839Nh4VQEEboGAAoGBtB7P9O52yJ2jb
EwzYE8R0tN6+1Sl2gjY7wQA7QYwr7toJBCpygjY5wQA5QeBovNl0SpygLU4wIE4QPNru3ugVNUGb
mmCAmiDmU+PtK6D6zoYmGIAmiOXoCthPPAVO0AYnGAAniHHgXf9eBhU+QRufYACfINYTF8B/7qnU
syUKBiQKoh9fAPvJp5LPFikYECmI7Xi++exTNAVtmoIBmoKcjte7937lU9D2KRjwKcg6Od+/BSqr
grZVwYBVQeLsVbDvg4qsoE1WMEBWkDx5FeyfB1WDtlvBgFtBzsfXwK4h5VbQdisYcCvI5ez+CzcE
FYU2X8EAX0G205fBvyOoNLQJCwYIC3Kchv6xPCq4gjZcwQBcQd4k4XWIjgqqoA1VMABVkNt4t3ks
j8qloO1SMOBScJ7Gs/1jeVQQBW2IggGIgnPtLHfvbMqdoO1OMOBOcMZ496VjeVT+BG1/ggF/gjMP
xvuvvCo826BgwKDgPO+Pv/jbjgIpaIMUDIAUnJczV8B/D6i8s20KBmwKzm3/ClwtXKVU0FYqGFAq
OK+nLoH/LlCRZ3MVDHAVnPv+JfiCj3+VYEFbsGBAsOC8nb0K9ntBoRa0UQsGUAsu08mrcPHxoKAL
2tAFA9AFl7Iuhf+uUJVo4xcM4BdccPJSXH1gKBKDNonBAInBhd618N8XqiFtKYMBKYPLTkO6x/Ko
tAzaWgYDWgaXnXK8dCxPsRm02QwG2AwubW+7eSxP4Rm08QwG8AwuO6F44VieMjRoGxoMGBpc+t7y
CyfTlKJBW9FgQNHgslOF147lKUiDNqTBAKTBNo5B91ieQjRoIxoMIBps4+5zv/2gCA3ahAYDhAYb
dle7x/IUpEEb0mAA0mDj7nL3WJ5yNGg7Ggw4Gmzz7nL3xqb6zVY0GFA02Mb95p9jUIYGbUODAUOD
bdxu9rE8JWjQFjQYEDTYxunmHstTegZtPYMBPYNtnG3m19iUmUHbzGDAzGAb95r7bR3FZdDmMhjg
MrhO+6v9D2SUlkFby2BAy+BaB+PtT2AUlkEby2AAy+CK/fH+40xpGbS1DAa0DK7cH2//xKt0s7UM
BrQMruN0s7+Wp6AM2lAGA1AG1+Vg9oU7nco328hgwMjg2o7W+7c6VXE2j8EAj8F1XHEXDycoGoM2
jcEAjcG1H403m07JGLRlDAZkDK7b0Xb3Rq9IDNokBgMkBvt0arx9BVTf2SAGAyAGex1dAfuJp2AM
2jAGAzAG+zjwvuB7GUrIoC1kMCBksPPEBbCfe8rKoG1lMGBlsM/HF8B98ikwgzaYwQCYwb4czzef
fYrNoM1mMMBmsLfj9fa9XzWfDWcwAGewryfnX7gFqvizBQ0GBA32fvYq+PdBlYG2osGAosG+nbwK
7s+DcjRoOxoMOBrcpuNrYNeQQjRoIxoMIBrc6ux+/4agIA3akAYDkAY3nL4M9h1BSRq0JQ0GJA1u
4zS8cCxP4Rm08QwG8Aze4Bl/+wy8dDZPcRm0uQwGuAzecBm/Hu8e0FM+Bm0fgwEfgzc+xq+3Xzil
p0gM2iQGAyQGb0iMm/n23U5VoG1gMGBg8MbA+PX4a+f1lIZBW8NgQMPgjYYhr8C598D//vn/ACUV
vkRCiAEA
T_EOF
echo "payload bytes: $(wc -c < "$ROOT/table.json")"
python3 - "$ROOT" <<'PY_EOF'

import json, os, re, shutil, subprocess, sys, time

ROOT = sys.argv[1]
T = json.load(open(os.path.join(ROOT, "table.json")))
LANG = T["language"]
PROBES = T["probes"]
OUT = T["out"]
out = open(OUT, "w")
WORK = os.path.join(ROOT, "u")

# --- verbatim delimiter codec, copied from verbatim_diag.py ---
def esc(text):
    """make `text` safe to place in one pipe-delimited field, reversibly."""
    for raw, rep in _ENC:
        text = text.replace(raw, rep)
    return text

_ENC = [('\\', '\\\\'), ('|', '\\p'), (';', '\\s'), ('\n', '\\n'), ('\r', '\\r')]
MARKER = '#verbatim-escape v1'
out.write(MARKER + '\n')


print("op lane %s: %d candidate probes" % (LANG, len(PROBES)))
sys.stdout.flush()


def sh(cmd, cwd=None, timeout=180):
    try:
        p = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE, timeout=timeout)
        so = p.stdout.decode("utf-8", "replace")
        se = p.stderr.decode("utf-8", "replace")
        return p.returncode, so, se
    except subprocess.TimeoutExpired:
        return 124, "", "TIMEOUT after %ds" % timeout
    except OSError as e:
        return 125, "", "OSError %s" % e


# ------------------------------------------------------ objdump reading

LABEL = re.compile(r"^([0-9a-f]+)\s+<(.+)>:\s*$")
INSN = re.compile(r"^\s*([0-9a-f]+):\t(.*)$")
RELOC = re.compile(r"^\s+([0-9a-f]+): (R_\S+)\t(.+?)\s*$")


def extract(text, sym, exact):
    """the two columns for one symbol.

    bytes  every byte objdump printed, in order, flattened
    mnem   the instruction text, with objdump's own trailing `# ...`
           comment dropped -- that comment is arithmetic objdump did
           for the reader, not part of the instruction.  A relocation
           is appended to the instruction it applies to as
           ` !!reloc=<type>:<symbol>`, because in an object file the
           call displacement is literally zero and the callee's name
           lives only in the relocation.
    """
    lines = text.splitlines()
    k = -1
    for idx, ln in enumerate(lines):
        m = LABEL.match(ln)
        if not m:
            continue
        lab = m.group(2)
        hit = (lab == sym) if exact else (sym in lab)
        if hit:
            k = idx
            break
    if k < 0:
        return None
    raw = []
    mn = []
    for ln in lines[k + 1:]:
        if LABEL.match(ln):
            break
        m = INSN.match(ln)
        if not m:
            r = RELOC.match(ln)
            if r and mn:
                mn[-1] = "%s !!reloc=%s:%s" % (mn[-1], r.group(2), r.group(3))
            continue
        parts = m.group(2).split("\t")
        bs = parts[0].split()
        raw.extend(bs)
        txt = parts[1] if len(parts) > 1 else ""
        txt = txt.split("#")[0]
        txt = " ".join(txt.split())
        if txt:
            mn.append(txt)
    return raw, mn


def disasm(obj, sym, exact):
    rc, so, se = sh(["objdump", "-dr", "--disassemble=" + sym, obj])
    got = extract(so, sym, exact) if rc == 0 else None
    if got is None:
        rc, so, se = sh(["objdump", "-dr", obj], timeout=600)
        got = extract(so, sym, exact)
    return got


# --------------------------------------------------------- DWARF reading
#
# objdump --dwarf=info prints one entry per line block:
#
#   <1><2d>: Abbrev Number: 2 (DW_TAG_subprogram)
#      <2e>   DW_AT_name        : op_12
#   <2><4a>: Abbrev Number: 3 (DW_TAG_formal_parameter)
#      <4b>   DW_AT_name        : a
#      <52>   DW_AT_location    : 2 byte block: 91 7c (DW_OP_fbreg: -4)
#
# The leading <N> is the tree depth.  A formal parameter one level
# below the matching subprogram is a parameter OF that subprogram.

DIE = re.compile(r"^\s*<(\d+)><[0-9a-f]+>:\s*Abbrev Number:\s*\d+\s*\((\S+)\)")
ATTR = re.compile(r"^\s*<[0-9a-f]+>\s+(DW_AT_\w+)\s*:\s*(.*?)\s*$")


def clean(text):
    text = " ".join(text.split())
    return text


STRPREFIX = re.compile(r"^\((?:indexed string|indirect string)[^)]*\):\s*")


def dwname(text):
    """objdump prints a string attribute as `(indexed string: 0x5): a`.
    The parenthesised part is objdump telling the reader WHERE in the
    string table it found the name; the name is what follows.  Keeping
    the prefix would have put objdump's bookkeeping into the parameter
    name column."""
    return STRPREFIX.sub("", text.strip())


def dwarf_params(text, sym):
    """[(name, location)] for the subprogram named `sym`.

    More than one subprogram can carry the name.  swift's `@_cdecl`
    emits a C-entry thunk beside the real function, and the thunk has
    no DW_TAG_formal_parameter children at all, so the first match is
    not always the one holding the parameter table.  Every match is
    collected and the first one that actually has parameters wins."""
    lines = text.splitlines()
    depth = None
    tag = None
    attrs = {}
    entries = []
    for ln in lines:
        m = DIE.match(ln)
        if m:
            if tag is not None:
                entries.append((depth, tag, attrs))
            depth = int(m.group(1))
            tag = m.group(2)
            attrs = {}
            continue
        a = ATTR.match(ln)
        if a and tag is not None:
            attrs[a.group(1)] = a.group(2)
    if tag is not None:
        entries.append((depth, tag, attrs))

    hits = []
    for idx, (d, t, at) in enumerate(entries):
        if t != "DW_TAG_subprogram":
            continue
        names = []
        if "DW_AT_name" in at:
            names.append(dwname(at["DW_AT_name"]))
        if "DW_AT_linkage_name" in at:
            names.append(dwname(at["DW_AT_linkage_name"]))
        for nm in names:
            if nm == sym or sym in nm:
                hits.append(idx)
                break
    if not hits:
        return None
    best = []
    for k in hits:
        base = entries[k][0]
        got = []
        for d, t, at in entries[k + 1:]:
            if d <= base:
                break
            if d != base + 1:
                continue
            if t != "DW_TAG_formal_parameter":
                continue
            nm = clean(dwname(at.get("DW_AT_name", "(unnamed)")))
            loc = clean(at.get("DW_AT_location", "(no location)"))
            got.append((nm, loc))
        if got:
            return got
        best = got
    return best


def dwarf(obj, sym):
    rc, so, se = sh(["objdump", "--dwarf=info", obj], timeout=600)
    if rc != 0:
        return None, "objdump --dwarf=info rc=%d" % rc
    got = dwarf_params(so, sym)
    if got is None:
        return None, "no DW_TAG_subprogram named %s" % sym
    if not got:
        return None, "subprogram %s has no DW_TAG_formal_parameter" % sym
    return got, None


# ------------------------------------------------------------ compiling

GOMOD = "module opprobe\n\ngo 1.26\n"

CLANG = "/usr/bin/clang"
CLANGXX = "/usr/bin/clang++"
SWIFTC = "/persist/swift/usr/bin/swiftc"


def compile_probe(p, d, mode):
    """(rc, artifact path, diagnostic text)."""
    if LANG == "c":
        src = os.path.join(d, "unit.c")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANG, "-std=c17"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "cpp":
        src = os.path.join(d, "unit.cpp")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANGXX, "-std=c++20"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "rust":
        src = os.path.join(d, "unit.rs")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        if mode == "anchor":
            opt = ["-C", "opt-level=0", "-g"]
        else:
            opt = ["-C", "opt-level=1", "-C", "debug-assertions=off"]
        cmd = (["rustc", "--crate-type=lib", "--emit=obj"] + opt
               + ["-o", obj, src])
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "go":
        open(os.path.join(d, "go.mod"), "w").write(GOMOD)
        open(os.path.join(d, "main.go"), "w").write(p["source"])
        obj = os.path.join(d, "bin_%s" % mode)
        cmd = ["go", "build"]
        if mode == "anchor":
            cmd.append("-gcflags=-N -l")
        cmd.extend(["-o", obj, "."])
        rc, so, se = sh(cmd, cwd=d, timeout=300)
        return rc, obj, (se or so)
    if LANG == "swift":
        src = os.path.join(d, "unit.swift")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-Onone", "-g"] if mode == "anchor" else ["-O"]
        cmd = [SWIFTC] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd, timeout=300)
        return rc, obj, (se or so)
    raise KeyError(LANG)


DIAG = re.compile(r"^[^\s:]+:\d+(:\d+)?:")


def firstline(txt):
    """the compiler's own words for why it refused.

    The first line is not reliably the reason.  clang leads with a
    warning and puts the error underneath.  go leads with a banner
    naming the package -- `# opprobe` -- and its diagnostics never
    contain the word `error` at all, so a rule that only looked for
    that word recorded the banner and threw the testimony away.
    Three passes, in order: a line saying `error`, a line in the
    `file:line:col:` diagnostic shape, then the first line that is
    not a banner."""
    lines = []
    for ln in txt.splitlines():
        s = ln.strip()
        if s:
            lines.append(s)
    for ln in lines:
        if re.search(r"\berror\b", ln, re.I):
            return ln[:200]
    for ln in lines:
        if DIAG.match(ln):
            return ln[:200]
    for ln in lines:
        if not ln.startswith("#"):
            return ln[:200]
    if lines:
        return lines[0][:200]
    return "(no diagnostic)"


def write_unit(n, build, obj, sym, exact):
    got = disasm(obj, sym, exact)
    if got is None:
        rc2, so2, se2 = sh(["objdump", "-t", obj])
        near = 0
        for l in so2.splitlines():
            if sym in l:
                near += 1
        out.write("op_%d|%s|NOSYM|%s\n"
                  % (n, build, esc("symbol %s absent, %d near matches"
                                   % (sym, near))))
        return False
    raw, mn = got
    out.write("op_%d|%s|OK|%s|%s\n"
              % (n, build, " ".join(esc(x) for x in raw),
                 ";".join(esc(x) for x in mn)))
    return True


t0 = time.time()
tally = {"REFUSED": 0, "ACCEPTED": 0, "ANCHOR_OK": 0, "SHIP_OK": 0,
         "DWARF": 0}

for k, p in enumerate(PROBES):
    n = p["n"]
    sym = p["symbol"]
    exact = p["symbol_exact"]
    d = os.path.join(WORK, "n%d" % n)
    shutil.rmtree(d, ignore_errors=True)
    os.makedirs(d)

    rc, obj, err = compile_probe(p, d, "ship")
    if rc != 0 or not os.path.exists(obj):
        out.write("op_%d|REFUSED|%s\n" % (n, esc(firstline(err))))
        tally["REFUSED"] += 1
        out.flush()
        shutil.rmtree(d, ignore_errors=True)
        continue
    tally["ACCEPTED"] += 1
    if write_unit(n, "SHIP", obj, sym, exact):
        tally["SHIP_OK"] += 1

    rc, aobj, aerr = compile_probe(p, d, "anchor")
    if rc != 0 or not os.path.exists(aobj):
        out.write("op_%d|ANCHOR|BUILDFAIL|%s\n" % (n, esc(firstline(aerr))))
    else:
        if write_unit(n, "ANCHOR", aobj, sym, exact):
            tally["ANCHOR_OK"] += 1
        rows, why = dwarf(aobj, sym)
        if rows is None:
            out.write("op_%d|ANCHOR|NODWARF|%s\n" % (n, esc(why)))
        else:
            joined = ";".join("%s=%s" % (esc(a), esc(b)) for a, b in rows)
            out.write("op_%d|ANCHOR|DWARF|%s\n" % (n, joined))
            tally["DWARF"] += 1
    out.flush()
    shutil.rmtree(d, ignore_errors=True)

    if (k + 1) % 25 == 0 or (k + 1) == len(PROBES):
        el = time.time() - t0
        print("[progress] %s [%d/%d] elapsed %.1fs mean %.2fs  "
              "REFUSED %d ACCEPTED %d SHIP_OK %d ANCHOR_OK %d DWARF %d"
              % (LANG, k + 1, len(PROBES), el, el / (k + 1),
                 tally["REFUSED"], tally["ACCEPTED"], tally["SHIP_OK"],
                 tally["ANCHOR_OK"], tally["DWARF"]))
        sys.stdout.flush()

out.close()
print("done: %s -> %s" % (json.dumps(tally), OUT))

PY_EOF
echo "--- lane finished, rc=$?"
date -u +%Y-%m-%dT%H:%M:%SZ
