#!/bin/sh
# op-pipeline lane -- c -- generated by
# Research/op_pipeline/lane_gen.py .  Do not hand-edit.
# steps 1b/2/3: compile-or-refuse, then the ANCHOR and SHIP
# builds of every probe the compiler accepted, then objdump
# extraction, then the anchor's DWARF parameter table.
set -u
export HOME=/work
export PATH=/persist/swift/usr/bin:$PATH
export GOTOOLCHAIN=local
export GOPROXY=off
export GOFLAGS=-mod=mod
ROOT=/work/regen_c_c0047
export GOCACHE="$ROOT/gocache"
export GOPATH="$ROOT/gopath"
# swift's binaries want libncurses.so.6 and the image ships
# only libncursesw.so.6.6; the symlink lives in the image's
# own /usr/lib and does NOT survive a container restart.
if [ -f /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 ]; then
  ln -sf /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 \
     /usr/lib/x86_64-linux-gnu/libncurses.so.6 2>/dev/null
  ldconfig 2>/dev/null
fi
echo "=== op pipeline -- c -- 400 candidate probes ==="
date -u +%Y-%m-%dT%H:%M:%SZ
# refuse in seconds rather than in an hour
if ! /usr/bin/clang --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: /usr/bin/clang is not runnable in this container."
  echo "!! tried: /usr/bin/clang --version"
  exit 4
fi
/usr/bin/clang --version 2>&1 | head -2
if ! objdump --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: objdump is not runnable."
  exit 4
fi
objdump --version 2>&1 | head -1
rm -rf "$ROOT"; mkdir -p "$ROOT" "$GOCACHE" "$GOPATH"
df -Pm /work | awk 'NR==2{print "free /work: " $4 " MB"}'
FREE=`df -Pm /work | awk 'NR==2{print $4}'`
if [ "$FREE" -lt 400 ]; then
  echo "!! REFUSING TO START: only $FREE MB free on /work, need 400"
  exit 3
fi
base64 -d <<'T_EOF' | gunzip > "$ROOT/table.json"
H4sIAAAAAAAC/8Wd3Y4cx5WEX2XABQzZkK06+X/WxgK7F36BvVwuBhyK+gGoGYIisRZkvftWURxP
dZ7IbkaxT9I3kma6uyais09+Xc5A/Prs9Yv779+/+P7Vs3+/efby2dc3zx7ev9v+/Zv1n9+8ffX9
q/vbl7cvlyXVv7z7x7vtAW/ePty9+nl9zP/8+ux+/Ye0tizrz3/+5ae7h9fbcx/e3H744bN//fT2
1T9evNxe993b96+2nz68f/vywzW/+dPNhxf8/WVu/vznm7sf71+8/eXmn/+8+dM3z+//7cf7l6/f
f/vq5m8/v/v2x/t3f/nhP7of3j08vP7w0+f3t7fvfnnz6uG729uvvvq/lz+8eHv77o+/Lr9tr/XV
9p9Sfv/BH5/fP/6Nj4+7efH1zeNDbu7WB/z6/P5m/d/bV+/ev72/ebG9xt1fn9//9vz+2W9f3zxJ
FyRdaOniLD2GXrr00reHUNIDkh5o6cFZeuuVh155I4VHJDzSwqOj8G8f3t+9fnWqO+51//4ASnZC
shMtOznK/u71w4vu3U571R9+T4nOSHSmRWdH0T+8eP3dqea817z9mpJckORCSy6Oktfnnioue8Xr
bynBFQmutODqKPj1w/33p4rrXvH2a0pyQ5IbLbk5S765/c+XL9//dKq8GeW/P4oyQJEBShug7gb8
/e36d5waoNaAD49iDBDEbEIzmyzeBoCdTBZjAL+dCSI3oclNxNsA89EXMfLZz78gdhOa3cST3X7+
4eHt6cKXE3L78HtKNOI2oblNordoNPUkWu382BPEcEIznCR/C+zckwQs4AcfIjqhiU48ie7nH7+/
f/Xth+8mpw6cgN3uUZQBiO+E5jsp/gb0mCcF6CdpTxDtCU17Uv3l28lfgX569iP2E5r9pM0xALjQ
Ri7QViAKFJoCRf2tALuhAhvoTTEgDgw0BwZPDnx//1Ed2BfDCQt2j6SMQDwYaB4MMsUIuzsGwUbQ
G2RAbBhoNgxhhhFmiwwB2sBukgGxYqBZMcQZJvTbZIjQA3KjDIgVA82KIc2wwGwSIUEP2B0iIFoM
NC2GPMsEOCPz2IsDgxLxY6D5MZR5loBpWc5Ywo9MxJSBZspQp1liPy91bAj9oUGEGWjCDG2GHRas
QoNW8GiF6DLQdBl0mg1weOgZN/jpERFvRpo34zLRFDs+4nLOFHp+RMSekWbP6Mmeu/9+suGEOR//
lRGOWDPSrBn3rPmHP3ye8KfPwPZSX4GPRAwff7qpPvMRWJ8ORSO2jDRbxugo+r/Wh51qjnvN268p
yYglI82SMTlK/vv2/w1LOVWd9qo/PoISjvgx0vwYs6dwO97yiezhOBuJRoQYaUKMxVH0f7+Au10s
e+VPD6LkIxqMNA3G6i0fvPHVyOfffUR/kaa/2Jzlj74txdZ7cOmL0sgIxH+R5r+oU4wAi0GxEfSK
SIj5Es18aXE2YsjAaemduIi/IysQ6SWa9JLMscIuiiQDK/hVgdgv0eyXgrMV5+4+p9C78Sl3oEeG
IC5MNBemOM0QsDzi2BB+hSBqTDQ1pjTLkNGWktLQlYN7S0JcmWiuTHmuNWDB5AvW8KsG0Wei6TOV
WdaMt50y9Obw/oPYNNFsmupkc8DCqZfM4VcOItdEk2vyJNfbu++676jphFc//J4SjSg10ZSaPCn1
9sO5bQntVPgJn/7rMYz4jMg002SaF1fxb7p3PC+nwt9w73hGDJppBs2eDHr7491P/fudT9Dz4yMo
4Yg4M02cObgKv98WcXejNYdT6R8fQ4lHdJlpusyedHn7Hqs/gcqnB1HyEUtmmiWzI0ve9fdc8x4b
78hbrhkRYqYJMTsSojm8kfcwODyyMRKMuC/T3JeLr2ATQsylEz3MII6EI6bLNNPl6ivcRBBz7YQP
E4gj4YjXMs1rufkKN+OsdbrZUYaILdPElh2JDYQ28p7WzsQ1BqILIrVCk1pxJDUbPix7UBtnD0eS
EacVmtOKI6eZ6GHZM9oweTgSjPis0HxWHPmsP2pX9mA2OmA3kouIrNBEVhyJzBwTKnsUG54LGglG
DFZoBivJVzC6FVNSr5u/91IQkRWayEr2lm9vtpRs5NN3Vwris0LzWSnO8sHeVUov/8AGhiit0JRW
qrN8+5GvvXj6c484rdCcVhw5zZ4CLHtKG5/9G0lGjFZoRivqLBnOOjXK+WFXEa9Vmtfq4m6AnXZ1
sQbQ464ieqs0vVVHehtlKOoe4i4FKEbyEctVmuVqcJffI10NVj1JdhWRXaXJrkZ38Wba12jVs/O+
Is6rNOfVNEU+8CANPKCNQMRXaeKr2d0Iu//VbE2gt8GKmK/SzFcdme/c8Y66577PONlREftVmv1q
nWED2A8rtIHfEhEHVpoDa5tgg90UGzKB3hYRF1aaC6tOsMBsjIocILfGhriw0VzYlgkGmI2hLcgB
dldoiAwbTYZNJlmAJmOToRP8eGyIFRvNii1MM8TOyBbGhtCDsiF+bDQ/tjjLEPtJiUM76I8LoslG
02RLE8ywGNUSMoIGqYZIstEk2fIsE+DQyGMvDkwNxJaNZstW5lkCxkY5Ywk/NxBnNpozmyNnohhh
2/PluRThSDbiykZzZbsqVz4m6EYhwtZ+f8yxDGFDHNlojmzqJ9lECJvuFLMJQkXcqDQ36uInGAUI
ddlpPpAfVMSKSrOiiqNsM9RU9qLZIaaIBpWmQQ1+kgfhQQ073ceyg4rIT2ny0+gsHrzpsRfPv/OI
9JQmPU2+4kffiTR1Dhz8OqSI9ZRmPc0zbAALIUMb+NWA+E5pvtPia8OQdrV0PhwFXUVUpzTVaZ1i
BFgQFRvBrwjEeUpznjZfI87dUdbWefEZd5UVMaDSDKg6yw6wNHRoB7s6FLWQKN1CossyyY7BNrL+
ASNPju0nijpKlO4o0UWmGmMWy/oHnDeGXzEBGRNoY8IkY0ZbzfoXjJw5uOco6jhRuuNElzjXGrBo
4gVr+FWTkDWJtsaRUk1IcL3azgY2I6ioBUXpFhRdHIkURgTXK+5lH0gIKmpDUboNRZfiKf1N/26X
E9lvyHe7IsmVluzImyAeuF5vL5pOByrqRFG6E0WX5ikbxOPWK54I58NxitpQlG5D0cWRJHE0cL3k
XvuRZKCiJhSlm1BU/LixDwau13pSTeYCFfWeKN17ouJHg/3Ri/VaT3LJAxeKmk6UbjpRCa5y+1Dg
er1TyWQmUFHXidJdJyrRVXYfCVyvdyqbTAQq6jdRut9EJbnK7oeYpFPV7ABDdEY3mqj40ZmNVKxX
e9JMhykUdZgo3WGi4kdlJgy4XuxJMZsFVNRaonRriYofk/VRwPVaT3rJJKCijhKlO0pU/FisOxy3
XupJLXckTlELidItJCp+9NUf71mv9aSWPM+jqHFE6cYRDYurXHSbJSydav6+CmoZUbplRIM4i7c3
UoL04uk7J6hZROlmEQ3BVzzYrULoxPNbFmoUUbpRREP0FW8+6iF20unPO2IyukdEgx+TmVN768We
RLNn9RR1hijdGaIh+wqGEy73ug+MOMRmdD+IhuItH8y4YuTzQw6RGt0FosGP1AYJh/WSO/WH4g2K
mj+Ubv7Q0LzF9/gWmtFOUhxq+1C67UODeku3E16NdnbGo1YPpVs9NC4zxFsH4oIdoG1AdEf3eGgU
bxvsjhfFWEBvfKjNQ+k2D41+fHfmaIbGHeMdP5WhqN1D6XYPjXGCCXYHjBGZQG+CqO9D6b4Pjcnf
BLMNxgQsYDdC1PuhdO+HxuxvQL8Vxgz0k5shagBRugFEY/GXbzeDAvTTOwGiQLoDRGOdYwCch3Xk
w4GhiLiQ7gTR2GbZASZjG9rBj0fEinQziEadZIf9jOjIDPaDgrpBlO4G0bT4W2GhKS3ABhqbUCeI
0p0gmmSSBWhYJBk6wU8L1AyidDOIpjDNEDsuUhgbQs8L1AyidDOIJj+mBLE+TTuW5FN9ito/lG7/
0Ou2f+wyXoNgn25lH49JryPZPkXdHkp3e+h1uz2M8D7ep1uTx143mfBT1NuhdG+HXre3w8gGIT/d
ejr2yvmcn6JeDqV7OfS6vRxWvB1ztZNOjzZEhnTnhl63c8MIx4E/3ao39uoPZf4UNXAo3cCh123g
wBaABaDAAnoVoB4OpXs49Lo9HNCC0belrZOj9+HglyXUz6F0P4det5/jjBl2UWxNHdgMfmUgFqQ7
O/S6nR3QjCEbb+UdvRtH0Ri1eCjd4qHXbfE4ZwdYHHFoB786ECPSrR6ak7sd5+4852Qd+Yw70Kj5
Q+nmD815oilgmeRzpvArBdEl3Q6iucwzZbjVlDPOHN1zEH/SHSKa62x7wMKpF+3hVw+iVLppRHOb
Z894O2pn/Dm8LyGGpTtJNOt0g8AC0ssG0SsI9Zco3V+ixZdwbXCwdFxLZwdRi4nSLSZafGkWxwdL
x7GHEoSo1UTpVhMtwdmAPkRYQi+ezBGifhOl+020+LIqihKWDlEPpAlR14nSXSdakrN4FKorqZd/
IFaH2k6UbjvR4kuhg1hh6eDzWLIQNZ4o3XiixZU5TbiwnOIlmy9EPSdK95xocSVJc+ijnEIje9wD
NZwo3XCipXmLNkHD0oxwNmuIuk6U7jrRot7iTdywqBHPJg5Rz4nSPSdaF2/x/Yiri9FOjjfUcKJ0
w4lWV7IDYY56SnV8lAN1myjdbaLVlehsALGeAh2dQUStJkq3mmh15TkTQ6ynLMcmEVGXidJdJlpd
Oa4/wldPAY48vIdaS5RuLdHqSm7mSFI9RTb2HBJqKlG6qURr8RaNbunUYrXz93BQS4nSLSVaq78F
9qZNrcAC+i4NaihRuqFEa3O3AO1rzVpwYHNDNEc3lGhVdwvsCFBrADsHUD+J0v0k2lx5zp5EbKc0
R59BRJ0kSneSaBN32Wj+NQHq+QGIekiU7iHRFiaYYCdgC8gEegSi7hGlu0e0uVLeKLvRTmHvYHgD
NY4o3TiiLU2woEe/lpADJAGithGl20a05QkGmF2gZeQAvQ8gHqTbRbSVSRYAH8rQB9oMRIZ0r4i2
OsEMsDdWZAS/RSI2pFtGtLmy4bljJu2UDz/jhAlqH1G6fUSbzrEC7JU6sILeLlEvidK9JKrLFCvM
hqkLNoLdMlFPidI9JaoyxYZ+01TBLpDbJmouUbq5RDVMMcFsGBqwC+xugTpMlO4wUY3TbEDTUuMZ
N/iRibpNlO42UU0TTbFzU9M5U/jhiTiTbjpRzfNMsZ+afMYS+qODqJPuPFEtUwyxqKUFm0HDFuo8
UbrzRLXOMwIOkXrOjwNTBDEo3YCi2mbaAsZIO2sLP0cQj9JNKKquPIoiknrKoXRKUhfQerL9kJO+
PeOq0h/fcZyR3C738UFHEpLr0wWJFlq0OIru8pHb1faauXTk+uyAJAdacnCUbLOR2wX3qulk5PoC
EQmPtPDoKbybcNvlTmRzA219ekKiEy06OYqGmcjtmnvlRxKR62tkJD/T8rO3fPDGZyOff/cLkl9o
+cVZPv7qtF249+DQl6b1hSoyotJG1ClGgMVQsRH8imjIiEYb0ZyNGIDwduXeiWMIvL6SIiuUtkLn
WAEWhQ6soFeFIPYTmv1kcbZifFN6u3jvxuH70uuLIS4UmgtFphlil4fI2BB+hSBqFJoaJcwyZLSl
SBi6cnBvEcSVQnOlxLnWgAUTL1jDrxpEn0LTp6RZ1gy3HUlDb47uP4LYVGg2lTzZHLBw8iVz+JWD
yFVochVPcu0zjtvl9kaQCcf16YhShaZU8aRUlG/cLnkinE83ri+ByFRoMpXmKv5N/463U+FvyHcc
MajQDCqeDGpzjdsFT2SzqUZdAiLOQBNnWFyF20TfdslT6XScb30JRJeBpsvgSZcwz7hd80T9+0Py
EUsGmiWDI0ve9fdcwx4b78hbrgERYqAJMTgSYneeY7vYTjB3iGN9MuK+QHNfSL6CuwzjdsFONJdg
XF8AMV2gmS5kX+FdfnG7YCecSy+uL4B4LdC8FoqvcDPOSqebHWWI2AJNbMGR2Ey+Y7vcTjUb7Fif
jkgt0KQWHEmtzyxuV9tpJhOL67MRpwWa04Ijp3V5xe1iO8VcWlGXiPgs0nwWHfns9Ozddq2dXurA
3fpcRGSRJrLoSGTdeaHtYju93Pmg9cmIwSLNYDH4Cka3YmLodfP3XiIiskgTWYze8u3NlhiNfPru
SkR8Fmk+i8lZPti7Yurl8xtYRJQWaUqL2Vm+/cjnXjz9uUecFmlOi46c1h8G3K62k02eAFyfjRgt
0owWq7NkOOuqUX5g2CFeizSvxeZuAJh2zRrAjztEb5Gmt+hIbzhWsV1zr/9IpEKXhFgu0SyXFnf5
PdKlxaonyS4hsks02SVxF2+mfRKrnp33CXFeojkvhSnygQdh4AFtBCK+RBNfiu5G2P0vRWsCvQ0m
xHyJZr7kyHznjnekPfd9xsmOhNgv0eyX8gwb7H6YMrSB3hIT4sBEc2AqE2wwm2IqyAR6W0RcmGgu
THWCBWZjrMgBdmtEXJhoLkxtggF2Y2jIAXpXQGSYaDJMOskCOBl16AQ/HjNixUyzYl6mGWJnZF7G
htCDMiN+zDQ/ZplliPmkZBnawX5cMqLJTNNkDhPMsBiVAzKCBqmMSDLTJJnjLBPQ0Mhx7MWBqYHY
MtNsmdM8S8DYSGcs4ecG4sxMc2Z25EybI9yutzPhQIowI67MNFdetx3lNGA0ihJubSi7lNGhPGFG
TJlpprxu+wmSb0KFW9lJp55NFmbEk5nmyet2myDxKF64lZl0+g9kDDPiyUzz5HXbS6AFdvypNYAd
egXRY6Hp8brdJEj+IHK4dZR0HhzLHRZEjYWmxut2lQyNsIth6ytBRvArAhFjoYnxup0lIyNG37C2
AhPgxsGvWAXxY6H58bptJuctAQsknrGEXyWIHwvNj9ftOBlZMmTqre0EeHIUqgsiyEIT5HV7Ty6Y
AhZKPmcKv1IQXxaaL0uZYcq5+9mlQF8+4852QexZaPYsda41YMnUC9bwqwaRaaHJtLSp1gy3o3be
n6P7EmLXQrNr0S9gElhE+ikm0SupIsKtNOHWZapJwy2rLuddOrp3VcS/lebfKl/CJruYqnySTfxq
QnRcaTqu7nRso47VMjGdd6yIhCtNwtWdhHHosVoGPpR8rIh+K02/Nfnb0McfawIWkBnIiji30pxb
3TkXBSGrxdsDaciKqLbSVFuLvwUoFFgLMOFAMLAigq00wVZ3gh2EI6sF12MJyYp4tdK8Wr151cQk
q0FTNitZEYVWmkKrN4WaQynVACd7IKUhtmw0W7ZlgnQTnWwLks/mJxvixkZzY5MJFpgQZRNkAZuk
bIgJG82ELUywoB+ALSAHyOHXEBU2mgqbNxWCcEozRMiHUxqiwUbTYPOmQRuxbAYG6ZxlQyzYaBZs
3ixowpbNcCCbuGyIARvNgM2bAfujiM3AH3kMsSHqazT1NW/qMwermsE99jxVQ5zXaM5rbYJ0dPuo
NegAf7+oIeprNPU1nWKEvUHUFBtB3xFSxIBKM6AuM4wAO6Au0Ah+G1REgkqToMoMI8xoUIE2sPNB
EQsqzYLqzYL2rKUaEqTPWSriQKU5UOMM8Wg6asQe8ONRERMqzYSa5lhh56OmgRX8gESEqDQhqjch
jrIrakDxYHxFES8qzYta5hjRY6OWgQ8kPSqiR6XpUescG+xOUQc+0HsFYkmlWVLbPCOAG+2cG7Ql
iCqVpkrVOZaAXVQHdrCbqaB2F6HbXWTx5sozR2ZkMWx5/LSMoOYXoZtfZJFphphdVRYZG8JurIJ6
YYTuhZElzDKk31plCUM7yM1VUFeM0F0xssRZZnTbqyxx6AW3wQpqkBG6QUaWNMuKflORJQ29IHcU
QX0yQvfJyJJnmgFnaT7vyYGBWpA1hbamzLUGTNVywRp+tFZkTaWtqVOtsZ+jet4Y+sPUkC2NtqXN
ssUAmixtaAmPaIrsUNoOnWoHHC56wRV+uqCGGqEbakSWyebY8SLLJXPo+YLaaoRuqxHxZlkQOBUx
DMunTgW10wjdTiNyfXa9VGApEvaPPJQ6FdRAI3QDjUj0lt+nTkWiUU+mTgV1zAjdMSOSvMWD1KlI
Mvr51KmgJhmhm2REsrsFdhpmawA9/hB50l0xIsVbPk6dihTjwaHUqaD+GKH7Y0TqFCPAYqjYCH5F
ILKku2RE2gwjRl/RpEE3Dn49Q00zQjfNiOg8S8AC0TOW0KsEddAI3UEjYZlhyRC2wwI9OQraqJtG
6G4aCTLRFLtQgpwzhV8piC/pxhoJYYYp526hhwB9+Yz76KjbRuhuGwlxrjVgycQL1vCrBpEp3YIj
IU21ZrQdhXTen4P7EmrMEboxR0L+AiaBRZQ/xSR+JSHCpdt1JJSpJo23rHLepcN7F+Jfuo1HQv0S
NoHFVD/JJn41ITqm+3skuNOxSZ1KsEzMpk4FdfkI3eUjwZ2EYepUgmXgI6lTQQ0/Qjf8SFz8behS
pxIXYAGXOhXU+CN0449Ed84FqVOJFm/51KmgDiChO4AkBn8LQNpSYgAm8GFLQV1AQncBSXQnWJw6
lWjB9VDqVFArkNCtQBK9ebVPnUo0aEqmTgU1AgndCCTRm0LNmZdogJM96oIagYRuBJJYJkjvU6cS
C5JPpk4FNQQJ3RAksU6woE+dSqzIAjJ1KqgjSOiOIIltggVmADbkADv8EBXSHUESvanQZm4kGiKk
4zaCOoKE7giS5E2DJnUqycAgmzoV1BEkdEeQJG8W7FOnkgwHkqlTQf1AQvcDSfJmwP58YzLwRx5r
RH1AQvcBSfKmPnMKKxncY89doSYgoZuAJKUJ0tHto5SgA/z9ItQFJHQXkKQ8xQh7gyhlbAR9Rwi1
AQndBiSpzDAC7ICpQCMObIOIBOlOIEl1hhF2NFRoAz0fEAvSvUCSvFnQHsdMhgTpU5ioEUjoRiBJ
OkM8nI6KPeDHI+oCEroLSPIyxwo7H/MysIIekKgFSOgWIMnehDiKxmQDigeDMagBSOgGIMlhjhE9
NuYw8IGkR9QBJHQHkOQ4xwazU+Q48IHdK1Dzj9DNP5LTPCOAG+mcG7QliCrp5h/JeY4ldhfNeWAH
vZmiNiCh24Ake3PluSMz2bDlZ5yWQf1AQvcDSa7TDAG7ah0bwm+siDXpziDJbZYhdmttQzvozRWx
J90eJFlnmWG2Vx16QW6wqElI6CYhKcssK8ymUpahF+yOgtqEhG4TkiIzzUCztMh5T/iBivqFhO4X
khLmWmOnagkXrKFHK+oZErpnSEqcao39HMXzxtAfJkSsdNeQlDTLFgtoJQ0toRENtQwJ3TIkJU+1
Aw6XfMGVA9MF8SvdNiSlTDYHjJdyyRx+viCWpfuGpHizLEqdFsOwB1KnqFVI6FYhuX6rULf9jqKn
jz1C+633UP4UNQcJ3Rwk128OgkaYEOpjVVDvA5tERd1AQncDyfW7gaANKI76WAfUO3Egk4oagIRu
AJLrNwBhM8zAfKz8MVawYxJ1/Ajd8SPX7/iBRgwiqo9tP70bx3KqqPdH6N4fuX7vz9gSsEDiGUv4
VYKolO4Akut3AA0tGX3He6wEQr4c/JKHGoKEbgiS6zcEXTAHLJp8yRx+5SBGpbuD5PrdQUNzhgT/
2COE3DmK8KhTSOhOIbl+p9Ale8DiqRft4VcPYli6aUhqm2bPuXv1tY0d+oy79qiTSOhOIqn6BUwC
y0g/xSR6JaH2IqHbi6Qt800abWVt+QSnDu5pqOlI6KYjafKl7LILq8kn28WvLkTRdCuStDDfruF2
18In+HV030MtSkK3KEmLX8wwsMDipxvGrzBE4HTvkrQ5BG6jsW3A3XQ+FnUwCd3BJG0ObeOQbBtw
9qGkLGpmErqZSVqZZEgfl21lZAaZmUVNTUI3NUmbw9IoONsGCH0gPYu6m4TubpLWJpmBoqOtjew4
EB9FHU5CdzhJm0PJgzBtG8DxsUQtanMSus1JdAoTm1itYvxls7WoyUnoJifRKaRrjvcohlr2aA9q
chK6yUk0zDLBRG01DI1g87ao2UnoZifROMsME7rVODSDTd6ibiehu51E0ywz+pGpaegFOy4RedLd
TqJTyBPEkBRTJx9DQt1OQnc7iU4hThvJVQycdC4XdTsJ3e0kOoU3TThXMWuyCV3U6yR0r5PoFM7s
D4QqBkzyMCjqcRK6x0l0ClmaA2yKkfKTzq3972//D/TnehtamQEA
T_EOF
echo "payload bytes: $(wc -c < "$ROOT/table.json")"
python3 - "$ROOT" <<'PY_EOF'

import json, os, re, shutil, subprocess, sys, time

ROOT = sys.argv[1]
T = json.load(open(os.path.join(ROOT, "table.json")))
LANG = T["language"]
PROBES = T["probes"]
OUT = T["out"]
out = open(OUT, "w")
WORK = os.path.join(ROOT, "u")

# --- verbatim delimiter codec, copied from verbatim_diag.py ---
def esc(text):
    """make `text` safe to place in one pipe-delimited field, reversibly."""
    for raw, rep in _ENC:
        text = text.replace(raw, rep)
    return text

_ENC = [('\\', '\\\\'), ('|', '\\p'), (';', '\\s'), ('\n', '\\n'), ('\r', '\\r')]
MARKER = '#verbatim-escape v1'
out.write(MARKER + '\n')


print("op lane %s: %d candidate probes" % (LANG, len(PROBES)))
sys.stdout.flush()


def sh(cmd, cwd=None, timeout=180):
    try:
        p = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE, timeout=timeout)
        so = p.stdout.decode("utf-8", "replace")
        se = p.stderr.decode("utf-8", "replace")
        return p.returncode, so, se
    except subprocess.TimeoutExpired:
        return 124, "", "TIMEOUT after %ds" % timeout
    except OSError as e:
        return 125, "", "OSError %s" % e


# ------------------------------------------------------ objdump reading

LABEL = re.compile(r"^([0-9a-f]+)\s+<(.+)>:\s*$")
INSN = re.compile(r"^\s*([0-9a-f]+):\t(.*)$")
RELOC = re.compile(r"^\s+([0-9a-f]+): (R_\S+)\t(.+?)\s*$")


def extract(text, sym, exact):
    """the two columns for one symbol.

    bytes  every byte objdump printed, in order, flattened
    mnem   the instruction text, with objdump's own trailing `# ...`
           comment dropped -- that comment is arithmetic objdump did
           for the reader, not part of the instruction.  A relocation
           is appended to the instruction it applies to as
           ` !!reloc=<type>:<symbol>`, because in an object file the
           call displacement is literally zero and the callee's name
           lives only in the relocation.
    """
    lines = text.splitlines()
    k = -1
    for idx, ln in enumerate(lines):
        m = LABEL.match(ln)
        if not m:
            continue
        lab = m.group(2)
        hit = (lab == sym) if exact else (sym in lab)
        if hit:
            k = idx
            break
    if k < 0:
        return None
    raw = []
    mn = []
    for ln in lines[k + 1:]:
        if LABEL.match(ln):
            break
        m = INSN.match(ln)
        if not m:
            r = RELOC.match(ln)
            if r and mn:
                mn[-1] = "%s !!reloc=%s:%s" % (mn[-1], r.group(2), r.group(3))
            continue
        parts = m.group(2).split("\t")
        bs = parts[0].split()
        raw.extend(bs)
        txt = parts[1] if len(parts) > 1 else ""
        txt = txt.split("#")[0]
        txt = " ".join(txt.split())
        if txt:
            mn.append(txt)
    return raw, mn


def disasm(obj, sym, exact):
    rc, so, se = sh(["objdump", "-dr", "--disassemble=" + sym, obj])
    got = extract(so, sym, exact) if rc == 0 else None
    if got is None:
        rc, so, se = sh(["objdump", "-dr", obj], timeout=600)
        got = extract(so, sym, exact)
    return got


# --------------------------------------------------------- DWARF reading
#
# objdump --dwarf=info prints one entry per line block:
#
#   <1><2d>: Abbrev Number: 2 (DW_TAG_subprogram)
#      <2e>   DW_AT_name        : op_12
#   <2><4a>: Abbrev Number: 3 (DW_TAG_formal_parameter)
#      <4b>   DW_AT_name        : a
#      <52>   DW_AT_location    : 2 byte block: 91 7c (DW_OP_fbreg: -4)
#
# The leading <N> is the tree depth.  A formal parameter one level
# below the matching subprogram is a parameter OF that subprogram.

DIE = re.compile(r"^\s*<(\d+)><[0-9a-f]+>:\s*Abbrev Number:\s*\d+\s*\((\S+)\)")
ATTR = re.compile(r"^\s*<[0-9a-f]+>\s+(DW_AT_\w+)\s*:\s*(.*?)\s*$")


def clean(text):
    text = " ".join(text.split())
    return text


STRPREFIX = re.compile(r"^\((?:indexed string|indirect string)[^)]*\):\s*")


def dwname(text):
    """objdump prints a string attribute as `(indexed string: 0x5): a`.
    The parenthesised part is objdump telling the reader WHERE in the
    string table it found the name; the name is what follows.  Keeping
    the prefix would have put objdump's bookkeeping into the parameter
    name column."""
    return STRPREFIX.sub("", text.strip())


def dwarf_params(text, sym):
    """[(name, location)] for the subprogram named `sym`.

    More than one subprogram can carry the name.  swift's `@_cdecl`
    emits a C-entry thunk beside the real function, and the thunk has
    no DW_TAG_formal_parameter children at all, so the first match is
    not always the one holding the parameter table.  Every match is
    collected and the first one that actually has parameters wins."""
    lines = text.splitlines()
    depth = None
    tag = None
    attrs = {}
    entries = []
    for ln in lines:
        m = DIE.match(ln)
        if m:
            if tag is not None:
                entries.append((depth, tag, attrs))
            depth = int(m.group(1))
            tag = m.group(2)
            attrs = {}
            continue
        a = ATTR.match(ln)
        if a and tag is not None:
            attrs[a.group(1)] = a.group(2)
    if tag is not None:
        entries.append((depth, tag, attrs))

    hits = []
    for idx, (d, t, at) in enumerate(entries):
        if t != "DW_TAG_subprogram":
            continue
        names = []
        if "DW_AT_name" in at:
            names.append(dwname(at["DW_AT_name"]))
        if "DW_AT_linkage_name" in at:
            names.append(dwname(at["DW_AT_linkage_name"]))
        for nm in names:
            if nm == sym or sym in nm:
                hits.append(idx)
                break
    if not hits:
        return None
    best = []
    for k in hits:
        base = entries[k][0]
        got = []
        for d, t, at in entries[k + 1:]:
            if d <= base:
                break
            if d != base + 1:
                continue
            if t != "DW_TAG_formal_parameter":
                continue
            nm = clean(dwname(at.get("DW_AT_name", "(unnamed)")))
            loc = clean(at.get("DW_AT_location", "(no location)"))
            got.append((nm, loc))
        if got:
            return got
        best = got
    return best


def dwarf(obj, sym):
    rc, so, se = sh(["objdump", "--dwarf=info", obj], timeout=600)
    if rc != 0:
        return None, "objdump --dwarf=info rc=%d" % rc
    got = dwarf_params(so, sym)
    if got is None:
        return None, "no DW_TAG_subprogram named %s" % sym
    if not got:
        return None, "subprogram %s has no DW_TAG_formal_parameter" % sym
    return got, None


# ------------------------------------------------------------ compiling

GOMOD = "module opprobe\n\ngo 1.26\n"

CLANG = "/usr/bin/clang"
CLANGXX = "/usr/bin/clang++"
SWIFTC = "/persist/swift/usr/bin/swiftc"


def compile_probe(p, d, mode):
    """(rc, artifact path, diagnostic text)."""
    if LANG == "c":
        src = os.path.join(d, "unit.c")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANG, "-std=c17"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "cpp":
        src = os.path.join(d, "unit.cpp")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANGXX, "-std=c++20"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "rust":
        src = os.path.join(d, "unit.rs")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        if mode == "anchor":
            opt = ["-C", "opt-level=0", "-g"]
        else:
            opt = ["-C", "opt-level=1", "-C", "debug-assertions=off"]
        cmd = (["rustc", "--crate-type=lib", "--emit=obj"] + opt
               + ["-o", obj, src])
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "go":
        open(os.path.join(d, "go.mod"), "w").write(GOMOD)
        open(os.path.join(d, "main.go"), "w").write(p["source"])
        obj = os.path.join(d, "bin_%s" % mode)
        cmd = ["go", "build"]
        if mode == "anchor":
            cmd.append("-gcflags=-N -l")
        cmd.extend(["-o", obj, "."])
        rc, so, se = sh(cmd, cwd=d, timeout=300)
        return rc, obj, (se or so)
    if LANG == "swift":
        src = os.path.join(d, "unit.swift")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-Onone", "-g"] if mode == "anchor" else ["-O"]
        cmd = [SWIFTC] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd, timeout=300)
        return rc, obj, (se or so)
    raise KeyError(LANG)


DIAG = re.compile(r"^[^\s:]+:\d+(:\d+)?:")


def firstline(txt):
    """the compiler's own words for why it refused.

    The first line is not reliably the reason.  clang leads with a
    warning and puts the error underneath.  go leads with a banner
    naming the package -- `# opprobe` -- and its diagnostics never
    contain the word `error` at all, so a rule that only looked for
    that word recorded the banner and threw the testimony away.
    Three passes, in order: a line saying `error`, a line in the
    `file:line:col:` diagnostic shape, then the first line that is
    not a banner."""
    lines = []
    for ln in txt.splitlines():
        s = ln.strip()
        if s:
            lines.append(s)
    for ln in lines:
        if re.search(r"\berror\b", ln, re.I):
            return ln[:200]
    for ln in lines:
        if DIAG.match(ln):
            return ln[:200]
    for ln in lines:
        if not ln.startswith("#"):
            return ln[:200]
    if lines:
        return lines[0][:200]
    return "(no diagnostic)"


def write_unit(n, build, obj, sym, exact):
    got = disasm(obj, sym, exact)
    if got is None:
        rc2, so2, se2 = sh(["objdump", "-t", obj])
        near = 0
        for l in so2.splitlines():
            if sym in l:
                near += 1
        out.write("op_%d|%s|NOSYM|%s\n"
                  % (n, build, esc("symbol %s absent, %d near matches"
                                   % (sym, near))))
        return False
    raw, mn = got
    out.write("op_%d|%s|OK|%s|%s\n"
              % (n, build, " ".join(esc(x) for x in raw),
                 ";".join(esc(x) for x in mn)))
    return True


t0 = time.time()
tally = {"REFUSED": 0, "ACCEPTED": 0, "ANCHOR_OK": 0, "SHIP_OK": 0,
         "DWARF": 0}

for k, p in enumerate(PROBES):
    n = p["n"]
    sym = p["symbol"]
    exact = p["symbol_exact"]
    d = os.path.join(WORK, "n%d" % n)
    shutil.rmtree(d, ignore_errors=True)
    os.makedirs(d)

    rc, obj, err = compile_probe(p, d, "ship")
    if rc != 0 or not os.path.exists(obj):
        out.write("op_%d|REFUSED|%s\n" % (n, esc(firstline(err))))
        tally["REFUSED"] += 1
        out.flush()
        shutil.rmtree(d, ignore_errors=True)
        continue
    tally["ACCEPTED"] += 1
    if write_unit(n, "SHIP", obj, sym, exact):
        tally["SHIP_OK"] += 1

    rc, aobj, aerr = compile_probe(p, d, "anchor")
    if rc != 0 or not os.path.exists(aobj):
        out.write("op_%d|ANCHOR|BUILDFAIL|%s\n" % (n, esc(firstline(aerr))))
    else:
        if write_unit(n, "ANCHOR", aobj, sym, exact):
            tally["ANCHOR_OK"] += 1
        rows, why = dwarf(aobj, sym)
        if rows is None:
            out.write("op_%d|ANCHOR|NODWARF|%s\n" % (n, esc(why)))
        else:
            joined = ";".join("%s=%s" % (esc(a), esc(b)) for a, b in rows)
            out.write("op_%d|ANCHOR|DWARF|%s\n" % (n, joined))
            tally["DWARF"] += 1
    out.flush()
    shutil.rmtree(d, ignore_errors=True)

    if (k + 1) % 25 == 0 or (k + 1) == len(PROBES):
        el = time.time() - t0
        print("[progress] %s [%d/%d] elapsed %.1fs mean %.2fs  "
              "REFUSED %d ACCEPTED %d SHIP_OK %d ANCHOR_OK %d DWARF %d"
              % (LANG, k + 1, len(PROBES), el, el / (k + 1),
                 tally["REFUSED"], tally["ACCEPTED"], tally["SHIP_OK"],
                 tally["ANCHOR_OK"], tally["DWARF"]))
        sys.stdout.flush()

out.close()
print("done: %s -> %s" % (json.dumps(tally), OUT))

PY_EOF
echo "--- lane finished, rc=$?"
date -u +%Y-%m-%dT%H:%M:%SZ
