#!/bin/sh
# op-pipeline lane -- cpp -- generated by
# Research/op_pipeline/lane_gen.py .  Do not hand-edit.
# steps 1b/2/3: compile-or-refuse, then the ANCHOR and SHIP
# builds of every probe the compiler accepted, then objdump
# extraction, then the anchor's DWARF parameter table.
set -u
export HOME=/work
export PATH=/persist/swift/usr/bin:$PATH
export GOTOOLCHAIN=local
export GOPROXY=off
export GOFLAGS=-mod=mod
ROOT=/work/regen_cpp_c0085
export GOCACHE="$ROOT/gocache"
export GOPATH="$ROOT/gopath"
# swift's binaries want libncurses.so.6 and the image ships
# only libncursesw.so.6.6; the symlink lives in the image's
# own /usr/lib and does NOT survive a container restart.
if [ -f /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 ]; then
  ln -sf /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 \
     /usr/lib/x86_64-linux-gnu/libncurses.so.6 2>/dev/null
  ldconfig 2>/dev/null
fi
echo "=== op pipeline -- cpp -- 400 candidate probes ==="
date -u +%Y-%m-%dT%H:%M:%SZ
# refuse in seconds rather than in an hour
if ! /usr/bin/clang++ --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: /usr/bin/clang++ is not runnable in this container."
  echo "!! tried: /usr/bin/clang++ --version"
  exit 4
fi
/usr/bin/clang++ --version 2>&1 | head -2
if ! objdump --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: objdump is not runnable."
  exit 4
fi
objdump --version 2>&1 | head -1
rm -rf "$ROOT"; mkdir -p "$ROOT" "$GOCACHE" "$GOPATH"
df -Pm /work | awk 'NR==2{print "free /work: " $4 " MB"}'
FREE=`df -Pm /work | awk 'NR==2{print $4}'`
if [ "$FREE" -lt 400 ]; then
  echo "!! REFUSING TO START: only $FREE MB free on /work, need 400"
  exit 3
fi
base64 -d <<'T_EOF' | gunzip > "$ROOT/table.json"
H4sIAAAAAAAC/73dXW8cV3oE4L/CKDcO4I2n3urP3SRAEmD/QC6jBUHJ9AcgkwJNYr0w/N9zJMfi
SFPdM3UI1N4Ykr16Xd095xTHffD8+urdzd33Tzff377689Wrt+/fv/r66tX90+OHX33T/vrNw+33
t3fX7W9cvz0clvFfH395/PCPvH+4f3P7c/un/vfXV3ftLxwOh0P7/Z//8dOb+3cf/t/3768//uar
T797ffvLzdsPf/Ljw9Pth9+9f3p4+3HuN99cffwDf/9jrv70p6s3P97dPPzj6p/+/fXdP/949/bd
07e3V//29ufHb3+8e/yPz37v/qf3Nw+3n/3e3e3f269f393+8nj7cHf1+tV/v351dfP0eP/67o9/
q69+/vH7u9tvr9ofd3Xz9dXPP9w/PF5d//Wh/QtevfmX13e/vr67av97uH18an/CTfsXuXrzl9d3
v72+e/Xb11fPmaEyw86MQGZ8mfn3X7394ebBilwqctmRKxC5dOQPv3ISUyWmnZiBxNSJ393ffW9F
HlTkwY48BCIPO5Ht3KPKPdq5x0DuUef+fSlzMk8q82RnngKZpy8yP939/6+v//Pt26efrNizij3b
sedA7Hkztr9jLSr2YsdeArGXrdj2nrWq0Ksdeg2EXrdCm7sWVB2DXccQqGM4bGV212+oPga7jyHQ
x4Dd0P6CBlXMYBczBIoZaj+7vapBVTTYFQ2BigbuZrefeNXUYDc1BJoahq3kdmeB6mmwexoCPQ3j
fuqOD7oqbLALGwKFDdOZ8P4nXdU22LUNgdqGL2vb3z/0lmsvrqprsOsaAnUNn+raxzWs5e14tFVR
g13UEChqWE/i/tf9/TsnbamKVnZFq0BFq8NJ2r++u795bIuIE1jVs7LrWQXqWeE0sLtWlWpkZTey
CjSyqpO4/3PTszmVamJlN7EKNLGizuzfZ9XByu5gFehgNcjMnT9ylKphZdewCtSwGneC+3dcVbCy
K1gFKlhNMnhv+SzVv8ruXxXoXzXvJffvuapiZVexClSxWmTyF3xbWqqYlV3MKlDMaj0T3r7zVD2N
dk9joKfxsB++c6GnKm60ixsDxY245Ar4z4DqcrS7HANdjrV/BXqXfqpqR7vaMVDtyIsugf8UqKZH
u+kx0PR42vSu33zn/bxG1e9o9zsG+h1P+931dx9/Qm0brhNZNTvazY6BZsdJRH5v3mFV52jXOQbq
HE/r3PWPb35y769qcbRbHAMtjosIfPfhgfa+Q6TqbrS7GwPdjafd7fqpJ/OgKttgV7YhUNmGk8r2
xvwecVDtbLDb2RBoZ8NJO3P/W/6githgF7EhUMSGUmExmY+yql2DXbuGQO0aqAKzzMCqZA12yRoC
JWsYVGB3rVIta7Bb1hBoWcNJy/r2/unNu1srrmpYg92whkDDGk4a1sdKaaVVBWuwC9YQKFjDScH6
4ebdd1ZYVa4Gu1wNgXI1nJQr8/2qQbWqwW5VQ6BVDSetyn3LZFR1arTr1BioU+NBhvW/7hhVqxrt
VjUGWtUIndn+fmNU5Wq0y9UYKFdjycz+fjSqfjXa/WoM9KuRMrP9aVYFa7QL1hgoWONJwbLfFRtV
vRrtejUG6tU46rQdi5cqWaNdssZAyRqnjdD+6qW61mh3rTHQtcaTrtX5avuoKtdoV64xULnGZSOz
2bxG1bxGu3mNgeY1rhuR3SV7UgVssgvYFChg02Evsx1ctbDJbmFToIVN2Ahub1mTqmGTXcOmQA2b
TmrYC94ymFQVm+wqNgWq2MTt3PbGNalCNtmFbAoUsmnYzO1uXZMqZpNdzKZAMZvGzdTm5jWpYjbZ
xWwKFLNp2gxtr+KqmU12M5sCzWya91N3rGqqok12RZsCFW1azoT3lzZV1ia7rE2Bsjat++Hdh35W
nW22O9sc6GzzYTO6XV5m1dhmu7HNgcY240xs/8M+q+o229VtDlS3uc6ltz/tsypws13g5kCBm08K
XMfxrFkVt9kubnOguM2fF7f+M1qzqm2zXdvmQG2bR53ZPag1q9I226VtDpS2edKRO05rzaq0zXZp
mwOlbZ43UtsLmOpqs93V5kBXmxedue/c1qx62mz3tDnQ0+Z1J7h9xxfV0ha7pS2BlrYctoN3/myy
qLK22GVtCZS1BefS+/delbXFLmtLoKwttZ2+t6suqq0tdltbAm1t4dn4/t1X5W2xy9sSKG/LsB3/
Bd+3LqrKLXaVWwJVbhkvuQL+M6Ca3WI3uyXQ7JbpgivQuw2oqrfYVW8JVL1lvvgy+E+Dan+L3f6W
QPtblgsuQ/fGoMrgYpfBJVAGl/Xy62A/D6vqhqvdDddAN1w3uqF95mtVjXC1G+EaaITrRiPsOvi1
qi642l1wDXTBtbZym6e/VlUAV7sAroECuG4UwI4jYKvqfavd+9ZA71uHrdQdZ6JW1fZWu+2tgba3
brS9vsNgqyp5q13y1kDJW3XJc0+ErarPrXafWwN9btV9zn2ZYFXVbbWr2xqobuuymdg9G7aqorba
RW0NFLV13UxtHhCDkgZgSwMISAM4HDZTL2ZoqNCwQyMQWvcy+9V8KGsAtjWAgDWAg+5k7nkxKGwA
NjaAADaAg65k5qExKGsAtjWAgDWAg65j3itgUMgAbGQAAWQAB93DzDdhoIgB2MQAAsQADtN2YvuL
FChkADYygAAygMO8E9z95gSKGYDNDCDADOCwbAfv2LJWFXy1g6+B4Ot2cPcTrrQB2NoAAtoAoCuZ
+54blDUA2xpAwBoAsBPZX9WUNABbGkBAGgBqL7m9rClnALYzgIAzAOh21veuPhQzAJsZQIAZAIa9
4GZXU9AAbGgAAWgAGPdy2wu6qmw2MoAAMgBMZ4Pb6VVvs5UBBJQBYN5L7+9qqrjZ4AAC4ACgi1v/
+xBQ/ABsfgABfgBYz4S39zalEcDWCBDQCFCH/fDu7qZcAtguAQIuAQr70c39TREFsIkCBIgCVO0n
d9d4JRXAlgoQkApQvCC6v9wptwC2W4CAW4AaLrkC/pqn6p0NGCAAGKDGC66A/RlQLc92DBBwDFDT
fn676SjJALZkgIBkgJovyd6xAKiyZ5MGCJAGqOWiS+CvAKry2bABArABSlc+/9gaFGgAGzRAADTA
M2jw+x3uObIGxRfA5gsQ4AvwzBc85zWPq0FZBbCtAgSsAjxbBc9x/aNqUDQBbJoAAZoAzzTBUWJ3
1VIOAWyHAAGHAM8OwXPeriNqUBoBbI0AAY0AzxrBF6H9O60amu0RIOAR4Nkj+Dx0508niiaATRMg
QBPgmSZQyf17rmqZbRQgYBTg2Sj4PHlvI1VWAWyrAAGrAM9WgYxu33VFFsAmCxAgCzAcdPQXfPWq
DAPYhgEChgEGnEvv33vV2GzUAAHUAEOdSd+53CvmADZzgABzgIEXXQL/KVCtzoYPEIAPMAxnLkHv
BqAwBNgYAgIYAobxsmvgPweq89lCAgJCAgbR+dwjZ1BGAmwjAQEjAYNoej3HzaCoBNhUAgJUAoZF
ZX5v3mNV7GwuAQEuAYModv4xMygzAbaZgICZgPGgEvsnraDMBNhmAgJmAkbR4rqOl0GhCbDRBATQ
BIyn5c08WgbFJcDmEhDgEjCe9jT3zQBFJcCmEhCgEjAOMq15pAyKS4DNJSDAJWAcZWL3OJmyEmBb
CQhYCRgnmdhdsFTfsp0EBJwEjKd9y38nXxkJsI0EBIwEjKddyz5CpnwE2D4CAj4CxtOq5R4fUzIC
bBkBARkB02nNMl/XUhoCbA0BAQ0B02m/ct9OUQwCbAYBAQYBU+m0/hcgykCAbSAgYCBg4kZo+xsP
BSDABhAQABAwDTq0vy0p/wC2f4CAf4Bp1KHtT7SqWrZ+gIB+gOm0atmvmCn2ADZ7gAB7gGneiNux
gqm6ZXsHCHgHmJat1P4SplqXDR0gAB1gOm1dnS/OK+IANnGAAHGA+bAV2uxgyjeA7Rsg4BtgxlZm
d+FWrAFs1gAB1gBz7Ya2k6s+ZpMGCJAGmLmV3N65FGwAGzZAADbAfFrIXvAegtINYOsGCOgGmMed
4Pb+pYwD2MYBAsYB5mk7uL2DqYpmIwcIIAeY5+3Y7h6mKprNHCDAHGBetlPba7nqaDZygABygHk9
E9tf2pR0AFs6QEA6wHI4l95e35R0AFs6QEA6wIIz6d3nXjkHsJ0DBJwDLLWd3W4xCjiADRwgABxg
4bncHR94VeJs4AAB4ADLcDa+/4lXVc7WDRDQDbCcVrmOY10KM4CNGSCAGbQZX31Z0rtOdim4ADZc
gABc0GbIyO7hLmUUwDYKEDAK2gyZuON8lwIJYIMECIAEbYYO7a5eyh6AbQ8gYA+0GTJy3ykv5Q/A
9gcQ8AfajO3c/v1WHc32BxDwB9qMzdydP5ooiAA2RIAARNBmnAnv33lV02yPAAGPoM3YDN9bUpVK
AFslQEAlaDPOpffvvapsNk2AAE3QZmymf8H3rUoqgC0VICAVtBkXXAD/CVB9zoYLEIAL2ozzF6B3
A1AFz4YMEIAM2oxLr4L7LJSCDcqGDSoAG7QZ569C55ZQijoomzqoAHXQZlx8GfynodRlKPsyVOAy
6EbongQrpR+UrR9UQD9oM3TkjsNgpQiEsgmEChAIbcZG7PfmnR5V5NGOPAYi69rnHwkr5SCU7SBU
wEFoMzZC+wekSikIZSsIFVAQ2gwd+6kr96JyL3buJZBbVjvzbFgp/KBs/KAC+EGboQKbbw+UYg/K
Zg8qwB60GVuBzRNipeCDsuGDCsAHbcZWaPOQWCnzoGzzoALmQZuxFdpcv5R2ULZ2UAHtoM1Qme13
8ks5B2U7BxVwDtoMFdk9LVZKOChbOKiAcNBmqMTmgbFSskHZskEFZIM2QwX23vUqZRmUbRlUwDJo
M1Re822XUoRB2YRBBQiDNmMzsP+1idILytYLKqAXtBnbue3vSRRcUDZcUAG4oM3YzO3vVUotKFst
qIBa0GZs5nY/3UosKFssqIBY0Gao1O5bbKWggrKhggpABW3GdmJ/QVM+Qdk+QQV8gjZjJ7i/oqlO
ZrMEFWAJ2gwZvOtl/FIcQdkcQQU4gjZjJ7fZ0JREULZEUAGJoM3YiW0v5aqo2fxABfiBNuNcbju8
ams2PFABeKDN2Alvb2cKHygbH6gAPtBmqOD9bzuUggjKhggqABG0GfvZ7U1NqQRlqwQVUAnajN3s
7ramdIKydYIK6ARtxm5yc2NTTEHZTEEFmII2Yze4u7orq6Bsq6ACVkGbcT55x0qnqpztFlTALWgz
LrgA/nKnSp3NF1SAL2gzzl8A+wOgup1tGFTAMGgzduP7BUc1O9swqIBh0GZcEN3/8CvKoGzKoAKU
QZtxyRWwP/2KMyibM6gAZ9BmqCvgHz8rhRiUjRhUADFoM776ssn2HD8rhRaUjRZUAC1oM2Rk8/hZ
KaOgbKOgAkZBmyET+8fPSqEEZaMEFUAJ2gwd2l7AVH+zDYIKGARthozcdfyslEVQtkVQAYugzdjO
7d9v1ddsj6ACHkGbsZm784cVhROUjRNUACdoM86Et++8cgrKdgoq4BS0GZvhe6uqEgvKFgsqIBa0
GefS+/deVTabLqgAXdBmbKZ/wReySjMoWzOogGbQZlxwAfwnQPU5GzioAHDQZpy/AJ0bgEIPykYP
KoAetBmXXgX/WVCdz4YQKgAhtBnnr0L3lqAqoM0jVIBHaDMuvgz+06Aaoa0mVEBNaDPkZbCPnyk5
oWw5oQJyQpuhI/ccP1OEQtmEQgUIhTZjI7Z5/ExBCmVDChWAFNoMHdk/fqY8hbI9hQp4Cm3GRuiO
Y1hKVChbVKiAqNBm6Nhdx88UqlA2qlABVKHNULnd42cKVCgbVKgAqNBmqMDuiwWKUyibU6gAp9Bm
bAV2j58pVKFsVKECqEKbsRXaPX6mTIWyTYUKmAptxlZod/1SbcwWFSogKrQZKrP/Sr/yFMr2FCrg
KbQZKrJ9/ExpCmVrChXQFNoMldg9fqYkhbIlhQpICm2GCmy+A6b8hLL9hAr4CW2Gyuu++aLohLLp
hArQCW3GZmD/axMlJ5QtJ1RATmgztnPb35MoOKFsOKECcEKbsZm7Y69SPcyWEyogJ7QZm7ntT7cq
YracUAE5oc1Qqe3X2RSaUDaaUAE0oc3YTuwvaMpLKNtLqICX0GbsBLdXNEUllE0lVIBKaDNk8L73
9BWTUDaTUAEmoc3YyW02NKUklK0kVEBJaDN2YrtLueIRyuYRKsAjtBnnctvhVVuzcYQK4Ahtxk54
eztTSELZSEIFkIRaZF17wdsOSksoW0uogJZQy7yf3d/UVHGz3YQKuAm1LLvZ7W1NFTgbT6gAnlDL
upvc3NgUoVA2oVABQqHWw25wd3VXiELZiEIFEIVacT65v9IpTaFsTaECmkKtdcEFsJc7JSqULSpU
QFSolecvgP0BUN3ONhUqYCrUOuzGtwuOAhXKBhUqACrUOl4QvePDryqejSpUAFWodbrkCvifflX0
bFWhAqpCrbLodRw/U5BC2ZBCBSCFOoYUPra5rsNnykwo20yogJlQx2bCp8Dm0TMqHYG2jsCAjsBj
HeFTXv/gGZWEQFtCYEBC4LGE8BzZXLiozAPa5gED5gGPzYNPgbsOnVGxB7TZAwbYAx6zB5+n9u/1
oFIPduohkHrYSN334wmVfkBbP2BAP+CxfiCi+3d9UtEnO/oUiD5tRO8splQQAm0IgQEIgccQgsru
3/dFZV/s7Esg+7KRvf+rVyoagTaNwACNwMN6Nr599xWUQBtKYABKIA7n4ncu+spNoO0mMOAmELjs
GvjPgep3NqPAAKNA1Llr0LsNKFeBtqvAgKtA8MKL4D8Jqv3Z0gID0gKh2p97uIwKWqANLTAALRCq
8/UcLaPCFmhjCwxgC8QkQ78377KqeLa2wIC2QKiK5x8ro/IWaHsLDHgLxCIj+4erqLAF2tgCA9gC
ofpc15EyKmqBNrXAALXAEjXOPFBGJSzQFhYYEBZYorGZLwpQ0Qq0aQUGaAVW6bjmYTIqW4G2rcCA
rcCijmweJaNSFWirCgyoCqxBR3ZXLdW8bE6BAU6BJZqX/Wo+laNA21FgwFFgidblHiKjAhRoAwoM
AAosUbrMI2RUbgJtN4EBN4ElCpf3FhcVlEAbSmAASmCJpmW+uULFI9DmERjgEcjDRlz/KxEFI9CG
ERiAEUhspba/A1EkAm0SgQESgayN1P7upDgE2hwCAxwCyY3U9qdalS5bQmBAQiBF6XJfQqPyD2j7
Bwz4B+S4lbdjGVPFy1YPGFAPyGkztr+Oqf5lWwcMWAek6F9979VTEQe0iQMGiANy2UxttjGFG9DG
DRjADch1M7S7fCvQgDZowABowOGwn9qOrpqZLRkwIBlwwGZ0ewNTmAFtzIABzICDqGYveFNBmQa0
TQMGTAMO3Etub2PKNqBtGzBgG3AYdpK7G5niDWjzBgzwBhzGndzmVqaIA9rEAQPEAYdpJ7a9oqu2
ZhMHDBAHHOZzuTvWN1XbbOmAAemAw3I2vr/IqQJnWwcMWAcc1nPx3UdfWQe0rQMGrAOOh53wdp1R
zAFt5oAB5oAjzgb3P/QKOqANHTAAHXCs8/ntT71yDmg7Bww4BxxFqfOPg1HBBrRhAwZgAx7DBh86
TM9pMCrCgDZhwABhwGPC4I+87mEwZRXQtgoYsAp4bBX8EbfjLJhiCWizBAywBDxmCT4ltpcs1dNs
f4ABf4DH/sAfeftOgimBgLZAwIBAwGOB4LPQ9p1W/gBtf4ABf4DH/sBx6M6fRRRDQJshYIAh4DFD
cJrcv+eqkNkWAQMWAY8tguPkvV1UeQS0PQIGPAIeewQiun/XVSmzSQIGSAJOg47+gm9WlU9A2ydg
wCfgNJ5L79971dhsrIABrIDTdCZ973KvKpxNFzBAF3CaL7oE/lOgWp0NGTAAGXBazlyC7g1AlTwb
NmAANuC0XnYN7OdASQe0pQMGpAPOovPZp7+Uc0DbOWDAOeAsml7X4S9FHdCmDhigDjiXymye/VLU
AW3qgAHqgLModh1Hv5R1QNs6YMA64DyoxB1noJRzQNs5YMA54CxaXN/BL4Uc0EYOGEAOOJ+WN/fc
l6INaNMGDNAGnE97mvuf/xVpQJs0YIA04LzItO6pL0Ua0CYNGCANOK8ysXvoS1kGtC0DBiwDLgeZ
2FywlGFA2zBgwDDgctq3/JfqlV1A2y5gwC7gctq17BNfyiygbRYwYBZwOa1a7oEvJRXQlgoYkAq4
nNYs87UsJRPQlgkYkAm4nPYr940UxRHQ5ggY4Ai4TDqt/wWIcghoOwQMOARc5o3Q9jceCiCgDRAw
ABBwWXTojm1JNS3bHmDAHuCy6tDuJ1qpA7TVAQbUAa6nVct+s0xRA7SpAQaoAa7YiOuvYMoXoO0L
MOALcK2t1PYSplAB2qgAA6gA19PW1fl2vKIEaFMCDFACXIet0GYHU4YAbUOAAUOA67iV2V64VRWz
2QAG2ACu025oO7nqYzYXwAAXwHXeSu7vXKqQ2WAAA2AA19NC9oL3EBQcQBsOYAAO4LruBL9s//rb
b/8H1vLdj+WCAQA=
T_EOF
echo "payload bytes: $(wc -c < "$ROOT/table.json")"
python3 - "$ROOT" <<'PY_EOF'

import json, os, re, shutil, subprocess, sys, time

ROOT = sys.argv[1]
T = json.load(open(os.path.join(ROOT, "table.json")))
LANG = T["language"]
PROBES = T["probes"]
OUT = T["out"]
out = open(OUT, "w")
WORK = os.path.join(ROOT, "u")

# --- verbatim delimiter codec, copied from verbatim_diag.py ---
def esc(text):
    """make `text` safe to place in one pipe-delimited field, reversibly."""
    for raw, rep in _ENC:
        text = text.replace(raw, rep)
    return text

_ENC = [('\\', '\\\\'), ('|', '\\p'), (';', '\\s'), ('\n', '\\n'), ('\r', '\\r')]
MARKER = '#verbatim-escape v1'
out.write(MARKER + '\n')


print("op lane %s: %d candidate probes" % (LANG, len(PROBES)))
sys.stdout.flush()


def sh(cmd, cwd=None, timeout=180):
    try:
        p = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE, timeout=timeout)
        so = p.stdout.decode("utf-8", "replace")
        se = p.stderr.decode("utf-8", "replace")
        return p.returncode, so, se
    except subprocess.TimeoutExpired:
        return 124, "", "TIMEOUT after %ds" % timeout
    except OSError as e:
        return 125, "", "OSError %s" % e


# ------------------------------------------------------ objdump reading

LABEL = re.compile(r"^([0-9a-f]+)\s+<(.+)>:\s*$")
INSN = re.compile(r"^\s*([0-9a-f]+):\t(.*)$")
RELOC = re.compile(r"^\s+([0-9a-f]+): (R_\S+)\t(.+?)\s*$")


def extract(text, sym, exact):
    """the two columns for one symbol.

    bytes  every byte objdump printed, in order, flattened
    mnem   the instruction text, with objdump's own trailing `# ...`
           comment dropped -- that comment is arithmetic objdump did
           for the reader, not part of the instruction.  A relocation
           is appended to the instruction it applies to as
           ` !!reloc=<type>:<symbol>`, because in an object file the
           call displacement is literally zero and the callee's name
           lives only in the relocation.
    """
    lines = text.splitlines()
    k = -1
    for idx, ln in enumerate(lines):
        m = LABEL.match(ln)
        if not m:
            continue
        lab = m.group(2)
        hit = (lab == sym) if exact else (sym in lab)
        if hit:
            k = idx
            break
    if k < 0:
        return None
    raw = []
    mn = []
    for ln in lines[k + 1:]:
        if LABEL.match(ln):
            break
        m = INSN.match(ln)
        if not m:
            r = RELOC.match(ln)
            if r and mn:
                mn[-1] = "%s !!reloc=%s:%s" % (mn[-1], r.group(2), r.group(3))
            continue
        parts = m.group(2).split("\t")
        bs = parts[0].split()
        raw.extend(bs)
        txt = parts[1] if len(parts) > 1 else ""
        txt = txt.split("#")[0]
        txt = " ".join(txt.split())
        if txt:
            mn.append(txt)
    return raw, mn


def disasm(obj, sym, exact):
    rc, so, se = sh(["objdump", "-dr", "--disassemble=" + sym, obj])
    got = extract(so, sym, exact) if rc == 0 else None
    if got is None:
        rc, so, se = sh(["objdump", "-dr", obj], timeout=600)
        got = extract(so, sym, exact)
    return got


# --------------------------------------------------------- DWARF reading
#
# objdump --dwarf=info prints one entry per line block:
#
#   <1><2d>: Abbrev Number: 2 (DW_TAG_subprogram)
#      <2e>   DW_AT_name        : op_12
#   <2><4a>: Abbrev Number: 3 (DW_TAG_formal_parameter)
#      <4b>   DW_AT_name        : a
#      <52>   DW_AT_location    : 2 byte block: 91 7c (DW_OP_fbreg: -4)
#
# The leading <N> is the tree depth.  A formal parameter one level
# below the matching subprogram is a parameter OF that subprogram.

DIE = re.compile(r"^\s*<(\d+)><[0-9a-f]+>:\s*Abbrev Number:\s*\d+\s*\((\S+)\)")
ATTR = re.compile(r"^\s*<[0-9a-f]+>\s+(DW_AT_\w+)\s*:\s*(.*?)\s*$")


def clean(text):
    text = " ".join(text.split())
    return text


STRPREFIX = re.compile(r"^\((?:indexed string|indirect string)[^)]*\):\s*")


def dwname(text):
    """objdump prints a string attribute as `(indexed string: 0x5): a`.
    The parenthesised part is objdump telling the reader WHERE in the
    string table it found the name; the name is what follows.  Keeping
    the prefix would have put objdump's bookkeeping into the parameter
    name column."""
    return STRPREFIX.sub("", text.strip())


def dwarf_params(text, sym):
    """[(name, location)] for the subprogram named `sym`.

    More than one subprogram can carry the name.  swift's `@_cdecl`
    emits a C-entry thunk beside the real function, and the thunk has
    no DW_TAG_formal_parameter children at all, so the first match is
    not always the one holding the parameter table.  Every match is
    collected and the first one that actually has parameters wins."""
    lines = text.splitlines()
    depth = None
    tag = None
    attrs = {}
    entries = []
    for ln in lines:
        m = DIE.match(ln)
        if m:
            if tag is not None:
                entries.append((depth, tag, attrs))
            depth = int(m.group(1))
            tag = m.group(2)
            attrs = {}
            continue
        a = ATTR.match(ln)
        if a and tag is not None:
            attrs[a.group(1)] = a.group(2)
    if tag is not None:
        entries.append((depth, tag, attrs))

    hits = []
    for idx, (d, t, at) in enumerate(entries):
        if t != "DW_TAG_subprogram":
            continue
        names = []
        if "DW_AT_name" in at:
            names.append(dwname(at["DW_AT_name"]))
        if "DW_AT_linkage_name" in at:
            names.append(dwname(at["DW_AT_linkage_name"]))
        for nm in names:
            if nm == sym or sym in nm:
                hits.append(idx)
                break
    if not hits:
        return None
    best = []
    for k in hits:
        base = entries[k][0]
        got = []
        for d, t, at in entries[k + 1:]:
            if d <= base:
                break
            if d != base + 1:
                continue
            if t != "DW_TAG_formal_parameter":
                continue
            nm = clean(dwname(at.get("DW_AT_name", "(unnamed)")))
            loc = clean(at.get("DW_AT_location", "(no location)"))
            got.append((nm, loc))
        if got:
            return got
        best = got
    return best


def dwarf(obj, sym):
    rc, so, se = sh(["objdump", "--dwarf=info", obj], timeout=600)
    if rc != 0:
        return None, "objdump --dwarf=info rc=%d" % rc
    got = dwarf_params(so, sym)
    if got is None:
        return None, "no DW_TAG_subprogram named %s" % sym
    if not got:
        return None, "subprogram %s has no DW_TAG_formal_parameter" % sym
    return got, None


# ------------------------------------------------------------ compiling

GOMOD = "module opprobe\n\ngo 1.26\n"

CLANG = "/usr/bin/clang"
CLANGXX = "/usr/bin/clang++"
SWIFTC = "/persist/swift/usr/bin/swiftc"


def compile_probe(p, d, mode):
    """(rc, artifact path, diagnostic text)."""
    if LANG == "c":
        src = os.path.join(d, "unit.c")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANG, "-std=c17"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "cpp":
        src = os.path.join(d, "unit.cpp")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANGXX, "-std=c++20"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "rust":
        src = os.path.join(d, "unit.rs")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        if mode == "anchor":
            opt = ["-C", "opt-level=0", "-g"]
        else:
            opt = ["-C", "opt-level=1", "-C", "debug-assertions=off"]
        cmd = (["rustc", "--crate-type=lib", "--emit=obj"] + opt
               + ["-o", obj, src])
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "go":
        open(os.path.join(d, "go.mod"), "w").write(GOMOD)
        open(os.path.join(d, "main.go"), "w").write(p["source"])
        obj = os.path.join(d, "bin_%s" % mode)
        cmd = ["go", "build"]
        if mode == "anchor":
            cmd.append("-gcflags=-N -l")
        cmd.extend(["-o", obj, "."])
        rc, so, se = sh(cmd, cwd=d, timeout=300)
        return rc, obj, (se or so)
    if LANG == "swift":
        src = os.path.join(d, "unit.swift")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-Onone", "-g"] if mode == "anchor" else ["-O"]
        cmd = [SWIFTC] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd, timeout=300)
        return rc, obj, (se or so)
    raise KeyError(LANG)


DIAG = re.compile(r"^[^\s:]+:\d+(:\d+)?:")


def firstline(txt):
    """the compiler's own words for why it refused.

    The first line is not reliably the reason.  clang leads with a
    warning and puts the error underneath.  go leads with a banner
    naming the package -- `# opprobe` -- and its diagnostics never
    contain the word `error` at all, so a rule that only looked for
    that word recorded the banner and threw the testimony away.
    Three passes, in order: a line saying `error`, a line in the
    `file:line:col:` diagnostic shape, then the first line that is
    not a banner."""
    lines = []
    for ln in txt.splitlines():
        s = ln.strip()
        if s:
            lines.append(s)
    for ln in lines:
        if re.search(r"\berror\b", ln, re.I):
            return ln[:200]
    for ln in lines:
        if DIAG.match(ln):
            return ln[:200]
    for ln in lines:
        if not ln.startswith("#"):
            return ln[:200]
    if lines:
        return lines[0][:200]
    return "(no diagnostic)"


def write_unit(n, build, obj, sym, exact):
    got = disasm(obj, sym, exact)
    if got is None:
        rc2, so2, se2 = sh(["objdump", "-t", obj])
        near = 0
        for l in so2.splitlines():
            if sym in l:
                near += 1
        out.write("op_%d|%s|NOSYM|%s\n"
                  % (n, build, esc("symbol %s absent, %d near matches"
                                   % (sym, near))))
        return False
    raw, mn = got
    out.write("op_%d|%s|OK|%s|%s\n"
              % (n, build, " ".join(esc(x) for x in raw),
                 ";".join(esc(x) for x in mn)))
    return True


t0 = time.time()
tally = {"REFUSED": 0, "ACCEPTED": 0, "ANCHOR_OK": 0, "SHIP_OK": 0,
         "DWARF": 0}

for k, p in enumerate(PROBES):
    n = p["n"]
    sym = p["symbol"]
    exact = p["symbol_exact"]
    d = os.path.join(WORK, "n%d" % n)
    shutil.rmtree(d, ignore_errors=True)
    os.makedirs(d)

    rc, obj, err = compile_probe(p, d, "ship")
    if rc != 0 or not os.path.exists(obj):
        out.write("op_%d|REFUSED|%s\n" % (n, esc(firstline(err))))
        tally["REFUSED"] += 1
        out.flush()
        shutil.rmtree(d, ignore_errors=True)
        continue
    tally["ACCEPTED"] += 1
    if write_unit(n, "SHIP", obj, sym, exact):
        tally["SHIP_OK"] += 1

    rc, aobj, aerr = compile_probe(p, d, "anchor")
    if rc != 0 or not os.path.exists(aobj):
        out.write("op_%d|ANCHOR|BUILDFAIL|%s\n" % (n, esc(firstline(aerr))))
    else:
        if write_unit(n, "ANCHOR", aobj, sym, exact):
            tally["ANCHOR_OK"] += 1
        rows, why = dwarf(aobj, sym)
        if rows is None:
            out.write("op_%d|ANCHOR|NODWARF|%s\n" % (n, esc(why)))
        else:
            joined = ";".join("%s=%s" % (esc(a), esc(b)) for a, b in rows)
            out.write("op_%d|ANCHOR|DWARF|%s\n" % (n, joined))
            tally["DWARF"] += 1
    out.flush()
    shutil.rmtree(d, ignore_errors=True)

    if (k + 1) % 25 == 0 or (k + 1) == len(PROBES):
        el = time.time() - t0
        print("[progress] %s [%d/%d] elapsed %.1fs mean %.2fs  "
              "REFUSED %d ACCEPTED %d SHIP_OK %d ANCHOR_OK %d DWARF %d"
              % (LANG, k + 1, len(PROBES), el, el / (k + 1),
                 tally["REFUSED"], tally["ACCEPTED"], tally["SHIP_OK"],
                 tally["ANCHOR_OK"], tally["DWARF"]))
        sys.stdout.flush()

out.close()
print("done: %s -> %s" % (json.dumps(tally), OUT))

PY_EOF
echo "--- lane finished, rc=$?"
date -u +%Y-%m-%dT%H:%M:%SZ
