#!/bin/sh
# op-pipeline lane -- c -- generated by
# Research/op_pipeline/lane_gen.py .  Do not hand-edit.
# steps 1b/2/3: compile-or-refuse, then the ANCHOR and SHIP
# builds of every probe the compiler accepted, then objdump
# extraction, then the anchor's DWARF parameter table.
set -u
export HOME=/work
export PATH=/persist/swift/usr/bin:$PATH
export GOTOOLCHAIN=local
export GOPROXY=off
export GOFLAGS=-mod=mod
ROOT=/work/regen_c_c0115
export GOCACHE="$ROOT/gocache"
export GOPATH="$ROOT/gopath"
# swift's binaries want libncurses.so.6 and the image ships
# only libncursesw.so.6.6; the symlink lives in the image's
# own /usr/lib and does NOT survive a container restart.
if [ -f /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 ]; then
  ln -sf /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 \
     /usr/lib/x86_64-linux-gnu/libncurses.so.6 2>/dev/null
  ldconfig 2>/dev/null
fi
echo "=== op pipeline -- c -- 400 candidate probes ==="
date -u +%Y-%m-%dT%H:%M:%SZ
# refuse in seconds rather than in an hour
if ! /usr/bin/clang --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: /usr/bin/clang is not runnable in this container."
  echo "!! tried: /usr/bin/clang --version"
  exit 4
fi
/usr/bin/clang --version 2>&1 | head -2
if ! objdump --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: objdump is not runnable."
  exit 4
fi
objdump --version 2>&1 | head -1
rm -rf "$ROOT"; mkdir -p "$ROOT" "$GOCACHE" "$GOPATH"
df -Pm /work | awk 'NR==2{print "free /work: " $4 " MB"}'
FREE=`df -Pm /work | awk 'NR==2{print $4}'`
if [ "$FREE" -lt 400 ]; then
  echo "!! REFUSING TO START: only $FREE MB free on /work, need 400"
  exit 3
fi
base64 -d <<'T_EOF' | gunzip > "$ROOT/table.json"
H4sIAAAAAAAC/8Wd245cR3JFf6VBv2gGM6MTEXm1Bwbsh/kBP5pGg6SoC0A1CYqERxD0766mWKyq
jJ3V3AcV6XmYC7uGpb07K3PVQQbWb8/evHj44eOLH14/+9e7Z6+e/eXu2duPHx7/+7eH//z2/esf
Xj/cv7p/tYnkv33454fHF7x7//bl618Or/nv3549HP4jlW3bDn/+y68/v3z75vH/+/bd/ac/fPbl
T+9f//PFq8e/98P7j68f//Ttx/evPr3nt3+++/QX/vHX3P31r3cvf3p48f7Xu7/f/fnb5w//8tPD
qzcfv3t99/dfPnz308OHv/3478Mfvnz79s2nP33+cH//4dd3r99+f3//zTeH1/7pt+33w1/zzceH
X3764eH1d3f3/3h/+Kd4/OM/PX84/kM+vvLuxV/uhlfdvTy85rfnD3eHf71//eHj+4e7F4e/7OW/
PX/4/fnDs9//cndKLyi90OklNv2rH1+8v8wuLvvja5jkipIrnVxjk3/+s1NwdcEf/zeR21Buo3Nb
bO43bx9+uAxuLvjja5jkCSVPdPIUn/zu/j9evfr482UBCRfwx0uZHjLqIdM95BU9gG0vT3qg976C
eih0D2VBD/7jUHAL7Geiog4q3UGN7eCXH9++H1ZBdfk/vYjJ3lD2RmdvC7LDDaFNKuB3hI6a6HQT
fUkTYEvosybYPUEQDQpNgxJDg//7yDj3l9nlCwV+/imTFtGf0PQnN6S/40b3GBeseZFPr3iMS69y
QcQnNPGJBqX9z8NrLsPqKezjD5msiPKEpjyxoKz/ePP2xQcpl3HtFPfzz5nEiO6EpjtJUYndriXp
LC+7TyGGE5rhJAel/a8X8MiSfIp8egmTGzGb0MwmJTI3+FWXITf9+0acJjSnSQ3MPfviIvUy/L5v
LYJoTWhakxbeAPj1N9QAvQYQpQlNadIDG5jCqvTLCnaSqiI+U5rPdIvvwC8D3WAH7DpQRG1KU5tK
YAenJ5J+Kahc1jC8lmkCEZ3SRKe6pAmwIHTWBL0mEO8pzXtqK5qYHRRqkzr2nRiKiFBpItS0rhOw
RNLVTuh1grhRaW7UvKKT6WGieVLK3lMFUaXSVKllYStgqZTrrdBrBTGn0sypUcx5//L74RuknpHm
p58yaRFfKs2XGsWX999/+kqs7TLxGVl+eQWTGjGl0kypPSz1u/F33M8Tv6N+x4bo0Wh6tCh6vP/p
5c/jb9jOoPHzz5nEiBWNZkWTsMQPjyt2eKZpcp758yuY1IgLjeZCi+LC+4849hkOnl7C5EYUaDQF
WhAFvhwfcNoJ+F5yzzcNsZ3RbGdBbOfuK9gJ48h7CoaIzWhisxyXVMq4kPNF2sefM4kRjRlNY1bi
EpuOictF4sefM4kRaRlNWlbjEru9ql4EJvcpxFpGs5YFsdZ3bz++fPP6Mu6Js/74KZMWMZbRjGVB
jPWJGi/DnhDr0w+JrAkRVqIJKwUR1o8v3nx/ETWd6OrxZ0xSRFaJJqsURFbjvbF0QiruvlhCLJVo
lkpBLOUuxqQTRJF3YRKip0TTU7K4pOhhSLLLwPTTj4RYKtEslVJkbv+4I6UhN/t8IyGySjRZpRyY
GxxFKV/mps+jhPgq0XyVSmBu/7Eul6nZzzYirEQTVgoiLH+/LZ34ir3XlhBdJZquUgvMCjeyNkTm
dzJEWokmrdRDk4OtrI/J2b0sI+7KNHflIO6aXePPJ/zad4s/IwrLNIVlCc09wliWMTbHZBkxWaaZ
LGtoareHZx1jk7t4RoSWaULLFp4bhDcYnm0AsVqmWS2n0Ab8cZbTmJ491TKitUzTWg6itWsXHvKJ
2PbfdciI2jJNbblE5/fHWy4gP33CIYLLNMHlGpzfn3HVp2dPOUR0mSa63IKzu3Ou+ejkSYeILtNE
l3twcr/ddx+d3OsLYrpCM13ZFmRH217ZJhXQe19BlFdoyiuypAm/ARaZNcHuggWRX6HJr+iKJtyH
ouikB/aTgTiw0BxYLLgFz0HFfAMsCRXEgIVmwJJWpIcbQ5qVwO8MiAoLTYUlr+kCbA152gW9NyBC
LDQhliBCRMNr5USG/PRaQURYaCIsNybCsxU/GWIr9fyFu2bZCiLCQhNhabHZ3UhbaS46OdlWEBEW
mghLj02OBtxKd+H5ObeKqLDSVFi34Pxup6ubT0/ucBVxYKU5sEps9snwWxVXwK4ZuIoYsNIMWHVB
C2AZKG6BXguIASvNgNXiW5h9QaoGq9j3HakiKqw0Fda0qg+wNNKVPuj1gciw0mRYc3wfU1CuGRay
k5Ur4sNK82EtyxoBS6Rca4ReI4ggK02QtcY3cu35cq2wlP3Pmiuiy0rTZW0rewGLpT3RC71eEHtW
mj1rX9jL9PDp18vZdwo1RKeNptO2LW/IL5+2fU1D7BpqiGEbzbBNFjY0PaCaXK9o50nVEOE2mnCb
ru8ILCP9qo7odYT4t9H824L51w/pNU+97KxeQ6zbaNZtwayLR/aap9w9k3sN8W2j+bbl6A7GAb6W
QX5ujq8hkm00ybZgkkXjfM0DLD/V1xC3NppbW43Oj6bcWgUN8LNuDTFqoxm1BTPqZNSveTTdNfHX
EJE2mkhbLJG6wb/m4JOc/+uIMzvNmT2WM91dkO6QkrwJ0hE9dpoeu4TndkOBXVB2cjawIzLsNBl2
Dc/vRgS7ovzkpGBH1Ndp6usWnn/c8bqh+Nxu1xH3dZr7eiz3gZmN7piPntroiPc6zXs9lvf8MGF3
uMfOFHZEe52mvR5Le260sDvSIycMO6K8TlNej6W88c5fd3jH3fjriOs6zXU9luvc1abugI6809QR
yXWa5HoPz40eBPUO47NPfgTZOIS2cci2LWjBPeo5vC1ugXy2I8jKIbSVQzaJb8Efdoe3hS2wJ54g
Q4fQhg7ZNL6FcTs4vCnsgNsTBLk6hHZ1yBZLe+6W4+ENx/TkHUdBrg6hXR2ypfjkYDs8vC8ugN8P
M+oh0z3kFT2ADTFPeqB3xIJ6KHQPsQw4GQE5vK2rYc8ciCBbh9C2DtnqihYGMDy866QEig8FWTuE
tnbI1lZ04M+FNimBPRk6aqHTLfRVLYAq+rUqyD6Qt0Nob4fItqIPf2DKNumCPTeR0UNoo4dILDle
ucwi4uhx9z0WQcYPoY0fIrqoDX+Ais7bYM9Q5AQR2gkiYmvacKeo2LQL8hxFrhChXSEiaU0T40kq
aVoEd5Yii4jQFhGRvKYHd4RInhbBnh+IL2mviEhZ1wTcPMv1QvgdFBEn7R0RqSt7AdtofaIXei9F
FErbSETawl78x6ddb4X9DCEmpf0kIn1NJ4DC+rQPlsOQp0RoT4notrALtKHo9kQl9I6C7CVC20tE
ZWkzfktReaoZdk9BNhOhbSaisbQKxjhFHaXS05yCDCZCG0xEb06nX371eJpTjtaSz7/vHdOcgkwl
QptKRFNs9nGaU45ykrPo3DSnIB+J0D4S0RybHExzylFCchaenuYUZB4R2jwiWoLz++2v+PTsfofY
kvaLiNbY7HiaU46ukbMC9kxzCvKOCO0dEW0LWgDLoOEW6LWA2JH2kIj2+BZm372OYpKhin3fu5Cp
RGhTidi2qg+/NI7iEtgHuz6Qx0Roj4mYxPcxZemj1WQoZCdHI8eJ0I4TMV3WCFgieq0Reo0ggqTt
J2IW38i1B+BmsJT9T8GRK0VoV4pYWtkLWCzpiV7o9YLYkzariOWFvcwOH8vXy9l5CiE6pU0sYmV5
Q2D5lK9piF5DiGFpc4tYXdjQ/ICq1yvae1IhwqVtL2JtfUdgGbWv6oheR4h/aUeMWDD/umlOMU+9
5DSnIGeM0M4YScGsC6c5JXnK3THNKcgmI7RNRpJEdzBMc0oSkP8d9/tHJEsbZiQFkyyY5pTkAZae
5hTknRHaOyPJovODQUZJBhqg5xgFOWiEdtBICmZUPM0pyaPpnmlOQUYaoY00kmKJdJzmlOTgk5vm
FGSkEdpIIymWM92FlOSQkryHgqw0QltpJNXw3OM0p6SKsnPTnIJMNUKbaiS18PzjNKekhvJz05yC
fDVC+2ok9fD8bsfrKD632yFnjdDOGsmx3AcGXLJjPnq2BXlrhPbWSI7lPTfNKdnhHjnNKchdI7S7
RnIs7Y3TnJId6XHTnILcNUK7ayTHUt541TA7vONuGCJfjdC+GsmxXOduRmUHdORdKGSrEdpWIzmH
50YPgnKG8eknP8hZI7SzRnJZ0IJ/1JMLboF9toPMNUKbayTX+BbQYVdhC/yJh1iPdthIbvEt+O2g
wQ7YPQHRHu2ykRxLe/5aZHasx96GRCYboU02Urb45Gg7LBsugN4PkcdGaI+NFFnRg98Qi0x6YHdE
ZLER2mIjJZYBZ3MoxaHgvikUZLER2mIjxVa0MIJhsUkJHB8il43QLhspaUUH7lwoaVICeTIgi43Q
FhspeVULoIp8rQq2D8SNtMlGSlnRhz8wS5l0QZ+biBxpw42UWHK8dpmlOHrcf48FOW+Edt5IaYva
AAdom7dBn6GIJmkPjpS+pg1/ivZpF+Q5iow4QhtxpG5rmhhP0rpNi+DOUmTHEdqOI1XW9OCOkCrT
IsjzAxlyhDbkSNV1TaDNs+r1QugdFDlzhHbmSLWVvfhttNoTvbB7KXLnCO3OkZoW9uI/Pul6K+xn
CDEp7c+Rmtd04ims5mkfLIchc47Q5hypZWEXcEMpT1TC7yiIUGmDjtS6tBmwpdSnmqH3FESrtENH
aiytomnO6iiVn+ZEphyhTTlyc1PO6QH3ZJrzqMX5/Hx7zzQncuAI7cCRmztwhuxumvPouzmLTk5z
IreN0G4bubnbZkiOpjmPJpuz8Pw0J/LWCO2tkZt7a8b8bvs7OmrO05P7HfLRCO2jkZv7aIbsk2nO
o5TmrIBd05zITCO0mUZubqZBLYBlkHAL9FpA7Ei7aeTmbhrQwuy719FSM1Sx73sX8tUI7auRm/tq
pn2ApVGu9EGvD0SNtL9Gbu6vAX1MWfqosRkK2cnRyGYjtM1Gbm6zmTcClki71gi9RhBB0mYbaT2+
kWsPwFuHpex/Co7MN0Kbb6RvK3vxi6VvT/TCrhdkxhHajCNdFvYyO3y6XC9n3ymE3DlCu3Ok6/KG
wPLRr2mIXkOIYWm7jnRb2ND0gOp2vaKdJxVy8Ajt4JGe1ncEllH6qo7odYT4l3b1SA/mXz/N2T31
stOcyNYjtK1HejDr4mnO7il3zzQnMvcIbe6RXqM7GKc5ewX5uWlO5O8R2t8jPZhk0TRn9wDLT3Mi
j4/QHh/pPTo/GmTsHTRAzzEqsvgobfHRLZhR8TSnbh5N90xzKrL4KG3x0S2WSMdpTt0cfHLTnIq8
PUp7e3SL5czxQopuDim5eyiKbD1K23p0s/Dc4zSnboayc9Ocipw9Sjt7dEvh+cdpTt0Sys9Ncypy
9Sjt6tEth+d3O15G8cndrqD0hU4fy31+wEU3x3zsbIsiL4/SXh7dYnnPTXPq5nCPnOZUZONR2saj
WyztjdOcujnS46Y5Ffl3lPbv6BZLecNVQ90c3lE3DBVZdpS27KjEct14M0rFAR13F0qRVUdpq46K
hOcGD4JUBMZnn/wosukobdNR0QUtuEc9KopbIJ/tKLLoKG3RUbH4FsBhJwZboE88ZNBR2qCjkuJb
8NtBgh2wewKiPdqdoxJLe+5apIpjPfI2pCJXjtKuHJUSnxxuhwUXwO+HiPpoN45KXdED2BDrpAd6
R0QMSLtwVGIZcDKHouJQcNcUiiL7jdL2G5W+ooURDKVPSuD4EFlvlLbeqG4rOnDngm6TEsiTARlu
lDbcqMqqFkAVcq0Ktg/EjbTXRlVX9OEPTNVJF+y5iQw3ShtuVGPJ8cplFlVHj7vvsShy3ijtvFFN
i9rwB6imeRvsGYo8OEp7cFTzmjbcKap52gV5jiIjjtJGHNWyponxJNUyLYI8SxFd0nYc1bqmB3+E
1GkR7PmB+JI25Ki2dU3AzbNdL4TfQRFx0s4c1b6yF7CN9id6YfdS5M5R2p2jti3sxX18bLveCvkZ
Qv4cpf05arKmE09hJtM+WA5D5hylzTlqurALtKGYPlEJvaMgg47SBh01W9qM31LMnmqG3lMQrdIO
HbVYWgXTnGqOUulpTkWmHKVNOXpzU85x18SznHqU4nz6tx2TnIr8N0r7b/Tm/puL3OMcpx5NN19i
c1Ocipw2Sjtt9OZOm4vUYIZTj/6aL8HpCU5FrhqlXTV6c1fNZXa/4bUxObu/IZak/TN6c//MRW48
u6lHBc2X8HsmNxVZaJS20OjNLTS+Af/rP0poLhtg1wBy0CjtoNGbO2hcA7NvWEcXzUUN+75bISeN
0k4avbmTZtIFWBI67YJeF4gKaT+N3txP47qYkvJRUnNRxk5GRqYapU01enNTzawNsDTSvA16bSAy
pI01mnJ0G9cea6cMCtn/ZBvZbJS22Wgq6zoBi6Rc7YReJ4gpadONprqsk+khU68Vs/O0QdRJe3A0
tcXtgGXTnm6HXjuITWlLjqa+rJ35QdSv1bPzREIeHaU9Opq31f345ZO3r+iHXT/ItaO0a0dzKNe6
WUzNI82Sk5iKTDtKm3Y0hzIsnMPUPNLrjilMRcYdpY07mi02/7vx924u+zvu944IlXbuaA4lVDB/
qXkEU3r6UpF3R2nvjuYcmx2NHebs0vMzh8i4o7RxR3Moe07mLvOInLumLpFtR2nbjuZI0nQzl3mA
SnLiErl1lHbraI7kR3dlJA+oSN4TQTYdpW06mntwZjdrmbvPTU5aIp+O0j4dLVtwdjdnWTafnZyy
RA4dpR06WiQ4+7i7FfHRuZ0NWXOUtuZoieQ5MHJSBpajZ02QJ0dpT46WSI7zs5VlwDh2shKZcZQ2
42iJpDg3V1kGgiOnKpEHR2kPjpZIehsv/JUB27hbfsh0o7TpRkskr7m7SWUANfIuErLaKG210VKD
M6MHOKWC6PQTG2SyUdpko6WFN+Af0ZSGGmCfySB7jdL2Gi09ugF0oHXQAH2qIWuN0tYarVt0A+7j
XzeQn9wDkKtGaVeN1kiK85cQ68Bw7M1D5KVR2kujVaNTo62vKgpP733IQaO0g0arxXfgN79qsAN2
90O+GaV9M1oj2W426VEHxNs35YHsMkrbZbTm+AZG4KsZFsBxHzLKKG2U0Vri8/v9v8AC2BMAUSBt
jtFa1zQAaqjzGtguEA/SrhitLb4LcCg22AN9NiIipI0xWiOJ8NolkjpQ4f77I8gfo7Q/Rtu2pAl/
SLZt1gR7TiKfjNI+GW2yogl3UjaZ9ECelcgqo7RVRpuuaGE8LZtOSuDOS2SXUdouo81WdOCOimaT
EshzAtlllLbLaEurWkAbZUvXyuB3S0SStGtGW17XCdgy89VO6H0T0SXtm9FWlnXiPzLlWiPs5wax
Ju2b0VZX9OEJq9VJFyxjIcuM0pYZbW1ZD3ADaVfr4HcQRJ60aUZbX9gK2EL69VbYPQR5ZpT2zGiP
pFA079gH+uSnHZFJRmmTjN7SJPNlT5hMOnb5/Mxqz5Qj8sIo7YXRW3phLvO6CceuZ3HJ6UbkeFHa
8aK3dLxcpkWTjd3OAvNTjcjZorSzRW/pbBkyu+2sp/PE7N6FmJD2r+gt/SuXeSeTjD2fhd41xYjs
K0rbV/SW9hWQHPy6y5ic/p0jxqOdK3pL54pPPvtO1OsQf993IeReUdq9ord0r8w6AEugwQ7odYBo
jvav6C39K76DKdv2PpSwj2kNGViMNrDYLQ0s0xbcUji8LW6BXAuGDCxGG1hsk8gWrjxUPrzzUMTu
p8qGrCxGW1ls0zVdgEWh0y7odWGoC6O7sCVdTA6Nw9vPCtl1ehjytxjtb7EtLWwFLJN0vRV6rWTU
SqZbyUtamR0sh/ef1bL3hCmol0L3Ulb2ApZLeaIXer1U1EulewnjUDdpeHivsw7IKUNDBhijDTC2
hTEnnDA8vN95Zn660JABxmgDjG09Lve78ffcLzJTU4WG3C9Gu19MwogSTBQe3u08MTtNaMj7YrT3
xUTiMoNBusP7XaSmZ+gMmV6MNr2YhLEiniA8vOF58I97kiMypO0uJlFkOE4OHt7pFJmbGjTkcDHa
4WISxXvjhYrDO52ycncoDNlajLa1mOTArOOk4OHdLvNyU4KGPC1Ge1pMSmDmcULw8G6XmbnpQENO
FqOdLCY1MLPbteplZHLHQvxF21dMovjLD1Ac3usUmJ2bMORZMdqzYhLFXW4S8PBWp7jkFKAho4rR
RhXTKOoaJwAP73QKy03/GfKmGO1NMY2ireFq2+GNTlGp22yGjChGG1FMo/hqvI1zeKdTVO7ujSHr
idHWE1MLzIoemKgNkeknJMhwYrThxDSFJvePRDSNydlnIMhmYrTNxDRHJgcHk+YhOX06IXuJ0fYS
0xKZ3H+8y5Cb/Ywj6qJdJaZR1OWu1B3e6pSYvEVnyEditI/EtEWmhVtaG0PzexqiL9o5Ytpjs4NN
rbvs7K6GvCJGe0XMolhsModweMOz6HsmEAzZQ4y2h5hJbPIR0ExccI7TkCnEaFOImcbmdvu5qQtO
7ujIBGK0CcTM4pOD+Ibjsx0gfqOdH2YptgN/uFly+dkzDhk/jDZ+mEUR3LVLE3ZGcfvvSyD3h9Hu
D7MS3oA/7KygBujzDlEd7QExq9EN+BOvgvzsmYcojzaBmLXo9O7UayA8ee4hyqNtIGY9Orvf+jsI
T+77yARitAnE0rYiPdoA0zYrgd4FkRPEaCeIJVnThd8Kk0y7YPdD5AQx2gliSZd04T4aSWdNsJ8P
xIa0D8SSRffgySgZ6IBlI2QAMdoAYiktyQ83iDStgd8hECnSBhBLeVEbYIvI8zboPQJRI+3+sBRF
jWBi7vBmp/z0tJwhs4fRZg9Lt6bEs3WPh+YOb3nxyj2zc4bMHUabOyy14PTjCN3hHX14bpLOkJfD
aC+HpR6cHQzUHd7Ux6fn6gyZN4w2b1jeohtwe17eQH5yr0NeDaO9GpYlOD0etju8r69gz8ydIc+G
0Z4Ny7qiB7AUdNIDvR4QF9K+Dcu2oIfZV6dsuIx9356QicNoE4fltKwRsDzStUboNYJokfZzWM4L
Gpnic864kp0EjZwdRjs7LJd1nYBlUq52Qq8TRJW0xcNyXdDJtWfRueJa9j+XRq4Po10fltvSZsCC
aU81Q68ZxKO0EcRyX9nM9CDqT9Sz70RC5hCjzSFWtvUd+SVUtq/qiF1HyDBitGHEiqzsaHpYFXmi
pJ2nFrKRGG0jsaL/Dy2BpaRf1xK9lhAT0+4SK9FM7IcCCyBhdjYQOUyMdphYieZfPCJYAPnumRRE
VhOjrSZWcngL48BgyagBbm4QGU6MNpxYiaZbND5YANTyU4TId2K078RKDW8AzdSVijrgJ+uQ88Ro
54mVaG6djBYWgKu7JgyR+cRo84mVYEp1g4bFAyk5b4iMJ0YbT6wGs6e7TVI9ZpJ3SZDtxGjbiVWJ
T+6GEKvA9OQsIjKfGG0+sarxDbiRxKqwAXIyEXlPjPaeWLX4Bsa9rxosgNv3kPPEaOeJ1WAWBFMh
1XMgPReCfCdG+06sBjOgH16sHgHZGUbkOjHadWI1mADdKGP19EdONCLHidGOE6vB5DfeIKwe+bj7
g8hnYrTPxGow67krUtVDHnk3CllMjLaYWO3xydHDotpxAfTTIeQwMdphYm1b0YN/HNS2SQ/s8x9k
MDHaYGJNFvQAjr4muAf6/EMOE6MdJtZ0QQ9uW2iKWyD3BuQwMdphYi2YAP2tyeb5j70zicwlRptL
rKUF2dHG2NKkAn5nRCRI+0qs5SVNgK0xz5qg90bEhbSlxFowF86GTJrHw32TJshOYrSdxFpd0sMI
i63OauCYEblJjHaTWGtLWvBnRJvVwJ4SiCBpG4m1vqwHUEa/WgbZCDKRGG0isb4tacQfn32btcGe
oshMYrSZxHowTV67ENM9Ue6/C4PMJUabS6zrqj78cdr1Sh/siYrcJka7Tazboj7cmdpt3gZ5qiLn
idHOE+tpURfjudrTvAruZEU2FKNtKNbzoibccdLzvAr2LEHMSftRrJeFXcBttDxRCb+XIgql/SnW
69JmwIZan2qG3lURmdJWFettZTP+Q9Se6IX9JCFOpT0r1vuiVgCX9XkjX0Vm//P7/wEYOsE+hJYB
AA==
T_EOF
echo "payload bytes: $(wc -c < "$ROOT/table.json")"
python3 - "$ROOT" <<'PY_EOF'

import json, os, re, shutil, subprocess, sys, time

ROOT = sys.argv[1]
T = json.load(open(os.path.join(ROOT, "table.json")))
LANG = T["language"]
PROBES = T["probes"]
OUT = T["out"]
out = open(OUT, "w")
WORK = os.path.join(ROOT, "u")

# --- verbatim delimiter codec, copied from verbatim_diag.py ---
def esc(text):
    """make `text` safe to place in one pipe-delimited field, reversibly."""
    for raw, rep in _ENC:
        text = text.replace(raw, rep)
    return text

_ENC = [('\\', '\\\\'), ('|', '\\p'), (';', '\\s'), ('\n', '\\n'), ('\r', '\\r')]
MARKER = '#verbatim-escape v1'
out.write(MARKER + '\n')


print("op lane %s: %d candidate probes" % (LANG, len(PROBES)))
sys.stdout.flush()


def sh(cmd, cwd=None, timeout=180):
    try:
        p = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE, timeout=timeout)
        so = p.stdout.decode("utf-8", "replace")
        se = p.stderr.decode("utf-8", "replace")
        return p.returncode, so, se
    except subprocess.TimeoutExpired:
        return 124, "", "TIMEOUT after %ds" % timeout
    except OSError as e:
        return 125, "", "OSError %s" % e


# ------------------------------------------------------ objdump reading

LABEL = re.compile(r"^([0-9a-f]+)\s+<(.+)>:\s*$")
INSN = re.compile(r"^\s*([0-9a-f]+):\t(.*)$")
RELOC = re.compile(r"^\s+([0-9a-f]+): (R_\S+)\t(.+?)\s*$")


def extract(text, sym, exact):
    """the two columns for one symbol.

    bytes  every byte objdump printed, in order, flattened
    mnem   the instruction text, with objdump's own trailing `# ...`
           comment dropped -- that comment is arithmetic objdump did
           for the reader, not part of the instruction.  A relocation
           is appended to the instruction it applies to as
           ` !!reloc=<type>:<symbol>`, because in an object file the
           call displacement is literally zero and the callee's name
           lives only in the relocation.
    """
    lines = text.splitlines()
    k = -1
    for idx, ln in enumerate(lines):
        m = LABEL.match(ln)
        if not m:
            continue
        lab = m.group(2)
        hit = (lab == sym) if exact else (sym in lab)
        if hit:
            k = idx
            break
    if k < 0:
        return None
    raw = []
    mn = []
    for ln in lines[k + 1:]:
        if LABEL.match(ln):
            break
        m = INSN.match(ln)
        if not m:
            r = RELOC.match(ln)
            if r and mn:
                mn[-1] = "%s !!reloc=%s:%s" % (mn[-1], r.group(2), r.group(3))
            continue
        parts = m.group(2).split("\t")
        bs = parts[0].split()
        raw.extend(bs)
        txt = parts[1] if len(parts) > 1 else ""
        txt = txt.split("#")[0]
        txt = " ".join(txt.split())
        if txt:
            mn.append(txt)
    return raw, mn


def disasm(obj, sym, exact):
    rc, so, se = sh(["objdump", "-dr", "--disassemble=" + sym, obj])
    got = extract(so, sym, exact) if rc == 0 else None
    if got is None:
        rc, so, se = sh(["objdump", "-dr", obj], timeout=600)
        got = extract(so, sym, exact)
    return got


# --------------------------------------------------------- DWARF reading
#
# objdump --dwarf=info prints one entry per line block:
#
#   <1><2d>: Abbrev Number: 2 (DW_TAG_subprogram)
#      <2e>   DW_AT_name        : op_12
#   <2><4a>: Abbrev Number: 3 (DW_TAG_formal_parameter)
#      <4b>   DW_AT_name        : a
#      <52>   DW_AT_location    : 2 byte block: 91 7c (DW_OP_fbreg: -4)
#
# The leading <N> is the tree depth.  A formal parameter one level
# below the matching subprogram is a parameter OF that subprogram.

DIE = re.compile(r"^\s*<(\d+)><[0-9a-f]+>:\s*Abbrev Number:\s*\d+\s*\((\S+)\)")
ATTR = re.compile(r"^\s*<[0-9a-f]+>\s+(DW_AT_\w+)\s*:\s*(.*?)\s*$")


def clean(text):
    text = " ".join(text.split())
    return text


STRPREFIX = re.compile(r"^\((?:indexed string|indirect string)[^)]*\):\s*")


def dwname(text):
    """objdump prints a string attribute as `(indexed string: 0x5): a`.
    The parenthesised part is objdump telling the reader WHERE in the
    string table it found the name; the name is what follows.  Keeping
    the prefix would have put objdump's bookkeeping into the parameter
    name column."""
    return STRPREFIX.sub("", text.strip())


def dwarf_params(text, sym):
    """[(name, location)] for the subprogram named `sym`.

    More than one subprogram can carry the name.  swift's `@_cdecl`
    emits a C-entry thunk beside the real function, and the thunk has
    no DW_TAG_formal_parameter children at all, so the first match is
    not always the one holding the parameter table.  Every match is
    collected and the first one that actually has parameters wins."""
    lines = text.splitlines()
    depth = None
    tag = None
    attrs = {}
    entries = []
    for ln in lines:
        m = DIE.match(ln)
        if m:
            if tag is not None:
                entries.append((depth, tag, attrs))
            depth = int(m.group(1))
            tag = m.group(2)
            attrs = {}
            continue
        a = ATTR.match(ln)
        if a and tag is not None:
            attrs[a.group(1)] = a.group(2)
    if tag is not None:
        entries.append((depth, tag, attrs))

    hits = []
    for idx, (d, t, at) in enumerate(entries):
        if t != "DW_TAG_subprogram":
            continue
        names = []
        if "DW_AT_name" in at:
            names.append(dwname(at["DW_AT_name"]))
        if "DW_AT_linkage_name" in at:
            names.append(dwname(at["DW_AT_linkage_name"]))
        for nm in names:
            if nm == sym or sym in nm:
                hits.append(idx)
                break
    if not hits:
        return None
    best = []
    for k in hits:
        base = entries[k][0]
        got = []
        for d, t, at in entries[k + 1:]:
            if d <= base:
                break
            if d != base + 1:
                continue
            if t != "DW_TAG_formal_parameter":
                continue
            nm = clean(dwname(at.get("DW_AT_name", "(unnamed)")))
            loc = clean(at.get("DW_AT_location", "(no location)"))
            got.append((nm, loc))
        if got:
            return got
        best = got
    return best


def dwarf(obj, sym):
    rc, so, se = sh(["objdump", "--dwarf=info", obj], timeout=600)
    if rc != 0:
        return None, "objdump --dwarf=info rc=%d" % rc
    got = dwarf_params(so, sym)
    if got is None:
        return None, "no DW_TAG_subprogram named %s" % sym
    if not got:
        return None, "subprogram %s has no DW_TAG_formal_parameter" % sym
    return got, None


# ------------------------------------------------------------ compiling

GOMOD = "module opprobe\n\ngo 1.26\n"

CLANG = "/usr/bin/clang"
CLANGXX = "/usr/bin/clang++"
SWIFTC = "/persist/swift/usr/bin/swiftc"


def compile_probe(p, d, mode):
    """(rc, artifact path, diagnostic text)."""
    if LANG == "c":
        src = os.path.join(d, "unit.c")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANG, "-std=c17"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "cpp":
        src = os.path.join(d, "unit.cpp")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANGXX, "-std=c++20"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "rust":
        src = os.path.join(d, "unit.rs")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        if mode == "anchor":
            opt = ["-C", "opt-level=0", "-g"]
        else:
            opt = ["-C", "opt-level=1", "-C", "debug-assertions=off"]
        cmd = (["rustc", "--crate-type=lib", "--emit=obj"] + opt
               + ["-o", obj, src])
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "go":
        open(os.path.join(d, "go.mod"), "w").write(GOMOD)
        open(os.path.join(d, "main.go"), "w").write(p["source"])
        obj = os.path.join(d, "bin_%s" % mode)
        cmd = ["go", "build"]
        if mode == "anchor":
            cmd.append("-gcflags=-N -l")
        cmd.extend(["-o", obj, "."])
        rc, so, se = sh(cmd, cwd=d, timeout=300)
        return rc, obj, (se or so)
    if LANG == "swift":
        src = os.path.join(d, "unit.swift")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-Onone", "-g"] if mode == "anchor" else ["-O"]
        cmd = [SWIFTC] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd, timeout=300)
        return rc, obj, (se or so)
    raise KeyError(LANG)


DIAG = re.compile(r"^[^\s:]+:\d+(:\d+)?:")


def firstline(txt):
    """the compiler's own words for why it refused.

    The first line is not reliably the reason.  clang leads with a
    warning and puts the error underneath.  go leads with a banner
    naming the package -- `# opprobe` -- and its diagnostics never
    contain the word `error` at all, so a rule that only looked for
    that word recorded the banner and threw the testimony away.
    Three passes, in order: a line saying `error`, a line in the
    `file:line:col:` diagnostic shape, then the first line that is
    not a banner."""
    lines = []
    for ln in txt.splitlines():
        s = ln.strip()
        if s:
            lines.append(s)
    for ln in lines:
        if re.search(r"\berror\b", ln, re.I):
            return ln[:200]
    for ln in lines:
        if DIAG.match(ln):
            return ln[:200]
    for ln in lines:
        if not ln.startswith("#"):
            return ln[:200]
    if lines:
        return lines[0][:200]
    return "(no diagnostic)"


def write_unit(n, build, obj, sym, exact):
    got = disasm(obj, sym, exact)
    if got is None:
        rc2, so2, se2 = sh(["objdump", "-t", obj])
        near = 0
        for l in so2.splitlines():
            if sym in l:
                near += 1
        out.write("op_%d|%s|NOSYM|%s\n"
                  % (n, build, esc("symbol %s absent, %d near matches"
                                   % (sym, near))))
        return False
    raw, mn = got
    out.write("op_%d|%s|OK|%s|%s\n"
              % (n, build, " ".join(esc(x) for x in raw),
                 ";".join(esc(x) for x in mn)))
    return True


t0 = time.time()
tally = {"REFUSED": 0, "ACCEPTED": 0, "ANCHOR_OK": 0, "SHIP_OK": 0,
         "DWARF": 0}

for k, p in enumerate(PROBES):
    n = p["n"]
    sym = p["symbol"]
    exact = p["symbol_exact"]
    d = os.path.join(WORK, "n%d" % n)
    shutil.rmtree(d, ignore_errors=True)
    os.makedirs(d)

    rc, obj, err = compile_probe(p, d, "ship")
    if rc != 0 or not os.path.exists(obj):
        out.write("op_%d|REFUSED|%s\n" % (n, esc(firstline(err))))
        tally["REFUSED"] += 1
        out.flush()
        shutil.rmtree(d, ignore_errors=True)
        continue
    tally["ACCEPTED"] += 1
    if write_unit(n, "SHIP", obj, sym, exact):
        tally["SHIP_OK"] += 1

    rc, aobj, aerr = compile_probe(p, d, "anchor")
    if rc != 0 or not os.path.exists(aobj):
        out.write("op_%d|ANCHOR|BUILDFAIL|%s\n" % (n, esc(firstline(aerr))))
    else:
        if write_unit(n, "ANCHOR", aobj, sym, exact):
            tally["ANCHOR_OK"] += 1
        rows, why = dwarf(aobj, sym)
        if rows is None:
            out.write("op_%d|ANCHOR|NODWARF|%s\n" % (n, esc(why)))
        else:
            joined = ";".join("%s=%s" % (esc(a), esc(b)) for a, b in rows)
            out.write("op_%d|ANCHOR|DWARF|%s\n" % (n, joined))
            tally["DWARF"] += 1
    out.flush()
    shutil.rmtree(d, ignore_errors=True)

    if (k + 1) % 25 == 0 or (k + 1) == len(PROBES):
        el = time.time() - t0
        print("[progress] %s [%d/%d] elapsed %.1fs mean %.2fs  "
              "REFUSED %d ACCEPTED %d SHIP_OK %d ANCHOR_OK %d DWARF %d"
              % (LANG, k + 1, len(PROBES), el, el / (k + 1),
                 tally["REFUSED"], tally["ACCEPTED"], tally["SHIP_OK"],
                 tally["ANCHOR_OK"], tally["DWARF"]))
        sys.stdout.flush()

out.close()
print("done: %s -> %s" % (json.dumps(tally), OUT))

PY_EOF
echo "--- lane finished, rc=$?"
date -u +%Y-%m-%dT%H:%M:%SZ
