#!/bin/sh
# op-pipeline lane -- cpp -- generated by
# Research/op_pipeline/lane_gen.py .  Do not hand-edit.
# steps 1b/2/3: compile-or-refuse, then the ANCHOR and SHIP
# builds of every probe the compiler accepted, then objdump
# extraction, then the anchor's DWARF parameter table.
set -u
export HOME=/work
export PATH=/persist/swift/usr/bin:$PATH
export GOTOOLCHAIN=local
export GOPROXY=off
export GOFLAGS=-mod=mod
ROOT=/work/regen_cpp_c0151
export GOCACHE="$ROOT/gocache"
export GOPATH="$ROOT/gopath"
# swift's binaries want libncurses.so.6 and the image ships
# only libncursesw.so.6.6; the symlink lives in the image's
# own /usr/lib and does NOT survive a container restart.
if [ -f /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 ]; then
  ln -sf /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 \
     /usr/lib/x86_64-linux-gnu/libncurses.so.6 2>/dev/null
  ldconfig 2>/dev/null
fi
echo "=== op pipeline -- cpp -- 400 candidate probes ==="
date -u +%Y-%m-%dT%H:%M:%SZ
# refuse in seconds rather than in an hour
if ! /usr/bin/clang++ --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: /usr/bin/clang++ is not runnable in this container."
  echo "!! tried: /usr/bin/clang++ --version"
  exit 4
fi
/usr/bin/clang++ --version 2>&1 | head -2
if ! objdump --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: objdump is not runnable."
  exit 4
fi
objdump --version 2>&1 | head -1
rm -rf "$ROOT"; mkdir -p "$ROOT" "$GOCACHE" "$GOPATH"
df -Pm /work | awk 'NR==2{print "free /work: " $4 " MB"}'
FREE=`df -Pm /work | awk 'NR==2{print $4}'`
if [ "$FREE" -lt 400 ]; then
  echo "!! REFUSING TO START: only $FREE MB free on /work, need 400"
  exit 3
fi
base64 -d <<'T_EOF' | gunzip > "$ROOT/table.json"
H4sIAAAAAAAC/73dX28cV3YE8K9CMC8O4F1P/zmnupMgQBJgv0Aeo0CgJFoWIJMCRWK9MPzdcynH
5NBTt3vqEKh9Mczd1XXd7rldHPfB79fLz1c3Hx+uPl5f/svF5fsvXy6/v7i8fbh//Lsf2l9/uLv+
eH3ztv0Xb98fhhj+ev/L/eP/5Mvd7bvrr+1/9T+/Xt60v+RhPhzaz7/+4+d3t58f/9+3X95+++Hl
00/fXv9y9f7xT76/e7h+/Ontw937b+v+8MPFtz/w9z/m4i9/uXj36ebq7h8XVzcf3tz806eb958f
Plxf/Nv7r/cfPt3c//uLn93+/OXq7vrFz26u/97+/s3N9S/313c3F28u/+vN5cXVw/3tm5s//rG+
+/rp4831h4vPtzcfL66+v3j731f3Fw83xz99+x/v3z/8fPHun9/c/Prm5qL95+76/qH9eVeP/1wX
7/71zc1vb24uf/v+4nkPBrYHg7wHg2MPhnP24G937Z9X24OR7cEo78Ho2INxew++/nR7d1+6ESa2
CZO8CZNjE6azNqFwJ8xsE2Z5E2bHJswnm/D23Y9DaoGDBQ45cDgCx2ngHz/fXt0P46KFThY65dDp
CJ0k9Bf1KoMFhhwYjsA4Dfzp3c/yNV5Y5EWOvDgiLyTyzeNt/VY8vlYWepVDr47Q62noh1LqgdW4
Qa5xg6PGDSc17t3t7WctLmtsg9zYBkdjG04a2/ufru60uKycDXI5GxzlbBhZ3CHVG5pVsUGuYoOj
ig0TizyNamRWvAa5eA2O4jXMLLJ8arHmNcjNa3A0r+GkeX24fXj3+VoLzFrXILeuwdG6hpPW9a1o
anlZ6Rrk0jU4StdwUrp+uvr8oxaXFa5BLlyDo3ANJ4Wr/bFaWta0BrlpDY6mNZw0rW9/VeKOrGKN
csUaHRVrPNC4ha9ERta0RrlpjY6mNQ48tf4dyMgK1ygXrtFRuMaRpi48nUbWuUa5c42OzjVONLX+
qWala5RL1+goXeNJ6fr9Sz4pL6tco1y5RkflGoPnrRxjrHiNcvEaHcVrzE7swjnG+tco96/R0b/G
k/71/38r/7o8sho2yjVsdNSwcemkVtvYyNrYKLex0dHGxrUTWj6+J1bKJrmUTY5SNh22UuvRWTOb
5GY2OZrZNHSi6w+wiVWzSa5mk6OaTSfV7OlfzxWeYROrZ5NczyZHPZumfnL9MTaxkjbJJW1ylLRp
7iaXH2QTK2uTXNYmR1mboptbfZRNrKxNclmbHGVtym5s/URnbW2S29rkaGsTtnNXzjdW2ya5tk2O
2jYtO/ELhxwrcJNc4CZHgZvW7fjyrT+zHjfLPW529Lj50A2v15mZtbhZbnGzo8XNw07wwod+ZnVu
luvc7Khz87iXX//Uz6zUzXKpmx2lbj4pdX9/rDTiv/SbWZmb5TI3O8rc/LLMPb2lUbjPWZWb5So3
O6rcHDz1f6qvacysyM1ykZsdRW5OHvpv396u0941m1mRm+UiNzuK3IxObv0oY/1tlvvb7Ohv88JT
P75CW/l0s+42y91tdnS3ed2Irl/1YM0t5OYWjuYWh3706m8twQpcyAUuHAUuhr38hevPClzIBS4c
BS7Gfv5ygw3W4EJucOFocDHtbkDhDmCFLuRCF45CF3N/A17z3WywehdyvQtHvYs4Zw8K9wFreyG3
vXC0vcgz9qD8SGD1L+T6F476Fzh7Iwp3BGuEITfCcDTCWM7YiPpDghXEkAtiOApirOfvhH5PJOuL
KffFdPTF7PRFfcYsWUtMuSWmoyVmpyXWBs2S9cOU+2E6+mGOveTqtFmyUphyKUxHKcxOKayMnCXr
gil3wXR0wZx7uSsTWMkaYMoNMB0NMDsNsDh8lqz4pVz80lH8khc/eQItWcdLueOlo+Ml73jy6wjJ
6lzKdS4ddS6XbmZ5Fi1ZeUu5vKWjvOXazS0PpIFVNchVDY6qhkM3t3qcgXU1yF0Njq4G3tUKL/+D
9TTIPQ2Ongbe0/T5NLCaBrmmwVHTwGuaPKQGVtEgVzQ4Khp4RVNfKAPrZpC7GRzdDLybyW/UgJUy
yKUMjlKG7GcufNkC1s0gdzM4uhmwEV3/dgWsokGuaHBUNCz96JUHGGtpkFsaHC0Naz+6/ElfWE1b
5Jq2OGrawmua/t7cwkraIpe0xVHSlmEjdOF8W1hVW+Sqtjiq2jJuZdcPuIU1tkVubIujsS28sVWn
ARZW3Ba5uC2O4rbMW9HV/raw/rbI/W1x9LcltpLrhzurcYtc4xZHjVtyN7qen3W5Re5yi6PLLdjK
X3jGsTK3yGVucZS5hZe517xTsbBCt8iFbnEUumXdia8/6VZW61a51q2OWrcetuPLz7qV1btVrner
o96tw3Z49Wm3snq3yvVuddS7ddzOLp/3K+t3q9zvVke/W6czwhcOvpUVvVUuequj6K3zOXtQOP1Y
5Vvlyrc6Kt8aZ+yB/klgzW+Vm9/qaH5rbu+A3n1W1vtWufetjt634pz0lYOAFcBVLoCrowCuy1mb
UDgJWA1c5Rq4OmrgymtgYUwuGMwQMswQDpghnmGG369yaUQuGMMQMsMQDoYhnhmG58TqeFwwcyFk
cyEc5kI8mwvPgQujccGIhZCJhXAQC/FMLBxlVs+vYJ5CyJ5CODyFePYUnhPXRuKCqQohqwrhUBXi
WVX4U+zC1U4WO+XY6YidPHbx95ZgxELIxEI4iIV4JhZY9sJ1X1j2Rc6+OLIvPHu1pwYzF0I2F8Jh
LsSzuUDD61ee0Qsh0wvhoBdiOPDwr/iaNpjFELLFEA6LIYZhL3/h+rMWJ+MM4cAZYhh38lePfsY1
hMw1hINriGE6axMKdwJrejLgEA7AIYZ5ZxPKDwOGOoSMOoQDdYghztuFwr3AeqAsPYRDeoiB9EB5
xC2Y9RCy9RAO6yEG0v5K423ByIeQyYdwkA8xLCz1F/U6s7Insw/hYB9iIGWvMNYWzH4I2X4Ih/0Q
44FlLsx1BbMfQrYfwmE/xEiaXW2cLRj+EDL+EA78IcbTQqeOsgVjH0JmH8LBPsR42t3UdwuCkQ8h
kw/hIB9inGledYQtGPsQMvsQDvYhxqCZ1fG1YOZDyOZDOMyHGJNmlo8u1sFk7yEc3kOMpx1Mf+s/
mPUQsvUQDushxtP+JY+sBXMeQnYewuE8xHhav9RxtWDCQ8jCQziEh5hOq5f48lcw1SFk1SEcqkNM
p51LfcslGOcQMucQDs4hppHnLXxJwiyHkC2HcFgOMU2d2Pq3IgxyCBlyCAfkENPMYxceUsxxCNlx
CIfjEFPw2Ponm9UvWXEIh+IQ02n9kl9ZC8Y3hMw3hINviAmdwJWzjFUw2W0Ih9sQ09LLXTjMWBOT
wYZwgA0xnTax4qv5waiGkKmGcFANMR96sdVexpyGkJ2GcDgNMQ+91PIhzniGkHmGcPAMMY+bsfXs
rKPJNEM4aIaYp152/TnGgIaQgYZwAA0xn5a017zLwJSGkJWGcCgNMcdGdP1pxqyGkK2GcFgNMWc/
uv48Y7VNxhrCgTXEjH5w+YnGapvMNYSDa4h56efWz3XW22SsIRxYQ8zrTvDCIcfEhpDFhnCIDRGH
vfz6ScfEhpDFhnCIDRHDTn757mdeQ8heQzi8hoixn17vNQxqCBlqCAfUEDHtJa988Fmxk6GGcEAN
EfPuBhQ++azeyUpDOJSGiNN6VxkjYyhDyChDOFCGtsh3fy7vtUkyBjCEDDCEA2Boi9DQ8jAZsxZC
thbCYS20RWjmyjwZgxVChhXCASu0RXhs+RxjhkLIhkI4DIW2CA1dnCpjjkLIjkI4HIW2SD954Zqz
3iY7CuFwFNoi3eTVX1oYqBAyqBAOUKEtshO/cPVZdZNdhXC4Cm2RbvxydWW6Qsi6Qjh0hbbIXv7C
9Wc1TiYWwkEstEW6+V/z3SwTF0IWF8IhLrRFztiCwl3AOp4MMIQDYGiL7G9B+WHASp8MMoQDZGiL
nLsP+v3AgIaQgYZwAA1tkf19KD8eGNkQMtkQDrKhLXL2RhTuCNYSZcUhHIpDW4RuhD55xhSHkBWH
cCgObREeujR8xiiHkCmHcFAObZFOcHX+jGEOIWMO4cAc2iI8dGEEjXkOIXsO4fAc2iKd2JVxLKY5
hKw5hENzaIvw4LVBNIY5hIw5hANzaIuw5PIsGkMcQkYcwoE4tEVYZPn9A8Y3hMw3hINvaIv0IssT
aQxwCBlwCAfg0BbpxZaH0pjdELLdEA67oS3Si62eZExtCFltCIfa0BZhqQtv/TOvIWSvIRxeQ1uE
hdan05jUELLUEA6poS3CMssDakxoCFloCIfQ0BZhkdU3x5jJELLJEA6ToS3CEstvzTCKIWSKIRwU
Q1ukG7nw1QpTGEJWGMKhMLRF+sn171IYwBAywBAOgKEt0k1eeHIxfSFkfSEc+kJbpJtc/pQzeSFk
eSEc8kJbhOXW34pj4ELI4EI4wIW2SD9z4WhjzkLIzkI4nIW2yEb0wtnGeprMK4SDV2iL0OjF1/0Z
qxAyqxAOVqEtspFcbW1MVAhZVAiHqNAW2QiuH+usvMmMQjgYhbbIXnI9PmtwMqAQDkChLbIRX364
JUMUUkYU0oEotEVY9Fe8MZEMVEgZVEgHqNAW2U4vP+KS6Qop6wrp0BXaIpvp1YdcMmUhZWUhHcpC
W2Qzu/iYS8YtpMwtpINbaItsRldP+mTmQsrmQjrMhbbIfvbKmZdsC1LegnRsQZ6xBYWDD2wLIG8B
HFuA/S3QPwYL24BF3oDFsQHL5gYUKs/Kwq9y+NURfj0jfOEQYCRDyiRDOkiGtsg5e6CfAoxlSJll
SAfL0BZhe1AYd0uGMaSMMaQDY2iLfPfnflsad0uGL6SML6QDX2iL0NDquFsyayFlayEd1kJbhGYu
jLslwxVSxhXSgSu0RXhs/ShjnU62FNJhKbRFaOjauFsyUyFlUyEdpkJbpJ+8cM1Zh5NdhXS4Cm2R
bvLqrzEMWUgZWUgHstAW2YmvX33mLaTsLaTDW2iLdOOXCyyTF1KWF9IhL7RF9vIXrj+rcTLBkA6C
oS3Szf+aL2+ZypCyypAOlaEtcsYWFO4C1vFkqCEdUENbZH8Lqg8DhjekjDekA29oi5y7D4X7gfVA
GXRIB+jQFtnfh/rjgdVCmXlIB/PQFjl7Iwp3BGuJsv6QDv2hLUI3Qh53SyZApCxApEOAaIvw0JVx
t2QURMoURDooiLZIJ7g47pYMhEgZhEgHCNEW4aH1cbdkLkTKLkQ6XIi2SCd2YegrmQyRsgyRDhmi
LcKDP9SSs7on4xDpwCHaIiy5Ou6WDIZIGYZIBwzRFmGR5VcTGAuRMguRDhaiLdKLrI67JcMhUsYh
0oFDtEV6sdVxt2Q2RMo2RDpsiLZIL7Z8krGGJssQ6ZAh2iIstT40kMyFSNmFSIcL0RZhoeVxt2Qq
RMoqRDpUiLYIy6yOuyUTIVIWIdIhQrRFWGT1jTLmQKTsQKTDgWiLsMTyGzSMgEiZgEgHAdEW6UYu
fLXCBIiUBYh0CBBtkX5y/bsUBkCkDECkA4Boi3STV55crJvJAkQ6BIi2SDe5/iln5UwWINIhQLRF
WG799TiGP6SMP6QDf2iL9DMXjjbmPqTsPqTDfWiLbETXzzZGPqRMPqSDfGiL0OjFSQDGPaTMPaSD
e2iLbCRXWxvTHlLWHtKhPbRFNoLLxzpjHlJmHtLBPLRF9pLr8VmDk5GHdCAPbZGN+PrDjWEPKWMP
6cAeMmiFe80bE0x9SFl9SIf6kIHt9IVHHCtzsv+QDv8hY9lMrz/kWKmTEYh0IBAZ62Z29THHKIiU
KYh0UBCZh83o8knPMIiUMYh0YBCZw372wpnHVIiUVYh0qBCZ4xlboB98TIZIWYZIhwyROe1vgf4x
YH1PtiHSYUNkzpsboFceBkOkDEOkA4bIjDPCVw4BVvtkHCIdOERmnrMHhVOAlT9Zh0iHDpFJy19l
3I2BECmDEOkAIfIYhPjW8GrDbsx+SNl+SIf9kMf2w1NkedSNKQ8pKw/pUB7yWHl4SlwZdGOiQ8qi
QzpEhzwWHZ5Dy0cYsxtSthvSYTfksd3wFLk45Mb4hpT5hnTwDXnMN7zMXbjerLfJekM69IY81hte
5K7+4sIUh5QVh3QoDnmsOJDwhSvPCptsOaTDcshjy+FF+HJdZaBDyqBDOkCHPAYdWPrCtWeVTUYd
0oE6JJZO+td8TcuIh5SJh3QQD4l1dwP0O4CBDymDD+kAH3I57G1A9QHA/IeU/Yd0+A+5DOftQuFe
YJ1P5iDSwUHkMu7tQvmRwHyIlH2IdPgQuUxnbkPhbmCNUBYj0iFG5MIaoT7MxsCIlMGIdIARubAe
WBtlY2hEymhEOtCIXJLGVgfZmBqRshqRDjUiF1b7KmNszI1I2Y1IhxuRy0JDV0a5GBqRMhqRDjQi
F9bxiiNsjIxImYxIBxmRK6l28gAbkyJSliLSIUXkSlqc/KoBIyJSJiLSQUTkOvLA8vAaMyJSNiLS
YUTkOvHQ8uga0yFS1iHSoUPkOvPQ8vnF2pjMQqSDhciVtLHCy//Mg0jZg0iHB5EraWL60BqDIFKG
INIBQeRKipg8ssb8h5T9h3T4D7mSEqa+E8bAh5TBh3SAD7mS9qW+AQPGPEBmHuBgHnA4dALrX5uA
AQ+QgQc4gAcchl5u+XsSMNoBMu0AB+2Aw9jJrT+rwFgHyKwDHKwDDlMnt/7pnlnqWU49O1KTIia/
1AbmOEB2HOBwHHCIXuLKgZYseMrB0xE8u8ELJxpYcMjB4QhOOlnxzX0wqgEy1QAH1YDD0s0tNjQw
pAEy0gAH0oDD2o0tH+UMZoAMM8ABM2A4bOfWw7O2JosMcIgMGIZueP1xxlAGyCgDHCgDBlLXXvG2
A5jNANlmgMNmwDBtZdcfasxogGw0wGE0YJg3ssuPNcY0QGYa4GAaMMRGcvXBxqgGyFQDHFQDhtwI
rp/urMHJVAMcVAMG7CWvnHSsysliAxxiA4ZldwMKxx0rdbLZAIfZgGHd2wD5A8DMBshmAxxmA8bD
Rny94DCuATLXAAfXgHHYjV748DOwATLYAAfYgHHc3wH908+8BsheAxxeA0ZS9ArjZ2BAA2SgAQ6g
AcdAw2OrKU2fgVEMkCkGOCgGHFMMfyRWh8/AzAXI5gIc5gKOzYU/Ahdmz8B4Bci8Ahy8Ao55hafM
+uHFupvsKMDhKODYUfgjcW3yDExSgCwpwCEp4FhSeBFbv9rMUYDsKMDhKODYUTiOXf0thXEKkDkF
ODgFHHMKp9kL152VNNlUgMNUwLGpcJy93FCZqwDZVYDDVcCxq0DCF648K2oyrQAHrYBp5uFf8y0s
cxYgOwtwOAuYYi9/4fqzFiejC3CgC5hyJ3/56Ge1TiYY4CAYMOGsTSjcCazpySADHCADpmVnE+oP
A1b8ZKABDqAB03reLuj3AhMbIIsNcIgNmEkPlKfNwLwGyF4DHF4DZtL+SsNmYGQDZLIBDrIB88hS
f1GvMyt7MtkAB9mAmZS9wqgZmNkA2WyAw2zAPLPMhYkrMK8BstcAh9eAmTS72qAZGNYAGWuAA2vA
fFro1DkzMKIBMtEAB9GA+bS7yS8QMJoBMs0AB82AeaF51SkzMJoBMs0AB82AeaWZ1SEzMJMBsskA
h8mAONDM6tHFLAbIFgMcFgPitIMVXttnBgNkgwEOgwFx2r/kCTMwewGyvQCHvYA4rV/qgBmYuABZ
XIBDXECcVi/1JS8mLEAWFuAQFhCnnUt+s4WxCpBZBThYBUTyvIUvSZinANlTgMNTQKATW/9WhEEK
kCEFOCAFxMJjVx5SrH3JhgIchgJi5bHlTzbTEyDrCXDoCcjT+qW/qcbIBMhkAhxkAnLoBC6cZcxJ
gOwkwOEkIMdebv0wYzgCZBwBDhwBedrEqu/fMxIBMokAB4mAnHux1V7GLATIFgIcFgIyeqn1Q5zV
M5k/gIM/QOZmbD0762gyewAHe4BEL3vhOcZKmgwfwAEfIE9L2mveZWAAAmQAAQ4AAbluRNefZkxC
gCwhwCEhAId+dPl5xjQEyBoCHBoCMPSDq080RiJAJhHgIBGAsZ9bPteZiQDZRIDDRACmneCFQ47Z
CJBtBDhsBGDey1846ViVk3kEOHgEIHby63c/a3SyjwCHjwBkP73ea5iNANlGgMNGALCXvPLBZ8VO
5hHg4BGAZXcDCp98Vu9kHgEOHgE4rXeVMTIGIkAGEeAAEXAMInw712pzZEw/gKwfwKEf4Fg/eIos
D5Ix6QCydACHdIBj6eApcWWSjLkGkF0DOFwDHLsGz6Hl84sZBpANAzgMAxwbBk+Ri7NkDDKADBnA
ARngGDJ4mbtwvVlXkyUDOCQDHEsGL3JXf01hpgFk0wAO0wDHpgEJX7jyrKrJtgEctgGObYMX4ctF
lREHkIkDOIgDHBMHLL1+7Rl0ABk6gAM6wHropH/Nt7AMPoAMH8ABH2AddjegcAewPidDCHBACFjH
vQ2oPgCYjABZRoBDRsA6nbcLhXuBdT6ZSoCDSsA67+1C+ZHA9ATIegIcegLWOHMbCncDa4SyqACH
qICVNUJ9royRCpBJBThIBaysB9YGyxisABlWgANWwLrQ2OpkGbMVINsKcNgKWFntO3u07H9/+z8/
IWpXZ4YBAA==
T_EOF
echo "payload bytes: $(wc -c < "$ROOT/table.json")"
python3 - "$ROOT" <<'PY_EOF'

import json, os, re, shutil, subprocess, sys, time

ROOT = sys.argv[1]
T = json.load(open(os.path.join(ROOT, "table.json")))
LANG = T["language"]
PROBES = T["probes"]
OUT = T["out"]
out = open(OUT, "w")
WORK = os.path.join(ROOT, "u")

# --- verbatim delimiter codec, copied from verbatim_diag.py ---
def esc(text):
    """make `text` safe to place in one pipe-delimited field, reversibly."""
    for raw, rep in _ENC:
        text = text.replace(raw, rep)
    return text

_ENC = [('\\', '\\\\'), ('|', '\\p'), (';', '\\s'), ('\n', '\\n'), ('\r', '\\r')]
MARKER = '#verbatim-escape v1'
out.write(MARKER + '\n')


print("op lane %s: %d candidate probes" % (LANG, len(PROBES)))
sys.stdout.flush()


def sh(cmd, cwd=None, timeout=180):
    try:
        p = subprocess.run(cmd, cwd=cwd, stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE, timeout=timeout)
        so = p.stdout.decode("utf-8", "replace")
        se = p.stderr.decode("utf-8", "replace")
        return p.returncode, so, se
    except subprocess.TimeoutExpired:
        return 124, "", "TIMEOUT after %ds" % timeout
    except OSError as e:
        return 125, "", "OSError %s" % e


# ------------------------------------------------------ objdump reading

LABEL = re.compile(r"^([0-9a-f]+)\s+<(.+)>:\s*$")
INSN = re.compile(r"^\s*([0-9a-f]+):\t(.*)$")
RELOC = re.compile(r"^\s+([0-9a-f]+): (R_\S+)\t(.+?)\s*$")


def extract(text, sym, exact):
    """the two columns for one symbol.

    bytes  every byte objdump printed, in order, flattened
    mnem   the instruction text, with objdump's own trailing `# ...`
           comment dropped -- that comment is arithmetic objdump did
           for the reader, not part of the instruction.  A relocation
           is appended to the instruction it applies to as
           ` !!reloc=<type>:<symbol>`, because in an object file the
           call displacement is literally zero and the callee's name
           lives only in the relocation.
    """
    lines = text.splitlines()
    k = -1
    for idx, ln in enumerate(lines):
        m = LABEL.match(ln)
        if not m:
            continue
        lab = m.group(2)
        hit = (lab == sym) if exact else (sym in lab)
        if hit:
            k = idx
            break
    if k < 0:
        return None
    raw = []
    mn = []
    for ln in lines[k + 1:]:
        if LABEL.match(ln):
            break
        m = INSN.match(ln)
        if not m:
            r = RELOC.match(ln)
            if r and mn:
                mn[-1] = "%s !!reloc=%s:%s" % (mn[-1], r.group(2), r.group(3))
            continue
        parts = m.group(2).split("\t")
        bs = parts[0].split()
        raw.extend(bs)
        txt = parts[1] if len(parts) > 1 else ""
        txt = txt.split("#")[0]
        txt = " ".join(txt.split())
        if txt:
            mn.append(txt)
    return raw, mn


def disasm(obj, sym, exact):
    rc, so, se = sh(["objdump", "-dr", "--disassemble=" + sym, obj])
    got = extract(so, sym, exact) if rc == 0 else None
    if got is None:
        rc, so, se = sh(["objdump", "-dr", obj], timeout=600)
        got = extract(so, sym, exact)
    return got


# --------------------------------------------------------- DWARF reading
#
# objdump --dwarf=info prints one entry per line block:
#
#   <1><2d>: Abbrev Number: 2 (DW_TAG_subprogram)
#      <2e>   DW_AT_name        : op_12
#   <2><4a>: Abbrev Number: 3 (DW_TAG_formal_parameter)
#      <4b>   DW_AT_name        : a
#      <52>   DW_AT_location    : 2 byte block: 91 7c (DW_OP_fbreg: -4)
#
# The leading <N> is the tree depth.  A formal parameter one level
# below the matching subprogram is a parameter OF that subprogram.

DIE = re.compile(r"^\s*<(\d+)><[0-9a-f]+>:\s*Abbrev Number:\s*\d+\s*\((\S+)\)")
ATTR = re.compile(r"^\s*<[0-9a-f]+>\s+(DW_AT_\w+)\s*:\s*(.*?)\s*$")


def clean(text):
    text = " ".join(text.split())
    return text


STRPREFIX = re.compile(r"^\((?:indexed string|indirect string)[^)]*\):\s*")


def dwname(text):
    """objdump prints a string attribute as `(indexed string: 0x5): a`.
    The parenthesised part is objdump telling the reader WHERE in the
    string table it found the name; the name is what follows.  Keeping
    the prefix would have put objdump's bookkeeping into the parameter
    name column."""
    return STRPREFIX.sub("", text.strip())


def dwarf_params(text, sym):
    """[(name, location)] for the subprogram named `sym`.

    More than one subprogram can carry the name.  swift's `@_cdecl`
    emits a C-entry thunk beside the real function, and the thunk has
    no DW_TAG_formal_parameter children at all, so the first match is
    not always the one holding the parameter table.  Every match is
    collected and the first one that actually has parameters wins."""
    lines = text.splitlines()
    depth = None
    tag = None
    attrs = {}
    entries = []
    for ln in lines:
        m = DIE.match(ln)
        if m:
            if tag is not None:
                entries.append((depth, tag, attrs))
            depth = int(m.group(1))
            tag = m.group(2)
            attrs = {}
            continue
        a = ATTR.match(ln)
        if a and tag is not None:
            attrs[a.group(1)] = a.group(2)
    if tag is not None:
        entries.append((depth, tag, attrs))

    hits = []
    for idx, (d, t, at) in enumerate(entries):
        if t != "DW_TAG_subprogram":
            continue
        names = []
        if "DW_AT_name" in at:
            names.append(dwname(at["DW_AT_name"]))
        if "DW_AT_linkage_name" in at:
            names.append(dwname(at["DW_AT_linkage_name"]))
        for nm in names:
            if nm == sym or sym in nm:
                hits.append(idx)
                break
    if not hits:
        return None
    best = []
    for k in hits:
        base = entries[k][0]
        got = []
        for d, t, at in entries[k + 1:]:
            if d <= base:
                break
            if d != base + 1:
                continue
            if t != "DW_TAG_formal_parameter":
                continue
            nm = clean(dwname(at.get("DW_AT_name", "(unnamed)")))
            loc = clean(at.get("DW_AT_location", "(no location)"))
            got.append((nm, loc))
        if got:
            return got
        best = got
    return best


def dwarf(obj, sym):
    rc, so, se = sh(["objdump", "--dwarf=info", obj], timeout=600)
    if rc != 0:
        return None, "objdump --dwarf=info rc=%d" % rc
    got = dwarf_params(so, sym)
    if got is None:
        return None, "no DW_TAG_subprogram named %s" % sym
    if not got:
        return None, "subprogram %s has no DW_TAG_formal_parameter" % sym
    return got, None


# ------------------------------------------------------------ compiling

GOMOD = "module opprobe\n\ngo 1.26\n"

CLANG = "/usr/bin/clang"
CLANGXX = "/usr/bin/clang++"
SWIFTC = "/persist/swift/usr/bin/swiftc"


def compile_probe(p, d, mode):
    """(rc, artifact path, diagnostic text)."""
    if LANG == "c":
        src = os.path.join(d, "unit.c")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANG, "-std=c17"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "cpp":
        src = os.path.join(d, "unit.cpp")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-O0", "-g"] if mode == "anchor" else ["-O1"]
        cmd = [CLANGXX, "-std=c++20"] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "rust":
        src = os.path.join(d, "unit.rs")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        if mode == "anchor":
            opt = ["-C", "opt-level=0", "-g"]
        else:
            opt = ["-C", "opt-level=1", "-C", "debug-assertions=off"]
        cmd = (["rustc", "--crate-type=lib", "--emit=obj"] + opt
               + ["-o", obj, src])
        rc, so, se = sh(cmd)
        return rc, obj, (se or so)
    if LANG == "go":
        open(os.path.join(d, "go.mod"), "w").write(GOMOD)
        open(os.path.join(d, "main.go"), "w").write(p["source"])
        obj = os.path.join(d, "bin_%s" % mode)
        cmd = ["go", "build"]
        if mode == "anchor":
            cmd.append("-gcflags=-N -l")
        cmd.extend(["-o", obj, "."])
        rc, so, se = sh(cmd, cwd=d, timeout=300)
        return rc, obj, (se or so)
    if LANG == "swift":
        src = os.path.join(d, "unit.swift")
        obj = os.path.join(d, "unit_%s.o" % mode)
        open(src, "w").write(p["source"])
        opt = ["-Onone", "-g"] if mode == "anchor" else ["-O"]
        cmd = [SWIFTC] + opt + ["-c", src, "-o", obj]
        rc, so, se = sh(cmd, timeout=300)
        return rc, obj, (se or so)
    raise KeyError(LANG)


DIAG = re.compile(r"^[^\s:]+:\d+(:\d+)?:")


def firstline(txt):
    """the compiler's own words for why it refused.

    The first line is not reliably the reason.  clang leads with a
    warning and puts the error underneath.  go leads with a banner
    naming the package -- `# opprobe` -- and its diagnostics never
    contain the word `error` at all, so a rule that only looked for
    that word recorded the banner and threw the testimony away.
    Three passes, in order: a line saying `error`, a line in the
    `file:line:col:` diagnostic shape, then the first line that is
    not a banner."""
    lines = []
    for ln in txt.splitlines():
        s = ln.strip()
        if s:
            lines.append(s)
    for ln in lines:
        if re.search(r"\berror\b", ln, re.I):
            return ln[:200]
    for ln in lines:
        if DIAG.match(ln):
            return ln[:200]
    for ln in lines:
        if not ln.startswith("#"):
            return ln[:200]
    if lines:
        return lines[0][:200]
    return "(no diagnostic)"


def write_unit(n, build, obj, sym, exact):
    got = disasm(obj, sym, exact)
    if got is None:
        rc2, so2, se2 = sh(["objdump", "-t", obj])
        near = 0
        for l in so2.splitlines():
            if sym in l:
                near += 1
        out.write("op_%d|%s|NOSYM|%s\n"
                  % (n, build, esc("symbol %s absent, %d near matches"
                                   % (sym, near))))
        return False
    raw, mn = got
    out.write("op_%d|%s|OK|%s|%s\n"
              % (n, build, " ".join(esc(x) for x in raw),
                 ";".join(esc(x) for x in mn)))
    return True


t0 = time.time()
tally = {"REFUSED": 0, "ACCEPTED": 0, "ANCHOR_OK": 0, "SHIP_OK": 0,
         "DWARF": 0}

for k, p in enumerate(PROBES):
    n = p["n"]
    sym = p["symbol"]
    exact = p["symbol_exact"]
    d = os.path.join(WORK, "n%d" % n)
    shutil.rmtree(d, ignore_errors=True)
    os.makedirs(d)

    rc, obj, err = compile_probe(p, d, "ship")
    if rc != 0 or not os.path.exists(obj):
        out.write("op_%d|REFUSED|%s\n" % (n, esc(firstline(err))))
        tally["REFUSED"] += 1
        out.flush()
        shutil.rmtree(d, ignore_errors=True)
        continue
    tally["ACCEPTED"] += 1
    if write_unit(n, "SHIP", obj, sym, exact):
        tally["SHIP_OK"] += 1

    rc, aobj, aerr = compile_probe(p, d, "anchor")
    if rc != 0 or not os.path.exists(aobj):
        out.write("op_%d|ANCHOR|BUILDFAIL|%s\n" % (n, esc(firstline(aerr))))
    else:
        if write_unit(n, "ANCHOR", aobj, sym, exact):
            tally["ANCHOR_OK"] += 1
        rows, why = dwarf(aobj, sym)
        if rows is None:
            out.write("op_%d|ANCHOR|NODWARF|%s\n" % (n, esc(why)))
        else:
            joined = ";".join("%s=%s" % (esc(a), esc(b)) for a, b in rows)
            out.write("op_%d|ANCHOR|DWARF|%s\n" % (n, joined))
            tally["DWARF"] += 1
    out.flush()
    shutil.rmtree(d, ignore_errors=True)

    if (k + 1) % 25 == 0 or (k + 1) == len(PROBES):
        el = time.time() - t0
        print("[progress] %s [%d/%d] elapsed %.1fs mean %.2fs  "
              "REFUSED %d ACCEPTED %d SHIP_OK %d ANCHOR_OK %d DWARF %d"
              % (LANG, k + 1, len(PROBES), el, el / (k + 1),
                 tally["REFUSED"], tally["ACCEPTED"], tally["SHIP_OK"],
                 tally["ANCHOR_OK"], tally["DWARF"]))
        sys.stdout.flush()

out.close()
print("done: %s -> %s" % (json.dumps(tally), OUT))

PY_EOF
echo "--- lane finished, rc=$?"
date -u +%Y-%m-%dT%H:%M:%SZ
