'use strict';
// generated by scripts/build_arch_units_int.py
//
// The RV64 integer arch-opcodes as javascript.  Every value is a BigInt and
// the 64-bit width is carried by an EXPLICIT MASK on every result that can
// leave it; `au_s` reads a pattern signed.  BigInt and not Number: a Number
// is an IEEE double and would lose the low bits.  Shift counts are masked to
// the width RISC-V uses; au_sra / au_sraw are written out in unsigned bit
// operations; signed divide and remainder go through unsigned magnitudes so
// the sign rule is RISC-V's (truncate toward zero).

const M64 = 0xffffffffffffffffn;
const M32 = 0xffffffffn;
const ONES = M64;
const MIN64 = 0x8000000000000000n;

function au_s(x) { x &= M64; return (x >> 63n) ? x - (1n << 64n) : x; }

const au_b2u = (b) => (b ? 1n : 0n);
const au_sext32 = (x) =>
  ((x >> 31n) & 1n) ? (((x & M32) - (1n << 32n)) & M64) : (x & M32);
const au_add = (a, b) => (a + b) & M64;
const au_sub = (a, b) => (a - b) & M64;
const au_and = (a, b) => a & b;
const au_or = (a, b) => a | b;
const au_xor = (a, b) => a ^ b;
const au_andn = (a, b) => a & (~b & M64);
const au_mul = (a, b) => (a * b) & M64;
const au_addw = (a, b) => au_sext32((a + b) & M64);
const au_subw = (a, b) => au_sext32((a - b) & M64);
const au_mulw = (a, b) => au_sext32((a * b) & M64);
const au_sll = (a, s) => (a << (s & 63n)) & M64;
const au_srl = (a, s) => (a >> (s & 63n)) & M64;

function au_sra(a, n) {
  const s = n & 63n;
  const r = a >> s;
  const m = (0n - (a >> 63n)) & M64;
  return (r | (((m << (63n - s)) << 1n) & M64)) & M64;
}

const au_sllw = (a, n) => au_sext32((a << (n & 31n)) & M32);
const au_srlw = (a, n) => au_sext32((a & M32) >> (n & 31n));

function au_sraw(a, n) {
  const s = n & 31n;
  let r = (a & M32) >> s;
  const m = (0n - ((a >> 31n) & 1n)) & M64;
  r |= ((m << (31n - s)) << 1n) & M32;
  return au_sext32(r & M32);
}

const au_slt = (a, b) => au_b2u(au_s(a) < au_s(b));
const au_sltu = (a, b) => au_b2u((a & M64) < (b & M64));
const au_eqz = (a) => au_b2u((a & M64) === 0n);
const au_nez = (a) => au_b2u((a & M64) !== 0n);
const au_ltz = (a) => au_b2u(au_s(a) < 0n);
const au_gez = (a) => au_b2u(au_s(a) >= 0n);
const au_czeqz = (v, c) => ((c & M64) === 0n ? 0n : v);
const au_cznez = (v, c) => ((c & M64) !== 0n ? 0n : v);

const au_divu = (a, b) => (b === 0n ? ONES : (a / b) & M64);
const au_remu = (a, b) => (b === 0n ? a : (a % b) & M64);

function au_div(a, b) {
  if (b === 0n) return ONES;
  if (a === MIN64 && b === ONES) return MIN64;
  const na = a >> 63n, nb = b >> 63n;
  const ua = na ? (0n - a) & M64 : a, ub = nb ? (0n - b) & M64 : b;
  const q = ua / ub;
  return (na ^ nb) ? (0n - q) & M64 : q & M64;
}

function au_rem(a, b) {
  if (b === 0n) return a;
  if (a === MIN64 && b === ONES) return 0n;
  const na = a >> 63n, nb = b >> 63n;
  const ua = na ? (0n - a) & M64 : a, ub = nb ? (0n - b) & M64 : b;
  const r = ua % ub;
  return na ? (0n - r) & M64 : r & M64;
}

const au_divw = (a, b) => au_sext32(au_div(au_sext32(a), au_sext32(b)));
const au_remw = (a, b) => au_sext32(au_rem(au_sext32(a), au_sext32(b)));
const au_divuw = (a, b) => au_sext32(au_divu(a & M32, b & M32));
const au_remuw = (a, b) => au_sext32(au_remu(a & M32, b & M32));

module.exports = {
  au_s, au_b2u, au_sext32, au_add, au_sub, au_and, au_or, au_xor, au_andn,
  au_mul, au_addw, au_subw, au_mulw, au_sll, au_srl, au_sra, au_sllw,
  au_srlw, au_sraw, au_slt, au_sltu, au_eqz, au_nez, au_ltz, au_gez,
  au_czeqz, au_cznez, au_divu, au_remu, au_div, au_rem, au_divw, au_remw,
  au_divuw, au_remuw,
};
