-- generated by construct/general/run_lemmas_t4.py from construct/general/build.py itself
import Std.Tactic.BVDecide

theorem construction_complement_w1_u64__bvnot_w1 (a : BitVec 1) :
    (~~~a) =
      (let t0 : BitVec 1 := (a.extractLsb 0 0)
      let t1 : BitVec 1 := (~~~t0)
      let t2 : BitVec 1 := (t1.extractLsb 0 0)
      t2) := by
  bv_decide
