-- generated by construct/general/run_lemmas_t4.py from construct/general/build.py itself
import Std.Tactic.BVDecide

theorem construction_subtract_w9_u64__bvsub_w9 (a : BitVec 9) (b : BitVec 9) :
    (a - b) =
      (let t0 : BitVec 9 := ((1#1).zeroExtend 9)
      let t1 : BitVec 9 := (b.extractLsb 8 0)
      let t2 : BitVec 9 := (~~~t1)
      let t3 : BitVec 9 := (a.extractLsb 8 0)
      let t4 : BitVec 9 := (t3 ^^^ t2)
      let t5 : BitVec 9 := (t4 &&& t0)
      let t6 : BitVec 9 := (t3 &&& t2)
      let t7 : BitVec 9 := (t6 ||| t5)
      let t8 : BitVec 9 := (t7 <<< (1#9))
      let t9 : BitVec 9 := (t4 &&& t8)
      let t10 : BitVec 9 := (t7 ||| t9)
      let t11 : BitVec 9 := (t10 <<< (2#9))
      let t12 : BitVec 9 := (t4 <<< (1#9))
      let t13 : BitVec 9 := (t4 &&& t12)
      let t14 : BitVec 9 := (t13 &&& t11)
      let t15 : BitVec 9 := (t10 ||| t14)
      let t16 : BitVec 9 := (t15 <<< (4#9))
      let t17 : BitVec 9 := (t13 <<< (2#9))
      let t18 : BitVec 9 := (t13 &&& t17)
      let t19 : BitVec 9 := (t18 &&& t16)
      let t20 : BitVec 9 := (t15 ||| t19)
      let t21 : BitVec 9 := (t20 <<< (8#9))
      let t22 : BitVec 9 := (t18 <<< (4#9))
      let t23 : BitVec 9 := (t18 &&& t22)
      let t24 : BitVec 9 := (t23 &&& t21)
      let t25 : BitVec 9 := (t20 ||| t24)
      let t26 : BitVec 9 := (t25 <<< (1#9))
      let t27 : BitVec 9 := (t26 ||| t0)
      let t28 : BitVec 9 := (t4 ^^^ t27)
      let t29 : BitVec 9 := (t28.extractLsb 8 0)
      t29) := by
  bv_decide
