-- generated by construct/general/run_lemmas_t4.py from construct/general/build.py itself
import Std.Tactic.BVDecide

theorem construction_wiring__widen__narrow__spread_the_sign__join_w56_u64__extract_from112_h58_l3 (a : BitVec 112) :
    (a.extractLsb 58 3) =
      (let t0 : BitVec 64 := (a.extractLsb 63 0)
      let t1 : BitVec 56 := (t0.extractLsb 58 3)
      let t2 : BitVec 56 := (t1.extractLsb 55 0)
      t2) := by
  bv_decide
