-- generated by construct/general/run_lemmas_t4.py from construct/general/build.py itself
import Std.Tactic.BVDecide

theorem construction_wiring__widen__narrow__spread_the_sign__join_w2_u64__extend_zero_from1_t2 (b : BitVec 1) :
    (b.zeroExtend 2) =
      (let t0 : BitVec 1 := (b.extractLsb 0 0)
      let t1 : BitVec 1 := (t0.extractLsb 0 0)
      let t2 : BitVec 2 := ((0#1) ++ t1)
      let t3 : BitVec 2 := (t2.extractLsb 1 0)
      t3) := by
  bv_decide
