-- generated by construct/general/run_lemmas_t4.py from construct/general/build.py itself
import Std.Tactic.BVDecide

theorem construction_wiring__widen__narrow__spread_the_sign__join_w33_u64__extend_zero_from16_t33 (b : BitVec 16) :
    (b.zeroExtend 33) =
      (let t0 : BitVec 16 := (b.extractLsb 15 0)
      let t1 : BitVec 16 := (t0.extractLsb 15 0)
      let t2 : BitVec 33 := ((0#17) ++ t1)
      let t3 : BitVec 33 := (t2.extractLsb 32 0)
      t3) := by
  bv_decide
