#!/bin/sh
# layer-3 CARTESIAN lane -- cpp -- level 2 shard 0 of 2 --
# generated by Research/kind_fuzz_clustering/l3_cart_gen.py (log_062).
# Do not hand-edit.  Static path: the ACCEPTED holder pairs only, from
# the census's own acceptance_cpp_A2.json.  A value the holder cannot represent is
# ABSENT from the row, never coerced.
set -u
export HOME=/work
export PATH=/persist/dart-sdk/bin:/persist/dotnet:/persist/kotlinc/bin:/persist/swift/usr/bin:$PATH
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_NOLOGO=1
export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1
# swift's binaries need libncurses.so.6 and the image ships only
# libncursesw.so.6.6.  The symlink lives in the image's own /usr/lib and
# therefore does NOT survive a container restart, so it is re-made here.
if [ -f /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 ]; then
  ln -sf /usr/lib/x86_64-linux-gnu/libncursesw.so.6.6 \
     /usr/lib/x86_64-linux-gnu/libncurses.so.6 2>/dev/null
  ldconfig 2>/dev/null
fi
echo "=== layer-3 CARTESIAN -- cpp -- level 2 -- 1261233 probes ==="
date -u +%Y-%m-%dT%H:%M:%SZ
# refuse in seconds rather than in an hour if the toolchain is not here
if ! g++ --version >/dev/null 2>&1; then
  echo "!! REFUSING TO START: g++ is not runnable in this container."
  echo "!! tried: g++ --version"
  echo "!! gcc-15/g++-15 is installed by Airlock's own Containerfile"
  exit 4
fi
g++ --version 2>&1 | head -2
ROOT=/work/ct_cpp_l2_s0
rm -rf "$ROOT"; mkdir -p "$ROOT"
df -Pm /work | awk 'NR==2{print "free /work: " $4 " MB"}'
FREE=`df -Pm /work | awk 'NR==2{print $4}'`
if [ "$FREE" -lt 400 ]; then
  echo "!! REFUSING TO START: only $FREE MB free on /work, need 400"
  exit 3
fi
base64 -d <<'T_EOF' | gunzip > "$ROOT/table.json"
H4sIAAAAAAAC/92bbW/jxhWF/4qrIkJCiib1wjdnPEDRTwGafGqAAptK0MzIa6GyJNhSEyDKfy9J
ieI5GooaGUU/1LtL6g4v51jnPhxeU97fe6v5+ut+/nXRe3ro6e22N3jobbYfRfSl55dBUG68chOW
m2/Kjag2z+VWVpvq5XO1/VO17ZebQ7mZVrnVGbJK7h+PHY5zyN4/i/3rZmUW75Xq771lsRsXgy+b
97fyu9q973evvXNWOaQ2m1U58r7YYvix2M2W5nxO+LdROHoqXi4GL/PVx6JK2S5Wq+X66/EdlsfK
0ePh8juZq4/FelcdjMojw3LzS/Gn3K+XqyppXRwflclVXqn+MH94fihn+77MO49U835fnaOaXGXl
Ks7VTa62cjXnmibXWLmGc7fvVZl7fwwejjZPwOZfC3sXbPNyvRuPZjtwGkYas6szS7Pjp2A4iAbD
QToYTcfDYGg7fhxrrE3LzSn5wv9gNE3G9eHjPh4H51f+6VUyPp1aViU+V+X0nVZlCIaVJTgUWSN2
TmqN/PDT34vXP/7lH1jTOkHZSspSUpaSspSUraRJSdtK2lLSlpK2lLStZEjJ2ErGUjKWkrGUjK10
ovHPy7Ve7c3iQeiPnSny5S/rZuxj916wIxtk45vIJpNLZOuRFmSH0VPF2eCC3Go3OBI3OOI2OLFm
M12D2gW3O8fNJVBTPYwQ6/Ld1DQWr3/84afa6Ysjf/02GH539Vh0/VDHWen1Q6PhJJ1k42TikpNd
z8mjKB3m+SguUqM8Hzpnjq9l2hdslaCueqg6PFTXPVTXPVTXPVQOHioHD5Wzh8rZQ2V7qMlDfdVD
3eGhvu6hvu6hvu6hdvBQO3ionT3Uzh5q20NDHpqrHpoOD811D811D811D42Dh8bBQ+PsoXH20Nge
fu72kXTfPvb2/WPffQPJnj572/jv3SfoDlTfNLLzPWOPK+LPTFrbsTM07QfTroOX4NzIyrqy2uFx
yh135o5G43E6isZJVqSncRaV32xzf9jj6nfNL9Xll+rySzn5pZz8Unf4pe7wS7n5pdkv3eGX7vJL
d/mlnfzSTn7pO/zSd/il3fwy7Jfp8Mt0+WW6/DJOfhknv8wdfpk7/DJufn1ujU+71/jZrJhhOMpg
jceh/4MfEuq3Uy1739bRd0xaZ1LTblxJ+/mi9biV5jhb6pZ2SbVzfuaW3076nWeNHc+6cTc6n69c
iqnciqnciqnciqnciqnuLKa6s5jqU8VUnyqmureYmoupXYqp3Yqp3Yqp3Yqp3Yqp7yymvrOY+lPF
1J8qpr63mIaLaVyKadyKadyKadyKadyKae4sprmzmOZTxTSfKqa5t5hWk3FqKLDHmK++bt6Xu9c3
aDMyaDNe3ud6t9ys5yvuNcxmr479x6nTaAaaPqM5uW423ua/zV6W6+VuUbQcj9EgiIqNX23eluvZ
x16tC+H5alAcDIb71bZ8Uf7zqwBOjx7bepEm4diRPFbtSKlS7v16T1pVw3KSO70+7fx6iKctpW+2
Kkc/Tk/pH9M8TfLxcDzJktF4GKcLfxxlVXk5L7LGInusZSheBOPRxE7ML74uM1oUiyH+GtkZTm+n
sAlv96cjytEQ1WKIajFE2YaoVkPUTUOUbYi6aYhyM0ShIRoN0Y6G6BZDdIsh2jZEtxqibxqibUP0
TUO0myEaDTFoiHE0xLQYYloMMbYhptUQc9MQYxtibhpi3AwxaIi9dBdr92L+Rmv3cvM2Xy+3NKbf
5rtXGlkt35a7j+4fLHOHFf9ltZnj48NzfG29nzxdLPGnhfXyc9P2NbocvnwYyMvwzVX8xvK9Pn1O
fFyvq7dzXoZfqsrAWGSPtQwdz2zWvOMR1TKpaplU2ZMqmlTDpLplUt0yqbYn1TSpgUlNy6SmZVJj
T2po0v8Rv5UpBU0VSl+Ov6IxLv4W400UU5RSlDdRgcKEooSirIliUohJISaFmBQSUkhIISGFlBRS
UkhJISWFjBQyUshIISeFnBRyUshrhW+Olk0wSM7BpJ7wFMQYpOcgxglinCDBCRKcIMEJUpwgrSfo
Y+H7WPc+lr2Pde5jmftY1z6WtY9V7WMZ+1jFPpatj1XrY9H6fXSxjhKKsiY6u1pHMUUpRXkTxaQQ
k0JMCgkpJKSQkEJCCikppKSQkkJGChkpZKSQkUJOCjkp5LWCh4X3sPAeFt7Dy91DCjykwMNr3UMk
PETCQyQ8vM495MNDPjy8yD2ExUNYPITFwwvcw+vbw8vbw6vbw4vbw2vbw0vbwyvbRyZ9RNJHIn0E
0kcefcTRRxp9hNFHFn1E0UcSfQTRRw59xNBHCn2E0EcGfUTQRwJ9BNBH/nzEz0f6fIQvQPgChC9A
+AKEL0D4AoQvQPgChC9A+AKEL0D4AoQvQPgChC9A+AKEL0D4AoQvQPgChC9A+AKEL0D4AoQvQPhC
hC9E+EKEL0T4QoQvRPhChC9E+EKEL0T4QoQvRPhChC9E+EKEL0T4QoQvRPhChC9E+EKEL0T4QoQv
RPgEwicQPoHwCYRPIHwC4RMIn0D4BMInED6B8AmETyB8AuETCJ9A+ATCJxA+gfAJhE8gfALhEwif
QPgEwicE0ldHSROdkaujmKK0iWKaJaZZEpoloVkSmiWlWc5QCepsBXW2gjpbQZ2toM5WUGcrqLMV
1NkK6mwFdbaCOltBna2gzlZQZyuosxXU2QrqbAV1toI6W0GdraDOVlBnK6izFdTZCupsn5+RgjpK
KMqa6MxEHcUUpRSBQkwKMSnEpJCQQkIKCSkkpJCSQkoKKSlkpJCRQkYKGSnkpJCTwnlpkgirRFYl
oiqRVImgSuRUIqYSKZUIqURGJSIqkVCJgErkUyKeEumUCKdENiWiKZFMiWBK5FIilhKplAilJCgl
QSkJSklQSoJSEpSSoJQEpSQoJUEpCUpJUEqCUhKUkqCUBKUkKCVBKQlKSVBKglISlJKglAwlU8lY
MpfMIsPIADKBjCBjx9wxawwb0TZFCKbIwBSLPsWaT7HkU6zxFEs8xZpOsaRTrOgUSzjFCh7Q0AP6
eUA7D+jmAc08oJcHtPKATh7QyAP6eEAbD+jiAU08HNDFOkooypro7GodxRSlFOVNFJNCTAoxKSSk
kJBCQgoJKaSkkJJCSgoZKWSkkJFCRgo5KeSkUF1K5SO31eLfi9Xpvwrp1/36X+WHhlEUnR/8fWn5
zabyUaH9CI8G4cPIQdvDQx6tHx/y6PEBIo+dHiFWTyY3+/Jhci8s9qHezfR2O1uNZh/R4+6349Ps
3Xy1mpUPFIfxY3QceN/tt9VQEj1Gf/wH2HB41Vs2AAA=
T_EOF
base64 -d <<'X_EOF' | gunzip > "$ROOT/rt.txt"
H4sIAAAAAAAC/71XUY/iNhB+51dMUx1KDm61XO/abRao9tRttRJd7nbhabuKTOKA1eBEsZPlevDf
O7ZDSCBwRysVwcaejOebb2Zsz7a+Z9yPsoBC3xcyYPGwVZdEbLYnShmf72sxLquiQyX5OaGeTAmT
Yl/MeFhHjZcJSWlNtFqRGbtYDFstIYlkPiCm6xoY8Barme3HXEjIuGBzTgPwFySF10kXBPsbgYE7
8KUFUKw2ykZnAQOwLntvf3j3/sefrn4mMz+goXWtlXcYQgnCOAW7MMhw2eU1PvrA8dHpIAAI6Axg
8ZQ8sWcYDuHd83VN1IbeexRt0FRKZZZyZXbTknSZREQqnhERAiZDaGI5w9gVNCfQzg2hOuGUvDwp
/+LQnjjPXZjRyrSktKRLP/lso3IX7ZgQaRXnBMlSqSCLppHRoA4Jb6CHP6axCoo6OzNah9kcyeOW
YFXcFoZq1V5zuh1xERBJbAfBLhScbbC+McCS2wYJqxnfaO44M7YDnGINuq7n+SviBXRJ+Dyitq7g
AFldcLKkCvpSf9tCOvtFlKKNAH7Bnwv765QuC8EOHAhTSvFZiWHayKILZjCAPGaB4pRmvgSPSZoi
gkYOSSQwkwgGXzbXDZFoVVf10aZepgx6sh9QP1JrbS2c0TnjZqhe5CTql+U4xFA7XfT4+KdujPLg
lKnhUNsqWKCLFRLN+awkknK/ulHOX2GqIDTnBF0lakcodSY8gdnychWoWRxHQ6NaJirH7FofxuOR
dtlC/81Mp0EfKhugOPyqcc/DIuy9vdoHsO7uJy7KXQs6xZGQO2fYLXfMUYDpv0JAY3Sekkih7Jvc
uaGhtYqKkwLSIdKQlgOdav2YxMeeSZG9O2NewxWqgnWeg5RnyybnrNv76R/a1B6gHcVYGeqP8w3m
wyjGA4XPvSTGUDQC/TYa30yakP4rtV12tzWNTntxGlB9C8N6fWxfHrHwQslfu/UHJd6HS5W+8cOv
7miiEmjnMBjshLefdFbV8PeJdbb/ePlLhpV04IA6HjVSo5rrZlyPKR6h25grH6b3euP9fwSK7mc/
/4+Th6bs59ubapv4E5vgQNfcmWfVSLX3Oa82ijXVdHyX72J9Px2NikjXOqfCva8GQpwRCNEcCHF2
rngWRYlMPXmQrpLOSXN6u9O0acPru+Dj5EHX0mlrxeU7xIuXRBndGjpoQKFsZ7fNSdGvmaSSTMbQ
poiXb02YNGH3q/tQq1skCMxc33vU2cp4p2OGm1okRnePjecW19F/0m/U6LlKsB7M8cebT9Nb1yhg
L9N0IaueAz1aMmlXa5QF25rdXc21wGAoWKBbLU1xbRVNN/ZzGFLsrA5eKNZ5Kf+Ta7fClxSzYO9a
yN6ui9TFEmemowvDKBMLu5SUvawhgP/jCHqEgZm/LIg0PBJkIEPbeiXWb9YPN3ePt+4rgf50Qa3R
es2I/wA3N7hItw0AAA==
X_EOF
python3 - "$ROOT" <<'PY_EOF'

import json, os, queue, re, shutil, subprocess, sys, threading, time, glob

ROOT = sys.argv[1]
T = json.load(open(os.path.join(ROOT, "table.json")))
OUT = T["out"]
CH = T["chunk"]
LVL = T["level"]
LANG = T["language"]
# log_063: STALL used to be read here and never used again anywhere in
# this driver -- `run_binary`'s read loop had NO timeout at all, so one
# probe that never wrote a line froze the lane forever.  STARTUP is the
# grace before the first line (a JVM/.NET cold start is not a stall);
# STALL applies to every line after that, and a stall now COSTS ONE
# PROBE via the same START-INDEX restart discipline an uncatchable crash
# already used, never the whole lane.
STALL = T.get("stall_s", 15.0)
STARTUP = T.get("startup_s", 60.0)
RTX = open(os.path.join(ROOT, "rt.txt")).read()
HOLD = {h["i"]: h for h in T["holders"]}
OPS = T["ops"]
PRELINES = T.get("pre", [])
TAG = "A" if LVL == 1 else "B"
DOT = "/persist/dotnet"

# ---- the probe list.  A probe is (id, fn name, [decl lines], expr).
probes = []
for (op, i, j) in T["cells"]:
    k = OPS.index(op)
    ha, hb = HOLD[i], HOLD[j]
    na, nb = ha["n"], hb["n"]
    if LVL == 1:
        for i0 in range(na):
            for i1 in range(nb):
                p = i0 * nb + i1
                probes.append(("A%d_%d_%d_%d" % (k, i, j, p),
                               "p_%d_%d_%d_%d" % (k, i, j, p),
                               [ha["a"][i0], hb["b"][i1]],
                               "((a) %s (b))" % op))
    else:
        for i0 in range(na):
            for i1 in range(nb):
                for i2 in range(na):
                    for i3 in range(nb):
                        p = ((i0 * nb + i1) * na + i2) * nb + i3
                        probes.append((
                            "B%d_%d_%d_%d" % (k, i, j, p),
                            "p_%d_%d_%d_%d" % (k, i, j, p),
                            [ha["a"][i0], hb["b"][i1],
                             ha["c"][i2], hb["d"][i3]],
                            "(((a) %s (b)) %s ((c) %s (d)))" % (op, op, op)))

print("cartesian %s level %d: %d cells -> %d probes"
      % (LANG, LVL, len(T["cells"]), len(probes)))
sys.stdout.flush()

COMPILES = {"n": 0, "s": 0.0}


def _split_head(lines, kw):
    h, b = [], []
    for l in lines:
        (h if l.startswith(kw) else b).append(l)
    return h, b


def _dedup(seq):
    out = []
    for s in seq:
        if s not in out:
            out.append(s)
    return out


def _dispatch(ps, decl_fmt, case_fmt, close, group=100):
    """the two-level switch java, kotlin and c# need: a single method
    holding thousands of calls exceeds the 64 KB method limit."""
    n = len(ps)
    src = ""
    for g in range(0, n, group):
        src += decl_fmt % (g // group)
        for i in range(g, min(g + group, n)):
            src += case_fmt % (i, ps[i][1])
        src += close
    return src


def build_src(ps):
    """the whole chunk as ONE source file.  Every probe carries a
    `// __PROBE__ <id>` marker so a compiler error line maps back to the
    probe that caused it."""
    n = len(ps)

    def bodies(fmt):
        return "".join("// __PROBE__ %s\n%s" % (p[0], fmt(p))
                       for p in ps) + "// __PROBE__ -\n"

    if LANG == "cpp":
        src = RTX + "\n" + "\n".join(_dedup(PRELINES)) + "\n"
        src += bodies(lambda p:
                      "static void %s() {\n%s    auto _r = %s;\n"
                      '    _emit("%s", _r);\n}\n'
                      % (p[1], "".join("    %s\n" % d for d in p[2]),
                         p[3], p[0]))
        src += "\ntypedef void (*_FN)();\nstatic _FN _P[] = {\n"
        for p in ps:
            src += "  %s,\n" % p[1]
        src += "};\nstatic const char* _I[] = {\n"
        for p in ps:
            src += '  "%s",\n' % p[0]
        src += "};\n\nint main(int argc, char** argv) {\n"
        src += "  size_t n = %d;\n" % n
        src += "  size_t s = argc > 1 ? (size_t)atol(argv[1]) : 0;\n"
        src += ("  for (size_t i = s; i < n; i++) {\n"
                "    try { _P[i](); } catch (...) { _raise(_I[i], \"cxx\"); }\n"
                "  }\n")
        src += '  printf("__END__\\n");\n  return 0;\n}\n'
        return src, "chunk.cpp"

    if LANG == "swift":
        # swift cannot catch a trap IN LANGUAGE.  The START INDEX is the
        # whole defence: the driver restarts past the probe that stopped
        # the process, so an uncatchable stop costs ONE probe.
        src = RTX + "\n" + "\n".join(_dedup(PRELINES)) + "\n"
        src += bodies(lambda p:
                      "func %s() {\n%s    let _r = %s\n"
                      '    _emit("%s", _r)\n}\n'
                      % (p[1], "".join("    %s\n" % d for d in p[2]),
                         p[3], p[0]))
        src += "\nlet _I: [String] = [\n"
        for p in ps:
            src += '  "%s",\n' % p[0]
        src += "]\nlet _P: [() -> Void] = [\n"
        for p in ps:
            src += "  %s,\n" % p[1]
        src += "]\nsetvbuf(stdout, nil, _IONBF, 0)\nvar _s = 0\n"
        src += ("if CommandLine.arguments.count > 1 "
                "{ _s = Int(CommandLine.arguments[1]) ?? 0 }\n")
        src += "var _i = _s\nwhile _i < _P.count {\n  _P[_i]()\n  _i += 1\n}\n"
        src += 'print("__END__")\n'
        return src, "main.swift"

    if LANG == "dart":
        hdr, rest = _split_head(_dedup(PRELINES), "import ")
        src = "\n".join(hdr) + "\n" + RTX + "\n" + "\n".join(rest) + "\n"
        src += bodies(lambda p:
                      "void %s() {\n  try {\n%s    var _r = %s;\n"
                      "    _emit('%s', _r);\n  } catch (e) {\n"
                      "    stdout.writeln('%s|-|RAISE:' + "
                      "e.runtimeType.toString());\n  }\n}\n"
                      % (p[1], "".join("    %s\n" % d for d in p[2]),
                         p[3], p[0], p[0]))
        src += "\nfinal _P = <void Function()>[\n"
        for p in ps:
            src += "  %s,\n" % p[1]
        src += "];\n\nvoid main(List<String> args) {\n"
        src += "  var s = args.isNotEmpty ? int.parse(args[0]) : 0;\n"
        src += "  for (var i = s; i < _P.length; i++) { _P[i](); }\n"
        src += "  stdout.writeln('__END__');\n}\n"
        return src, "chunk.dart"

    if LANG == "typescript":
        src = "\n".join(_dedup(PRELINES)) + "\n" + RTX + "\n"
        src += bodies(lambda p:
                      "function %s(): void {\n  try {\n%s    let _r = %s;\n"
                      '    _emit("%s", _r);\n  } catch (e: any) {\n'
                      '    process.stdout.write("%s|-|RAISE:" + ((e && '
                      'e.constructor && e.constructor.name) || "error") + '
                      '"\\n");\n  }\n}\n'
                      % (p[1], "".join("    %s\n" % d for d in p[2]),
                         p[3], p[0], p[0]))
        src += "\nconst _P: Array<() => void> = [\n"
        for p in ps:
            src += "  %s,\n" % p[1]
        src += ("];\nconst _s: number = process.argv.length > 2 ? "
                "parseInt(process.argv[2]) : 0;\n")
        src += "for (let i = _s; i < _P.length; i++) { _P[i](); }\n"
        src += 'process.stdout.write("__END__\\n");\n'
        return src, "chunk.ts"

    if LANG == "java":
        rt_h, rt_b = _split_head(RTX.splitlines(), "import ")
        pr_h, pr_b = _split_head(_dedup(PRELINES), "import ")
        src = "\n".join(_dedup(pr_h + rt_h)) + "\n" + "\n".join(pr_b) + "\n"
        src += "\n".join(rt_b) + "\n\nclass Chunk {\n"
        src += bodies(lambda p:
                      "  static void %s() {\n    try {\n%s"
                      '      var _r = %s;\n      RT.emit("%s", _r);\n'
                      "    } catch (Throwable _t) {\n"
                      '      RT.raise("%s", _t);\n    }\n  }\n'
                      % (p[1], "".join("      %s\n" % d for d in p[2]),
                         p[3], p[0], p[0]))
        src += _dispatch(ps, "  static void d%d(int i) {\n    switch (i) {\n",
                         "      case %d: %s(); break;\n", "    }\n  }\n")
        src += "  static void run(int i) {\n    switch (i / 100) {\n"
        for g in range(0, n, 100):
            src += "      case %d: d%d(i); break;\n" % (g // 100, g // 100)
        src += "    }\n  }\n"
        src += ("  public static void main(String[] a) {\n    int s = "
                "a.length > 0 ? Integer.parseInt(a[0]) : 0;\n"
                "    for (int i = s; i < %d; i++) run(i);\n"
                '    System.out.println("__END__");\n  }\n}\n' % n)
        return src, "Chunk.java"

    if LANG == "kotlin":
        rt_h, rt_b = _split_head(RTX.splitlines(), "import ")
        pr_h, pr_b = _split_head(_dedup(PRELINES), "import ")
        src = "\n".join(_dedup(pr_h + rt_h)) + "\n" + "\n".join(pr_b) + "\n"
        src += "\n".join(rt_b) + "\n\n"
        src += bodies(lambda p:
                      "fun %s() {\n  try {\n%s    val _r = %s\n"
                      '    RT.emit("%s", _r)\n  } catch (_t: Throwable) {\n'
                      '    RT.raise("%s", _t)\n  }\n}\n'
                      % (p[1], "".join("    %s\n" % d for d in p[2]),
                         p[3], p[0], p[0]))
        src += _dispatch(ps, "fun d%d(i: Int) {\n  when (i) {\n",
                         "    %d -> %s()\n", "  }\n}\n")
        src += "fun run(i: Int) {\n  when (i / 100) {\n"
        for g in range(0, n, 100):
            src += "    %d -> d%d(i)\n" % (g // 100, g // 100)
        src += "  }\n}\n"
        src += ("fun main(args: Array<String>) {\n  val s = if "
                "(args.isNotEmpty()) args[0].toInt() else 0\n"
                "  for (i in s until %d) run(i)\n"
                '  println("__END__")\n}\n' % n)
        return src, "Chunk.kt"

    if LANG == "csharp":
        rt_h, rt_b = _split_head(RTX.splitlines(), "using ")
        pr_h, pr_b = _split_head(_dedup(PRELINES), "using ")
        src = "\n".join(_dedup(pr_h + rt_h)) + "\n" + "\n".join(pr_b) + "\n"
        src += "\n".join(rt_b) + "\n\nclass Chunk {\n"
        src += bodies(lambda p:
                      "  static void %s() {\n    try {\n%s"
                      '      var _r = %s;\n      RT.Emit("%s", _r);\n'
                      "    } catch (System.Exception _e) {\n"
                      '      RT.Raise("%s", _e.GetType().FullName);\n'
                      "    }\n  }\n"
                      % (p[1], "".join("      %s\n" % d for d in p[2]),
                         p[3], p[0], p[0]))
        src += _dispatch(ps, "  static void d%d(int i) {\n    switch (i) {\n",
                         "      case %d: %s(); break;\n", "    }\n  }\n")
        src += "  static void Run(int i) {\n    switch (i / 100) {\n"
        for g in range(0, n, 100):
            src += "      case %d: d%d(i); break;\n" % (g // 100, g // 100)
        src += "    }\n  }\n"
        src += ("  static void Main(string[] a) {\n    int s = a.Length > 0 "
                "? int.Parse(a[0]) : 0;\n"
                "    for (int i = s; i < %d; i++) Run(i);\n"
                '    System.Console.Out.Write("__END__\\n");\n'
                "    System.Console.Out.Flush();\n  }\n}\n" % n)
        return src, "Chunk.cs"

    raise SystemExit("no source builder for " + LANG)


def build_cmds(d, fname):
    """(compile argv list, run argv factory).  Copied unchanged from
    `l3_exec_lanes.build_cmds` -- these are the invocations the execution
    campaign of log_032 actually used inside this image."""
    if LANG == "cpp":
        return ([["g++", "-std=c++20", "-O0", "-w", "-o", d + "/bin",
                  d + "/" + fname]],
                lambda s: [d + "/bin", str(s)])
    if LANG == "swift":
        return ([["/persist/swift/usr/bin/swiftc", "-Onone",
                  "-suppress-warnings", "-o", d + "/bin", d + "/" + fname]],
                lambda s: [d + "/bin", str(s)])
    if LANG == "dart":
        return ([["/persist/dart-sdk/bin/dart", "compile", "exe",
                  d + "/" + fname, "-o", d + "/bin"]],
                lambda s: [d + "/bin", str(s)])
    if LANG == "java":
        return ([["javac", "-nowarn", "-d", d + "/cls", d + "/" + fname]],
                lambda s: ["java", "-cp", d + "/cls", "Chunk", str(s)])
    if LANG == "kotlin":
        std = "/persist/kotlinc/lib/kotlin-stdlib.jar"
        return ([["/persist/kotlinc/bin/kotlinc", "-nowarn", "-d", d + "/cls",
                  d + "/" + fname]],
                lambda s: ["java", "-cp", d + "/cls:" + std, "ChunkKt",
                           str(s)])
    if LANG == "csharp":
        refd = sorted(glob.glob(
            DOT + "/packs/Microsoft.NETCore.App.Ref/*/ref/net*"))[-1]
        csc = sorted(glob.glob(DOT + "/sdk/*/Roslyn/bincore/csc.dll"))[-1]
        ver = refd.split("/")[-3]
        tfm = refd.split("/")[-1]
        open(d + "/Chunk.runtimeconfig.json", "w").write(
            '{"runtimeOptions":{"tfm":"%s","framework":{"name":'
            '"Microsoft.NETCore.App","version":"%s"}}}' % (tfm, ver))
        refs = ["-reference:" + os.path.join(refd, f)
                for f in os.listdir(refd) if f.endswith(".dll")]
        return ([[DOT + "/dotnet", "exec", csc, "-nologo", "-nowarn:CS0168",
                  "-out:" + d + "/Chunk.dll", "-target:exe"] + refs
                 + [d + "/" + fname]],
                lambda s: [DOT + "/dotnet", d + "/Chunk.dll", str(s)])
    if LANG == "typescript":
        tsc = "/persist/tv/ts5/node_modules/typescript/lib/typescript.js"
        open(d + "/tr.js", "w").write(
            "const ts=require(%r);const fs=require('fs');"
            "const src=fs.readFileSync(process.argv[2],'utf8');"
            "const o=ts.transpileModule(src,{compilerOptions:"
            "{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}});"
            "fs.writeFileSync(process.argv[3],o.outputText);" % tsc)
        return ([["node", d + "/tr.js", d + "/" + fname, d + "/chunk.js"]],
                lambda s: ["node", "--stack-size=4000", d + "/chunk.js",
                           str(s)])
    raise SystemExit("no toolchain for " + LANG)


_MARK = re.compile(r"^// __PROBE__ (\S+)\s*$")
_ERL = re.compile(r"(?:chunk|Chunk|main)\.[A-Za-z]+:(\d+)[:.]")
_ERC = re.compile(r"(?:chunk|Chunk|main)\.[A-Za-z]+\((\d+),\d+\)")


def probe_spans(src):
    marks = []
    for n, line in enumerate(src.splitlines(), 1):
        m = _MARK.match(line)
        if m:
            marks.append((n, m.group(1)))
    out = []
    for k, (n, pid) in enumerate(marks):
        end = marks[k + 1][0] - 1 if k + 1 < len(marks) else 10 ** 9
        out.append((n, end, pid))
    return out


def map_errors(msg, spans):
    """which probes did the compiler NAME?  {pid: short reason}.  This is
    the REPAIR step: the compiler points at its own line, so one refused
    probe costs one rebuild rather than a bisection."""
    hit = {}
    for ml in msg.splitlines():
        ms = _ERL.search(ml) or _ERC.search(ml)
        if not ms:
            continue
        ln = int(ms.group(1))
        for a, b, pid in spans:
            if a <= ln <= b:
                if pid != "-":
                    hit.setdefault(pid, ml.strip()[:120])
                break
    return hit


def compile_chunk(d, ps):
    shutil.rmtree(d, ignore_errors=True)
    os.makedirs(d)
    src, fname = build_src(ps)
    open(os.path.join(d, fname), "w").write(src)
    cmds, runf = build_cmds(d, fname)
    t = time.time()
    ok, msg = True, ""
    for c in cmds:
        r = subprocess.run(c, capture_output=True, text=True, cwd=d,
                           timeout=3000)
        if r.returncode != 0:
            ok = False
            msg = (r.stderr or "") + "\n" + (r.stdout or "")
            break
    el = time.time() - t
    COMPILES["n"] += 1
    COMPILES["s"] += el
    return ok, el, msg, src, runf


def _pump(fh, q):
    for line in fh:
        q.put(line.rstrip("\n"))
    q.put(None)


def run_binary(d, ps, runf, out):
    """the START-INDEX discipline, identical to rust's and go's: an
    uncatchable stop costs ONE probe, never the chunk.  log_063 adds the
    other half of that discipline -- a STALL (no line for STALL seconds
    once output has started, or none at all within STARTUP) is now also
    caught, `pr.kill()`-ed and restarted past, exactly like a crash, so
    it too costs one probe and not the lane's entire remaining budget."""
    ids = [p[0] for p in ps]
    pos = dict((p, k) for k, p in enumerate(ids))
    got = {}
    start = 0
    restarts = 0
    stall_s = 0.0
    t = time.time()
    while start < len(ids) and restarts < 2000:
        pr = subprocess.Popen(runf(start), stdout=subprocess.PIPE,
                              stderr=subprocess.DEVNULL, text=True, cwd=d,
                              bufsize=1)
        q = queue.Queue()
        threading.Thread(target=_pump, args=(pr.stdout, q),
                         daemon=True).start()
        last = start - 1
        ended = stalled = False
        ready = False
        while True:
            try:
                line = q.get(timeout=(STARTUP if not ready else STALL))
            except queue.Empty:
                stalled = True
                stall_s += (STARTUP if not ready else STALL)
                break
            if line is None:
                break
            ready = True
            if line == "__END__":
                ended = True
                continue
            if "|" not in line:
                continue
            pid = line.split("|", 1)[0]
            k = pos.get(pid)
            if k is None:
                continue
            got[pid] = line
            if k > last:
                last = k
        if stalled:
            try:
                pr.kill()      # the subprocess API's own name; the
                               # OUTCOME this produces is ABORT
            except OSError:
                pass
        pr.wait()
        if ended or last >= len(ids) - 1:
            break
        nxt = last + 1
        why = ("stalled>%.0fs" % (STARTUP if not ready else STALL)) \
            if stalled else ("rc%s" % pr.returncode)
        got[ids[nxt]] = "%s|-|ABORT:%s" % (ids[nxt], why)
        start = nxt + 1
        restarts += 1
        if stalled:
            print("   .. probe %s stalled (%s); killed and restarting "
                  "at probe %d" % (ids[nxt], why, start))
            sys.stdout.flush()
    el = time.time() - t
    a = r_ = ab = 0
    for pid in ids:
        line = got.get(pid, "%s|-|MISSING" % pid)
        out.write(line + "\n")
        if "|-|RAISE:" in line:
            r_ += 1
        elif "|-|ABORT:" in line:
            ab += 1
        elif "|-|MISSING" in line:
            pass
        else:
            a += 1
    out.flush()
    return a, r_, ab, restarts, el, stall_s


def handle(d, ps, out, depth=0):
    """compile with REPAIR, then run.  Returns
    (answers, raises, aborts, buildfail, restarts, build_s, run_s,
    stall_s)."""
    refused = {}
    cur = list(ps)
    tb = 0.0
    ok = False
    runf = None
    for attempt in range(16):
        if not cur:
            ok = True
            break
        okc, el, msg, src, runf = compile_chunk(d, cur)
        tb += el
        if okc:
            ok = True
            break
        bad = map_errors(msg, probe_spans(src))
        if not bad:
            break
        print("   .. chunk of %d refused; the compiler named %d probe(s), "
              "dropping them and rebuilding (attempt %d)"
              % (len(cur), len(bad), attempt + 1))
        sys.stdout.flush()
        for pid, why in bad.items():
            refused[pid] = why
        cur = [p for p in cur if p[0] not in bad]
    if not ok:
        # the compiler refused and named no line at all -- BISECT, so a
        # nameless refusal still costs one probe and not a chunk.
        if len(cur) == 1:
            open(OUT + ".compilefail." + cur[0][0] + ".txt", "w").write(
                (msg or "")[:60000])
            refused[cur[0][0]] = "buildfail"
            for pid in refused:
                out.write("%s|-|BUILDFAIL\n" % pid)
            out.flush()
            return 0, 0, 0, len(refused), 0, tb, 0.0, 0.0
        print("   !! chunk of %d failed to build and named nothing; "
              "bisecting (depth %d)" % (len(cur), depth))
        sys.stdout.flush()
        h = len(cur) // 2
        acc = [0, 0, 0, 0, 0, tb, 0.0, 0.0]
        for half, sub in enumerate((cur[:h], cur[h:])):
            got = handle(d + "_%d%d" % (depth, half), sub, out, depth + 1)
            for x in range(8):
                acc[x] += got[x]
        for pid in refused:
            out.write("%s|-|BUILDFAIL\n" % pid)
            acc[3] += 1
        out.flush()
        return tuple(acc)
    a = r_ = ab = rs = 0
    tr = ss = 0.0
    if cur:
        a, r_, ab, rs, tr, ss = run_binary(d, cur, runf, out)
    for pid in refused:
        out.write("%s|-|BUILDFAIL\n" % pid)
    out.flush()
    shutil.rmtree(d, ignore_errors=True)
    return a, r_, ab, len(refused), rs, tb, tr, ss


chunks = [probes[x:x + CH] for x in range(0, len(probes), CH)]
print("chunking: %d probes -> %d chunk files, at most %d probes per file"
      % (len(probes), len(chunks), CH))
sys.stdout.flush()

out = open(OUT, "w")
t0 = time.time()
answers = raises = aborts = buildfail = restarts = 0
build_s = run_s = stall_s = 0.0
done = 0
for ci, ps in enumerate(chunks):
    d = os.path.join(ROOT, "c%05d" % ci)
    a, r_, ab, bf, rs, tb, tr, ss = handle(d, ps, out)
    answers += a; raises += r_; aborts += ab
    buildfail += bf; restarts += rs
    build_s += tb; run_s += tr; stall_s += ss
    done += len(ps)
    el = time.time() - t0
    eta = (el / done) * (len(probes) - done) if done else -1.0
    print("[progress] %s L%d chunk %d/%d [%d/%d] %5.1f%%  build %.2fs  "
          "run %.2fs  stall %.2fs  elapsed %.0fs  ETA %.0fs"
          % (LANG, LVL, ci + 1, len(chunks), done, len(probes),
             100.0 * done / max(1, len(probes)), tb, tr, ss, el, eta))
    sys.stdout.flush()

el = time.time() - t0
print("[progress] %s L%d [%d/%d] 100.0%%  elapsed %.0fs"
      % (LANG, LVL, len(probes), len(probes), el))
out.write("__SUMMARY__|%s|%d|%d|%d|%d|%d|%.3f\n"
          % (LANG, len(probes), answers, raises, aborts, buildfail, el))
out.write("__TIMING__|%s|level=%d|chunk_files=%d|probes=%d|chunk_cap=%d|"
          "compile_invocations=%d|compile_s=%.3f|execute_s=%.3f|"
          "other_s=%.3f|total_s=%.3f|restarts=%d|stall_s=%.3f\n"
          % (LANG, LVL, len(chunks), len(probes), CH, COMPILES["n"],
             COMPILES["s"], run_s, el - COMPILES["s"] - run_s, el, restarts,
             stall_s))
out.close()
print("== cartesian %s L%d: %d probes, %d answers, %d raises, %d aborts, "
      "%d buildfail, %.2f s" % (LANG, LVL, len(probes), answers, raises,
                                aborts, buildfail, el))
print("== TIMING %s L%d: %d chunk FILES (cap %d probes each), %d compile "
      "invocations totalling %.2f s; execution %.2f s; driver overhead "
      "%.2f s; wall %.2f s"
      % (LANG, LVL, len(chunks), CH, COMPILES["n"], COMPILES["s"], run_s,
         el - COMPILES["s"] - run_s, el))

PY_EOF
rm -rf "$ROOT"
echo "swept $ROOT; /work free: $(df -Pm /work | awk 'NR==2{print $4}') MB"
date -u +%Y-%m-%dT%H:%M:%SZ
echo "=== cartesian cpp level 2 done ==="
