#!/bin/sh
# layer-3 CARTESIAN lane -- python -- level 2 shard 6 of 8 --
# generated by Research/kind_fuzz_clustering/l3_cart_gen.py .
# Do not hand-edit.  Route C: execution is the only acceptance evidence
# python has, so every ordered holder pair times the operator menu runs.
set -u
export HOME=/work
ROOT=/work/ct_python_l2_s6
rm -rf "$ROOT"; mkdir -p "$ROOT"
echo "=== layer-3 CARTESIAN -- python -- level 2 -- 1613967 probes ==="
date -u +%Y-%m-%dT%H:%M:%SZ
python3 --version
base64 -d <<'T_EOF' | gunzip > "$ROOT/table.json"
H4sIAAAAAAAC/+XbW2/jNhYA4L/iGmjRxjeJlEh5sBn0YdGnxT7t28xOYB4qM8Y6dmA7vaDtf1+R
sqRzokOGWqAvswGGJinqmPxIixPJ+X1+2B0/v+w+1/N3s/nzb9cvp+N8OZufni9NxYf5whVWLrlz
ycYl37rkbz65d+l7n/jsvU+/8el3LvnDJZ98W3/Ge9944+Pc+ZC7o/VveHbp3r/58XSdtbn9pU1n
TZXL/Tj/d5N+OR1sffYd/H2+b17ypvLxdH5yY7ieX65f5n0rV2VOp4OrOdfPuHiprw9725+z+YfY
qHdNtl4+7g6Xepkt8+XH+cf58rhv2z/Xh8P++LmVcQ1drW/rMplLcpe4k/w4mvNcf3fmUh+v7ixX
OjYZ5Wp9mN3sfvavWyiX/6kL5wpZl8m7TBfa5f95OtY+vvGRDIpkcCTTRTJdJIMiGRwJfCRAkQBH
gi4SdJEARQIcyfpIFkWyOJLtItkukkWRLI70fPZrc/7nctbOtkCz/UszyzWd7f3xiib7Vhrm2p/h
5jrP3q3EJyWXq9xPtV6KTzJvCu6lSUq5al8W7kU1pfEi8AH8RySnS0C7pI3X5drXUq763OKW87H5
hZJnZKWstkJIqUUmVVUWWpdVVnXLYZWHl43uMiIvdFFJVYxr+kDbLNP5diuaNyiy7TYP1Mu+ftQn
/WpZhrpt+m7za1R3GdptM+q2CXTbBLptIt0ePgOhbkPfbf4DobsM7TaMug2BbkOg2xDp9vCBC3Xb
9t3mP326y9Bu21G3baDbNtBtG+n26NMt45/uv9ewf9rhy7lta9boyFfyab+N6PuPc25KP85/6D6B
qGHOVmdsLd9Ws7XDmogf5rv1erWkNJJ8o/E6cu3o9SYJzvBwhoUzLJxh4UwczsThTAqcSYEzqXDD
FS8JDng4YOGAhQMWDuJwEIeDFDhIgYNUuOGamwRneTjLwlkWzrJwNg5n43A2Bc6mwNlUuNtV//F8
eprdrt+z/dPz6Xztzh82hCK+Ifx03sF13/7WctsRHm9VlzU++JVsCt2QvucW2nKW99fMoWHOVmds
Ld9Ws7XDQosf5rv1eqGlNJJ8o/FC8+3oppAEZ3g4w8IZFs6wcCYOZ+JwJgXOpMCZVLhhU0iCAx4O
WDhg4YCFgzgcxOEgBQ5S4CAVbtgUkuAsD2dZOMvCWRbOxuFsHM6mwNkUOJsKhzeF/hLebQv9lbzf
F8r4vgAPza/+qkDbAlx/e64va3TgK9kS6MDY1fbD+ufdYbjL9PqMPH48ix9+42wdPzwszcR2bwzm
9WKd1Fq+0Xq8fLsT6GYzbUrMG1Ni4lNi4lNi4lNiEqfEJE6JmTQlZtKUmMlTMmxj06YE3pgSiE8J
xKcE4lMCiVMCiVMCk6YEJk0JTJ6SYYOcNiX2jSmx8Smx8Smx8SmxiVNiE6fETpoSO2lK7OQpuW29
t722PXfYaRXaabuNub3RNmy3j4fTDt9378vDHjuc2m20T7tfHx73x/21brbbdbZcZU2y8MnT/vhw
eTHH5m13h2VzcJW/HJ5dxv1b+AI6PVtz+/DQoN2N134rdu/iXhfdK3kvv1nf3u6Wv70suioa1r11
2s37fK23Wm1lLotKCZmXul5IfAN/3d+57/rob+cP2bJeSVEMB7avfvob/8MpTZb+iOFItDvduNBt
/MgZBg3AoAGYYQCGDMAEB2CGAZjgAEx8AAYNAN3Qj5wBaACABgDDAIAMAIIDgGEAEBwAxAcAaADo
1n7kDIsGYNEA7DAASwZggwOwwwBscAA2PgCLBjC6ya8TrigT7/T/v19d8I1FflYCDwzW/MMBNw7+
WUKgvl1YgVNerzL+eUQg8nj9BZqlD7thjT42iMcyIUITIjQBQhMmNGmEJkBo0gjNBEITImQfIMRj
QYgQQoQQIIQwIaQRQoAQ0ghhAiGECNlHCfFYNkRoQ4Q2QGjDhDaN0AYIbRqhnUBoQ4RTHipUCRvQ
//BkgW5C2/Ee9JdvP3/ZttNubN3msw08kwhMHfdQYp0xzyS4ynY9co1fL0bmcQYXcLwMuTaJA2mk
wk8aYlEMy2E4DhPgMAkchuMwCRwmlcOwHNzzg1gUYDmA44AAByRwAMcBCRyQygEsB/dUIBbFshyW
47ABDpvAYTkOm8BhUzksy5F4r98vpOaq5y95H9rvm7qnD039h/YbpX3Jf1V0ONYWhC98woX+y6V9
zbdtQfrCH7jQtWtLm7ZQ+MJ3uOC/vNqX7tpC6Qvf3ONS+2XXvrhqC8oX7u9x6e4OlxZtQfvC+3tc
2mxw6UfSsC1UbYGU+q/U9jXeVhBbQWwFthXYVoxsBbYV2FYQW4FtBbYVxFZgW0FsBbUV2FYQW0Fs
BbYVxFYQW4FtBbYVxFaMbAWxlcRWEluJbSW2lSNbiW0ltpXEVmJbiW0lsZXYVhJbSW0ltpXEVhJb
iW0lsZXEVmJbiW0lsZUjW0lsC2JbENsC2xbYthjZFti2wLYFsS2wbYFtC2JbYNuC2BbUtsC2BbEt
iG2BbQtiWxDbAtsW2LYgtsXItiC2JbEtiW2JbUtsW45sS2xbYtuS2JbYtsS2JbEtsW1JbEtqW2Lb
ktiWxLbEtiWxLYltiW1LbFsS23JkWxJbRWwVsVXYVmFbNbJV2FZhW0VsFbZV2FYRW4VtFbFV1FZh
W0VsFbFV2FYRW0VsFbZV2FYRWzWyVcRWE1tNbDW21dhWj2w1ttXYVhNbjW01ttXEVmNbTWw1tdXY
VhNbTWw1ttXEVhNbjW01ttXEVo9sNbGtiG1FbCtsW2HbamRbYdsK21bEtsK2FbatiG2FbStiW1Hb
CttWxLYithW2rYhtRWwrbFth24rYViNbX+P+q3uof64Pt79w+eV0/k/7R07uiy6X6+5weHClbO3K
pxf3S/l807xu4PrQ/uHWw0E8XNT6+ut1/ud/AVKGvyrZNQAA
T_EOF
base64 -d <<'DRV_EOF' > "$ROOT/drv.py"
aW1wb3J0IGpzb24KaW1wb3J0IG9zCmltcG9ydCByZXNvdXJjZQppbXBvcnQgc3RydWN0CmltcG9y
dCBzeXMKZnJvbSBkZWNpbWFsIGltcG9ydCBEZWNpbWFsCmZyb20gZnJhY3Rpb25zIGltcG9ydCBG
cmFjdGlvbgoKUk9PVCA9IHN5cy5hcmd2WzFdClNIQVJEID0gaW50KHN5cy5hcmd2WzJdIGlmIGxl
bihzeXMuYXJndikgPiAyIGVsc2UgIjAiKQpTVEFSVCA9IGludChzeXMuYXJndlszXSBpZiBsZW4o
c3lzLmFyZ3YpID4gMyBlbHNlICIwIikKCnRyeToKICAgIF9DQVAgPSAyICogMTAyNCAqIDEwMjQg
KiAxMDI0CiAgICByZXNvdXJjZS5zZXRybGltaXQocmVzb3VyY2UuUkxJTUlUX0FTLCAoX0NBUCwg
X0NBUCkpCmV4Y2VwdCBFeGNlcHRpb246CiAgICBwYXNzCgpUID0ganNvbi5sb2FkKG9wZW4ob3Mu
cGF0aC5qb2luKFJPT1QsICJ0YWJsZS5qc29uIikpKQpIUyA9IFRbImhvbGRlcnMiXTsgT1BTID0g
VFsib3BzIl07IExWTCA9IFRbImxldmVsIl07IENFTExTID0gVFsiY2VsbHMiXQpOVyA9IFRbIndv
cmtlcnMiXQpUQUcgPSAiQSIgaWYgTFZMID09IDEgZWxzZSAiQiIKCkJJR0JJVFMgPSA0MDk2ClRP
UEJJVFMgPSA1MTIKCgpkZWYgX3RvcChhKToKICAgIGJsID0gYS5iaXRfbGVuZ3RoKCkKICAgIHJl
dHVybiBibCwgZm9ybWF0KChhID4+IChibCAtIFRPUEJJVFMpKSBpZiBibCA+IFRPUEJJVFMgZWxz
ZSBhLCAieCIpCgoKZGVmIHNlcihyKToKICAgICIiInRoZSBwYXlsb2FkIGdyYWluLiAgQmluYXJ5
IGZsb2F0cyB0cmF2ZWwgYXMgQklUUyAtLSB0aGUgc2FtZQogICAgYEZMT0FUOjx3aWR0aD46PGhl
eD5gIHRva2VuIHJ1c3QgYW5kIGdvIGVtaXQgLS0gc28gbm8gcHJpbnRlZCBkZWNpbWFsCiAgICBp
cyBldmVyIHJlYWQgYmFjayBhcyBhbiBleGFjdCBkZWNpbWFsICh0aGUgbG9nXzA1NyBmYXVsdCku
ICBEZWNpbWFsCiAgICBhbmQgRnJhY3Rpb24ga2VlcCB0aGUgcHJpbnRlZCBncmFpbiwgd2hlcmUg
dGhlIHRleHQgSVMgdGhlIHZhbHVlLiIiIgogICAgaWYgciBpcyBOb25lOgogICAgICAgIHJldHVy
biAiTlVMTCIKICAgIGlmIHIgaXMgVHJ1ZToKICAgICAgICByZXR1cm4gImJvb2w6VHJ1ZSIKICAg
IGlmIHIgaXMgRmFsc2U6CiAgICAgICAgcmV0dXJuICJib29sOkZhbHNlIgogICAgdCA9IHR5cGUo
cikKICAgIGlmIHQgaXMgaW50OgogICAgICAgIGEgPSAtciBpZiByIDwgMCBlbHNlIHIKICAgICAg
ICBpZiBhLmJpdF9sZW5ndGgoKSA+IEJJR0JJVFM6CiAgICAgICAgICAgIGJsLCBoeCA9IF90b3Ao
YSkKICAgICAgICAgICAgcmV0dXJuICJCSUdOVU06JWQ6JWQ6JXMiICUgKC0xIGlmIHIgPCAwIGVs
c2UgMSwgYmwsIGh4KQogICAgICAgIHJldHVybiAiSW50ZWdlcjolZCIgJSByCiAgICBpZiB0IGlz
IGZsb2F0OgogICAgICAgIHJldHVybiAiRkxPQVQ6NjQ6IiArIHN0cnVjdC5wYWNrKCI+ZCIsIHIp
LmhleCgpCiAgICBpZiB0IGlzIEZyYWN0aW9uOgogICAgICAgIG4gPSByLm51bWVyYXRvcgogICAg
ICAgIGQgPSByLmRlbm9taW5hdG9yCiAgICAgICAgYW4gPSAtbiBpZiBuIDwgMCBlbHNlIG4KICAg
ICAgICBpZiBhbi5iaXRfbGVuZ3RoKCkgPiBCSUdCSVRTIG9yIGQuYml0X2xlbmd0aCgpID4gQklH
QklUUzoKICAgICAgICAgICAgbmIsIG5oID0gX3RvcChhbikKICAgICAgICAgICAgZGIsIGRoID0g
X3RvcChkKQogICAgICAgICAgICByZXR1cm4gIkJJR1JBVDolZDolZDolczolZDolcyIgJSAoLTEg
aWYgbiA8IDAgZWxzZSAxLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgbmIsIG5oLCBkYiwgZGgpCiAgICAgICAgcmV0dXJuICJSYXRpb25hbDolZC8lZCIgJSAo
biwgZCkKICAgIGlmIHQgaXMgRGVjaW1hbDoKICAgICAgICBzID0gc3RyKHIpCiAgICAgICAgaWYg
bGVuKHMpID4gNDAwMDoKICAgICAgICAgICAgc2csIF9kZywgZXggPSByLmFzX3R1cGxlKCkKICAg
ICAgICAgICAgcmV0dXJuICJCSUdERUM6JWQ6JXM6JXMiICUgKC0xIGlmIHNnIGVsc2UgMSwgZXgs
IHNbOjIwMF0pCiAgICAgICAgcmV0dXJuICJEZWNpbWFsOiVzIiAlIHMKICAgIGlmIHQgaXMgc3Ry
OgogICAgICAgIHJldHVybiAiU3RyaW5nOiVzIiAlIChyIGlmIGxlbihyKSA8PSAyMDAwIGVsc2Ug
cls6MjAwMF0pCiAgICBpZiB0IGlzIGNvbXBsZXg6CiAgICAgICAgcmV0dXJuICJvcGFxdWU6Y29t
cGxleCIKICAgIHRyeToKICAgICAgICByZXR1cm4gIiVzOiVzIiAlICh0Ll9fbmFtZV9fLCByZXBy
KHIpWzo0MDBdKQogICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICByZXR1cm4gIm9wYXF1ZTol
cyIgJSB0Ll9fbmFtZV9fCgoKSEIgPSB7fQpmb3IgaCBpbiBIUzoKICAgIEhCW2hbImkiXV0gPSBo
CgojIFRoZSBwcm9iZSBsaXN0IGlzIE5FVkVSIG1hdGVyaWFsaXNlZCAtLSB0aGUgcnVieSBsYW5l
J3MgZGVmZWN0IEEKIyAobG9nXzA1MiBzZWN0aW9uIDEwKSBhcHBsaWVzIHdvcmQgZm9yIHdvcmQg
dG8gcHl0aG9uOiBidWlsZGluZyBtaWxsaW9ucwojIG9mIHNvdXJjZSBzdHJpbmdzIHVwIGZyb250
IGNvc3RzIG1vcmUgdGhhbiB0aGUgd2hvbGUgc3RhbGwgYnVkZ2V0IGFuZAojIG1vcmUgdGhhbiB0
aGUgYWRkcmVzcy1zcGFjZSBjYXAuICBUaGUgZW51bWVyYXRpb24gaXMgYXJpdGhtZXRpYzogYQoj
IHNtYWxsIHBlci1jZWxsIHBsYW4gd2l0aCBwcmVmaXggc3VtcyBhbmQgYW4gTygxKSBkZWNvZGUg
ZnJvbSBhIGdsb2JhbAojIHByb2JlIGluZGV4IHRvIHRoZSBmb3VyIG9wZXJhbmQgaW5kaWNlcywg
c28gYSByZXN0YXJ0IHJlc3VtZXMgaW4KIyBjb25zdGFudCB0aW1lIGluc3RlYWQgb2YgcmVwbGF5
aW5nIHRoZSBydW4gc28gZmFyLgpQTEFOID0gW10KVE9UQUwgPSAwCmZvciBjZWxsIGluIENFTExT
OgogICAgb3AsIGksIGogPSBjZWxsCiAgICBrID0gT1BTLmluZGV4KG9wKQogICAgaGEgPSBIQltp
XQogICAgaGIgPSBIQltqXQogICAgbmEgPSBoYVsibiJdCiAgICBuYiA9IGhiWyJuIl0KICAgIG4g
PSAobmEgKiBuYikgaWYgTFZMID09IDEgZWxzZSAobmEgKiBuYikgKiAobmEgKiBuYikKICAgIFBM
QU4uYXBwZW5kKChUT1RBTCwgbiwgaywgaSwgaiwgb3AsIGhhLCBoYiwgbmEsIG5iKSkKICAgIFRP
VEFMICs9IG4KCiMgdGhlIGhvbGRlciBkZWNsYXJhdGlvbnMgbmFtZSBEZWNpbWFsLCBGcmFjdGlv
biBhbmQgY3R5cGVzOyB0aGV5IGFyZQojIGJvdW5kIE9OQ0UgaGVyZSBhbmQgY29waWVkIGludG8g
ZWFjaCBwcm9iZSdzIG5hbWVzcGFjZSwgc28gbm8gcHJvYmUKIyBwYXlzIGFuIGltcG9ydC4KaW1w
b3J0IGN0eXBlcyAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIyBu
b3FhOiBFNDAyCkJBU0UgPSB7IkRlY2ltYWwiOiBEZWNpbWFsLCAiRnJhY3Rpb24iOiBGcmFjdGlv
biwgImN0eXBlcyI6IGN0eXBlc30KCnN5cy5zdGRvdXQucmVjb25maWd1cmUobGluZV9idWZmZXJp
bmc9VHJ1ZSkKcHJpbnQoIl9fUkVBRFlfXyIpCgoKZGVmIGxvY2F0ZShnKToKICAgIGxvID0gMAog
ICAgaGkgPSBsZW4oUExBTikgLSAxCiAgICB3aGlsZSBsbyA8IGhpOgogICAgICAgIG1pZCA9IChs
byArIGhpICsgMSkgLy8gMgogICAgICAgIGlmIFBMQU5bbWlkXVswXSA8PSBnOgogICAgICAgICAg
ICBsbyA9IG1pZAogICAgICAgIGVsc2U6CiAgICAgICAgICAgIGhpID0gbWlkIC0gMQogICAgcmV0
dXJuIFBMQU5bbG9dCgoKbCA9IFNUQVJUCndoaWxlIFRydWU6CiAgICBnID0gbCAqIE5XICsgU0hB
UkQKICAgIGlmIGcgPj0gVE9UQUw6CiAgICAgICAgYnJlYWsKICAgIGJhc2UsIG4sIGssIGksIGos
IG9wLCBoYSwgaGIsIG5hLCBuYiA9IGxvY2F0ZShnKQogICAgcCA9IGcgLSBiYXNlCiAgICBpZiBM
VkwgPT0gMToKICAgICAgICBpMSA9IHAgJSBuYgogICAgICAgIGkwID0gcCAvLyBuYgogICAgICAg
IHBpZCA9ICJBJWRfJWRfJWRfJWQiICUgKGssIGksIGosIHApCiAgICAgICAgc3JjID0gKGhhWyJh
Il1baTBdICsgIlxuIiArIGhiWyJiIl1baTFdICsKICAgICAgICAgICAgICAgIlxuX19yID0gKChh
KSAlcyAoYikpXG4iICUgb3ApCiAgICBlbHNlOgogICAgICAgIGkzID0gcCAlIG5iCiAgICAgICAg
dCA9IHAgLy8gbmIKICAgICAgICBpMiA9IHQgJSBuYQogICAgICAgIHQyID0gdCAvLyBuYQogICAg
ICAgIGkxID0gdDIgJSBuYgogICAgICAgIGkwID0gdDIgLy8gbmIKICAgICAgICBwaWQgPSAiQiVk
XyVkXyVkXyVkIiAlIChrLCBpLCBqLCBwKQogICAgICAgIHNyYyA9IChoYVsiYSJdW2kwXSArICJc
biIgKyBoYlsiYiJdW2kxXSArICJcbiIgKwogICAgICAgICAgICAgICBoYVsiYyJdW2kyXSArICJc
biIgKyBoYlsiZCJdW2kzXSArCiAgICAgICAgICAgICAgICJcbl9fciA9ICgoKGEpICVzIChiKSkg
JXMgKChjKSAlcyAoZCkpKVxuIiAlIChvcCwgb3AsIG9wKSkKICAgIHRyeToKICAgICAgICBjb2Rl
ID0gY29tcGlsZShzcmMsICI8cHJvYmU+IiwgImV4ZWMiKQogICAgZXhjZXB0IFN5bnRheEVycm9y
OgogICAgICAgIHByaW50KCIlc3xSRUZVU0V8U3ludGF4RXJyb3IiICUgcGlkKQogICAgICAgIGwg
Kz0gMQogICAgICAgIGNvbnRpbnVlCiAgICBucyA9IGRpY3QoQkFTRSkKICAgIHRyeToKICAgICAg
ICBleGVjKGNvZGUsIG5zKQogICAgICAgIHByaW50KCIlc3xBTlNXRVJ8JXMiICUgKHBpZCwgc2Vy
KG5zLmdldCgiX19yIikpKSkKICAgIGV4Y2VwdCBCYXNlRXhjZXB0aW9uIGFzIGU6CiAgICAgICAg
cHJpbnQoIiVzfFJBSVNFfCVzIiAlIChwaWQsIHR5cGUoZSkuX19uYW1lX18pKQogICAgbCArPSAx
CnByaW50KCJfX0VORF9fIikK
DRV_EOF
python3 - "$ROOT" <<'PY_EOF'

import json
import os
import queue
import subprocess
import sys
import threading
import time

ROOT = sys.argv[1]
T = json.load(open(os.path.join(ROOT, "table.json")))
OUT = T["out"]
STALL = T["stall_s"]        # a stall is an ABORT and an ABORT is excluded
                            # from scoring in the numerator AND the
                            # denominator, so this budget costs wall clock
                            # and no measurement.
STARTUP = 120.0             # a driver's setup grace, separate from the
                            # per-probe stall budget
NW = T["workers"]
LVL = T["level"]
HS, OPS, CELLS = T["holders"], T["ops"], T["cells"]
HB = dict((h["i"], h) for h in HS)

ids = []
for (op, i, j) in CELLS:
    k = OPS.index(op)
    na, nb = HB[i]["n"], HB[j]["n"]
    n = na * nb if LVL == 1 else (na * nb) ** 2
    tag = "A" if LVL == 1 else "B"
    for p in range(n):
        ids.append("%s%d_%d_%d_%d" % (tag, k, i, j, p))

shards = [ids[w::NW] for w in range(NW)]
print("cartesian python level %d: %d cells -> %d probes, sharded across %d "
      "worker processes; stall budget %.1f s"
      % (LVL, len(CELLS), len(ids), NW, STALL))
sys.stdout.flush()


def pump(fh, q):
    for line in fh:
        q.put(line.rstrip("\n"))
    q.put(None)


RES = {}
STATS = {}
LOCK = threading.Lock()


def work(w):
    mine = shards[w]
    pos = dict((p, k) for k, p in enumerate(mine))
    got = {}
    # every worker writes its own PART FILE as the answers arrive, so a
    # run the daemon stops at its ceiling still leaves on disk everything
    # it actually measured instead of nothing.
    part = open(OUT[:-4] + ".w%d.txt" % w, "w")
    written = 0
    start = 0
    restarts = 0
    stall_s = 0.0
    t0 = time.time()
    while start < len(mine) and restarts < 20000:
        pr = subprocess.Popen(["python3", os.path.join(ROOT, "drv.py"), ROOT,
                               str(w), str(start)],
                              stdout=subprocess.PIPE,
                              stderr=subprocess.DEVNULL, text=True,
                              bufsize=1)
        q = queue.Queue()
        threading.Thread(target=pump, args=(pr.stdout, q),
                         daemon=True).start()
        last = start - 1
        ended = stalled = False
        ready = False
        while True:
            # STARTUP grace: the driver announces `__READY__` once its
            # per-cell plan is built.  Until then the stall budget does not
            # apply -- a slow start is not a stuck probe.
            try:
                line = q.get(timeout=(STARTUP if not ready else STALL))
            except queue.Empty:
                stalled = True
                stall_s += STALL
                break
            if line is None:
                break
            if line == "__READY__":
                ready = True
                continue
            if line == "__END__":
                ended = True
                continue
            if "|" not in line:
                continue
            pid = line.split("|", 1)[0]
            k = pos.get(pid)
            if k is None:
                continue
            got[pid] = line
            part.write(line + "\n")
            written += 1
            if written % 5000 == 0:
                part.flush()
            if k > last:
                last = k
        if stalled:
            try:
                pr.kill()      # the subprocess API's own name; the OUTCOME
                               # this produces is ABORT
            except OSError:
                pass
        pr.wait()
        if ended or last >= len(mine) - 1:
            break
        nxt = last + 1
        why = ("stalled>%.0fs" % STALL) if stalled else ("rc%s"
                                                         % pr.returncode)
        got[mine[nxt]] = "%s|ABORT|%s" % (mine[nxt], why)
        part.write(got[mine[nxt]] + "\n")
        part.flush()
        start = nxt + 1
        restarts += 1
        if restarts % 25 == 0:
            print("[worker %d] %d restarts, at %d/%d after %.1f s"
                  % (w, restarts, start, len(mine), time.time() - t0))
            sys.stdout.flush()
    part.close()
    with LOCK:
        RES.update(got)
        STATS[w] = dict(restarts=restarts, stall_s=stall_s,
                        wall_s=time.time() - t0, probes=len(mine))
    print("[worker %d] done: %d probes, %d restarts, %.1f s stalled, "
          "%.1f s wall" % (w, len(mine), restarts, stall_s,
                           time.time() - t0))
    sys.stdout.flush()


t0 = time.time()
ths = [threading.Thread(target=work, args=(w,)) for w in range(NW)]
for t in ths:
    t.start()


def progress():
    # the standing `[n/total]` progress line, so `airlock status` and
    # progress.sh have something to read.  `RES` only fills as a worker
    # FINISHES, so the live count is taken off the part files instead --
    # they are written as the answers arrive.
    while any(t.is_alive() for t in ths):
        time.sleep(15.0)
        with LOCK:
            done = len(RES)
        live = 0
        for w in range(NW):
            try:
                with open(OUT[:-4] + ".w%d.txt" % w, "rb") as fh:
                    live += sum(1 for _ in fh)
            except OSError:
                pass
        n = max(done, live)
        el = time.time() - t0
        rate = n / el if el > 0 else 0.0
        eta = ((len(ids) - n) / rate) if rate > 0 else -1.0
        print("[progress] python L%d [%d/%d] %5.1f%%  elapsed %.0fs  "
              "ETA %s  %.0f probes/s"
              % (LVL, n, len(ids), 100.0 * n / max(1, len(ids)), el,
                 ("%.0fs" % eta) if eta >= 0 else "--", rate))
        sys.stdout.flush()


pth = threading.Thread(target=progress, daemon=True)
pth.start()
for t in ths:
    t.join()
el = time.time() - t0
print("[progress] python L%d [%d/%d] 100.0%%  elapsed %.0fs"
      % (LVL, len(ids), len(ids), el))
sys.stdout.flush()

ans = raises = aborts = refused = missing = 0
with open(OUT, "w") as f:
    for pid in ids:
        line = RES.get(pid, "%s|MISSING|" % pid)
        f.write(line + "\n")
        kind = line.split("|")[1]
        if kind == "ANSWER":
            ans += 1
        elif kind == "RAISE":
            raises += 1
        elif kind == "ABORT":
            aborts += 1
        elif kind == "REFUSE":
            refused += 1
        else:
            missing += 1
    restarts = sum(s["restarts"] for s in STATS.values())
    stall_s = sum(s["stall_s"] for s in STATS.values())
    f.write("__SUMMARY__|python|%d|%d|%d|%d|%d|%.3f\n"
            % (len(ids), ans, raises, aborts, refused, el))
    f.write("__TIMING__|python|level=%d|workers=%d|processes=%d|probes=%d|"
            "compile_invocations=0|compile_s=0.000|stall_budget_s=%.1f|"
            "stall_s=%.3f|execute_s=%.3f|total_s=%.3f|restarts=%d\n"
            % (LVL, NW, restarts + NW, len(ids), STALL, stall_s,
               max(0.0, el - stall_s / max(1, NW)), el, restarts))
print("== cartesian python L%d: %d probes, %d answers, %d raises, %d aborts, "
      "%d refusals, %d missing, %d restarts, %.2f s wall"
      % (LVL, len(ids), ans, raises, aborts, refused, missing, restarts, el))
print("== TIMING python L%d: 0 files compiled (route C is exec, nothing is "
      "compiled ahead of time); %d python process(es) across %d workers -- "
      "%d workers plus %d restarts past a probe that stopped one; wall "
      "%.2f s; %.2f s of worker-time spent inside the %.1f s inactivity "
      "budget on stalls"
      % (LVL, restarts + NW, NW, NW, restarts, el, stall_s, STALL))
for w in sorted(STATS):
    s = STATS[w]
    print("   worker %d: %d probes, %d restarts, %.1f s stalled, %.1f s wall"
          % (w, s["probes"], s["restarts"], s["stall_s"], s["wall_s"]))

PY_EOF
rm -rf "$ROOT"
date -u +%Y-%m-%dT%H:%M:%SZ
echo "=== cartesian python level 2 done ==="
