#!/bin/bash
# task o11, lane 23: the law's `grep -c exempt` over every file this
# task added, naming each file rather than globbing, so the list does
# not grow when a later lane is written and the transcript the log
# pastes stays re-runnable.
set -u
echo "[1/1] grep -c exempt"
echo "\$ grep -c exempt PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/rust_render.py PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/rust_report.py PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/rust_facts.py PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l1_rust_facts.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l2_rust_facts2.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l3_rust_facts3.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l4_rust_facts4.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l5_optable_census.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l6_census_rerun.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l7_sample40.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l8_run_control_peropcode.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l9_peropcode_rerun.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l10_report.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l11_report_rerun.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l12_evidence.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l13_evidence2.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l14_evidence3.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l15_evidence4.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l16_verify_log226.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l17_evidence5.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l18_verify2_log226.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l19_verify3_log226.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l20_verify4_log226.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l21_verify5_log226.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l22_exempt_grep.sh"
grep -c exempt PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/rust_render.py PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/rust_report.py PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/rust_facts.py PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l1_rust_facts.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l2_rust_facts2.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l3_rust_facts3.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l4_rust_facts4.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l5_optable_census.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l6_census_rerun.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l7_sample40.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l8_run_control_peropcode.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l9_peropcode_rerun.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l10_report.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l11_report_rerun.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l12_evidence.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l13_evidence2.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l14_evidence3.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l15_evidence4.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l16_verify_log226.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l17_evidence5.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l18_verify2_log226.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l19_verify3_log226.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l20_verify4_log226.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l21_verify5_log226.sh PseudoCoupHQ/Research/oracle/cross_construction/emulation/rust/lanes_o11/o11_l22_exempt_grep.sh
echo "lane o11_l23 done"
