"""GENERATED by transpile_cpp.py -- do not edit.

Transpile of a named slice of LLVM's HAND-WRITTEN x86 encoder
(X86MCCodeEmitter.cpp): modRMByte, emitRegModRMByte, emitSIBByte,
emitByte, the PrefixKind enum, and X86OpcodePrefixHelper's
setR/setX/setB/setW + emit() (REX/None arms only -- REX2/VEX2/VEX3/XOP/
EVEX are cut, see the class docstring below). See transpile_cpp.py's
module docstring for the exact SCOPE list and the policy this transpile
follows.

This is LLVM's independent derivation of the SAME x86 ISA facts
../vocab_transpiler/vocab_support.py derives from Cranelift. See
test_agreement.py for the exhaustive cross-check between the two.

source file   X86MCCodeEmitter.cpp
source sha256 9322e2dd4bc197643a873983a77275ba89517f32d1d5ea0a63f0f3bbd6b6e47d
llvm tag      llvmorg-21.1.8
transpiler    v1

Deterministic: same input -> byte-identical output.
"""


def u8(x: int) -> int:
    """Not a transpile of any single C++ line: makes explicit the
    truncation-to-uint8_t that C++ performs implicitly at every
    uint8_t-typed expression boundary (bitfields promote to `int` for
    arithmetic; C++ narrows back to uint8_t at assignment/argument-
    passing). UNIFORM policy: every arithmetic node in a uint8_t-typed
    C++ expression in this file is wrapped in u8(), with no exemptions,
    matching vocab_support.py's rule for the sibling Rust transpile."""
    return x & 0xFF



# ---------------- emitByte (X86MCCodeEmitter.cpp:43) ----------------

def emit_byte(c, cb):
    """X86MCCodeEmitter.cpp:43 -- static void emitByte(uint8_t C, SmallVectorImpl<char> &CB) { CB.push_back(C); }"""
    cb.append(u8(c))


# ---------------- modRMByte (X86MCCodeEmitter.cpp:401-404) ----------------

def mod_rm_byte(mod_, reg_opcode, rm):
    """X86MCCodeEmitter.cpp:401-404 -- static uint8_t modRMByte(unsigned Mod, unsigned RegOpcode, unsigned RM).

    LLVM ASSERTS its input range (Mod<4, RegOpcode<8, RM<8) rather than
    masking it the way Cranelift's encode_modrm does (`m0d & 3`, etc. --
    see vocab_support.py). test_agreement.py checks both that the two
    agree inside the asserted domain and reports what happens outside it.
    """
    assert (mod_ < 4) and (reg_opcode < 8) and (rm < 8), "ModRM Fields out of range!"
    return u8(u8(rm | (u8(reg_opcode << 3))) | (u8(mod_ << 6)))


# ---------------- emitRegModRMByte / emitSIBByte ----------------

def emit_reg_modrm_byte(modrm_reg_num, reg_opcode_fld, cb):
    """X86MCCodeEmitter.cpp:603-607 -- X86MCCodeEmitter::emitRegModRMByte.

    `modrm_reg_num` stands in for the source's `getX86RegNum(ModRMReg)`
    call -- see extract_emit_reg_modrm_byte's docstring in transpile_cpp.py for
    exactly why that one call is elided rather than transpiled.
    """
    emit_byte(mod_rm_byte(3, reg_opcode_fld, modrm_reg_num), cb)


def emit_sib_byte(ss, index, base, cb):
    """X86MCCodeEmitter.cpp:609-613 -- X86MCCodeEmitter::emitSIBByte. SIB byte is in the same format as the modRM byte (source comment, verbatim)."""
    emit_byte(mod_rm_byte(ss, index, base), cb)


# ---------------- PrefixKind enum (X86MCCodeEmitter.cpp:41) ----------------

# X86MCCodeEmitter.cpp:41 -- enum PrefixKind { None, REX, REX2, XOP, VEX2, VEX3, EVEX };
PK_NONE, PK_REX, PK_REX2, PK_XOP, PK_VEX2, PK_VEX3, PK_EVEX = 0, 1, 2, 3, 4, 5, 6

PREFIX_KIND_NAMES = {"None": PK_NONE, "REX": PK_REX, "REX2": PK_REX2, "XOP": PK_XOP, "VEX2": PK_VEX2, "VEX3": PK_VEX3, "EVEX": PK_EVEX}


# ---------------- X86OpcodePrefixHelper (slice) ----------------

class X86OpcodePrefixHelper:
    """Transpiled slice of X86MCCodeEmitter.cpp's X86OpcodePrefixHelper (~line 45-336).

    ONLY the W/R/X/B bitfields, the Kind field, setR/setX/setB/setW, and
    emit()'s None/REX arms are transpiled -- every other field (M, R2, X2,
    B2, VEX_4V, VEX_L, VEX_PP, VEX_5M, EVEX_z/L2/b/V2/aaa) and every other
    method (setR2/setX2/setB2/set4V/setL/setPP/set5M/setRR2/setM/setXX2/
    setBB2/setZ/setL2/setEVEX_b/setEVEX_U/setV2/set4VV2/setAAA/setNF/setSC/
    setLowerBound/determineOptimalKind/getRegEncoding, and the constructor's
    full field-initializer list) exist only to feed VEX/EVEX/XOP/REX2
    prefix construction -- CUT.

    REACHABILITY INVARIANT: unreachable while only REX-form GPR
    instructions are exercised -- no APX (REX2) or AVX/AVX-512/XOP
    instruction is ever driven through this transpile. Each cut arm below
    asserts this at the call site rather than silently omitting bytes.
    """
    __slots__ = ("W", "R", "X", "B", "Kind")

    def __init__(self):
        """Not itself one of the four SCOPE items (the real constructor
        zero-initializes 16 fields via an initializer list feeding VEX/EVEX
        state this transpile cuts); W/R/X/B start at 0 and Kind at its
        declared field default (`PrefixKind Kind = None;`) -- the
        minimal bootstrapping needed for setR/setX/setB/setW/emit() to be
        callable at all."""
        self.W = 0
        self.R = 0
        self.X = 0
        self.B = 0
        self.Kind = PK_NONE

    def setR(self, encoding):
        self.R = u8(u8(encoding >> 3) & 1)

    def setX(self, encoding):
        self.X = u8(u8(encoding >> 3) & 1)

    def setB(self, encoding):
        self.B = u8(u8(encoding >> 3) & 1)

    def setW(self, v):
        self.W = v

    def emit(self, cb):
        """X86MCCodeEmitter.cpp:298-336 -- X86OpcodePrefixHelper::emit(SmallVectorImpl<char> &CB) const. Only the `case None:`/`case REX:` arms are transpiled; every other arm is CUT below."""
        if self.Kind == PK_NONE:
            return
        if self.Kind == PK_REX:
            emit_byte(u8(u8(u8(u8(0x40 | u8(self.W << 3)) | u8(self.R << 2)) | u8(self.X << 1)) | self.B), cb)
            return
        # CUT: REX2 / VEX2 / VEX3+XOP / EVEX -- see class docstring.
        raise NotImplementedError(
            f"PrefixKind {self.Kind} emission not cut (VEX/EVEX/XOP/REX2 path). "
            "Invariant 'only REX-form GPR instructions are exercised' has been "
            "violated.")
